### ISSUE TITLE
bluetooth still off after exe file

### ISSUE THREAD

**Issue by itsweekly** [Atlas-OS/Atlas#100]
**I launch the file to enable the exe, and still does not work**
After launching the exe file in the folder, and rebooting, bluetooth is still off for some reason.

**To Reproduce**
1. Go to the folder on desktop with all the stuff.
2. Click on bluetooth.
3. Scroll down to enable bluetooth.
4. Run the file, after reboot it will stay the same.

**Expected behavior**
I thought after a restart it would enable, but it still doesn't the OS is still very buggy.

**Desktop Info (please complete the following information):**
 - CPU [INTEL I7 1087H]
 - System Drive Type [SSD]
 - Version [20H2]

**Additional context**
I described this in discord, but ill write so other peolpe know about this.

**Comment by Zusier** [comment]
I am aware of this, there is a fix in the next update.
