### ISSUE TITLE
[BUG] - No configuration option given to enable or disable notifications on Windows 10

### ISSUE THREAD

**Issue by Tonur** [Atlas-OS/Atlas#1000]
### Description

Even though there is two scripts to enable or disable notifications, I do not get a choice in the matter when running the Atlas-OS playbook on Windows 10 Pro.

I would like to try and contribute to the codebase with such a configuration option, given that there currently are 2 cmd files to actually change this behaviour, but no config option for it here: [playbook/Executables/AtlasDesktop/3. Configuration/Notifications](https://github.com/Atlas-OS/Atlas/blob/main/src/playbook/Executables/AtlasDesktop/3.%20Configuration/Notifications/).

### Steps to reproduce

1. Install Windows 10
2. Download Atlas-OS Playbook and the AME Wizard.
3. Go through the installation flow.
4. Do not receive a config option to enable or disable notifications.
Images shown below:
![image](https://github.com/Atlas-OS/Atlas/assets/15033328/729c56da-5592-441d-bf77-fadbfc1d5df9)
![image](https://github.com/Atlas-OS/Atlas/assets/15033328/f87748ea-cd6a-4a7e-b63d-df8ad9fccf34)
![image](https://github.com/Atlas-OS/Atlas/assets/15033328/30050a01-9711-4517-9e51-3e766d255b6b)
![image](https://github.com/Atlas-OS/Atlas/assets/15033328/f8c20408-1b2a-4649-a0ac-2543bd18df0f)
![image](https://github.com/Atlas-OS/Atlas/assets/15033328/4803356d-e02b-4237-9cec-c8bb43e192e6)

Result:
![image](https://github.com/Atlas-OS/Atlas/assets/15033328/44001b82-2e94-4fb2-8edc-d01a8d0c1cad)

### Expected behavior

I would get a choice in the config options to enable or disable (default) notifications and Notification Center.

### Actual behavior

I do not get a choice. The RegEdit entry for `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer` is set to `DisableNotificationCenter=1`

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

- Processor: AMD Ryzen 5 7600X
- Memory: 32 GB DDR5
- Storage: 1TB M.2 NVMe SSD
- GPU: AMD Radeon RX 6950 XT

**Comment by xe1st** [comment]
and where is the bug?
atlas folder is there so you can disable/enable stuff after installation

**Comment by Tonur** [comment]
Never mind, I didn't follow the Atlas folder enough, sorry for the mess.

Appreciate your response @xe1st.
