### ISSUE TITLE
[BUG] - AtlasDesktop Configuration aren't getting applied 

### ISSUE THREAD

**Issue by Aditya-Tiwary** [Atlas-OS/Atlas#1001]
### Description

1. Enable Automatic Driver Updates.reg
2. Restore all folders in This PC.reg
3. Windows Spotlight set as wallpaper missing in settings 

### Steps to reproduce

Apply registry and  reboot and look for the change

### Expected behavior

The changes should reflect after changing configuration through registry 

### Actual behavior

Even after multiple clean install of windows. Whenever I change the registry and restart no changes are made and everything is default .

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Laptop HP Laptop 15s-eq2042AU with Ryzen 5300U 512GB SSD

**Comment by he3als** [comment]
All fixed in v0.4.0
