### ISSUE TITLE
[BUG] - Why the Notifications can't enable action?

### ISSUE THREAD

**Issue by elkan1788** [Atlas-OS/Atlas#1002]
### Description

Today I build some npm script but meet an error which message said : `Reason: DisabledForUser Please make sure that the app id is set correctly.` So then I gone to the settings wanted to enable notification , but found it can't move on.
![image](https://github.com/Atlas-OS/Atlas/assets/1217096/b6186e36-2706-4326-acdc-eff1bc69b2e3)

### Steps to reproduce

1. Press `Win+I` into settings
![image](https://github.com/Atlas-OS/Atlas/assets/1217096/30713f7c-5c5e-4844-8cd7-97912cc42078)

2. Click the button move it right
![image](https://github.com/Atlas-OS/Atlas/assets/1217096/0ece3b45-1e83-4516-8fe1-12ce18bc1648)

3. My Windows version
![image](https://github.com/Atlas-OS/Atlas/assets/1217096/50518ca5-4abf-401b-82da-04c8e5ee81c5)

### Expected behavior

This button can move on and message notice success.

### Actual behavior

This button can't move on and message notice failed.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

![image](https://github.com/Atlas-OS/Atlas/assets/1217096/5aec9615-1ad4-4946-bd93-59b328ccc1f4)

**Comment by xe1st** [comment]
Enable notifications from atlas folder

**Comment by elkan1788** [comment]
> Enable notifications from atlas folder

Thanks very much. The error was solved.
