### ISSUE TITLE
[BUG] - All OOBE Error after Sysprep

### ISSUE THREAD

**Issue by GuraNotFound** [Atlas-OS/Atlas#1004]
### Description

I planned to create a Custom Windows installer, but when I ran it on Hyper-V, I got an OOBE error

### Steps to reproduce

1. Install Windows, install some software and run Atlas Playbook
2. Adjust the default wallpaper and themes and run Sysprep
3. Capture again and Apply on another Hyper-V Machine
4. When setting up OOBE, every step of the setup gets an OOBE error at that step!

### Expected behavior

When I press "retry" it will ignore that OOBE error

### Actual behavior

Stuck on "OOBEKEYBOARD" error

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

![IMG_20231229_232112](https://github.com/Atlas-OS/Atlas/assets/77947043/03bff877-a663-4eed-b0d7-b46525ae0ab5)
![IMG_20231229_232105](https://github.com/Atlas-OS/Atlas/assets/77947043/2431a2e9-ee72-446d-a0a1-6e28d040b6d7)
![IMG_20231229_232057](https://github.com/Atlas-OS/Atlas/assets/77947043/e290666c-7cc1-4f0c-abce-d9a76bdeb00c)
![IMG_20231229_232035](https://github.com/Atlas-OS/Atlas/assets/77947043/1d73844f-6397-4117-8a2e-038233059ba4)
![IMG_20231229_232026](https://github.com/Atlas-OS/Atlas/assets/77947043/1881b46e-adfb-4bbf-9d31-86b5eb41af83)

**Comment by Xyueta** [comment]
It doubt it would work on Atlas, but i could try to make it functional, i'll keep you posted.

**Comment by he3als** [comment]
Atlas isn't meant to be used with SysPrep, but Atlas will likely have another solution to your use case in the future.
