### ISSUE TITLE
[BUG] - Start menu, jump lists and projector menu act as if tab has been pressed upon opening

### ISSUE THREAD

**Issue by el0c** [Atlas-OS/Atlas#1005]
### Description

The start menu and jump lists issue only seems to occur on first use/after a while of not using them. 
The Win+P shortcut consistently triggers this issue and prevents the arrow keys from being used in the expected fashion when trying to quickly enable/disable displays.

![projectmenutabbug](https://github.com/Atlas-OS/Atlas/assets/36245622/e13140af-3737-465b-b56b-d9e87980f711)
![jumplisttabbug](https://github.com/Atlas-OS/Atlas/assets/36245622/06275bb5-131f-4a19-98ff-dc4708ffa3c4)
![startmenutabbug](https://github.com/Atlas-OS/Atlas/assets/36245622/1f2eacde-aef7-4798-b16a-be5a59ee3190)

### Steps to reproduce

1. Start windows with atlasOS installed.
2. Open the start menu for the first time. 
3. Open a jump list for the first time
4. Press Win+P to open the project menu. 

### Expected behavior

The tab selection box should not appear until tab is pressed.

### Actual behavior

The tab selection box appears and selects the top most option in the list; which make the arrow key up and down not function on the project menu like it normally does; requiring a mouse interaction where none should be needed.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

- i7-9700k base clock 3.6ghz, typically running at 4.6ghz
- 32GB DDR4 3200mhz Trident Z
- 970 Evo 500GB m.2
- RTX 2080 non-super, driver version: 546.33
![image](https://github.com/Atlas-OS/Atlas/assets/36245622/c9139112-5b19-4693-ba2c-e350087e78af)
![image](https://github.com/Atlas-OS/Atlas/assets/36245622/7082b8cf-1d21-45f7-a564-0e3b4c81ed66)
![image](https://github.com/Atlas-OS/Atlas/assets/36245622/8231a5ce-e003-439d-a97c-17033ea4d3d2)

### Additional content

I've reinstalled atlasOS and Windows 11 and confirmed this was an issue before any applications were installed; especially those that are shell extensions like Nilesoft Shell and ExplorerPatcher. I've also uninstalled and reinstalled my input device drivers multiple times and can confirm it's not an issue with them (though if it was this issue would affect every app system wide so...)

**Comment by he3als** [comment]
Hi - I haven't been able to reproduce this on the latest version of Atlas. Closing but if this issue still happens on the latest version, feel free to make a new issue.
