### ISSUE TITLE
[BUG] - THIS IS A PROBLEM 

### ISSUE THREAD

**Issue by fuckatlas** [Atlas-OS/Atlas#1008]
### Description

WHERE IS MY APPS??????

### Steps to reproduce

![image](https://github.com/Atlas-OS/Atlas/assets/155592361/930ccbb3-cbbf-4970-af78-3d24fb36916f)  WHERE IS MY PROGRAMS??????

### Expected behavior

THEY HAVE DELETED MY PROGRAMS AFTER I DOWNLOADED THE ATLAS APP THING FUCK THIS.

### Actual behavior

WHEN I STARTED THE APP EVERYTHING WAS NORMAL THEN WHEN THEY RESTART MY COMPUTER ALMOST 90% OF MY DESKTOP IS GONE WHY?????????????????????????????????

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

SO BAD THING I HAVENT SEEN SOMETHING LIKE THIS BEFORE I DONT WANT TO RESET MY PC BUT THIS APP HAVE RESET MY PC WITH ALMOST 90%. DONT USE THIS SHIT.

**Comment by GhostlyCrowd** [comment]
This is not a bug, the devs cannot fix your mental disability for lack of comprehension. Please don't spam the issues. You're a vapid slut who lost their virginity to a goat, you even lit candles for it.

**Comment by WarmXR** [comment]
Bro did not read the docs

**Comment by GhostlyCrowd** [comment]
> Bro did not read the docs

He has AVG installed and it's crape ware. This says all we need to know about his mental capacity to read....

**Comment by JayXTQ** [comment]
Firstly, you need to install atlas on a clean system. Read the docs to install
Secondly, @GhostlyCrowd please don't be rude, or offensive at all. No need for the language. Post will be closed and locked
