### ISSUE TITLE
Microsoft Bopompfo disappeared from the input selection menu 

### ISSUE THREAD

**Issue by HaeImAlan** [Atlas-OS/Atlas#101]
**Describe the bug**
You cannot choose the Microsoft Bopomofo input method during setup as it's not shown. You also won't be able to install the input method once you're in the system as the name of the input method shows up as a single space. 

**To Reproduce**
1. Try to use Microsoft Bopomofo
2. It doesn't let you .

**Expected behavior**
The operating system installs the input method and the input method works.
**Screenshots**

**Desktop Info (please complete the following information):**
 - CPU Intel Core i5 10400F
 - System SSD
 - Version 20H2 FACEIT

**Additional context**

**Comment by Zusier** [comment]
I'll look into this.

**Comment by Zusier** [comment]
I'm afraid that Bopomofo is part of the IME >> Chinese component under NTLite which is stripped due to size on Atlas. If you'd like this feature on atlas you're going to have to [build the iso from source](https://github.com/Atlas-OS/Atlas/tree/main/src#building-from-source).
