### ISSUE TITLE
AtlasOS installation failed horribly,half corrupted Laptop

### ISSUE THREAD

**Issue by Crimson360** [Atlas-OS/Atlas#1012]
### Description

I had ReviOS installed,i switched to AtlasOS.Installation failed horribly with a lot of issues,removed most of my applications and corrupted half of my Laptop
![IMG_0619](https://github.com/Atlas-OS/Atlas/assets/149340042/ca978f73-3e18-4fcf-8b4b-2a14939171fe)
![IMG_0615](https://github.com/Atlas-OS/Atlas/assets/149340042/51cf43c0-e6a1-468c-a368-91e33e446026)
![IMG_0620](https://github.com/Atlas-OS/Atlas/assets/149340042/f872f6d4-aabd-4bfa-949a-16ae202ae48a)
![IMG_0621](https://github.com/Atlas-OS/Atlas/assets/149340042/460dcf90-032f-47d7-9309-c3edca1966b6)
![IMG_0622](https://github.com/Atlas-OS/Atlas/assets/149340042/85d1022e-c443-47c8-aa45-8a826f8a08a6)
![IMG_0623](https://github.com/Atlas-OS/Atlas/assets/149340042/1b35088c-abb3-4673-b681-311b7522de46)
![IMG_0624](https://github.com/Atlas-OS/Atlas/assets/149340042/1759e8ae-f021-4026-b0ea-0f67b8517472)
![IMG_0625](https://github.com/Atlas-OS/Atlas/assets/149340042/93d0df0e-bb88-4c1c-9d80-53edfd116835)
![IMG_0626](https://github.com/Atlas-OS/Atlas/assets/149340042/019dfb77-2b60-491c-b88b-4a5ce076b548)
![IMG_0627](https://github.com/Atlas-OS/Atlas/assets/149340042/4225076f-4aeb-4844-85af-b936135e6fed)
![IMG_0628](https://github.com/Atlas-OS/Atlas/assets/149340042/efadb834-0fa9-4e4f-acec-3395847a9b26)

### Steps to reproduce

Acquire Lenovo Ideapad 3 and change to windows 10,then add ReviOS.Then install AtlasOS

### Expected behavior

Atlas Os fully installed

### Actual behavior

AtlasOS corrupted laptop with ReviOS previously on it

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

AMD Ryzen5
AMD Radeon GRAPHICS
LENOVO Ideapad3 17”

### Additional content

When i open OneDrive icon,it opens two blank windows.One closable,and the other one not closable,leaving a massive white chunk one the screen.I tried reinstalling AtlasOS,and the same things happened.

**Comment by Crimson360** [comment]
I removed all the antiviruses before,including Windows Defender and Mcafee,so they where no longer existent

**Comment by JayXTQ** [comment]
We won't offer support with this as you didn't run atlas on a clean system like you were told to in the documentation.

**Comment by Ast3risk-ops** [comment]
@Crimson360 

the documentation: https://docs.atlasos.net/getting-started/installation/

**Comment by Crimson360** [comment]
> @Crimson360
> 
> the documentation: https://docs.atlasos.net/getting-started/installation/

that’s kinda too late bro
