### ISSUE TITLE
bro why you removed my issue report

### ISSUE THREAD

**Issue by Crimson360** [Atlas-OS/Atlas#1013]
### Description

Atlas fucking corrupted my pc and you removed my issue report

### Steps to reproduce

fuck you
second step:fix that shit
last step:stop deleting issues report and thinking people are dumb

### Expected behavior

shouldn’t be removed

### Actual behavior

has been removed

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

.

### Additional content

If you keep deleting my reports instead if helping me,your gay

**Comment by NyneDZN** [comment]
ooga booga

**Comment by Crimson360** [comment]
> ooga booga

bruh

**Comment by Crimson360** [comment]
> ooga booga

bro can respond to this but couldn't help me on their shitass OS that corrupt shit,and deletes everything when they can't assume shit💀

**Comment by Crimson360** [comment]
> You should have done the installation on a clean system, as recommended in the AtlasOS installation documentation. Before installing the AtlasOS modifications on your system, you should back up your files and reinstall Windows again, from scratch, so that you have a clean and secure installation to proceed with adding AtlasOS to your system.

Ok,thanks bro👍I was gonna reinstall windows 10 after,but can't rn.I appreciate it💪😁

**Comment by NyneDZN** [comment]
> > ooga booga
> 
> bro can respond to this but couldn't help me on their shitass OS that corrupt shit,and deletes everything when they can't assume shit💀

if you are unable to follow the docs and successfully install atlas, then that is the users fault. not the OS.

**Comment by JayXTQ** [comment]
closing and locking
