### ISSUE TITLE
[BUG] - Can't turn ON Notification. 

### ISSUE THREAD

**Issue by Lane0422** [Atlas-OS/Atlas#1014]
### Description

can't turn on my notification. Always says OFF. 

### Steps to reproduce

![bug](https://github.com/Atlas-OS/Atlas/assets/156275220/ed76bffe-240d-4285-aefb-6b01675ed3de)

### Expected behavior

restarted couple of times but still the same issue

### Actual behavior

can't toggle notification, ON.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

![sys](https://github.com/Atlas-OS/Atlas/assets/156275220/afea5ce2-1081-49f6-b84e-e0dae7ffe5e7)

### Additional content

Please let me know how to fix this.

**Comment by Lane0422** [comment]
Thank you!!

**Comment by voidxO7** [comment]
I did this and it still didn't work
