### ISSUE TITLE
[BUG] - Webcam not working properly

### ISSUE THREAD

**Issue by brxndonroux** [Atlas-OS/Atlas#1015]
### Description

I have a Microsoft Lifecam HD3000 that runs at 720p, 30FPS but since if installed Atlas my webcam is laggy (8FPS to be exact), the quality is also bad...its still 720p but its extremely bright and has a weird look to it, I've never had this problem before and I'm not sure what the problem is.

I've done my research and nothing came up so i hope someone can help, there is one thing that works and that is OBS's camera properties but i dont want to load OBS everytime just to use my webcam because its supposed to run perfectly on its own.

### Steps to reproduce

No screenshots since my problem is explained in the description.

### Expected behavior

Webcam should work fine on its own (720p, 30FPS) without any settings being changed, like when I had the original Windows 10

### Actual behavior

bro i already gave my problem

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

![image](https://github.com/Atlas-OS/Atlas/assets/103594572/656795fe-a21a-4918-ab1e-5cb1dbb08dab)

### Additional content

Never had this problem on the normal Windows, thats all.

**Comment by CodingMadness** [comment]
Any news on this?

**Comment by JayXTQ** [comment]
My guess is that you don't have the proper drivers installed. Check SDIO, if not then you may need to enable Windows driver installs via windows update due to it being a windows device
