### ISSUE TITLE
[BUG] -  Cannot open ANY settings on new Playbook. 

### ISSUE THREAD

**Issue by deksii** [Atlas-OS/Atlas#1018]
### Description

When i open settings from start, its not working. Search is ALSO not working. When i try to run personalize or display settings, it shows some warning like. this file does not have an app associated , etc.. Also disk management is not working. It's not optimized. It's just windows 10 with half the features.

### Steps to reproduce

1. just go to start and try to go to settings, or type..
2. try to go to display settings or personalize

### Expected behavior

To open settings..

### Actual behavior

shows some warning like. this file does not have an app associated , etc.

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

Ryzen 5 3600
16GB FURY RGB ram 
R9 380 2GB SAPPHIRE NITRO
B550M AORUS ELITE

**Comment by Ast3risk-ops** [comment]
Can someone with write access change the issue title?

@deksii ensure you installed atlas onto a fresh install of Windows.

**Comment by deksii** [comment]
I reinstalled my windows, and then installed the playbook

**Comment by Ast3risk-ops** [comment]
You may not have followed the install steps correctly, this is not normal Atlas behavior.

Also do not use custom windows ISOs with Atlas or install other tweaks onto it.

These are the official steps: https://docs.atlasos.net/getting-started/installation/

**Comment by deksii** [comment]
Ohhh shit.. I used some tweak risxn extreme.. I don't think it was happening to me before with it
i did everything right tho

**Comment by Ast3risk-ops** [comment]
> Ohhh shit.. I used some tweak risxn extreme.. I don't think it was happening to me before with it i did everything right tho

Reinstall. Follow the docs, do not use other tweaks.

**Comment by deksii** [comment]
the whole windows? oh well.. Should i do it with a usb drive or?

**Comment by Ast3risk-ops** [comment]
> the whole windows? oh well.. Should i do it with a usb drive or?

No USB drive required.

Get started 👉 https://docs.atlasos.net/getting-started/installation/

**Comment by deksii** [comment]
When i think about it, i know i change the background , and when i fixed tweaks it was no longer working.. Bruh

**Comment by deksii** [comment]
I REMEMBERED! I had a restore point before i used tweaks. Can i use that? And how to

**Comment by Ast3risk-ops** [comment]
> I REMEMBERED! I had a restore point before i used tweaks. Can i use that? And how to

Just reinstall at this point. If you really wanna use a restore point, the steps are on google.

**Comment by deksii** [comment]
i downloaded all the games, fixed it all up, everything is working. I think it would be easier to use a restore point.

**Comment by deksii** [comment]
I can't do it.. I don't have control panel 😂 oh god

**Comment by Ast3risk-ops** [comment]
> i downloaded all the games, fixed it all up, everything is working. I think it would be easier to use a restore point.

🤦 You're supposed to download your games and apps *after* running the playbook.

**Comment by deksii** [comment]
i exactly did that

**Comment by Ast3risk-ops** [comment]
Just reinstall.

**Comment by deksii** [comment]
shit

**Comment by Ast3risk-ops** [comment]
https://docs.atlasos.net/getting-started/installation/

**Comment by deksii** [comment]
will my other drives get resetted or nah? i think they won't but just curious

**Comment by Ast3risk-ops** [comment]
This should only touch C:.

**Comment by JayXTQ** [comment]
Closing issue because this is an issue which is irrelevent to atlas itself and is a user issue

**Comment by NLT33** [comment]
"DO NOT DOWNLOAD ATLASOS" should be "DO NOT INSTALL ATLASOS IF YOU'RE BRAIN DEAD AND A FUCKING RETARD"
