### ISSUE TITLE
Settings opens late

### ISSUE THREAD

**Issue by Artist76** [Atlas-OS/Atlas#102]
When I try to open settings, I have to click a few times to open it. Idk if it is because of my computer but I dont think so because it was fine on normal windows. HELP

**Comment by Zusier** [comment]
Nobody has ever reported this. If you've disabled UWP you need to enable it.

**Comment by Artist76** [comment]
How do I open it?

**Comment by Zusier** [comment]
Open what?

**Comment by Artist76** [comment]
UWP

**Comment by Zusier** [comment]
Desktop >> Atlas >> Config >> UWP

**Comment by Artist76** [comment]
I did it
