### ISSUE TITLE
[FEATURE] - Use NanaZip fork instead of 7-Zip

### ISSUE THREAD

**Issue by agowa** [Atlas-OS/Atlas#1021]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

Consider using the NanaZip fork of 7-Zip instead of 7-Zip itself as it has better integration into windows 11.
E.g. not needing to modify the path environment variable in order to use 7z.exe from the cli (because of it registering itself within "Apps > Advanced app settings > App execution aliases").

### Describe the solution you would like.

Instead of installing 7-Zip through the playbook install NanaZip

### Describe alternatives you have considered.

does not apply

**Comment by n00b69** [comment]
+1

Also, not sure if still applicable, but in the past Nanazip Preview worked better on win11 than the regular one. I have only ever used the Preview version, so I cannot confirm this.

**Comment by sp1cyf0x** [comment]
-1

Consider to NOT use NanaZip till a stable release is out.

**Comment by JayXTQ** [comment]
let's not have a debate about this topic. if there is no stable release, this issue will be put on hold until there is a stable release. closing for now until then.

**Comment by agowa** [comment]
@JayXTQ But there is a stable release https://apps.microsoft.com/detail/9N8G7TSCL18R?hl=en-us&gl=US

**Comment by JayXTQ** [comment]
just because it's on ms store doesn't mean it's stable lol. until there is valid evidence that it is stable this will be closed. or if it's not needed in atlas, which it isn't really as 7z works fine

**Comment by agowa** [comment]
7z is neither added to the path, nor does it register itself for an app execution alias, so that part at least is debatable.
Also just look at the list of other benefits on that windows store page. Like it supporting additional compression algorithms, archive types, better dpi awareness for multi monitor setups, additional hashing algorithms, improved security, 

Also what do you want as "prove" that it isn't unstable if this isn't enough?:
This is the stable version: https://apps.microsoft.com/detail/9N8G7TSCL18R?hl=en-us&gl=US
And this is the preview version: https://apps.microsoft.com/detail/9NZL0LRP1BNL?hl=en-us&gl=US
And this is the projects GitHub page: https://github.com/M2Team/NanaZip

**Comment by JayXTQ** [comment]
none of those benefits are needed in atlas and it doesn't need to be added to path for it to work for the average user. you forget this is not something for developers but for gamers.

**Comment by Ast3risk-ops** [comment]
I had no idea about those and I used the stable build of nanazip when on windows 💀

**Comment by agowa** [comment]
Same, wasn't aware of these ones.

**Comment by Ast3risk-ops** [comment]
> I'm not sure I'm understanding why NanaZip 2.0 (stable) is not being considered as an option.

Security issues and it's not actually stable and 7zip works just fine.

**Comment by he3als** [comment]
You can argue security issues, but 7-Zip doesn't automatically update or notify the users of updates. Once NanaZip gets more developed, it should be fundamentally more secure, as NanaZip is installed and updated via the Store.

Currently though, I don't think that NanaZip is in a developed enough state, and the process of automatic installation inside the playbook will be a bit more difficult due to it being AppX.

I'll keep this open to track it's development.

**Comment by he3als** [comment]
I've checked up on the project again and I'm happy to implement NanaZip. The only issue is that there's no permanent download links to the latest release (appx and license), and we can't use the GitHub API to get this as its blocked in certain regions.

**Comment by Ast3risk-ops** [comment]
> I've checked up on the project again and I'm happy to implement NanaZip. The only issue is that there's no permanent download links to the latest release (appx and license), and we can't use the GitHub API to get this as its blocked in certain regions.

There's the Microsoft store.

**Comment by he3als** [comment]
Sure.

**Comment by Ast3risk-ops** [comment]
> Sure.

Great backup in case of an API rate limit too 😬

**Comment by JayXTQ** [comment]
@he3als use jsdelivr

**Comment by he3als** [comment]
You can't use the GitHub API with JSDelivr, or download releases without asking them

**Comment by JayXTQ** [comment]
I know you can't use the GitHub API, but can't you use JSDelivr to download a release?

**Comment by JayXTQ** [comment]
Also, they do have sourceforge, but no clue if available in all regions: https://sourceforge.net/projects/nanazip/

**Comment by he3als** [comment]
> can't you use JSDelivr to download a release

If I recall correctly, no, unless you request them to set up a proxy for the repositories' releases. However, the GitHub API is required to get the download link first; without that, we can't get the latest release URL.

> they do have sourceforge, but no clue if available in all regions

I don't think it is, unfortunately.

**Comment by he3als** [comment]
I’ve implemented it currently so that if NanaZip isn’t accessible, it gets 7-Zip instead.

**Comment by Benik3** [comment]
Nanazip is missing one of the best feature of 7zip/winrar - right click drag context menu.  
Also the new style of file association in NanaZip is absolute pain...

**Comment by Ast3risk-ops** [comment]
> Also, they do have sourceforge, but no clue if available in all regions: [sourceforge.net/projects/nanazip](https://sourceforge.net/projects/nanazip/)

Worst. mirror. ever.

**Comment by he3als** [comment]
Fixed in [release v0.4.1](https://github.com/Atlas-OS/Atlas/releases/tag/0.4.1). See the release for more info on what v0.4 users can do.

**Comment by catsmoker** [comment]
Please remove any archive app because Windows 11 24h2 supports almost all formats (zip/rar/7z/tar-gz-bz2-zst-xz/tgz/tbz2/tzst/txz).

**Comment by Ast3risk-ops** [comment]
> Please remove any archive app because Windows 11 24h2 supports almost all formats (zip/rar/7z/tar-gz-bz2-zst-xz/tgz/tbz2/tzst/txz).

Atlas still needs one due to `7za`.
