### ISSUE TITLE
[BUG] - Install Software.ps1 not elevated properly

### ISSUE THREAD

**Issue by agowa** [Atlas-OS/Atlas#1023]
### Description

Currently the Install software.ps1 script does not self elevate before starting the software installation. This causes issues with the installation as almost every installer will cause an UAC popup to open and the user has to approve every single one. This kinda defeats the purpose of an automated installation.
I'd therefore suggest to have Install Software.ps1 self elevate after the user selected the desired software within the UI popup and before entering the installation loop.

### Steps to reproduce

1. Install AtlasOS without disabling the UAC
2. Run the "Install Software.ps1" script from "AtlasDesktop/1. Software" and try to install some apps.

### Expected behavior

Installing with only a single request for elevation

### Actual behavior

One elevation request per software.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

does not apply

**Comment by he3als** [comment]
Not every single app there needs UAC to install, and some apps (such as Spotify) need to not be elevated.

![vmconnect_VEaYUgFEPx](https://github.com/Atlas-OS/Atlas/assets/65787561/a9713931-4f9c-4822-8775-90a2461e647c)

**Comment by agowa** [comment]
Oh, I was not aware of that specific case. I never encountered applications that "prohibit Elevation" before. Only user installs that failed to install for machine wide, I.E. install without writing the executable files into the user profile with basically RWX permissions (looking at you MS Teams)...

Anyway, I opened https://github.com/microsoft/winget-cli/issues/4084 lets see if we can get this resolved within winget-cli then.
