### ISSUE TITLE
[BUG] - Scripts Not finding requested file. 

### ISSUE THREAD

**Issue by LYNK-INCUU** [Atlas-OS/Atlas#1025]
### Description

So all the scripts that use the files similar to RunAsTI.cmd don't work and give an error that the file can't be found. 
![image-26](https://github.com/Atlas-OS/Atlas/assets/83987610/589c9f1f-dd54-4232-9ccf-6987ec56e37a)
But if I copy the file path and edit the script like this..
![notepad_2024-01-15_19-33-45](https://github.com/Atlas-OS/Atlas/assets/83987610/036d7a7f-e245-446f-a0cb-64f67af8f623)
It does work. Issue being. The files in the Atlas folder are read-only and I'm also not going to do this for every script. 
![image-15](https://github.com/Atlas-OS/Atlas/assets/83987610/973def58-bfac-40d5-8440-e765286364f0)

### Steps to reproduce

Run script that errors out.
Edit.
Run script again.

### Expected behavior

Should complete the changes without any errors.

### Actual behavior

Can't find file or partially completes the script.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

I5 12th gen 2.60ghz
32gb ram ddr4
Gigabyte SSD and Samsung 980 1tb
RTX 4060

**Comment by n00b69** [comment]
One of these scripts is the "Enable sleep.cmd"
![20240119_004814](https://github.com/Atlas-OS/Atlas/assets/83274506/b7e61173-b57e-4147-80d4-86dd8e4f119f)

**Comment by acuteaura** [comment]
You can add `C:\Windows\AtlasModules` to `$PATH`, which is probably the intended way for this to work.

**Comment by ZeldrexK0DE** [comment]
I'll give it an shot

> You can add `C:\Windows\AtlasModules` to `$PATH`, which is probably the intended way for this to work.

**Comment by ZeldrexK0DE** [comment]
> You can add `C:\Windows\AtlasModules` to `$PATH`, which is probably the intended way for this to work.

this doesn't seem to work unless i've done it wrong
![image](https://github.com/Atlas-OS/Atlas/assets/83987610/ddfc2761-fb17-432b-a56c-e84a53a8bf91)
ex notifications on script judt quits without doing anything

**Comment by acuteaura** [comment]
You did. It needs to be added to the (existing) one called PATH, on the system one above.

**Comment by ZeldrexK0DE** [comment]
> You did. It needs to be added to the (existing) one called PATH, on the system one above.

I put $path before it aswell

**Comment by LYNK-INCUU** [comment]
![image](https://github.com/Atlas-OS/Atlas/assets/83987610/fb36880e-3808-4ebd-ae00-5b5061861214)
its in here but still doesnt work

**Comment by acuteaura** [comment]
pretty sure there's a bin folder inside there that contains the actual scripts; set it to that?

**Comment by lMagickl** [comment]
For me it fixed adding C:\Windows\AtlasModules\Scripts to $PATH

**Comment by LYNK-INCUU** [comment]
> For me it fixed adding C:\Windows\AtlasModules\Scripts to $PATH

I'll change it to this then and see if it changes

**Comment by LYNK-INCUU** [comment]
![image](https://github.com/Atlas-OS/Atlas/assets/83987610/d689de6c-38ce-4a83-889f-252a0aefe9b6)
![image](https://github.com/Atlas-OS/Atlas/assets/83987610/f29b5bf1-060e-4552-84c0-ede8152534f2)
![image](https://github.com/Atlas-OS/Atlas/assets/83987610/f881cb31-b850-4e87-8c6b-fb6b6f957457)
I put the Path under system and running toggle defender for example gives strange errors and also doesnt find the file whatever one it asks for.

**Comment by n00b69** [comment]
Sorry but what? Why is this not planned? You literally cannot use some of the scripts in the AtlasOS folder because of this error.

**Comment by he3als** [comment]
Apologies for closing without a reason - that was an accident.

---

I have implemented a different method for adding to the PATH variable for the next release, which should fix this issue.

The likely reason the PATH variable was not set correctly is that it was too long for `setx` to handle properly. This could be caused by software installed before the Atlas Playbook, which likely means that a fresh Windows install wasn't used.

I have rewritten the entire component removal script for v0.4.0, which likely means those weird errors in the Defender script will disappear.
