### ISSUE TITLE
[BUG] - 2203 error even after troubleshooting file

### ISSUE THREAD

**Issue by Galamooth** [Atlas-OS/Atlas#1027]
### Description

Windows does not install .MSI packages. error 2203. the fix contained in atlas troubleshooting does not repair it. I need assistance. This happened only after applying atlas.
I already tried to assign permissions to the temp and %temp% folders, the environment variables point to the correct place

### Steps to reproduce

just try to install some .MSI package
![SPOILER_SPOILER_20240116_142614](https://github.com/Atlas-OS/Atlas/assets/90434643/0c5fe693-1a23-469b-a159-eff3f1c57fb7)

### Expected behavior

msi packages should install normally

### Actual behavior

not apply

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Ryzen 9 5900hx  ssd 2 tb  nvme raid 0 samsung gpu rx 6800m 12gn vram  32gb ram ryphaws 3200mhz oc 3800mhz

**Comment by n00b69** [comment]
Try installing VCLibs

**Comment by Galamooth** [comment]
> Try installing VCLibs

Thanks a lot. I don't know what happened. She already had the vcredist AiO package installed. But I tried installing again and the problem was solved. I was stuck on this for a long time. Thank you so much
