### ISSUE TITLE
[BUG] - Windows Spotlight Wallpapers break with no way of reversing these changes

### ISSUE THREAD

**Issue by jonatino** [Atlas-OS/Atlas#1028]
### Description

Try to enable Windows Spotlight theme on windows and it will result in nothing happening.

### Steps to reproduce

1. Open Windows Settings personalization -> theme and click the theme with the spotlight icon

![image](https://github.com/Atlas-OS/Atlas/assets/1808569/debac2a4-77eb-4996-a954-7e1eb1354c5c)

### Expected behavior

Should apply the dynamic windows spotlight theme with changing wallpapers.

### Actual behavior

Does nothing

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

N/A

**Comment by he3als** [comment]
Spotlight is disabled via Group Policy, will look into having an option to toggle it next version.

**Comment by XSkipperX** [comment]
Is possible to know, more less, when this fix (or the toggle) could be released?

**Comment by Grosbof** [comment]
Or maybe to have a temporary fix available ? Re-enabling it in the Group Policy Editor is not doing the trick (Windows Component/Cloud Content)

**Comment by he3als** [comment]
Spotlight is now supported on v0.4.0.
