### ISSUE TITLE
[FEATURE] - Web Browsers - Replace Waterfox

### ISSUE THREAD

**Issue by bandogora** [Atlas-OS/Atlas#1029]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

Waterfox is the only Firefox variant available in the Web Browsers post-installation prompt. I don't think that's the best recommendation for "user-respectiveness", privacy, or security. Waterfox lacks privacy features offed by default on other browsers and isn't listed on [PrivacyTests.org](https://privacytests.org/).

### Describe the solution you would like.

Waterfox should be replaced with a more private option such as [LibreWolf](https://librewolf.net/) or [Mullvad Browser](https://mullvad.net/en/browser). Both of those browsers have better privacy out of the box and are listed on [PrivacyTests.org](https://privacytests.org/).

### Describe alternatives you have considered.

Firefox with [arkenfox](https://github.com/arkenfox/user.js/) installed by default.

**Comment by JayXTQ** [comment]
Firefox will be used instead of Waterfox for future updates.

**Comment by JayXTQ** [comment]
Also, arkenfox will not be default afaik, this probably won't change either.

**Comment by bandogora** [comment]
> Also, arkenfox will not be default afaik, this probably won't change either.

Atlas is already doing a lot of customization on behalf of the user to optimize privacy and performance, so why not do the same for the browser? 

Adding arkenfox is as simple as adding a few files to the user profile's root folder. It could at least be an option if the user opts for Firefox.

Of course, this would mean that the user has to worry about updating and maintaining their `user.js`. Hence why I suggested LibreWolf or Mullvad Browser. Both include arkenfox's features AFAIK and receive upstream updates within a few days of Firefox

**Comment by bandogora** [comment]
> Firefox will be used instead of Waterfox for future updates.

@JayXTQ is there a public roadmap or milestones available for viewing anywhere?

**Comment by JayXTQ** [comment]
https://github.com/Atlas-OS/Atlas/issues/1029#issuecomment-1913289211
The OS isn't made for privacy respectively, it's made for gamers and also has increased privacy, doesn't mean that we shouldn't make the OS for the average user, arkenfox is too strong for the average user and people may complain about firefox as default on atlas if arkenfox was installed. Firefox will be the replacement, and that was decided just after waterfox was introduced in atlas.

https://github.com/Atlas-OS/Atlas/issues/1029#issuecomment-1913294804
There is currently no public roadmap for Atlas, no, atleast not like a ticket thing like Jira or Trello. If you wish to get more involved in development though, feel free to join the Discord and get the development role to go to the development channels
