### ISSUE TITLE
[BUG] - Xbox Series Controller Drivers not installing

### ISSUE THREAD

**Issue by rubyzera** [Atlas-OS/Atlas#1031]
### Description

Hello, i've recently installed AtlasOS 10 and had some trouble getting my Xbox One controller connected wirelessly through the official adapter, i had to look it up on a random website and install it manually.

Now i'm facing another issue, i bought a newer Xbox Series controller and i'm trying to connect it in wired mode (using the included usb-c to usb-a cable) with no luck and couldn't find a suitable driver anywhere, and yes, i've tried running SDIO with no luck. I've also tried running the "Enable Automatic Driver Updates" reg file and rebooting my PC and it also didn't work.

### Steps to reproduce

1. Connect the controller to the PC
2. The controller vibrates but no device connected sound is played

### Expected behavior

I expected to plug in the controller and it just work, like an official Microsoft product should.

### Actual behavior

Literally nothing happens, not even a sound saying it was connected, and it didn't show up on Device Manager

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

i5 6600
16GB DDR4
2TB NVMe PciE SSD
AMD RX 5700 XT
Windows 10 Build 19045.3803

### Additional content

I tried multiple cables and usb ports on my pc without any success.

**Comment by Z1mon11** [comment]
I'm having the same Problem here
Tried with 2 different controllers and with a steering wheel. The LEDs on the devices turn on and they vibrate, but the don't work. The steering wheel does also not work with the software

I have automatic driver updates enabled, but when I check for Windows Updates it can't find any.

**Comment by rubyzera** [comment]
> Can you try enabling automatic driver updates in the Atlas folder, restarting, and clicking to check for Windows Updates? Make sure that you have your controller connected the entire time
> 
> This should automatically install your device's drivers

Unfortunately i've already tried doing this, and no matter how much i enable and disable this setting (with reboots after running the file), Windows Update doesn't seem to install anything.

**Comment by CodingMadness** [comment]
Any news on this?

**Comment by Ceekzs** [comment]
Install Driver Booster by iObit (uncheck third party programs), check the drivers you need in the list, especially the xBox one I guess, install, it should take 5 to 15 mins, reboot, you're done. Worked fine to me.

https://www.iobit.com/en/driver-booster.php

**Comment by jacksyrm** [comment]
Do not follow this advice, we have a forum which already solved the similar/same issue

**Comment by Ceekzs** [comment]
Are you for real ?

**Comment by jacksyrm** [comment]
> Are you for real? For the first time in my life, I thought "Hey I think I should do like those incredible people who helped me and so many others in the past and will continue to, and the first thing I see is "Do not follow this advice" not more than 2 minutes later xD ! It should be better, but we have ways to say it.

I'm sorry for the miscommunication. It's advised not to recommend IOBIT Driver Booster as many users have encountered issues with drivers because of it. 

We have an official guide for installing drivers, which can be found [on our documentation](https://docs.atlasos.net/getting-started/post-installation/drivers/others/). This is a safe and reliable way to install drivers and is the recommended method.

**Comment by Ceekzs** [comment]
I actually tried it out yesterday, couldn't pass the step where I should see a check mark.
And did someone try this ?

https://www.minitool.com/news/enable-disable-automatic-driver-updates-windows-11.html

I found it just now.
It could be useful or is it not recommended ?

**Comment by jacksyrm** [comment]
> I actually tried it out yesterday, couldn't pass the step where I should see a check mark. And did someone try this ?
> 
> https://www.minitool.com/news/enable-disable-automatic-driver-updates-windows-11.html
> 
> I found it just now. It could be useful or is it not recommended ?

We have files in the Atlas folder on the desktop which allows you to enable **automatic driver installations** and **automatic updates in general**.

Users have the option to either download and install driver and standard updates automatically or manually. While automatic driver installation is recommended for laptops with complex drivers such as biometric devices and touchpads, some users may prefer to have manual control over the update process. It is important to note that there are many other examples of intricate drivers that may require automatic installation. Regardless of the method chosen, our team recommends that all drivers be kept up-to-date for optimal performance.

**Comment by JayXTQ** [comment]
As to mention again, do not use driver booster, they do not give the correct up to date drivers and there has been cases where they modify drivers as well which is obviously a risk. Please use SDIO if possible.
