### ISSUE TITLE
[BUG] - VLANS are broken in Atlas

### ISSUE THREAD

**Issue by agowa** [Atlas-OS/Atlas#1032]
### Description

VLANs don't work. Neither ones created nor after installing Atlas work once the Atlas setup is complete.

### Steps to reproduce

1. Install Atlas
2. Install Hyper-V Services
3. Create a virtual switch with a VLAN for the host (or try to create additional vlan ports manually using powershell)

### Expected behavior

vlans working or a ticket about them and notes about how to enable them (or a post install customization script to re-enable them).

### Actual behavior

Vlan appearing to be configured but not working. Traffic is leaving untagged.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

KVM virtual machine

**Comment by thamouta** [comment]
Hello, 

I think the issue comes from the "Executable/Finalize.cmd" because it dumps a lot of network adapter options in the registry.
Check the block between line 57 and 131.

Maybe using the "Executables\AtlasDesktop\8. Troubleshooting\Network\Reset Network to Atlas Default.cmd" should fix your issue?

**Comment by he3als** [comment]
Network settings are being refactored for next release, and I presume that's the issue. For now, try the script mentioned above

**Comment by agowa** [comment]
I now got it working by running the reset network to windows script, removing the virtual switch, recreating the virtual switch, recreating the virtual adapter, re-adding the vlan setting to the adapter.

Maybe it helps. Before deleting the adapter using the command to set a vlan didn't find the network adapter. Could it be that it is somehow partially deleted?

**Comment by he3als** [comment]
Closing as this will be fixed next release.
