### ISSUE TITLE
[FEATURE] - please remove windows activation people are very sad because of this

### ISSUE THREAD

**Issue by ikrashpk** [Atlas-OS/Atlas#1033]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

[FEATURE] - please remove windows activation people are very sad because of this

### Describe the solution you would like.

[FEATURE] - please remove windows activation people are very sad because of this

### Describe alternatives you have considered.

[FEATURE] - please remove windows activation people are very sad because of this

**Comment by JayXTQ** [comment]
No, we can't due to the nature of the product.

**Comment by Ast3risk-ops** [comment]
@ikrashpk We can't remove this because:

1. Microsoft ("the nature of the product")
2. Atlas would remove activation-related components (and I think there was an AME bug where the activation watermark would stick around forever) so we told people to activate beforehand to avoid problems. We can now avoid problems by forcing them to.

**Comment by mkuznetsov** [comment]
Can I see a legal definition of MS "nature of the product"?
From legal stand point where are 4 things that u could not do:
1) get a windows and rebranded (debranding is one of cases) as new product without paying to MS and getting all kind of papers. Dramatically changing of UI can be ruled as debranding. It can be avoided if you mark you product as DIY script and don't do any branding. 
2) you somehow make customisation or alteration that some how break copyrighting, policies and partners agreements of MS, as result MS may be have some court time. Alteration usually is most finicky part. 
3) make a some kind of fraud or criminal tool that harm reputation of MS by association with original OS. 
4) add some prohibited content. Anything from pirated software, stollen books  to adult content. 

From the list above looks like you break (1). making this thing optional will make you free people again, and as a bonus you just make life of many enthusiasts and testers better. MS make a pain out of OS installation in homelab.

**Comment by JayXTQ** [comment]
We are keeping the activation. This is to avoid legal trouble that can arise. Stop complaining about it. If you really care, build Atlas yourself without it. We could care less.
