### ISSUE TITLE
[BUG] - Removing OneDrive with deleting my local files

### ISSUE THREAD

**Issue by xh321** [Atlas-OS/Atlas#1034]
### Description

The official default playbook deleted my entire OneDrive folder while uninstalling OneDrive. The uninstall of OneDrive is not configurable.

### Steps to reproduce

1. Follow the offical document.

### Expected behavior

Let me choose whether the OneDrive should be removed

### Actual behavior

Deleted the entire OneDrive folder contains files.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Not related to the problem

**Comment by JayXTQ** [comment]
Atlas is a performance (gaming) OS, it does not need productivity features like OneDrive. If you need OneDrive, reinstall it.

**Comment by he3als** [comment]
This will be fixed in the next version by detecting if the user has any OneDrive files and not uninstalling it if so.

However, setting up Atlas with the official install guide would not setup a Microsoft account and therefore not setup OneDrive.

**Comment by xh321** [comment]
> This will be fixed in the next version by detecting if the user has any OneDrive files and not uninstalling it if so.
> 
> However, setting up Atlas with the official install guide would not setup a Microsoft account and therefore not setup OneDrive.

In my situation, I want to install Atlas OS to clean my using win11 , to let it run faster. Has this situation not been taken into consideration?

**Comment by he3als** [comment]
That's what the installation guide walks you through; you either clean install Windows 11 or 10 and apply Atlas.

However, the guide never specifies to setup OneDrive, so you shouldn't of had this problem in the first place if each step in the guide was followed exactly.
