### ISSUE TITLE
[BUG] - SHOW LOGS

### ISSUE THREAD

**Issue by Anonymous-any** [Atlas-OS/Atlas#1035]
### Description

Hello team, 1st impression I'm incredibly surprised about the process gain I stopped with ur Atlas work.
Very very good jobs to all.
So I would just report a little contrib to help to give a fix about SHOW LOGS button the not work like expected it seem, (in my side maybe only) idk but truly can happen to other ? I hope I'm not alone...
Added the sc bellow.

My best regard

### Steps to reproduce

Install Atlas 0.3.2 like the explained documentation,
Gives the required internet connection to valid the packages installation required step,
Wait the end, click the log button who ask to contact the Team, and take the sc about what it showed.
and voilà :).
![1](https://github.com/Atlas-OS/Atlas/assets/25174503/9261a1eb-9957-42e5-a45f-a5550f0eda7c)

### Expected behavior

Well, See/Read logs about the errors encountered ?? would be the good behavior.

### Actual behavior

Simply like the screen show there is no way to have logs and need to contact the Team O-O.

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

I dislike give too much information's like this... but I will shorted them :
QuadCore *****Core i7-2600K,
Ram 16 Gb DDR3,
SSD1, Desktop SSHD,
3060ti.

### Additional content

F**k liars MS Corp

**Comment by JayXTQ** [comment]
This is an AME issue, we didn't make the tool

**Comment by he3als** [comment]
AME is aware of the issue and will be fixed in a subsequent version.

**Comment by Anonymous-any** [comment]
Thank glad to ear that, I add this I found maybe the cause... :

`AtlasOS\CBS.log
CBS    Failed to extract file TOC.xml from cabinet \\?\C:\WINDOWS\AtlasModules\Packages\Z-Atlas-NoDefender-Package31bf3856ad364e35amd643.0.0.0.cab [HRESULT = 0x80070002 - ERROR_FILE_NOT_FOUND]
CBS    Not able to add file to extract: update.ses [HRESULT = 0x80070002 - ERROR_FILE_NOT_FOUND]
CBS    Failed to extract file TOC.xml from cabinet \\?\C:\WINDOWS\AtlasModules\Packages\Z-Atlas-NoTelemetry-Package31bf3856ad364e35amd643.0.0.0.cab [HRESULT = 0x80070002 - ERROR_FILE_NOT_FOUND]
CBS    Not able to add file to extract: update.ses [HRESULT = 0x80070002 - ERROR_FILE_NOT_FOUND]`

but if you say @he3als they know then it's okay.
Br all
