### ISSUE TITLE
[BUG] - HEIC thumbnails never load and unable to open in Windows Photo app

### ISSUE THREAD

**Issue by jonatino** [Atlas-OS/Atlas#1038]
### Description

HEIC thumbnails dont load and causes explorer to be very laggy and slow to load folders with heic images.

### Steps to reproduce

1. Get a heic image (from iphone)
2. Ensure you have HEIF Image Extensions and HEVC Video Extensions installed from Windows Store
3. Try and load the image in explorer 

### Expected behavior

Thumbnail should show, windows photos should be able to open HEIC images once the proper extensions are installed.

### Actual behavior

HEIC thumbnails never load causing explorer to get stuck loading and very slow and laggy. Windows Photo app cannot view HEIC images either.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

N/A

**Comment by JayXTQ** [comment]
Do you have windows photos installed from the ms store? atlas removes it by default afaik

**Comment by jonatino** [comment]
> Do you have windows photos installed from the ms store? atlas removes it by default afaik

Yup. It refuses to open the image. Any 3rd party photo viewer can view the file perfectly fine so I know it's not a problem with the file itself.
 
![image](https://github.com/Atlas-OS/Atlas/assets/1808569/451e8fe0-f900-462c-bb1b-ed9863c63526)

**Comment by jonatino** [comment]
[IMG_0376.zip](https://github.com/Atlas-OS/Atlas/files/14321866/IMG_0376.zip)
Here is the image. I had to put it in a .zip file because github refuses uploads with .HEIC extension.

**Comment by jonatino** [comment]
[IMG_0376.zip](https://github.com/Atlas-OS/Atlas/files/14321875/IMG_0376.zip)

Here is the image. Had to zip it because github doesnt allow .HEIC extension uploads.

**Comment by JayXTQ** [comment]
I currently don't use atlas and I am currently on my mac too so I can not view the file without it working natively anyway haha. Maybe someone else can take a look?

**Comment by Ast3risk-ops** [comment]
Booted my Atlas VM, IrfanView shows just black.

I have HEIF image extensions.

![image](https://github.com/Atlas-OS/Atlas/assets/83875983/b36fe113-5362-4c8e-8243-dd7fc155f730)

**Comment by JayXTQ** [comment]
A user from atlas shared this with me, thought I should mention it:

> i really dont want to sign into github to reply to the photo viewer page; but letting you know here, that any HEIC file related stuff is either already fixed in nightly versions of the playbook; or its somehow user error configuration
![image](https://github.com/Atlas-OS/Atlas/assets/54886938/cd5d3448-3564-4474-b75b-ddf8b2a503c7)

**Comment by JayXTQ** [comment]
In other words from my previous comment, you should check nightly versions and see if you still get the same issue. If you do not, please close this issue. If no response, this will automatically be closed.

**Comment by jonatino** [comment]
Might be looking in the wrong place, but the latest nightly build I can find is here: https://github.com/Atlas-OS/Atlas/actions/runs/7846647336

and the download is expired. Are nighty builds archived anywhere else?

**Comment by jonatino** [comment]
Solved it. The Windows Store was logged into a microsoft account that didnt own the hevc video extensions app (even tho I had installed it previously on an microsoft account that did own it), and it seems like that breaks functionality of that codec.

For anyone with the same issue in the future: Make sure the microsoft account you're logged into actually owns the hevc video extensions app.

**Comment by Ast3risk-ops** [comment]
> Might be looking in the wrong place, but the latest nightly build I can find is here: [Atlas-OS/Atlas/actions/runs/7846647336](https://github.com/Atlas-OS/Atlas/actions/runs/7846647336)
> 
> and the download is expired. Are nighty builds archived anywhere else?

https://nightly.link/Atlas-OS/Atlas/workflows/apbx.yaml/dev/Atlas%20Playbook.zip

(this is for anyone else reading)
