### ISSUE TITLE
[BUG] - most apps (almost all) are being reset after system restart

### ISSUE THREAD

**Issue by ItsMadruga** [Atlas-OS/Atlas#1039]
### Description

most apps (almost all) are being reset after system restart.
I saw some issues saying that it has already been fixed, but I'm on the latest version and I'm facing this problem

### Steps to reproduce

- log in with an account on an application
- restart system
- open application

### Expected behavior

Stay in the account even after restarting the system

### Actual behavior

I need to log into the account again

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

- Processor: Intel Xeon e5 2670 v3
- RAM: 16gb ddr4 2133mhz
- Storage: 128gb nvme sata
- GPU: AMD RX580 8gb

**Comment by JayXTQ** [comment]
What version of atlas are you on? This doesn't happen with 0.3.2

**Comment by ItsMadruga** [comment]
I was on 0.3.2, I had to go back to normal Windows because of this bug

**Comment by yvvki** [comment]
What was the application(s) are you using and did you specify to set "remember authentication" or similar on that specific app?

**Comment by CodingMadness** [comment]
I cannot confirm this, i tested it with some games and websites all are stored perfectly
 * middle strong PC
 * windows 11 23H2

**Comment by osmin1** [comment]
The same goes with history of commands. I have enabled Run Command History by using registry entry Start_TrackProgs under: Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
Now Windows remembers my commands entered in Run dialog. But after reboot MRU commands disappear from Win+R dialog.

**Comment by CodingMadness** [comment]
Any news on this?

**Comment by JayXTQ** [comment]
This shouldn't happen in 0.4.0. If this is still the case, please comment.
