### ISSUE TITLE
[FEATURE] - Disable Download Folder sorting preset

### ISSUE THREAD

**Issue by Charismara** [Atlas-OS/Atlas#1041]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

The default sorting and grouping in the user download folder is super annoying

### Describe the solution you would like.

A way to permanently disable it

### Describe alternatives you have considered.

using a different file manager

**Comment by NyneDZN** [comment]
Please right click a blank area inside the downloads folder, select "Group by" and select "(None)"

**Comment by Charismara** [comment]
> Please right click a blank area inside the downloads folder, select "Group by" and select "(None)"

That resets every time i re-open the explorer for me

**Comment by he3als** [comment]
Hi, I'm closing this as it should be an easy option for users to change, and I think a tweak by default is optional. The issue about it resetting each time you open Explorer seems unrelated to Atlas, as I can't reproduce it in the latest version.
