### ISSUE TITLE
[BUG] - Adobe Acrobat Failing to Install on AtlasOS W11.

### ISSUE THREAD

**Issue by sombreserotonin** [Atlas-OS/Atlas#1042]
### Description

Whenver trying to install Adobe Acrobat, an error occurs and the install fails. 
It always exits in code 136.

Log File Shows: 

ERROR: DW071: 

ERROR: DW003: Third party payload installer Adobe Acrobat\Setup.exe failed with exit code: 1603

Also to note have tried uninstalling and reinstalling, as well as using Adobe's cleaning tool.

### Steps to reproduce

1. Download Creative Cloud
2. Install Acrobat.
3. Install fails.

### Expected behavior

Acrobat installs without issue.

### Actual behavior

Starts to install. At around 27% it fails.
### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Occurs on my Intel Desktop, and Ryzen Laptop. DDR4, and DDR5 RAM.  SSD storage.

### Additional content

Occurs on all my devices wit AtlasOS installed,

**Comment by JayXTQ** [comment]
Please provide an appropriate title for this issue.

**Comment by sombreserotonin** [comment]
> Please provide an appropriate title for this issue.

Thought I did. I guess not - updated now. Thanks for notifying me.

**Comment by whallin** [comment]
I had an article written on this in our docs a while back, but it seems to have been deleted at some point, as I was looking for it now for you.

However, to get to the point. Enable printing, restart your computer, and see if the installer works. As Acrobat tries to install some virtual printer during setup, printing services must be present.

If it still fails, let us know and we'll try to troubleshoot it.

**Comment by sombreserotonin** [comment]
> I had an article written on this in our docs a while back, but it seems to have been deleted at some point, as I was looking for it now for you.
> 
> However, to get to the point. Enable printing, restart your computer, and see if the installer works. As Acrobat tries to install some virtual printer during setup, printing services must be present.
> 
> If it still fails, let us know and we'll try to troubleshoot it.

Didn't realise that Atlas disabled printing. Is there somewhere specific where I need to re-enable it?

**Comment by Ast3risk-ops** [comment]
> > I had an article written on this in our docs a while back, but it seems to have been deleted at some point, as I was looking for it now for you.
> > However, to get to the point. Enable printing, restart your computer, and see if the installer works. As Acrobat tries to install some virtual printer during setup, printing services must be present.
> > If it still fails, let us know and we'll try to troubleshoot it.
> 
> Didn't realise that Atlas disabled printing. Is there somewhere specific where I need to re-enable it?

Atlas folder > General Config > Printing

**Comment by sombreserotonin** [comment]
Worked. Thanks!
