### ISSUE TITLE
[BUG] - System interrupts hovers around 1% to 3% idle

### ISSUE THREAD

**Issue by Ch0i10** [Atlas-OS/Atlas#1043]
### Description

as the title says, the system interrupts in task manager shows higher percentage of cpu usage after installing atlas os. before atlas os it only stays below 1%.

### Steps to reproduce

1. Open Task manager
2. check system interrupts process cpu usage

### Expected behavior

System interrupts process to use lower cpu usage

### Actual behavior

Higher cpu usage than expected

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

i5 10300h
16gb ram 2999mhz
1650ti

**Comment by CodingMadness** [comment]
Any news on this?

**Comment by Ch0i10** [comment]
> Any news on this?

i went back to stock windows, no problems there

**Comment by he3als** [comment]
Hi - I can't replicate this on the latest development builds or the latest release. This is likely to be something else such as a manually installed driver different from the drivers hosted on Windows Update.

If you still find that it's related to Atlas after ruling out other factors, try enabling power saving and disabling timer resolution (if previously enabled) in the Atlas folder.
