### ISSUE TITLE
[BUG] - Add reg delete "HKCU\SOFTWARE\Sysinternals\Process Explorer" /v "OneInstance" /f > nul 2>&1

### ISSUE THREAD

**Issue by NukeDev** [Atlas-OS/Atlas#1045]
### Description

After a while i decided to rollback to the default Task Manager, using the "Uninstall Process Explorer.cmd" .

Then, when i start the old Task Manager i receive this error.

![image](https://github.com/Atlas-OS/Atlas/assets/7417090/acc9b325-deb7-498e-8506-ee8b26ae99e5)
![image](https://github.com/Atlas-OS/Atlas/assets/7417090/52ebd11c-fb49-44b6-aa0b-345c2479bafd)

I've tried to delete the reg key: "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\taskmgr.exe", restarted the PC.

Then when i try to open Task Manager, it's start and close immediatly.

These are the logs of event viewer:

Faulting application name: taskmgr.exe, version: 10.0.22621.3085, time stamp: 0xf6325816

Faulting module name: taskmgr.exe, version: 10.0.22621.3085, time stamp: 0xf6325816

Exception code: 0xc0000005

Fault offset: 0x0000000000015b6b

Faulting process ID: 0x0x1860

Faulting application start time: 0x0x1DA6CC0EC0EC9A5

Faulting application path: C:\Windows\system32\taskmgr.exe

Faulting module path: C:\Windows\system32\taskmgr.exe

Report ID: 422c1d04-9b4b-435a-a8e3-121eed2b9110

Faulting package full name:

Faulting package-relative application ID:

**Then i deleted the key "HKCU\SOFTWARE\Sysinternals\Process Explorer" /v "OneInstance" and task manager now works!**

### Steps to reproduce

As in the description

### Expected behavior

As in the description

### Actual behavior

As in the description

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

not relevant

**Comment by duch11** [comment]
Same issue here.
Except the fix mentioned here does not work in my case. 

I DO GET a blue screen error as well, when I run the uninstall script.. 

I've narrowed it down to this line:
`sc start pcw > nul 2>&1`

When I run it manually from cmd it crashes my whole machine.
I could not find any logs for the blue screen of death.

Event Viewer from my side: (Exact same taskmgr.exe crash type and version)
```
Faulting application name: taskmgr.exe, version: 10.0.22621.3085, time stamp: 0xf6325816
Faulting module name: taskmgr.exe, version: 10.0.22621.3085, time stamp: 0xf6325816
Exception code: 0xc0000005
Fault offset: 0x0000000000015b6b
Faulting process id: 0x0x1310
Faulting application start time: 0x0x1DA6DB168A127CA
Faulting application path: C:\Windows\system32\taskmgr.exe
Faulting module path: C:\Windows\system32\taskmgr.exe
Report Id: 37b398d1-1673-4278-8e5b-1cabeacb0fd7
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by NukeDev** [comment]
To solve, run step by step uninstall script and reboot.
Next, remove "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\taskmgr.exe" &  "HKCU\SOFTWARE\Sysinternals\Process Explorer" /v "OneInstance"  then reboot.

**Comment by duch11** [comment]
> To solve, run step by step uninstall script and reboot. Next, remove "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\taskmgr.exe" & "HKCU\SOFTWARE\Sysinternals\Process Explorer" /v "OneInstance" then reboot.

## Thank you! 
### But I had an additional issue:
`sc config pcw start=boot` **had not run successfully on my machine.** 
_**And thus it still didn't work.**_

`sc start pcw` crashed my computer.. Probably due to BitDefender or some other reason.. 

I fixed it though and everything is back to normal 👍 

## Fix: 
0. Delete the registry keys as @NukeDev explained in this issue
1. Start `Command Prompt` with Administrator Privileges
2. Run: `sc config pcw start=boot`
3. Reboot!

Problem was that the Uninstall script would blue screen my computer. 
So the `sc config pcw start=boot` had not gone into effect due to the crash.. 

Hope this helps some other poor soul out there <3

**Comment by Xyueta** [comment]
Should be resolved now.
