### ISSUE TITLE
[FEATURE] - Option at install to completely wipe all microsoft related Apps EXCEPT MS Store

### ISSUE THREAD

**Issue by CodingMadness** [Atlas-OS/Atlas#1048]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

It sort of is, regarding more debloation.

### Describe the solution you would like.

Pretty much title. 

I know, I have already sort of asked that as a reply to another topic regarding the "hardening" of security surface, but I would like to go another step further and ask if you could bring an option to fully uninstall all pre-installed windows programs, i mean not apps, but programs, like notepad, terminal, ms office (and all related services and other files), xbox (and all related services and other files) ms edge, and so on, that you get a **fully** debloated windows, with like nothing prehand (ofc I would choose another brower than edge on install).

The reason for this request is ,that quite the amount of people are moving over to more open source alternatives due to security concerns of the respected MS apps and programs. 

And ofc, in order to avoid "pls help, I dont have any MS stuff installed..:" in discord and forums, there should come a big fat red warning by doing so that you get rid of legit all stuff pre installed, in order to avoid the crying, and even if its accidental, there is nothing that stops the user to reroll playbook OR just install the needed stuff again via internet. 

Please do give this a consideration!

ALl the best

### Describe alternatives you have considered.

none.

### Additional context.

none.

**Comment by JayXTQ** [comment]
No. Xbox is mostly required on Atlas because we are a gaming OS. We want people to be able to game out of the box. Also with lots of people, even if we add a disclaimer to a button or something, people will likely click it. If we have said button saying "Remove all apps" people may click it and then realise nothing is there and make complaints which we don't want to deal with at all, we already have tons of people who repeat the same questions so it's best not to introduce more ways to ask more questions. Other software may also be needed for school and stuff, many of our user base is below the age of 18 and may still be in school and do their work online. From this, I will repeat again, this is a bad idea, for our users and mostly all users in general.

**Comment by Ast3risk-ops** [comment]
UWP applications are also most of windows 11.

**Comment by CodingMadness** [comment]
> UWP applications are also most of windows 11 now. Removing all of that would break its base functionality.

Can you elaborate, how do you mean that?

**Comment by CodingMadness** [comment]
> No. Xbox is mostly required on Atlas because we are a gaming OS. We want people to be able to game out of the box. Also with lots of people, even if we add a disclaimer to a button or something, people will likely click it. If we have said button saying "Remove all apps" people may click it and then realise nothing is there and make complaints which we don't want to deal with at all, we already have tons of people who repeat the same questions so it's best not to introduce more ways to ask more questions. Other software may also be needed for school and stuff, many of our user base is below the age of 18 and may still be in school and do their work online. From this, I will repeat again, this is a bad idea, for our users and mostly all users in general.

I really cannot understand this argumentation, you are not responsible for every stupid crap people do, seriously, you can say the same for what if people decide to install some stuff which patches windows, like some graphic patching software which atlas is not so good with (which I did in the past) and it was MY problem, i cannot fault anyone for that and if I do that, then there is a simple answer to that: no answer at all or "read the docs" answer, but the benefit of getting (optionally as I said!) rid of the entire bulk of software which MS calls "standards" and replace it with custom wished software, is something alot of people are used to by using Linux where you define for yourself what you wanna have installed.

**Comment by CodingMadness** [comment]
And I mean, if someone does it you can just reinstall the entire stuff, no? Let aside the fact how retarded you should be to click on a button (*which I would furtherly advise to prompt a message box which states if the user is  REALLY sure to do that, as a 2. layer of accidental-protection*) AND CLICK ON "YES" in that alert message box.....

**Comment by Ast3risk-ops** [comment]
> > UWP applications are also most of windows 11 now. Removing all of that would break its base functionality.
> 
> Can you elaborate, how do you mean that?

Actually Microsoft dropped UWP, so we actually mean the Windows App SDK. What I mean is every included app (media player, notepad, photos, etc) is powered by WinUI and the windows app SDK.

**Comment by CodingMadness** [comment]
> > > UWP applications are also most of windows 11 now. Removing all of that would break its base functionality.
> > 
> > 
> > Can you elaborate, how do you mean that?
> 
> Actually Microsoft [dropped UWP](https://www.techradar.com/news/microsoft-is-finally-dropping-uwp-app-support-windows-app-sdk-heres-why), so we actually mean the Windows App SDK.
> 
> What I mean is every included app (media player, notepad, photos, etc) is powered by WinUI and the windows app SDK. All the new systemapps in win10 (which are included in win11, for win10 you have to update to them) are powered by this framework, and Atlas keeps some of them, we can't just purge them.
> 
> Also:
> 
>     1. People use the new notepad
> 
>     2. People use the new task manager in win11 (another winUI/app SDK app)
> 
>     3. People use apps from the Microsoft store that use this framework (kinda unrelated to this, but worth pointing out)
> 
>     4. People use Windows Calculator and the other apps that Atlas keeps.
> 
>     5. Atlas removes a lot of the useless default apps already ("[read the docs](https://docs.atlasos.net/faq-and-troubleshooting/removed-features/#applications-or-features-uninstalled-by-default)")
> 
> 
> > or "read the docs" answer
> 
> Nobody reads that.
> 
> > And I mean, if someone does it you can just reinstall the entire stuff, no? Let aside the fact how retarded you should be to click on a button
> 
> People are _really_ stupid, and we'd like to preserve functionality thank you very much.

okay, I understand, would you mind, maybe for people like me (believe me bro there are tons of people even in youtube who just wish to uninstall nearly everything (*okay, except the taskmanager or system-level stuff like that*), to sneak in a script which does that, so that you can run that post atlas install? Like a script, which removes the desired app/program AND all its other related files and services or drivers or whatever.

**Comment by Ast3risk-ops** [comment]
Please see the following tools:

- [Bulk Crap Uninstaller](https://www.bcuninstaller.com/)
- [Uninstall Tool](https://crystalidea.com/uninstall-tool)
- [Revo Uninstaller](https://www.revouninstaller.com/)
- [Bloatbox](https://github.com/builtbybel/bloatbox)

**Comment by CodingMadness** [comment]
> Please see the following tools:
> 
>     * [Bulk Crap Uninstaller](https://www.bcuninstaller.com/)
> 
>     * [Uninstall Tool](https://crystalidea.com/uninstall-tool)
> 
>     * [Revo Uninstaller](https://www.revouninstaller.com/)
> 
>     * [Bloatbox](https://github.com/builtbybel/bloatbox)

Okay thanks alot Bro and very well done what you guys have pulled of with AtlasOS, thanks alot for the hard work!

**Comment by CodingMadness** [comment]
> Please see the following tools:
> 
>     * [Bulk Crap Uninstaller](https://www.bcuninstaller.com/)
> 
>     * [Uninstall Tool](https://crystalidea.com/uninstall-tool)
> 
>     * [Revo Uninstaller](https://www.revouninstaller.com/)
> 
>     * [Bloatbox](https://github.com/builtbybel/bloatbox)

Mate, do you happen to know, what kind of these "pre installed" apps and services are really really not needed (if it can be said that easily ofc..)

1. MicrosoftWindows.UndockedDevKit
2. Microsoft.UI.Xaml.CBS
3. MicrosoftWindows.Client.Core
4. Microsoft.WindowsAppRuntime.CBS
5. MicrosoftWindows.Client.FileExp
6. Microsoft.Windows.CloudExperienceHost
7. Microsoft.BioEnrollment
8. MicrosoftWindows.Client.CBS
9. Microsoft.AAD.BrokerPlugin
10. Microsoft.Windows.StartMenuExperienceHost
11. Microsoft.Windows.ShellExperienceHost
12. windows.immersivecontrolpanel
13. Microsoft.NET.Native.Framework.2.2
14. Microsoft.NET.Native.Runtime.2.2
15. Microsoft.VCLibs.140.00
16. Microsoft.Windows.ContentDeliveryManager
17. Microsoft.WindowsStore
18. Microsoft.XboxIdentityProvider
19. Microsoft.WindowsNotepad
20. Microsoft.WebpImageExtension
21. Microsoft.SecHealthUI
22. Microsoft.LockApp
23. Microsoft.Windows.Apprep.ChxApp
24. Microsoft.Windows.PinningConfirmationDialog
25. Microsoft.Windows.PrintQueueActionCenter
26. Microsoft.Windows.AssignedAccessLockApp
27. Microsoft.MicrosoftEdgeDevToolsClient
28. Windows.PrintDialog
29. Microsoft.Windows.XGpuEjectDialog
30. Microsoft.XboxGameCallableUI
31. Windows.CBSPreview
32. Microsoft.Win32WebViewHost
33. Microsoft.Windows.NarratorQuickStart
34. Microsoft.Windows.CallingShellApp
35. 1527c705-839a-4832-9118-54d4Bd6a0c89
36. Microsoft.Windows.CapturePicker
37. NcsiUwpApp
38. c5e2524a-ea46-4f67-841f-6a9465d9d515
39. Microsoft.ECApp
40. Microsoft.CredDialogHost
41. Microsoft.AsyncTextService
42. Microsoft.AccountsControl
43. F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE
44. E2A4F912-2574-4A75-9BB0-0D023378592B
45. Microsoft.WebMediaExtensions
46. Microsoft.UI.Xaml.2.4
47. Microsoft.VP9VideoExtensions
48. RealtekSemiconductorCorp.RealtekAudioControl
49. Microsoft.XboxSpeechToTextOverlay
50. Microsoft.Xbox.TCUI
51. Microsoft.WindowsTerminal
52. Microsoft.VCLibs.140.00.UWPDesktop
53. Microsoft.WindowsCalculator
54. Microsoft.StorePurchaseApp
55. Microsoft.RawImageExtension
56. Microsoft.HEVCVideoExtension
57. Microsoft.HEIFImageExtension
58. Microsoft.NET.Native.Runtime.2.2
59. Microsoft.NET.Native.Framework.2.2
60. Microsoft.Services.Store.Engagement
61. Microsoft.Services.Store.Engagement
62. Microsoft.UI.Xaml.2.8
63. Microsoft.UI.Xaml.2.8
64. Microsoft.UI.Xaml.2.7
65. Microsoft.UI.Xaml.2.7
66. NVIDIACorp.NVIDIAControlPanel
67. Microsoft.VCLibs.140.00
68. Microsoft.VCLibs.140.00.UWPDesktop
69. Microsoft.Paint
70. MicrosoftWindows.Client.WebExperience
71. NotepadPlusPlus
72. Microsoft.MicrosoftEdge.Stable
73. Microsoft.DesktopAppInstaller

These are shown by the tool "BloatyNoiseyAI" which I use to furtherly debloat AtlasOS

**Comment by Ast3risk-ops** [comment]
> > Please see the following tools:
> > ```
> > * [Bulk Crap Uninstaller](https://www.bcuninstaller.com/)
> > 
> > * [Uninstall Tool](https://crystalidea.com/uninstall-tool)
> > 
> > * [Revo Uninstaller](https://www.revouninstaller.com/)
> > 
> > * [Bloatbox](https://github.com/builtbybel/bloatbox)
> > ```
> 
> Mate, do you happen to know, what kind of these "pre installed" apps and services are really really not needed (if it can be said that easily ofc..)
> 
>     1. MicrosoftWindows.UndockedDevKit
> 
>     2. Microsoft.UI.Xaml.CBS
> 
>     3. MicrosoftWindows.Client.Core
> 
>     4. Microsoft.WindowsAppRuntime.CBS
> 
>     5. MicrosoftWindows.Client.FileExp
> 
>     6. Microsoft.Windows.CloudExperienceHost
> 
>     7. Microsoft.BioEnrollment
> 
>     8. MicrosoftWindows.Client.CBS
> 
>     9. Microsoft.AAD.BrokerPlugin
> 
>     10. Microsoft.Windows.StartMenuExperienceHost
> 
>     11. Microsoft.Windows.ShellExperienceHost
> 
>     12. windows.immersivecontrolpanel
> 
>     13. Microsoft.NET.Native.Framework.2.2
> 
>     14. Microsoft.NET.Native.Runtime.2.2
> 
>     15. Microsoft.VCLibs.140.00
> 
>     16. Microsoft.Windows.ContentDeliveryManager
> 
>     17. Microsoft.WindowsStore
> 
>     18. Microsoft.XboxIdentityProvider
> 
>     19. Microsoft.WindowsNotepad
> 
>     20. Microsoft.WebpImageExtension
> 
>     21. Microsoft.SecHealthUI
> 
>     22. Microsoft.LockApp
> 
>     23. Microsoft.Windows.Apprep.ChxApp
> 
>     24. Microsoft.Windows.PinningConfirmationDialog
> 
>     25. Microsoft.Windows.PrintQueueActionCenter
> 
>     26. Microsoft.Windows.AssignedAccessLockApp
> 
>     27. Microsoft.MicrosoftEdgeDevToolsClient
> 
>     28. Windows.PrintDialog
> 
>     29. Microsoft.Windows.XGpuEjectDialog
> 
>     30. Microsoft.XboxGameCallableUI
> 
>     31. Windows.CBSPreview
> 
>     32. Microsoft.Win32WebViewHost
> 
>     33. Microsoft.Windows.NarratorQuickStart
> 
>     34. Microsoft.Windows.CallingShellApp
> 
>     35. 1527c705-839a-4832-9118-54d4Bd6a0c89
> 
>     36. Microsoft.Windows.CapturePicker
> 
>     37. NcsiUwpApp
> 
>     38. c5e2524a-ea46-4f67-841f-6a9465d9d515
> 
>     39. Microsoft.ECApp
> 
>     40. Microsoft.CredDialogHost
> 
>     41. Microsoft.AsyncTextService
> 
>     42. Microsoft.AccountsControl
> 
>     43. F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE
> 
>     44. E2A4F912-2574-4A75-9BB0-0D023378592B
> 
>     45. Microsoft.WebMediaExtensions
> 
>     46. Microsoft.UI.Xaml.2.4
> 
>     47. Microsoft.VP9VideoExtensions
> 
>     48. RealtekSemiconductorCorp.RealtekAudioControl
> 
>     49. Microsoft.XboxSpeechToTextOverlay
> 
>     50. Microsoft.Xbox.TCUI
> 
>     51. Microsoft.WindowsTerminal
> 
>     52. Microsoft.VCLibs.140.00.UWPDesktop
> 
>     53. Microsoft.WindowsCalculator
> 
>     54. Microsoft.StorePurchaseApp
> 
>     55. Microsoft.RawImageExtension
> 
>     56. Microsoft.HEVCVideoExtension
> 
>     57. Microsoft.HEIFImageExtension
> 
>     58. Microsoft.NET.Native.Runtime.2.2
> 
>     59. Microsoft.NET.Native.Framework.2.2
> 
>     60. Microsoft.Services.Store.Engagement
> 
>     61. Microsoft.Services.Store.Engagement
> 
>     62. Microsoft.UI.Xaml.2.8
> 
>     63. Microsoft.UI.Xaml.2.8
> 
>     64. Microsoft.UI.Xaml.2.7
> 
>     65. Microsoft.UI.Xaml.2.7
> 
>     66. NVIDIACorp.NVIDIAControlPanel
> 
>     67. Microsoft.VCLibs.140.00
> 
>     68. Microsoft.VCLibs.140.00.UWPDesktop
> 
>     69. Microsoft.Paint
> 
>     70. MicrosoftWindows.Client.WebExperience
> 
>     71. NotepadPlusPlus
> 
>     72. Microsoft.MicrosoftEdge.Stable
> 
>     73. Microsoft.DesktopAppInstaller
> 
> 
> These are shown by the tool "BloatyNoiseyAI" which I use to furtherly debloat AtlasOS

Edge can be removed. NVIDIA control panel is actually needed if you have an nvidia card (and it can be updated).

Windows Terminal is required on win11, and it's actually a good winUI app, I'd recommend it to anyone who uses powershell on win10. NotepadPlusPlus is not bundled, why did you send it. A lot of the smaller stuff you list is required by other apps.

**Comment by dennyamarojr** [comment]
Windows Components to Review
6. Microsoft.Windows.CloudExperienceHost (Required for MS Account)
7. Microsoft.BioEnrollment (Required by Biometric features)
8. MicrosoftWindows.Client.CBS (Breaks Windows Search)
9. Microsoft.AAD.BrokerPlugin (Required for MS Account)
10. Microsoft.Windows.StartMenuExperienceHost (Required by Start Menu)
11. Microsoft.Windows.ShellExperienceHost (Required by Explorer!?)
12. windows.immersivecontrolpanel (Breaks Windows Settings)
42. Microsoft.AccountsControl (Required for MS Account)
46. Microsoft.UI.Xaml.2.4 (Required by Windows Components and Apps)
40. Microsoft.CredDialogHost (Required by dialogs from windows)
36. Microsoft.Windows.CapturePicker (Required by Snipping Tool)
21. Microsoft.SecHealthUI (Windows Defender)
22. Microsoft.LockApp (Required by Lock Screen to show notifications)
30. Microsoft.XboxGameCallableUI (Required by Xbox)
34. Microsoft.Windows.CallingShellApp (Related to a feature in windows, needs to see which one)


Required by Windows Apps
13. Microsoft.NET.Native.Framework.2.2
14. Microsoft.NET.Native.Runtime.2.2
58. Microsoft.NET.Native.Runtime.2.2
59. Microsoft.NET.Native.Framework.2.2
60. Microsoft.Services.Store.Engagement
61. Microsoft.Services.Store.Engagement
62. Microsoft.UI.Xaml.2.8
63. Microsoft.UI.Xaml.2.8
64. Microsoft.UI.Xaml.2.7
65. Microsoft.UI.Xaml.2.7
67. Microsoft.VCLibs.140.00
68. Microsoft.VCLibs.140.00.UWPDesktop
54. Microsoft.StorePurchaseApp

Can be safely removed

17. Microsoft.WindowsStore
18. Microsoft.XboxIdentityProvider
19. Microsoft.WindowsNotepad
20. Microsoft.WebpImageExtension
45. Microsoft.WebMediaExtensions
47. Microsoft.VP9VideoExtensions
48. RealtekSemiconductorCorp.RealtekAudioControl
49. Microsoft.XboxSpeechToTextOverlay
50. Microsoft.Xbox.TCUI
51. Microsoft.WindowsTerminal
53. Microsoft.WindowsCalculator
55. Microsoft.RawImageExtension
56. Microsoft.HEVCVideoExtension
57. Microsoft.HEIFImageExtension
69. Microsoft.Paint
70. MicrosoftWindows.Client.WebExperience
73. Microsoft.DesktopAppInstaller

**Comment by Ast3risk-ops** [comment]
> Windows Components to Review 6. Microsoft.Windows.CloudExperienceHost (Required for MS Account) 7. Microsoft.BioEnrollment (Required by Biometric features) 8. MicrosoftWindows.Client.CBS (Breaks Windows Search) 9. Microsoft.AAD.BrokerPlugin (Required for MS Account) 10. Microsoft.Windows.StartMenuExperienceHost (Required by Start Menu) 11. Microsoft.Windows.ShellExperienceHost (Required by Explorer!?) 12. windows.immersivecontrolpanel (Breaks Windows Settings) 42. Microsoft.AccountsControl (Required for MS Account) 46. Microsoft.UI.Xaml.2.4 (Required by Windows Components and Apps) 40. Microsoft.CredDialogHost (Required by dialogs from windows) 36. Microsoft.Windows.CapturePicker (Required by Snipping Tool) 21. Microsoft.SecHealthUI (Windows Defender) 22. Microsoft.LockApp (Required by Lock Screen to show notifications) 30. Microsoft.XboxGameCallableUI (Required by Xbox) 34. Microsoft.Windows.CallingShellApp (Related to a feature in windows, needs to see which one)
> 
> Required by Windows Apps 13. Microsoft.NET.Native.Framework.2.2 14. Microsoft.NET.Native.Runtime.2.2 58. Microsoft.NET.Native.Runtime.2.2 59. Microsoft.NET.Native.Framework.2.2 60. Microsoft.Services.Store.Engagement 61. Microsoft.Services.Store.Engagement 62. Microsoft.UI.Xaml.2.8 63. Microsoft.UI.Xaml.2.8 64. Microsoft.UI.Xaml.2.7 65. Microsoft.UI.Xaml.2.7 67. Microsoft.VCLibs.140.00 68. Microsoft.VCLibs.140.00.UWPDesktop 54. Microsoft.StorePurchaseApp
> 
> Can be safely removed
> 
>     17. Microsoft.WindowsStore
> 
>     18. Microsoft.XboxIdentityProvider
> 
>     19. Microsoft.WindowsNotepad
> 
>     20. Microsoft.WebpImageExtension
> 
>     21. Microsoft.WebMediaExtensions
> 
>     22. Microsoft.VP9VideoExtensions
> 
>     23. RealtekSemiconductorCorp.RealtekAudioControl
> 
>     24. Microsoft.XboxSpeechToTextOverlay
> 
>     25. Microsoft.Xbox.TCUI
> 
>     26. Microsoft.WindowsTerminal
> 
>     27. Microsoft.WindowsCalculator
> 
>     28. Microsoft.RawImageExtension
> 
>     29. Microsoft.HEVCVideoExtension
> 
>     30. Microsoft.HEIFImageExtension
> 
>     31. Microsoft.Paint
> 
>     32. MicrosoftWindows.Client.WebExperience
> 
>     33. Microsoft.DesktopAppInstaller

`Xbox.TCUI` and related packages should be kept for gaming, and `Microsoft.WindowsStore` and `Microsoft.DesktopAppInstaller` are the Microsoft store and App Installer respectively, keep those.

Keep `Microsoft.HEVCVideoExtension` and `Microsoft.HEIFImageExtension`. Also maybe keep Notepad and Windows Terminal. And stop this discussion here because it's offtopic. (cc: @JayXTQ)

**Comment by JayXTQ** [comment]
Yeah, please don't spam this with random apps please, I also stated why no earlier, I am keeping this open incase @he3als wants to comment but as I said, no. This should not be implemented due to our user base, and there is no argument here like "you are not responsible for every stupid crap people do"... yes we are? as software engineers, you need to make your app useable for the most dumbest people on the planet. So if we started adding stuff which may upset people if they don't read, then we have made a mistake.

**Comment by Ast3risk-ops** [comment]
> Yeah, please don't spam this with random apps please, I also stated why no earlier, I am keeping this open incase @he3als wants to comment but as I said, no. This should not be implemented due to our user base, and there is no argument here like "you are not responsible for every stupid crap people do"... yes we are? as software engineers, you need to make your app useable for the most dumbest people on the planet. So if we started adding stuff which may upset people if they don't read, then we have made a mistake.

Pretty sure you can also mark posts as off-topic 😑

**Comment by JayXTQ** [comment]
true, but are they really off-topic though if they list appxs?

**Comment by Ast3risk-ops** [comment]
> true, but are they really off-topic though if they list appxs?

Maybe.

**Comment by CodingMadness** [comment]
> Windows Components to Review 6. Microsoft.Windows.CloudExperienceHost (Required for MS Account) 7. Microsoft.BioEnrollment (Required by Biometric features) 8. MicrosoftWindows.Client.CBS (Breaks Windows Search) 9. Microsoft.AAD.BrokerPlugin (Required for MS Account) 10. Microsoft.Windows.StartMenuExperienceHost (Required by Start Menu) 11. Microsoft.Windows.ShellExperienceHost (Required by Explorer!?) 12. windows.immersivecontrolpanel (Breaks Windows Settings) 42. Microsoft.AccountsControl (Required for MS Account) 46. Microsoft.UI.Xaml.2.4 (Required by Windows Components and Apps) 40. Microsoft.CredDialogHost (Required by dialogs from windows) 36. Microsoft.Windows.CapturePicker (Required by Snipping Tool) 21. Microsoft.SecHealthUI (Windows Defender) 22. Microsoft.LockApp (Required by Lock Screen to show notifications) 30. Microsoft.XboxGameCallableUI (Required by Xbox) 34. Microsoft.Windows.CallingShellApp (Related to a feature in windows, needs to see which one)
> 
> Required by Windows Apps 13. Microsoft.NET.Native.Framework.2.2 14. Microsoft.NET.Native.Runtime.2.2 58. Microsoft.NET.Native.Runtime.2.2 59. Microsoft.NET.Native.Framework.2.2 60. Microsoft.Services.Store.Engagement 61. Microsoft.Services.Store.Engagement 62. Microsoft.UI.Xaml.2.8 63. Microsoft.UI.Xaml.2.8 64. Microsoft.UI.Xaml.2.7 65. Microsoft.UI.Xaml.2.7 67. Microsoft.VCLibs.140.00 68. Microsoft.VCLibs.140.00.UWPDesktop 54. Microsoft.StorePurchaseApp
> 
> Can be safely removed
> 
>     17. Microsoft.WindowsStore
> 
>     18. Microsoft.XboxIdentityProvider
> 
>     19. Microsoft.WindowsNotepad
> 
>     20. Microsoft.WebpImageExtension
> 
>     21. Microsoft.WebMediaExtensions
> 
>     22. Microsoft.VP9VideoExtensions
> 
>     23. RealtekSemiconductorCorp.RealtekAudioControl
> 
>     24. Microsoft.XboxSpeechToTextOverlay
> 
>     25. Microsoft.Xbox.TCUI
> 
>     26. Microsoft.WindowsTerminal
> 
>     27. Microsoft.WindowsCalculator
> 
>     28. Microsoft.RawImageExtension
> 
>     29. Microsoft.HEVCVideoExtension
> 
>     30. Microsoft.HEIFImageExtension
> 
>     31. Microsoft.Paint
> 
>     32. MicrosoftWindows.Client.WebExperience
> 
>     33. Microsoft.DesktopAppInstaller

Thanks alot mate!!! This is what I have looked for, I re-arranged your list to my personal needs, as in, I want to remove everything related to a MS account (*since I do not need one and never needed one actually, despite MS forcing you to get one when installing windows 11*) and also everything related to XBox since I do not play any XBox related games! Thx alot!

**Comment by CodingMadness** [comment]
> > Windows Components to Review 6. Microsoft.Windows.CloudExperienceHost (Required for MS Account) 7. Microsoft.BioEnrollment (Required by Biometric features) 8. MicrosoftWindows.Client.CBS (Breaks Windows Search) 9. Microsoft.AAD.BrokerPlugin (Required for MS Account) 10. Microsoft.Windows.StartMenuExperienceHost (Required by Start Menu) 11. Microsoft.Windows.ShellExperienceHost (Required by Explorer!?) 12. windows.immersivecontrolpanel (Breaks Windows Settings) 42. Microsoft.AccountsControl (Required for MS Account) 46. Microsoft.UI.Xaml.2.4 (Required by Windows Components and Apps) 40. Microsoft.CredDialogHost (Required by dialogs from windows) 36. Microsoft.Windows.CapturePicker (Required by Snipping Tool) 21. Microsoft.SecHealthUI (Windows Defender) 22. Microsoft.LockApp (Required by Lock Screen to show notifications) 30. Microsoft.XboxGameCallableUI (Required by Xbox) 34. Microsoft.Windows.CallingShellApp (Related to a feature in windows, needs to see which one)
> > Required by Windows Apps 13. Microsoft.NET.Native.Framework.2.2 14. Microsoft.NET.Native.Runtime.2.2 58. Microsoft.NET.Native.Runtime.2.2 59. Microsoft.NET.Native.Framework.2.2 60. Microsoft.Services.Store.Engagement 61. Microsoft.Services.Store.Engagement 62. Microsoft.UI.Xaml.2.8 63. Microsoft.UI.Xaml.2.8 64. Microsoft.UI.Xaml.2.7 65. Microsoft.UI.Xaml.2.7 67. Microsoft.VCLibs.140.00 68. Microsoft.VCLibs.140.00.UWPDesktop 54. Microsoft.StorePurchaseApp
> > Can be safely removed
> > ```
> > 17. Microsoft.WindowsStore
> > 
> > 18. Microsoft.XboxIdentityProvider
> > 
> > 19. Microsoft.WindowsNotepad
> > 
> > 20. Microsoft.WebpImageExtension
> > 
> > 21. Microsoft.WebMediaExtensions
> > 
> > 22. Microsoft.VP9VideoExtensions
> > 
> > 23. RealtekSemiconductorCorp.RealtekAudioControl
> > 
> > 24. Microsoft.XboxSpeechToTextOverlay
> > 
> > 25. Microsoft.Xbox.TCUI
> > 
> > 26. Microsoft.WindowsTerminal
> > 
> > 27. Microsoft.WindowsCalculator
> > 
> > 28. Microsoft.RawImageExtension
> > 
> > 29. Microsoft.HEVCVideoExtension
> > 
> > 30. Microsoft.HEIFImageExtension
> > 
> > 31. Microsoft.Paint
> > 
> > 32. MicrosoftWindows.Client.WebExperience
> > 
> > 33. Microsoft.DesktopAppInstaller
> > ```
> 
> `Xbox.TCUI` and related packages should be kept for gaming, and `Microsoft.WindowsStore` and `Microsoft.DesktopAppInstaller` are the Microsoft store and App Installer respectively, keep those.
> 
> Keep `Microsoft.HEVCVideoExtension` and `Microsoft.HEIFImageExtension`. Also maybe keep Notepad and Windows Terminal. And stop this discussion here because it's offtopic. (cc: @JayXTQ)

This is very subjectional, like I dont need ,as maybe others aswell ,windows 11 notepad aswell as the old terminal, cause its old stuff and can be replaced anyway by notepad++  AND powershell which has way way more stuff in and is very efficient,same goes for windows photo app, XBox is smth everyone needs to see for themselves if its needed or not, in my case, its not, but the desktop app installer and MS Store installer I let there be, in order to be able to install stuff back later if I need to. W

**Comment by Ast3risk-ops** [comment]
Oh god please don't double post @CodingMadness

**Comment by CodingMadness** [comment]
> Oh god please don't double post @CodingMadness edit your last message

huh? where do I double post? its a new comment? I wont edit a comment to a post which was another question?

**Comment by CodingMadness** [comment]
> Yeah, please don't spam this with random apps please, I also stated why no earlier, I am keeping this open incase @he3als wants to comment but as I said, no. This should not be implemented due to our user base, and there is no argument here like "you are not responsible for every stupid crap people do"... yes we are? as software engineers, you need to make your app useable for the most dumbest people on the planet. So if we started adding stuff which may upset people if they don't read, then we have made a mistake.

 I didnt want to spam anything, but it was related to my desire to get rid of stuff which may not be nessecary for all users, it was still a related comment to my original post.

**Comment by Ast3risk-ops** [comment]
> > Yeah, please don't spam this with random apps please, I also stated why no earlier, I am keeping this open incase @he3als wants to comment but as I said, no. This should not be implemented due to our user base, and there is no argument here like "you are not responsible for every stupid crap people do"... yes we are? as software engineers, you need to make your app useable for the most dumbest people on the planet. So if we started adding stuff which may upset people if they don't read, then we have made a mistake.
> 
> I didnt want to spam anything, but it was related to my desire to get rid of stuff which may not be nessecary for all users, it was still a related comment to my original post.

No that list was very personal. Either way for now the answer is no. See https://github.com/Atlas-OS/Atlas/issues/1048#issuecomment-1981932914.

**Comment by Ast3risk-ops** [comment]
> If you want to remove AppX packages, use the PowerShell AppX module with commands such as `Get-AppxPackage` and `Remove-AppxPackage`.
> 
> There won't be an option built into the Playbook as the in-built AppX apps are useful, and I don't see a true 'security' concern with them.

You can also use the tools mentioned [here](https://github.com/Atlas-OS/Atlas/issues/1048#issuecomment-1982252063).
