### ISSUE TITLE
My laptop frozes while booting into the os!

### ISSUE THREAD

**Issue by Gamer1000YT** [Atlas-OS/Atlas#105]
My laptop literally frozes while im booting into Atlas OS, every single time!

Desktop Info:
 - CPU [Intel Core 2 Duo T7500 2.2Ghz]
 - System Drive Type [HDD]
 - Version [0.5.1]

**Comment by Zusier** [comment]
Did we not already talk about this on discord?

**Comment by Zusier** [comment]
Just asking, someone had it before and they fixed it. It could be the following:
- Improper BIOS/Disk configuration (e.g. MBR on UEFI w/ no CSM)
- Corrupted .iso

If you could provide a picture, or more information on when it freezes I could troubleshoot much better, thanks.

**Comment by Gamer1000YT** [comment]
> Just asking, someone had it before and they fixed it. It could be the following:
> 
> * Improper BIOS/Disk configuration (e.g. MBR on UEFI w/ no CSM)
> * Corrupted .iso
> 
> If you could provide a picture, or more information on when it freezes I could troubleshoot much better, thanks.

The laptop freezes on the boot screen

**Comment by Gamer1000YT** [comment]
![20220218_173617](https://user-images.githubusercontent.com/68267998/154713568-4b3bd536-0b47-478a-941d-35e9cad1d5e2.jpg)

**Comment by Zusier** [comment]
and the circle is frozen, correct?

**Comment by Gamer1000YT** [comment]
> and the circle is frozen, correct?

Exactly

**Comment by Gamer1000YT** [comment]
> Did you boot once and then this happened?

Yes, but multiple times

**Comment by Zusier** [comment]
What? So what did you do to cause it? If it booted after the post-install script ran, it isn't atlas related.

**Comment by Gamer1000YT** [comment]
> > and yes after the post-install scripts
> 
> What do you mean by that? Did it freeze after the script ran?

Yes

**Comment by Zusier** [comment]
Just making sure there isn't a miscommunication, **right** after the post-install script ran, no extra boots?
