### ISSUE TITLE
[FEATURE] - More clarifications about failed steps

### ISSUE THREAD

**Issue by dark-penguin** [Atlas-OS/Atlas#1051]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

I've tried installing Atlas OS on another PC, and it "finished with some errors" again. I can see the error logs, but even looking at them, I can't figure out exactly which actions failed.

### Describe the solution you would like.

Would it be possible to have the error messages include something like links to actions that failed? And it would be even more awesome to immediately see the reason they failed.

### Describe alternatives you have considered.

Looking through the folder the wizard creates on my desktop to maybe accidentally find what could have failed. I could not guess the answer.
Here are the logs:
[3-09-2024-Atlas-AtlasOS.zip](https://github.com/Atlas-OS/Atlas/files/14547753/3-09-2024-Atlas-AtlasOS.zip)

**Comment by trolljoe** [comment]
your user is a non english name, that may be why the issue is happening

**Comment by dark-penguin** [comment]
My user actually is English characters only, and only one word. "Все пользователи" means "All users".

**Comment by dark-penguin** [comment]
Some messages were actually pretty helpful! For example, the last one: I can see exactly what command was issues and what exit code it returned. It has also failed to execute TASKBARPINS,cmd, but I have no idea where should I look for it. It tried to set a registry key, which I could try to redo manually to see what the problem was, but... to what value? It tried to do something with LOCKSCREEN.ps1, which again I wonder where it is. It tried to robocopy "AtlasModules", but from where?

We can also see some actually strange errors here. It could not delete "defaultuser0", because turns out I don't have this user for some reason. Checking for updates fails for some reason, AND for some reason it actually generates an error. It can't find NTUSER.DAT in "All users", which is probably because it's looking in a localized directory name which is probably substituted by Windows.

**Comment by JayXTQ** [comment]
Hi, this is an AME Wizard issue actually, if you wish to gain support on said errors, join our Discord or make a forum post.

**Comment by dark-penguin** [comment]
Thanks, I'll try!
