### ISSUE TITLE
[FEATURE] - Missing touch keyboard service Handheld PC Dead on arrival for Handheld pc's Rog ally Legion GO and all others

### ISSUE THREAD

**Issue by denver8989** [Atlas-OS/Atlas#1053]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

i installed your os "playbook" "because it's for gamers" on my legion go now i cant bring the keyboard up in game in browsing basically a useless gaming os on a handheld take this into consideration please, 
I have seen an obnoxious reponse to a prior identical fr=eature request that this it is not a essential feature for gaming what about tablets and hand held computers this is a second chance at showing us this is a viable option for gamers specially handheld games.

### Describe the solution you would like.

An option to re-install touch keyboards and handwritting panel service or one to leave it installed in the playbook

### Describe alternatives you have considered.

Never installing Atlas os again dismiss it as a joke and marketing gimick, and spread the word out there.

### Additional context.

hand held computer ship without keyboards the touch keyboard service in windows is simplest option for in game seamless keyboard input the act of selecting on screen keyboard from accessibility menu shuts any open dialog or text box of example entering a wifi password renaming a file problems load osk on top of full screen games.

**Comment by Ast3risk-ops** [comment]
If you left automatic driver install on, I think your keyboard would still work.

**Comment by he3als** [comment]
Closing as invalid - Atlas doesn't touch this service
