### ISSUE TITLE
can you pls add a toggle about installing VC++ Redistributables and 7zip

### ISSUE THREAD

**Issue by rewalax** [Atlas-OS/Atlas#1054]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

sometimes i dont need to install all branches of vc++ redistributables, just [2015-2022](https://learn.microsoft.com/zh-CN/cpp/windows/latest-supported-vc-redist?view=msvc-170) would be enough.  And also i dont like to install 7zip.
so can you pls add a toggle here. thank u

### Describe the solution you would like.

 add a toggle about installing VC++ Redistributables and 7zip

### Describe alternatives you have considered.

 add a toggle about installing VC++ Redistributables and 7zip

**Comment by Ast3risk-ops** [comment]
But 7zip is the best archive manager 😔

**Comment by JayXTQ** [comment]
No, atlas requires these 2.
