### ISSUE TITLE
[FEATURE] - Customize expedited update toggle

### ISSUE THREAD

**Issue by acuteaura** [Atlas-OS/Atlas#1057]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

Windows Update's expedited rollout / "seeker" toggle is set via policy and can't be changed; in this mode Windows will let you defer updates for roughly 20-30 minutes, which is a terrible experience if you're doing something not so interruptable (like a large file copy, or a long gaming session)

### Describe the solution you would like.

This toggle can be set without Policy in HKLM\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings\IsExpedited (DWORD), allowing the user to toggle this setting.

### Describe alternatives you have considered.

I have actually not found where this policy is set.

**Comment by Ast3risk-ops** [comment]
There are other policies to control update deferrals, which Atlas uses. Atlas also disables automatic updates so your gaming sessions will be uninterrupted.

**Comment by CodingMadness** [comment]
so is this fixed?

**Comment by Ast3risk-ops** [comment]
> so is this fixed?

wdym this is a feature request.
