### ISSUE TITLE
[BUG] - Can't bypass steps that require OS activation

### ISSUE THREAD

**Issue by mkuznetsov** [Atlas-OS/Atlas#1059]
### Description

I want to install in on VM and don't want to activate it before testing. I gladly bypass personalisation of any kind (activation block basic staff), and clean up OS for gaming VM. I can't start playbook and you don't provide option to customise it. 

### Steps to reproduce

1) Load ame playbook runner
2) load latest playbook
3) turnoff security to install it
4) and activation requirement can't be bypassed and Next button is not active
 

### Expected behavior

Load playbook
Execute it
Make tests 
Activate OS later and install components that was blocked by activation 

### Actual behavior

Load playbook
Can't press Next button and unselect components that need activation

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

-Windows 11
-Proxmox 8.1 VM
-AMD Ryzen 7745hx
-AMD 610M iGPU

**Comment by JayXTQ** [comment]
Won't be done, this is because of Microsoft ToS, build it yourself to remove activation if you wish.

**Comment by TheyCreeper** [comment]
It's not a big; it's a feature

**Comment by mkuznetsov** [comment]
I DON'T need activation deletion or some kind of alternation to break it. I respect TOS and legal related things. I need an installation with option to install it without this restriction. For example, to choose install 2/3 of features before activation, test it and benchmark it,  and later install 1/3 of features that require activation. I need to test it with all cases I need before go and buy. Right now I don't have that choice. so this is a BUG. Why not to warn before installation that user will miss 1,2,3,... features without activation and proceed with user's choice and finish without personalisation tweaks. personally I don't think all people need it.

**Comment by JayXTQ** [comment]
No, this is impossible. and Atlas isn't built for you to be able to do this also. This won't be happening and it is not a bug either, it is a feature. There is a fine line.

**Comment by mkuznetsov** [comment]
Can I get a list of things that require activation?
From others I see only part of UI personalisation. Custom fonts, backgrounds with logos)), theme. Disable some UI animations. I don't  need them for my tasks anyway. Some registry hacks?
So far looks like I need a fork of Atlas without part that require activation.

**Comment by mkuznetsov** [comment]
So this is still a bug in scenario, that u mask as a feature. features that require activation don't make any significant performance gain. as result look like they are useless, I don't see a branding as valuable feature

**Comment by trolljoe** [comment]
> So this is still a bug in scenario, that u mask as a feature. features that require activation don't make any significant performance gain. as result look like they are useless, I don't see a branding as valuable feature

https://github.com/Atlas-OS/Atlas/issues/1033#issuecomment-1925313588

**Comment by JayXTQ** [comment]
locking
