### ISSUE TITLE
[BUG] - Bugs in 7a26459

### ISSUE THREAD

**Issue by the-P1neapple** [Atlas-OS/Atlas#1062]
### Description

1. My Videos and My Music is not removed
2. Edge does not uninstall with EdgeRemover

### Steps to reproduce

1. Just install the playbook
2. Run playbook while uninstalling edge, reinstall edge using the install software script, remove it using Remove Edge Script.

### Expected behavior

1. Not have my videos and my music folder
2. be able to uninstall edge

### Actual behavior

1.
```
Running PowerShell command '$o = new-object -com shell.application; $currentPins = $o.Namespace('shell:::{679f85cb-0220-4080-b29b-5540cc05aab6}').Items() | ForEach-Object { $_.Path }; foreach ($path in @(
    [Environment]::GetFolderPath('MyVideos'),
    [Environment]::GetFolderPath('MyMusic')
)) {
    if ($currentPins -notcontains $path) {
        $o.Namespace($path).Self.InvokeVerb('pintohome')
    }
}'...
0 files were deleted successfully. 0 files couldn't be deleted.
```

2.
Btw the powershell errors only show when removing user data. Search and Widgets are enabled at the time. Uploading as a file cause too long.
[Output.txt](https://github.com/Atlas-OS/Atlas/files/14789202/Output.txt)

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

not applicable

**Comment by the-P1neapple** [comment]
Btw this bugs i found but don't know how to fix in #1060

**Comment by he3als** [comment]
> My Videos and My Music is not removed

It's intended to be added, not removed. Previously, it was bugged and wasn't added, but now it works.

**Comment by the-P1neapple** [comment]
> > My Videos and My Music is not removed
> 
> It's intended to be added, not removed. Previously, it was bugged and wasn't added, but now it works.
Ah I see. My bad.

Regards to Edge install. Since Edge Remover can install Edge anyway, would it be better to just remove edge from the install software script and treat EdgeRemover as a Add/Remove edge script instead?

**Comment by he3als** [comment]
The Edge issue has been fixed, and I've removed it from `Install Software.cmd`. Thanks!
