### ISSUE TITLE
[BUG] - Not booting using QEMU

### ISSUE THREAD

**Issue by B4sicallyF0x** [Atlas-OS/Atlas#1064]
### Description

ISO not working in QEMU

### Steps to reproduce

1. Open QEMU
2. Boot the ISO
3. The ISO doesn't boot

### Expected behavior

It should boot (i think)

### Actual behavior

Not booting, black screen

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

Ryzen 5 5500
GTX 1650S
16GB RAM

**Comment by Ast3risk-ops** [comment]
WHAT ISO

**Comment by B4sicallyF0x** [comment]
Closed bc it's working now. Just updated QEMU
