### ISSUE TITLE
[FEATURE] - Block Settings application telemetry 

### ISSUE THREAD

**Issue by BobCostanzo** [Atlas-OS/Atlas#1067]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

Right now, Atlas does not block the telemetry call that comes from opening the **Settings** application. As such, it would be ideal if AtlasOS could block the following call:

`settings-win.data.microsoft.com`

### Describe the solution you would like.

Please block the Settings telemetry. I'm unsure if this can be done as a registry tweak or at least through the hosts file.

### Describe alternatives you have considered.

I blocked the endpoint initially through a blocklist as part of NextDNS, but I just added it to my hosts file for now: 127.0.0.1 settings-win.data.microsoft.com

**Comment by ls-wdiff** [comment]
Shipping by default a modified hosts file can have unintended consequences.

**Comment by he3als** [comment]
Unless a specific policy can disable this endpoint without breaking functionality, it won't be blocked in Atlas. Also, I want to point out that not all endpoints are telemetry, this one isn't:

>The following endpoint is used as a way for apps to dynamically update their configuration. Apps such as System Initiated User Feedback and the Xbox app use it.

https://learn.microsoft.com/en-us/windows/privacy/windows-11-endpoints-non-enterprise-editions
