### ISSUE TITLE
[BUG] -  Install error on an old computer

### ISSUE THREAD

**Issue by Retr0680** [Atlas-OS/Atlas#1071]
### Description

there is some error while installing the v4

### Steps to reproduce

1. installing on freshly installed windows 10 with all updates upto date

### Expected behavior

get installed successfully and atomatically reboot the system.

### Actual behavior

getting this instead.
[Packages.txt](https://github.com/Atlas-OS/Atlas/files/14940713/Packages.txt)
[TIOutput.txt](https://github.com/Atlas-OS/Atlas/files/14940714/TIOutput.txt)
[AdminOutput.txt](https://github.com/Atlas-OS/Atlas/files/14940716/AdminOutput.txt)
[ErrorLog.txt](https://github.com/Atlas-OS/Atlas/files/14940717/ErrorLog.txt)

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

- i3 7020u, 16 gb ddr4, 1.5tb storage, intel hd graphics 620

**Comment by he3als** [comment]
Hi, please follow our installation documentation: https://docs.atlasos.net/getting-started/installation/

If you still have the issue after doing so, respond here with fresh logs, and the issue will be reopened.
