### ISSUE TITLE
[BUG] - CMD stuffs get destroyed.

### ISSUE THREAD

**Issue by gitchuon** [Atlas-OS/Atlas#1072]
### Description

After install the new version of AtlasOS, i cant run .cmd files: the cmd window open and then close immediently. I tried to open CMD but some popular commands did not work (image below)

### Steps to reproduce

1. Double click to open a .cmd file or run some commands in cmd.
2. Watch it doesnt work like you expected.

### Expected behavior

It supposes to run normally.

### Actual behavior
1)
![image](https://github.com/Atlas-OS/Atlas/assets/155883444/cc5ada5c-d4b5-4d2c-bbb0-a3ad49bfa047)
2)
![image](https://github.com/Atlas-OS/Atlas/assets/155883444/229e2855-fce1-4ff0-bcad-0582fc4d4409)

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Operating System: Windows 11 IoT Enterprise 64-bit (10.0, Build 22631) (22621.ni_release.220506-1250)
System Manufacturer: Acer
System Model: Aspire A715-43G
Processor: AMD Ryzen 5 5625U with Radeon Graphics          (12 CPUs), ~2.3GHz
Memory: 24576MB RAM
Available OS Memory: 23916MB RAM
Card name: NVIDIA GeForce RTX 3050 Laptop GPU

### Additional content

_my primary language is not English so... hope you guys understand what is going on...._

**Comment by JayXTQ** [comment]
it appears you are running atlas on IoT Enterprise which is not recommended by us. For that this issue will be closed. If you want support please use Windows 10 22H2 or Windows 11 23H2.

**Comment by gitchuon** [comment]
I think I should reinstall Windows with a supported version… By the way, I absolutely love the new AtlasOS version and its theme 🙌🙌. You guys did a great job!
