### ISSUE TITLE
[BUG] - Installing new browser with playbook doesn't change default browser and url file associations

### ISSUE THREAD

**Issue by the-P1neapple** [Atlas-OS/Atlas#1074]
### Description

I have noticed that when you install a new browser with the playbook, the default browser selection does not get changed with the current implementation of changing with the registry. 

This is due to a new driver introduced in the February updates for Windows 10 (KB5034763) and Windows 11 (KB5034765). 
[More information on issue - Bleeping Computer](https://www.bleepingcomputer.com/news/microsoft/new-windows-driver-blocks-software-from-changing-default-web-browser/)

### Steps to reproduce

Install Atlas Playbook and make sure to install a browser (this issue occurred mostly with Librewolf in Internal testing but this may apply to other browsers too)

### Expected behavior

Browsers are installed and default browser is set to new browser installed by playbook.

### Actual behavior

Browsers are installed, but file associations for HTTP and HTTPS either stay as Edge if not removed or are broken and cannot be modified from settings.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Not specific to my device, I have seen this issue a few times with multiple users on our discord.

**Comment by he3als** [comment]
Can you send the `TIOutput.txt` please?

**Comment by the-P1neapple** [comment]
[TIOutput.txt](https://github.com/Atlas-OS/Atlas/files/14978452/TIOutput.txt)
This is the log from my current install that had the issue (ran release 0.4.0). It seems FILEASSOC.cmd never ran at all. I ran a few test playbooks from the latest dev 1797068182e8c7e0a477e699cdef61f8dc94ee3b and I had no issues with Librewolf and Firefox in a Hyper-V. Will test with the other 2 browsers tomorrow to see if it still happens.

**Comment by the-P1neapple** [comment]
Okay i realised I might be an idiot. I may have chosen not to install a browser on my install as I was importing my browser from my file system backup (which had program data and user profile data). I am going to assume the other reports were user error so I will close this issue and reopen it if I have any other findings.

Sorry he3als
