### ISSUE TITLE
[BUG] - "Recommended" is no longer displayed in the start menu

### ISSUE THREAD

**Issue by lovi-dzen** [Atlas-OS/Atlas#1078]
### Description

After Windows updates, the Recommended field is no longer displayed, now nothing is displayed there, even when new programs and openings appear

### Steps to reproduce

start-up opening

### Expected behavior

Everything worked when Atlas was installed, but now it doesn't. I need the recommended ones to work

### Actual behavior

After Windows updates, the Recommended field is no longer displayed, now nothing is displayed there, even when new programs and openings appear
![изображение_2024-04-15_121347719](https://github.com/Atlas-OS/Atlas/assets/153325878/7d0b5787-2dd9-4299-9ebe-25e48a84ce3b)
![изображение_2024-04-15_121424873](https://github.com/Atlas-OS/Atlas/assets/153325878/7dd54417-1af9-4ae6-804d-71a7eaf593d1)

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

-ASUS GTX 1060 6gb STRIX
-Intel i7 7700k

**Comment by JayXTQ** [comment]
This may be because of telemetry, why would you need this feature?

**Comment by lovi-dzen** [comment]
I didn't touch the telemetry settings, everything worked after installing Atlas. The function is convenient, it helps to open the most used applications or recently opened ones. The question is that it just stopped working and I don't know how to fix it

**Comment by he3als** [comment]
Try running the script in the Atlas folder to enable recent items. https://docs.atlasos.net/getting-started/post-installation/atlas-folder/interface-tweaks/

Make sure to enable any related options to recent programs after running the script as well.

**Comment by lovi-dzen** [comment]
The thing is that the options are enabled, but no shortcuts or programs get into this section, it is empty.
![Uploading Снимок экрана 2024-04-17 160908.png…]()

**Comment by lovi-dzen** [comment]
after rebooting everything worked, thanks for the recommendations
