### ISSUE TITLE
my acer pc says i cant project to another screen because i need to install a new video driver

### ISSUE THREAD

**Issue by feedyyyyy** [Atlas-OS/Atlas#108]
**Describe the bug**
A clear and concise description of what the bug is. Providing an error code is highly recommended.

**To Reproduce**
1. click windows+p

2. See error

**Expected behavior**

**Screenshots**

**Desktop Info (please complete the following information):**
 - CPU Intel
 - System Drive Type HDD
 - Version Version	10.0.22000 Build 22000

**Additional context**

**Comment by Zusier** [comment]
You're on Windows 11, not atlas.
