### ISSUE TITLE
[BUG] - wfs.exe missing 

### ISSUE THREAD

**Issue by Evonos** [Atlas-OS/Atlas#1081]
### Description

I had during install Printing enabled ( Printing works ) but when i try to scan things windows tells me wfs.exe is missing.

### Steps to reproduce

Install with printining enabled on a fresh w11 install atlas 0.4

### Expected behavior

wfs.exe being there so you can scan.

### Actual behavior

No wfs.exe and windows being sad

### Atlas Edition

Atlas for Windows 11

### Desktop information

Atlas 0.4 fresh installed with printing setting to yes.

**Comment by Evonos** [comment]
Solution -> Optional windows feature "Fax and Scan" install this ( this should be installed if you want printer functionality because most printers are scanner + print )

**Comment by Xyueta** [comment]
This is a normal behavior when Printing is disabled.
Thanks.

**Comment by he3als** [comment]
The user said that printing is enabled though, I'll keep this open as I want to ensure that scanner features are enabled when users enable printing.

**Comment by he3als** [comment]
On v0.4.0, Fax and Scan are enabled when printing is enabled with the script. Microsoft removed Fax and Scan from Windows 11 by default, so there's no issue.
