### ISSUE TITLE
[BUG] - Microsoft Store Error 0x80072EE7 and Game Pass Error 0x80070057

### ISSUE THREAD

**Issue by AcroFox** [Atlas-OS/Atlas#1082]
### Description

I tried to repair the Windows Store and Game Pass with all methods and it continues to give errors.

It was normal before installing Atlas.

### Steps to reproduce

![image](https://github.com/Atlas-OS/Atlas/assets/62516500/55981966-6beb-4d96-b362-8f095c40598a)
![0 (2)](https://github.com/Atlas-OS/Atlas/assets/62516500/e00f3b96-76c9-4326-a36c-4bfd4229a1c1)
Download does not start

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

📀 System:

⦁ OS: Windows 11 PRO (23H2 / 22631.3447)

💾 Storage:

⦁ SSD: Lexar NM800 512GB - 7,500 MB/s
⦁ SSD: Lexar NM620 4TB RAID0 - 6,600 MB/s

💻 Components:

⦁ Cabinet: COUGAR Panzer Max-G (Full Tower)
⦁ Motherboard: ASUS PRIME Z590-PRO WIFI
⦁ Processor: Intel I7-11700F 4.7GHz (Rocket Lake)
⦁ RAM memory: XPG Spectrix D45G 32GB 3600Mhz
⦁ Video Card: MSI RTX 4060 TI GAMING X 16GB
⦁ Source: XPG Core Reactor 850W (80 Plus Gold)
⦁ Watercooler: Deepcool Castle 360 RGB V2

### Additional content

I did a clean format and updated the store it was normal, then I installed the atlas and it stopped working.

**Comment by Evonos** [comment]
You need to click on the store , settings , then Reinstall / and reset the store.

Should work after that.

**Comment by Xyueta** [comment]
Do you still face this problem?

**Comment by he3als** [comment]
Going to presume not, so I'll close.
