### ISSUE TITLE
[BUG] - Can Not Update | Download error - 0x80248007

### ISSUE THREAD

**Issue by thedtvn** [Atlas-OS/Atlas#1083]
### Description

![image](https://github.com/Atlas-OS/Atlas/assets/80153297/c2157452-2a12-439c-a99a-5279f5f34cbb)

### Steps to reproduce

1. got update 
2. try to update

### Expected behavior

it download and update

### Actual behavior

Download error - 0x80248007

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

![image](https://github.com/Atlas-OS/Atlas/assets/80153297/1475d4ad-ef40-4b7c-9d04-c71a0f97922e)

**Comment by he3als** [comment]
Hi - This is v0.3.2, an unsupported version. We recommend following <https://docs.atlasos.net/getting-started/installation/> to reinstall Windows and install v0.4.0.

However, if you don't want to regardless, follow <https://067be0ec.atlasos-docs-enq.pages.dev/faq-and-troubleshooting/common-questions/windows-update-errors/#general-errors> and try again.

**Comment by MertDalbudak** [comment]
Check this out: https://github.com/Atlas-OS/Atlas/issues/1017#issuecomment-1925948501

You may want to Windows pause updates. I've only been able to test this on Windows 10 only.
