### ISSUE TITLE
Any possibility for docker image of this project to run atlas windows in browser?

### ISSUE THREAD

**Issue by HakaishinShwet** [Atlas-OS/Atlas#1084]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

:-)

### Describe the solution you would like.

:-)

### Describe alternatives you have considered.

:-))

### Additional context.

Since discussion option not enabled in this repo so asking here :-))

**Comment by Ast3risk-ops** [comment]
@JayXTQ close

**Comment by JayXTQ** [comment]
????????
