### ISSUE TITLE
[BUG] - Internet got slow down after new windows updates

### ISSUE THREAD

**Issue by kyloonkoo** [Atlas-OS/Atlas#1085]
### Description

i am using imac then boot camp into windows 10, been doing good for some time. However, today after the macOS update (as specify, it macOS force windows update), i find my internet connection got slow down by nearly 70%, 360mbps+- to 80mbps. 

i tried to boot into macOS, and test the speed, it just running as usual 360mbps, however, i boot back to windows, it just 80mbps.

not really sure what's more info to provide, please advice if need any. 

### Steps to reproduce

![ps1](https://github.com/Atlas-OS/Atlas/assets/167555469/3e633150-1270-4ed4-bf99-ac4f0ef38f24)

### Expected behavior

with the internet speed at least 300mbps

### Actual behavior

![ps1](https://github.com/Atlas-OS/Atlas/assets/167555469/3c5822c3-da59-4d2c-aebe-e8198b914ad1)

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz   2.30 GHz
8.00 GB (7.87 GB usable)
64-bit operating system, x64-based processor

**Comment by he3als** [comment]
I doubt this is an Atlas issue, as I can't see how it would be caused. This is likely to be a driver update from Windows Update that has installed a worse driver.

If you find this to be an Atlas issue specifically, comment here.
