### ISSUE TITLE
[BUG] - Every time I open the game, my mouse freezes.

### ISSUE THREAD

**Issue by maxwell-captains** [Atlas-OS/Atlas#1086]
### Description

Every time I open the game from Steam, the mouse freezes and sounds appear. Maybe a driver issue?

### Steps to reproduce

Open steam, open the game

### Expected behavior

Open steam, open the game

### Actual behavior

Open steam, open the game

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

Acer Predator · Qing Neo
I5-13500HX
RTX4060
32G RAM
500GB+2TB

### Additional content

help me

**Comment by JayXTQ** [comment]
This issue will be closed until the template is filled out correctly. "Expected behaviour" should not be the original issue.

**Comment by JayXTQ** [comment]
Please comment when and if fixed

**Comment by JayXTQ** [comment]
Well fill out the appropriate heading with the appropriate input
