### ISSUE TITLE
[BUG] - Sound systems and the second screen problem

### ISSUE THREAD

**Issue by berlinner** [Atlas-OS/Atlas#1089]
### Description

I use a laptop and it is connected to a screen. When I turn on the second screen, windows doesn't save “make this the main screen, screen layout, hz value” like it used to and it resets every time. When I turn on the screen my sound source, bluetooth, briefly gives the sound from the main laptop speaker and then goes back to bluetooth.

I have deleted and reinstalled the iGPU and Nvidia drivers with ddu, but it didn't fix it.

By the way, I just realized that every time I turn on the computer, the night light option is on.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Processor 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz   2.69 GHz
RAM: 16,0 GB

**Comment by JayXTQ** [comment]
It appears you deleted some stuff, please fill out our template correctly. Please comment when updated
