### ISSUE TITLE
New apps compatibility

### ISSUE THREAD

**Issue by Kekkobobone** [Atlas-OS/Atlas#1090]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

I installed a game and i have some problemii tested game on another PC and Is perfect,on Atlas os no.

> 

### Describe the solution you would like.

I Wish of Atlas add new booster how app

### Describe alternatives you have considered.

I tryed tò reset the PC and not go the game

### Additional context.

Pls fix it

**Comment by PencilNavigator** [comment]
Invalid issue (incorrect type, not enough info provided).
Please re-open the issue under the "BUG REPORT" template, and make sure you provide detailed info for us to identify the issue.
