### ISSUE TITLE
[BUG] - Widgets enable script installs Edge despite declining

### ISSUE THREAD

**Issue by coffandro** [Atlas-OS/Atlas#1091]
### Description

The widget enable script installs edge despite being declined

### Steps to reproduce

1. Open the Atlas folder
2. Run the widget enable script
3. Decline installing edge (pres N)

### Expected behavior

The script exists without an issue

### Actual behavior

The script goes ahead and installs edge

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

- Thinkpad p50
- Xeon E3 1505M
- 48gb ram
- Quadro M2000M
- three drives, 4XX NVME (with windows on a 256gb partition), 256 NVME, 2TB SATA
- Atlas v 0.4.0

### Additional content

Running Atlas v0.4.0

**Comment by Ast3risk-ops** [comment]
Pretty sure edge is required for the widgets (https://docs.atlasos.net/getting-started/post-installation/atlas-folder/general-configuration/#widgets-news-and-interests) but I think we should hook up a "no" answer to closing the script.

**Comment by coffandro** [comment]
Forgot a screenshot but there already is a no, it dosent work though![IMG_20240427_210020.jpg](https://github.com/Atlas-OS/Atlas/assets/75324436/549418fe-401f-43e3-8e36-d52a0f71f654)

**Comment by Xyueta** [comment]
This has been fixed in https://github.com/Atlas-OS/Atlas/commit/e4e9a1a25ad250d3875d8bb23aea0c0419e0349f, and will be available in the next release.
Thanks.

**Comment by he3als** [comment]
I'm going to re-open this as I think it's best to keep issues open until there's a new release for transparency with users.

**Comment by he3als** [comment]
Fixed in [release v0.4.1](https://github.com/Atlas-OS/Atlas/releases/tag/0.4.1). See the release for more info on what v0.4 users can do.
