### ISSUE TITLE
[BUG] - System on black screen after idle

### ISSUE THREAD

**Issue by uncognic** [Atlas-OS/Atlas#1092]
### Description

When system left idle for a while, screen will go black, no response from caps lock nor num lock

### Steps to reproduce

1. Boot computer 
2. Leave idle for 30m-1h
3. Won’t turn back on

### Expected behavior

For it to wake when I move the mouse

### Actual behavior

Black screen, not sleep mode, not responding 

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

Intel pentium 5405u
8GB DDR4
256gb ssd 
UHD 610

**Comment by candrapersada** [comment]
and the problem occurs if you use the backup, restore and clone partition features such as `DiskGenius`.

**Comment by uncognic** [comment]
I haven’t used any tools like those

**Comment by he3als** [comment]
Hi - what are your power plan settings?

**Comment by he3als** [comment]
Going to close as stale

**Comment by DV64** [comment]
Same problem!!
