### ISSUE TITLE
[BUG] - Automatic Maintenance shouldnt be Outright disabled.

### ISSUE THREAD

**Issue by Evonos** [Atlas-OS/Atlas#1095]
### Description

Automatic Maintenance does many Good ( and some bad ) things.
it should be Edited to leave out the "bad" things and leave the "good" things enabled.

### Steps to reproduce

Install Atlas OS.

### Expected behavior

Automated Maintenance Should still run the Critical components as in : 

- **SmartScreenSpecific: updates application signatures for SmartScreen.**
**- CleanupTemporaryState: clears temporary files in AppX (Metro/UWE) app packages. rundll32** **Windows.Storage.ApplicationData.dll,CleanupTemporaryState.**
**- Pre-Staged App Cleanup: part of the AppX cleanup process. rundll32 AppxDeploymentClient.dll,AppxPreStageCleanupRunTask.**
**- ProactiveScan: Does a chkdsk scan.**
**- ScheduledDefrag: runs the Windows Defragmenter: defrag -c -h -o -$. This is often the task that takes the longest. Oddly, the -h switch makes it run at normal instead of low priority, which is odd for automatic maintenance.** ( yes even important for NVME and SSD it does trim and stuff )
**- Diagnosis\Scheduled: runs Windows Diagnostics.**
**- SilentCleanup: runs Disk Cleanup: cleanmgr /autoclean /d %systemdrive%.**
- DiskDiagnosticDataCalculator: runs disk diagnostics. rundll32 dfdts.dll,DfdGetDefaultPolicyAndSMART.
**- RunFullMemoryDiagnostic: a RAM diagnostic.**
**- LPRemove: runs lpremove which removes unnecessarily or unusable language packs.**
**- Plug And Play Cleanup: clears the state information for any Plug and Play devices which haven't been used for 30 days.**
**- AnalyseSystem: runs Power Efficiency Diagnostics.**
**- RegIdleBackup: makes a backup of the registry.**
**- MRTHB: runs MRT /EHB /Q. This is the Malicious Software Removal tool, so this is likely a security scan.**
**- StartComponentCleanup: cleans up the WinSxS directory that holds optional Windows component images.
**- AccountCleanup: cleans up ancient user profiles on network shared machines.**
**- ResPriStaticDBSync.**
**- WsSwapAssessmentTask. Sysmain part.**
**- SystemRestore. srtasks ExecuteScheduledSPPCCreation. Makes a Restore Point.**
**- SynchronizeTime. sc start w32time task_started. Syncs the system clock.
- SynchronizeTimeZone. tzsync. Connected to the above.**
**- Maintenance Install. usoclient StartInstall. Installs any Windows Updates that have been downloaded but not installed yet.
- Work Folders Maintenance Work. Relates to the Work Folders file sharing server system.**

### Actual behavior

Maintenance service is disabled which is a High risk for multiple security and hardware related issues.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Not necessary its a "cut down too much " issue on Atlas part.

### Additional content

Disabling maintenance makes the OS slower , prone to more bugs , Trashing itself , and at risk of security and undiscovered hardware failures.

**Comment by PencilNavigator** [comment]
Hi there, please re-submit this issue as a "feature request".
