### ISSUE TITLE
[BUG] - Many Automatic Maintenance tasks seemingly don't run

### ISSUE THREAD

**Issue by Evonos** [Atlas-OS/Atlas#1096]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

Description
Automatic Maintenance does many Good ( and some bad ) things.
it should be Edited to leave out the "bad" things and leave the "good" things enabled.

Steps to reproduce
Install Atlas OS.

Expected behavior
Automated Maintenance Should still run the Critical components as in :

SmartScreenSpecific: updates application signatures for SmartScreen.
- CleanupTemporaryState: clears temporary files in AppX (Metro/UWE) app packages. rundll32 Windows.Storage.ApplicationData.dll,CleanupTemporaryState.
- Pre-Staged App Cleanup: part of the AppX cleanup process. rundll32 AppxDeploymentClient.dll,AppxPreStageCleanupRunTask.
- ProactiveScan: Does a chkdsk scan.
- ScheduledDefrag: runs the Windows Defragmenter: defrag -c -h -o -$. This is often the task that takes the longest. Oddly, the -h switch makes it run at normal instead of low priority, which is odd for automatic maintenance. ( yes even important for NVME and SSD it does trim and stuff )
- Diagnosis\Scheduled: runs Windows Diagnostics.
- SilentCleanup: runs Disk Cleanup: cleanmgr /autoclean /d %systemdrive%.
DiskDiagnosticDataCalculator: runs disk diagnostics. rundll32 dfdts.dll,DfdGetDefaultPolicyAndSMART.
- RunFullMemoryDiagnostic: a RAM diagnostic.
- LPRemove: runs lpremove which removes unnecessarily or unusable language packs.
- Plug And Play Cleanup: clears the state information for any Plug and Play devices which haven't been used for 30 days.
- AnalyseSystem: runs Power Efficiency Diagnostics.
- RegIdleBackup: makes a backup of the registry.
- MRTHB: runs MRT /EHB /Q. This is the Malicious Software Removal tool, so this is likely a security scan.
**- StartComponentCleanup: cleans up the WinSxS directory that holds optional Windows component images.
- AccountCleanup: cleans up ancient user profiles on network shared machines.
- ResPriStaticDBSync.
- WsSwapAssessmentTask. Sysmain part.
- SystemRestore. srtasks ExecuteScheduledSPPCCreation. Makes a Restore Point.
**- SynchronizeTime. sc start w32time task_started. Syncs the system clock.
SynchronizeTimeZone. tzsync. Connected to the above.**
**- Maintenance Install. usoclient StartInstall. Installs any Windows Updates that have been downloaded but not installed yet.
Work Folders Maintenance Work. Relates to the Work Folders file sharing server system.**
Actual behavior
Maintenance service is disabled which is a High risk for multiple security and hardware related issues.

Atlas Edition
Atlas for Windows 11 23H2

Desktop information
Not necessary its a "cut down too much " issue on Atlas part.

Additional content
Disabling maintenance makes the OS slower , prone to more bugs , Trashing itself , and at risk of security and undiscovered hardware failures.

### Describe the solution you would like.

see #1095 for better formatting

### Describe alternatives you have considered.

see #1095 for better formatting

### Additional context.

see #1095 for better formatting

**Comment by he3als** [comment]
Automatic maintenance is enabled, can you elaborate further if it's somehow not functioning correctly?

**Comment by Evonos** [comment]
> Automatic maintenance is enabled, can you elaborate further if it's somehow not functioning correctly?

hmm it says for me Deactivated and managed by System administrator ( which usually is group policys )

**Comment by Evonos** [comment]
> Automatic maintenance is enabled, can you elaborate further if it's somehow not functioning correctly?

i also checked while "Technically" maintenance isnt fully forced off , maintenance tasks seemingly doesnt run , like ResPriStaticDbSync and WsSwapAssessmentTask  which run during maintenance ( set to 1x per day for me as test )  they just never run not even when i leave the PC idle for hours 
Like right now it says "Last ran 3.5.2024 (DD/MM/YYYY) " while technically it should run each day.
i can force these to run but ... yeah maintenance doesnt seem to run as it should.

**Comment by Xyueta** [comment]
Those are SysMain related tasks, for now enable it.
In the future version, you will be able to enable/disable Sysmain in Atlas configuration folder. (Enabled - Default).

Thanks.

**Comment by he3als** [comment]
I'm going to re-open this as I think it's best to keep issues open until there's a new release for transparency with users.

**Comment by he3als** [comment]
https://raw.githubusercontent.com/Atlas-OS/Atlas/main/src/playbook/Executables/AtlasDesktop/3.%20General%20Configuration/Superfetch/Enable%20SuperFetch%20(default).cmd

If you want to re-enable SysMain, use this.

**Comment by Evonos** [comment]
> https://raw.githubusercontent.com/Atlas-OS/Atlas/main/src/playbook/Executables/AtlasDesktop/3.%20General%20Configuration/Superfetch/Enable%20SuperFetch%20(default).cmd
> 
> If you want to re-enable SysMain, use this.


that link is broken now. "404 not found"

**Comment by PencilNavigator** [comment]
https://raw.githubusercontent.com/Atlas-OS/Atlas/main/src/playbook/Executables/AtlasDesktop/6.%20Advanced%20Configuration/Services/Superfetch/Enable%20SuperFetch%20(default).cmd

Moved to another folder in a recent PR.

**Comment by he3als** [comment]
Fixed in [release v0.4.1](https://github.com/Atlas-OS/Atlas/releases/tag/0.4.1). See the release for more info on what v0.4 users can do.
