### ISSUE TITLE
[BUG] - individual application volume in volume mixer doesn't save, it returns to 100% after restart

### ISSUE THREAD

**Issue by matuuz** [Atlas-OS/Atlas#1097]
### Description

for example if i'm playing a game and i lower volume of that particular game from volume mixer after a restart it goes back to 100%

### Steps to reproduce

1: lower volume of any application in volume mixer
2: restart pc

### Expected behavior

i expect for the individual apps volume to be saved even after restart

### Actual behavior

doesn't save

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

not hardware related, it's pure software

**Comment by Ast3risk-ops** [comment]
Are you even on the latest version of Atlas?

**Comment by matuuz** [comment]
> it doesn't save even in normal windows?

yes it does save, it must be something they disabled but i don't know the option (maybe it is, i don't know)

**Comment by matuuz** [comment]
> Are you even on the latest version of Atlas?

yes, i installed it from scratch yesterday with latest iso and files from atlas

**Comment by gitchuon** [comment]
It's a common issue, maybe not related too much too AtlasOS. I have got this issue many times by using some other's tweakers on the Internet.

**Comment by he3als** [comment]
Hi, I tried this on Windows 11 and 10 but couldn't reproduce the issue.

Here's what I did:
1. Played audio in Chrome
2. Adjusted the volume mixer for Chrome
3. Restarted the PC
4. Opened Chrome again, played the audio
5. Checked the volume mixer (it's at what I left it at)

If you can give any further links to Atlas or anyone else can reproduce this, comment, and I'll reopen the issue. Ensure you've installed Atlas following the installation guide: https://docs.atlasos.net/getting-started/installation/
