### ISSUE TITLE
[FEATURE] - Ability to enable AutoPlay

### ISSUE THREAD

**Issue by frankh93** [Atlas-OS/Atlas#1098]
### Description

I just installed Atlas and it runs pretty good, but its missing something i use daily... I work using some pendrives and cards so the autoplay feature is a must for me, as it helps to get things go easier... is there any way to bring it back? thanks beforehand

### Steps to reproduce

No

### Expected behavior

No

### Actual behavior

No

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

No

**Comment by Ast3risk-ops** [comment]
This is the wrong template. Please use the correct one. As for Autoplay, it can be enabled in Windows settings.

**Comment by frankh93** [comment]
sorry for the wrong template.
![Captura de pantalla 2024-05-11 115725](https://github.com/Atlas-OS/Atlas/assets/16171231/c34751f6-6165-4aca-9ef8-395e66c7dae2)
checked in settings but the option isnt available, also checked in classic control panel and even when option is there it does nothing

**Comment by frankh93** [comment]
sorry for the wrong template
![Captura de pantalla 2024-05-11 115601](https://github.com/Atlas-OS/Atlas/assets/16171231/6794e2de-3620-4734-a9b7-c9a84ea45850)
checked in setting and there isnt such option, also checked in classic control panel and even when option is there it does nothing

**Comment by Xyueta** [comment]
Done in https://github.com/Atlas-OS/Atlas/commit/b5a9fadec6ef7b58f74c2dd1b774e80655797160.

Thanks for the suggestion.

**Comment by he3als** [comment]
I'm going to re-open this as I think it's best to keep issues open until there's a new release for transparency with users.

**Comment by he3als** [comment]
Fixed in [release v0.4.1](https://github.com/Atlas-OS/Atlas/releases/tag/0.4.1). See the release for more info on what v0.4 users can do.
