### ISSUE TITLE
[FEATURE] - An actual ISO or GNU/Linux support

### ISSUE THREAD

**Issue by compromisable** [Atlas-OS/Atlas#1099]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

  I need windows to download windows? Uh, tautology much? 

### Describe the solution you would like.

Provide an actual iso or a GNU/Linux port of your executable

### Describe alternatives you have considered.

There are none

### Additional context.

I need windows to download windows? Uh, tautology much?

**Comment by Ast3risk-ops** [comment]
Hi Linux user! Did you know we have a USB-based guy using Ventoy, which works on Linux?
