### ISSUE TITLE
[FEATURE] - Notifications should not be disabled by default

### ISSUE THREAD

**Issue by ghost** [Atlas-OS/Atlas#1100]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

Currently, by default, Atlas completely disables notifications. I think that this is an unintuitive default, and that something as important as notifications should be untouched, and left up to the user to configure.

### Describe the solution you would like.

Keep notifications enabled by default

### Describe alternatives you have considered.

n/a

**Comment by trolljoe** [comment]
doesn't it ask you if you wanna disable it or not in the playbook?

**Comment by june1025** [comment]
Yeah i guess i missed that. I still think it should be opt-in in the installer though, not enabled by default.

**Comment by Ast3risk-ops** [comment]
What are you even saying it *is* opt-in.

**Comment by june1025** [comment]
First of all, "What are you even saying" is not the nicest way to respond to someone. Second, let me clarify what I mean: when you go through the Atlas installer, `disable notifications` is on by default. Of course you can just turn it off, but I think that disabling notifications is quite extreme, and shouldn't be opt-out, as it's quite easy to gloss over, as I just did here.

**Comment by Xyueta** [comment]
> First of all, "What are you even saying" is not the nicest way to respond to someone. Second, let me clarify what I mean: when you go through the Atlas installer, `disable notifications` is on by default. Of course you can just turn it off, but I think that disabling notifications is quite extreme, and shouldn't be opt-out, as it's quite easy to gloss over, as I just did here.

This is due to a poll that has been conducted on our discord server. You have the ability to turn them on or off within the AME Wizard configuration part.

![image](https://github.com/Atlas-OS/Atlas/assets/101590573/4b2ff577-b642-44cd-a811-419606f71877)

Thanks.

**Comment by he3als** [comment]
In that poll, it wasn't noted that turning off the notification service was unlikely to improve performance. However, even if we go with the poll results, the security implications need to be factored in, as users who turn off auto-updates are meant to get notifications for updates via Windows notifications.

I want to refactor the overall options and tuck all the services into a 'Show advanced options' toggle for the next release.

**Comment by he3als** [comment]
Options are being refactored in #1111

**Comment by he3als** [comment]
Fixed in [release v0.4.1](https://github.com/Atlas-OS/Atlas/releases/tag/0.4.1). See the release for more info on what v0.4 users can do.
