### ISSUE TITLE
[BUG] - ASUS laptop resets power-plan and can't be changed from Control Panel on boot

### ISSUE THREAD

**Issue by Giocraft125** [Atlas-OS/Atlas#1102]
### Description

It's been a month since I installed Atlas on a clean windows copy on my laptop, and it really improved the fps in some games, but I noticed that every time I restart the PC, the selected power plan is always power saver.
I couldn't change that setting from the control panel, because it gave me an error saying: "your power plan information isn't available". To change it I used the Windows mobility center, which allowed me to choose the Atlas Power Scheme. Is there any way to fix this? Thanks. 

### Steps to reproduce

1. Power on the PC 
![unnamed](https://github.com/Atlas-OS/Atlas/assets/124938971/cff115ba-92be-48ed-8e41-6663bfd1ac8d)
2. Get in the desktop 
![Screenshot 2024-05-16 191428](https://github.com/Atlas-OS/Atlas/assets/124938971/7a4e215d-5922-4ec9-9d42-7776a451c578)
3. PC feels slow and goes in sleep mode after 5 minutes of waiting
4. Go to control panel to change power plan in Power Options.
5. It says: "your power plan information isn't available"
![Screenshot 2024-05-16 202539](https://github.com/Atlas-OS/Atlas/assets/124938971/9279c750-05b1-4330-9cc2-57b398895c28)
6. Go check in the Windows Mobility Center, find out you're on power saver
![Screenshot 2024-05-16 202556](https://github.com/Atlas-OS/Atlas/assets/124938971/22be306a-8c87-44e8-bb53-cb9883bb6031)
7. Change it from there
![Screenshot 2024-05-16 202610](https://github.com/Atlas-OS/Atlas/assets/124938971/76e09954-6ba7-490c-9245-286273b78ac4)
8. Go in control panel (that know works) and in Power Options select "Atlas Power Scheme" because in mobility center it only allows to chose "High Performance" 
![Screenshot 2024-05-16 202643](https://github.com/Atlas-OS/Atlas/assets/124938971/6142f113-6363-48e9-ade8-a5176b3ff6c1)
9. Repeat at every reboot

### Expected behavior

The power plan should always remain the same.

### Actual behavior

The power plan changes to power saver on every reboot.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Laptop Brand: Asus TUF Gaming FX505DT
CPU: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx Base Clock Speed: 2.30 GHz, 4 Cores
GPU: Nvidia GeForce GTX 1650 1560 MHz 4 GB VRAM (mobile), Driver Version: 552.44
Memory: 16 GB SODIMM DDR4 Single 2400 MHz RAM Stick
Storage:
Samsung SATA SSD 870 QVO 2 TB
Micron NVMe SSD 2200V 500 GB

**Comment by skaicacher** [comment]
i have the same issue with same computer lmfao

**Comment by Giocraft125** [comment]
Damn

**Comment by he3als** [comment]
Hi, can you try running `C:\Windows\AtlasDesktop\8. Troubleshooting\Telemetry Components.cmd`, removing the package, and restarting? This probably won't fix it, but I'm just making sure

I'm unsure how to diagnose your issue as we don't have that hardware.

**Comment by Giocraft125** [comment]
> Hi, can you try running `C:\Windows\AtlasDesktop\8. Troubleshooting\Telemetry Components.cmd`, removing the package, and restarting? This probably won't fix it, but I'm just making sure
> 
> I'm unsure how to diagnose your issue as we don't have that hardware.
> 
> Does the same not happen on stock Windows?

Hi, I ran the script but the problem remains, thanks for the help tho.

**Comment by nicklvh** [comment]
I've done a bit of research on this issue and it seems to be a general windows issue. I'm not very sure why this is happening either. Maybe this could be an ASUS issue?

https://www.reddit.com/r/ASUS/comments/1azrgox/your_power_plan_information_isnt_available/
https://answers.microsoft.com/en-us/windows/forum/all/your-power-plan-information-isnt-available-why/17fd5554-b61f-4570-a371-5b08bb007540

**Comment by he3als** [comment]
I am going to close this for now for that reason. If anyone has any comments for solutions or causes, then I'll re-open

**Comment by jean3dsign-collab** [comment]
Indeed, but I found its not related to Atlas OS or any other playbook. Its how Windows11 25H2 works.

I have a new 2026 ASUS TUF F16 and ran into a similar issue (where the power plans simplys disappear but no error msg, only the balanced reactivated alone). I managed to fix it and use any custom power plan I want with G-Helper by doing two things:

1. Fixing the Disappearing Power Plans: > Windows tends to hide custom power plans. To keep them permanently listed, you need to add a registry key. Navigate to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power, create/find PlatformAoAcOverride, and set its value to 0.

2. Mapping Plans in G-Helper:
I had to manually configure G-Helper to recognize these plans. You just need to open G-Helper's config.json and add the GUIDs of your desired power plans (you can do this manually, or just ask an AI to format the JSON correctly to avoid syntax errors).

Once the registry is tweaked and the .json is set, everything works flawlessly.

At least it worked in my case (I don't use Armoury Crate, G-Helpers is the right alternative to this sh*t)
