### ISSUE TITLE
[BUG] - DISM has a harmless error with RestoreHealth

### ISSUE THREAD

**Issue by vulcan4d** [Atlas-OS/Atlas#1103]
### Description

DISM no longer can repair the system after AtlasOS is deployed.  Normally DISM will run, however after AtlasOS is run DISM will ask for the source file.  A source file can be provided but it continues to fail.  The specific Windows can be specified in the source (Enterprise, Home, etc) but it still fails.  DISM is a very important tool.  If AtlasOS is tailored to gamers especially, many of which overclock and have unstable systems, DISM can be a savior to fix Windows problems that build up over time.  Without DISM working, I expect the system to get progressively worse over time.

### Steps to reproduce

Running DISM /Online /Cleanup-Image /RestoreHealth fails and requires source

### Expected behavior

DISM command would run, and complete.  Usually it does not require the source file.

### Actual behavior

DISM fails and asks for source files
You can aquire all possible versions of Windows 11 but DISM will continue to ask for source files.
![image](https://github.com/Atlas-OS/Atlas/assets/25832698/359ca27a-22bb-4f4e-80d5-cd6c0561eca7)

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Ryzen 7800x3D
32GB DD5
RTX3060TI
Intel NVME (OS Drive)
Plextor NVME (Data Drive)

**Comment by Ast3risk-ops** [comment]
Do other DISM operations work? I'd imagine this specific operation might be manually prevented from working, but someone will have to confirm this.

**Comment by he3als** [comment]
This is a known issue but can be safely ignored, it still completes successfully. DISM simply can't find Atlas' custom packages to remove telemetry and Defender (if you selected it) on Windows Update, so that's why it says the source can't be found.

There might be a workaround to this in the future.

**Comment by he3als** [comment]
A fix is being worked on for this.
