### ISSUE TITLE
[BUG] - Google Chrome sync paused after every browser reopen

### ISSUE THREAD

**Issue by ARenigma** [Atlas-OS/Atlas#1105]
### Description

Every time I open Chrome, the sync is paused requiring me to sign in again. This is after every browser restart and not system restart.

### Steps to reproduce

1. Start chrome
2. Sign in and turn on sync
3. Close Chrome and open it again
4. Sync paused (Sign in required again)

### Expected behavior

Sync continuously working after initial one-time setup and sign in.

### Actual behavior

Every time I restart Chrome, I have to sign in again to start sync.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Ryzen 5900x
16GB ram
Win 11 on 250GB SSD
Nvidia RTX 3080 10GB 

### Additional content

I have tried allowing cookies, reinstalling edge and reinstalling chrome but nothing worked. 
I cannot find Auto-Cleaner.cmd file in AtlasOS 0.4.0 scripts folder which was modified as a solution in earlier similar issues.

**Comment by ARenigma** [comment]
Just checked, and currently sync only works when Chrome is installed before installing AtlasOS.

**Comment by Ast3risk-ops** [comment]
Have you checked if it's a group policy?

P.S. Chrome itself is spyware, and the sync feature (which is confusing on purpose) is how they associate all the data with your account.

https://contrachrome.com/

**Comment by ARenigma** [comment]
Checking group policy was last resort but sync started working when I installed chrome before AtlasOS. I was also investigating chrome services but everything seemed fine there. I'm curious to know why it works when installed before atlas though.

**Comment by he3als** [comment]
Hi - After installing Atlas v0.4.0, I tested installing Chrome, signing in with sync, and restarting, but I can't reproduce your issue. I'll leave it open, but I don't know how to help.

Have you followed our documentation to get a fresh Windows install before installing Atlas? <https://docs.atlasos.net/getting-started/installation/>

**Comment by testermania** [comment]
just add url accounts.google.com 3rd party cookies allowed in chrome.

**Comment by candrapersada** [comment]
does the problem also occur with chromium or not?

**Comment by ARenigma** [comment]
The problem only occurs with chrome and not edge

**Comment by candrapersada** [comment]
what I mean is using chrome sync in chromium not edge sync

**Comment by ARenigma** [comment]
I haven't tested it with chromium
