### ISSUE TITLE
[BUG] - Slideshow lock screen not working

### ISSUE THREAD

**Issue by toxsickcity** [Atlas-OS/Atlas#1110]
### Description

Hello Members of ATLAS,

I am new around here and started to install atlas to my home pc's and love how clean the os is now,

stupid right click is restored to windows 10 style yay!!

Anywho I am here to ask support regarding a feature I do like in 10/11 which is when system is idle the system goes to LOCK SCREEN, then displays a slideshow of photos which I really enjoy.
Typically, you would set slide show, select the folder,. and hit WIN+L to bring lock screen, the changes are immediate and after usually 3 seconds will start display the photos..

This seems removed or broken in Atlas, Please help :)

![1714686437-634091-screenshot-2024-05-03-074526](https://github.com/Atlas-OS/Atlas/assets/29589685/76b4dc52-2e63-497d-b6c5-2b4e9fb6eb30)

Sadly I am unable to see this working with any of my Atlas systems,

Can someone please assist me to restore this feature :)

Many thanks,
Shaun.

### Steps to reproduce

Add a folder to the lock screen . Slideshow.

On normal windows 11. The folder with photos will be lock screen slideshow will occur and is nice visuals.

Put system to lock. (Win+L) Seconds later images flash up.

### Expected behavior

Slide show during lock screen

### Actual behavior

Static image, no slideshows.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Tested across at least 5 different configurations PCs.

Laptops and desktops. All exhibit same issue.

### Additional content

I have tried to use the atlas folder on desktop to enable lock screen, I have changed themes in system menu (old school menu tick boxes)
But no help.

**Comment by the-P1neapple** [comment]
Hello @toxsickcity,

Thanks for bringing this to our attention. A current workaround for this is to enable SlideShow through the power plan settings. You can do this by clicking Start Menu > Search for Edit Power Plan > Change advanced power settings >Desktop Background Settings >Slide Show > Change from Paused to Available.

I have implemented this fix here #1116

**Comment by toxsickcity** [comment]
Hello,

Thank you for your reply,

I have followed your instructions and found to already be enabled, but lock screen wont change or show any images from any folders when in slideshow mode,

I think the power option you refer to is the desktop background and not the lock screen functions?

I have for curious sakes put the setting into paused then back into available again which also didn't help,

many regards,
Shaun.

**Comment by the-P1neapple** [comment]
Thanks @toxsickcity,

We will investigate this further, I have tried this fix myself and thought it took a while for the images to start showing up on the lock screen.

-Pineapple

**Comment by the-P1neapple** [comment]
Hello Again @toxsickcity, I may have a solution for this issue.

Can you please try re-enabling Search indexing with the script found in the Atlas Folder > 3. General Configuration > Search Indexing. Then I need you to go to the lock screen wallpaper settings and swap from slideshow to picture, after a few moments swap back to slideshow and configure your folders if needed.

Please let me know if this works.

-Pineapple

**Comment by toxsickcity** [comment]
Hello the-Pineapple.

I share good news, the Enable the 'Windows Indexing ' resolved it for me too,

I really appreciate you looking into this, although its a silly feature, it's something that looks nice :)

Thanks again for your efforts in finding a solution :)

**Comment by anjai0904** [comment]
There is a further issue here. The above fix works for the lock screen Win+L or when pc goes to lockscreen when it is in idle. But for the initial boot-time log in screen the wallpaper is still a bland yellow-orange one. I cannot seem to change it.

**Comment by toxsickcity** [comment]
Not sure about that one. I'll have to take a look. Maybe the Devs will know
more.

I will look to see if I can replicate your issue on my machines and if so I
will update the ticket in GitHub,

Cheers.

**Comment by he3als** [comment]
> There is a further issue here. The above fix works for the lock screen Win+L or when pc goes to lockscreen when it is in idle. But for the initial boot-time log in screen the wallpaper is still a bland yellow-orange one. I cannot seem to change it.

After a brief test, I could reproduce this

**Comment by he3als** [comment]
### Fix slideshow lockscreen

1. **Navigate:** Start Menu > Search for Edit Power Plan Change advanced power settings >Desktop Background Settings >Slide Show
2. Change from Paused to Available

---

### Fix for lockscreen not displaying on boot

1. Open `regedit`
3. Delete the `DisableAutomaticRestartSignOn` in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System`
4. Enable 'Use sign-in info to auto-finish setting up device after update or restart' under 'Sign-in options' on the Accounts page

**Comment by toxsickcity** [comment]
How on earth did you even find that was the fix? Your a computer god!

Thank you so much for looking into this and investing time to resolve this..

Big cheers mate!

**Comment by he3als** [comment]
Fixed in [release v0.4.1](https://github.com/Atlas-OS/Atlas/releases/tag/0.4.1). See the release for more info on what v0.4 users can do.
