### ISSUE TITLE
[FEATURE] - Don't disable edge swipe if touchscreens / ARM64 is detected

### ISSUE THREAD

**Issue by n00b69** [Atlas-OS/Atlas#1114]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

By default, AtlasOS disables edge swipe. This however also disables the ability to swipe up on the bottom of the screen to access the taskbar on touchscreen devices.

### Describe the solution you would like.

To keep edge swipe enabled if it detects systems with touchscreen

### Describe alternatives you have considered.

The current fix is to manually re-enable it.

**Comment by he3als** [comment]
Fixed in [release v0.4.1](https://github.com/Atlas-OS/Atlas/releases/tag/0.4.1). See the release for more info on what v0.4 users can do.
