### ISSUE TITLE
[FEATURE] - Add an option to add back in phone link

### ISSUE THREAD

**Issue by Kaympe20** [Atlas-OS/Atlas#1119]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

When using Atlas, I am not able to use Windows Phone Link.

### Describe the solution you would like.

I would like Atlas to add a script to add Windows Phone Link back into Windows.

### Describe alternatives you have considered.

KDE Connect works, although it does not have full feature parity with phone link.

**Comment by Ast3risk-ops** [comment]
[According to Microsoft](https://support.microsoft.com/en-us/topic/phone-link-requirements-and-setup-cd2a1ee7-75a7-66a6-9d4e-bf22e735f9e3) you can install it like this:

> To install it on your Windows 10 PC:
> - Open Settings on your PC
> - Search for Phone Link
> - Select Enable or disable Phone Link
> - Turn on the toggle for Turn on Phone Link
> - A pop-up window will appear, prompting you to click on Install to add Phone Link to your PC.

> To install it on your Windows 11 PC:
> - Open Settings on your PC
> - Search for Phone Link
> - Select Enable or disable Phone Link
> - Turn on the toggle for  Phone Link
> - A pop-up window will appear, prompting you to click on Install to add Phone Link to your PC.

**Comment by he3als** [comment]
The above should work. I'll close this issue, but if there's an issue installing Phone Link, comment, and it'll be opened again.

**Comment by Kaympe20** [comment]
@he3als It does not work. [Here](https://github.com/Atlas-OS/Atlas/assets/117483128/d094016f-18a9-4cdc-ab85-14404dbee924) is a video showing the settings app acting as it does for removed features.

**Comment by he3als** [comment]
You have to enable it in the Atlas folder first

**Comment by Kaympe20** [comment]
I apologize. It must have been a feature added in v0.4 as when i checked during v0.3, it was not available as an option.

**Comment by he3als** [comment]
No worries! Does it work now?

**Comment by Kaympe20** [comment]
> No worries! Does it work now?

The calling is extremely choppy. I am unsure if this is Atlas' or Windows' fault.

**Comment by he3als** [comment]
Presuming that Bluetooth is being used, it could be Bluetooth drivers, but I'm unsure. It's unlikely to be Atlas' fault, as I can't imagine any changes that could affect that.
