### ISSUE TITLE
Xbow Gamebar not able to turn on 

### ISSUE THREAD

**Issue by montyop** [Atlas-OS/Atlas#112]
**Describe the bug**
Xbow Gamebar not able to turn on 

**To Reproduce**
1. Go to settings
2. Click on gaming
3. Click on Xbox Game Bar
4. turn the game bar button on
5. Then Close the setting And Repeat Step (1,2,3)
6. You will se game bar button will be of

**Desktop Info (please complete the following information):**
 - CPU intel i3
 - System Drive Type SSD and HDD
 - Version Dont know

**Comment by Zusier** [comment]
Atlas >> Config >> FSO >> enable
