### ISSUE TITLE
My [BUG "solution"] - Network Shares on Atlas10 running in Windows 11 (June 2024)

### ISSUE THREAD

**Issue by FDAHNet** [Atlas-OS/Atlas#1128]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

This is my solution to the folder Share BUG. I don´t know if this is the correct place, if not, Atlas-OS Admin please consider to move to the appropiate place.

https://github.com/Atlas-OS/Atlas/issues/923#issuecomment-2171829979

### Steps to reproduce

1. Follow the info on the linked comment at description for a "meshpatch" solution to Shared Folder Problem

### Expected behavior

Works similar to share folder service in Windows

### Actual behavior

Works. Slowly but works.

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

- I use a lot of machines all differents, but this "solution" works in all.

**Comment by he3als** [comment]
Hi,

Thank you for your solution. However, file sharing should work just like standard Windows on the latest version of Atlas. Please make sure that you have [enabled file sharing in the Atlas folder](https://docs.atlasos.net/getting-started/post-installation/atlas-folder/general-configuration/#file-sharing).

**Comment by FDAHNet** [comment]
I did all the logical things for network sharing, included cmds and
inclusive via powershell and no one runs. I have the last version installed
in various computers... all works ok, but when I need to retrieve files via
typical networks sharing, didn´t works. Before... the 4 machines... with
Atlas installed works correctly, after installation, not.... Because I need
to work via network shares and I don´t want to reformat the machines and
reinstall all again,, I try all my knowledgements and I get works with this
meshy system.

I´m in hope that works for yours.
