### ISSUE TITLE
[BUG] - ctrl +left shift shortcuts not working after switching to atlas

### ISSUE THREAD

**Issue by cerdocrash** [Atlas-OS/Atlas#1131]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

i'm currently using a SHIVA K512 Membrane Gaming Keyboard
when i try to do ctrl+lshift+esc it doesn't open task manager but with rshift it works, same issue with firefox and ctrl+lshift+p, and google with ctrl+lshift+N . I've searched a lot this issue because it was not happening before the change to atlas os, and i ran out of ideas. other shortcuts are working ok only left shift related ones are not working

### Steps to reproduce

1.hit ctrl+left shift +esc
2.hit ctrl+right shift + esc

### Expected behavior

expected to open task manager with both shift's

### Actual behavior

only works with lshift

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

Processor	AMD Ryzen 7 5700G with Radeon Graphics, 3801 Mhz, 8 Core(s), 16 Logical Processor(s)
BaseBoard Product	ROG STRIX B550-F GAMING (WI-FI)
SHIVA K512 Membrane Gaming Keyboard

**Comment by he3als** [comment]
I can't reproduce this issue. Maybe you don't have the appropriate drivers installed? See https://www.redragonzone.com/pages/download and type your keyboard model.

If you still can't get it to work, see https://docs.atlasos.net/getting-started/post-installation/drivers/getting-started/#want-driver-installation-updates-through-windows-update-instead.

**Comment by cerdocrash** [comment]
i've already tried drivers. But i guess i can adapt myself
