### ISSUE TITLE
[BUG] - Msi Afterburner lags and causing Discrete Gpu heating, cpu load

### ISSUE THREAD

**Issue by Hinokamiiii** [Atlas-OS/Atlas#1132]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

Tried 0.4.0 and 0.5.0 Atlas, same issue, it doesn't show GPU2 Temperature in monitoring, but if i open game it will show and msi afterburner working fine then. Me tried stock Windows and ReviOS they haven't this issue. If i disable monitoring in msi afterburner issue will be fixed, but then i can't check temperature and other sensors. btw me using laptop - Lenovo Ideapad Gaming 3 15ACH6

### Steps to reproduce

Open MSI Afterburner without opening heavy tasks like games.

### Expected behavior

Any fix for this issue

### Actual behavior

MSI Afterburner causing lags, heating cpu and gpu.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

AMD Ryzen 5 5600H, 16GB Ram Samsung DDR4 3200Mhz, 512gb SSD M.2 NVME Samsung, NVIDIA RTX 3050 Mobile 4GB

**Comment by Hinokamiiii** [comment]
https://github.com/Atlas-OS/Atlas/assets/112668426/1b555f72-689b-4c33-8ee6-80e61b53932d

I have this video which describes my issue

**Comment by TheOnlyChuon** [comment]
I dont know what can cause the the high usage of your GPU and temperature issue (maybe u messed up something with MSI Afterburner settings), but i pretty sure that Atlas doesnt make your GPU2 Temperature disappearing from monitoring. It's a MSI Afterburner bug, I'm on a clean Windows 23h2 and i got this bug too, you just need to open your game first, then launch the app to make it work normally, nothing is too inconvenient.

**Comment by neecr** [comment]
@Hinokamiiii it is caused by switching between integrated and discrete graphics card in the laptop. i have a similar configuration: ryzen 5 6600h + rtx 3060 and i have the same problem

**Comment by he3als** [comment]
Going to close due to inactivity
