### ISSUE TITLE
[FEATURE] - Windows Media Player Legacy should be enabled by default

### ISSUE THREAD

**Issue by Stizzie** [Atlas-OS/Atlas#1133]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

There are a quite number of games requires Windows Media Player Legacy to play their splash screen at launch. Without it games will simply crash with no error box or log, so it quite difficult for those who encountered the crash to troubleshoot. Windows Media Player Legacy itself takes close to none space and processing power.

### Describe the solution you would like.

Windows Media Player Legacy should be enabled by default

### Describe alternatives you have considered.

None

**Comment by Xyueta** [comment]
This will be available in the next release, it has been changed not a long time ago.

**Comment by he3als** [comment]
For a solution: https://docs.atlasos.net/faq-and-troubleshooting/common-questions/media-pack-not-found/

**Comment by he3als** [comment]
Fixed in [release v0.4.1](https://github.com/Atlas-OS/Atlas/releases/tag/0.4.1). See the release for more info on what v0.4 users can do.
