### ISSUE TITLE
[BUG] - i cant open the settings and change wifi

### ISSUE THREAD

**Issue by X3mN1** [Atlas-OS/Atlas#1134]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

why when i go to settings its not open and when i do right-click on desktop and press desplay setting its show a error window 

### Steps to reproduce

![IMG_2011](https://github.com/Atlas-OS/Atlas/assets/173769127/b5a5b2fc-0260-4691-babe-be3fbb8b8299)

### Expected behavior

.

### Actual behavior

-

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

i7 4600u
GT 730M
12GB ram

**Comment by he3als** [comment]
I can't personally reproduce this in any capacity. Maybe it's another tweak, software, or some corruption occurred. Try reinstalling Windows: https://docs.atlasos.net/getting-started/installation/
