### ISSUE TITLE
There is a further issue here. The above fix works for the lock screen Win+L or when pc goes to lockscreen when it is in idle. But for the initial boot-time log in screen the wallpaper is still a bland yellow-orange one. I cannot seem to change it.

### ISSUE THREAD

**Issue by anjai0904** [Atlas-OS/Atlas#1135]
There is a further issue here. The above fix works for the lock screen Win+L or when pc goes to lockscreen when it is in idle. But for the initial boot-time log in screen the wallpaper is still a bland yellow-orange one. I cannot seem to change it.

_Originally posted by @anjai0904 in https://github.com/Atlas-OS/Atlas/issues/1110#issuecomment-2193229296_

**Comment by Ast3risk-ops** [comment]
@JayXTQ Requesting close.

**Comment by the-P1neapple** [comment]
This was meant for #1110 . Closing issue
