### ISSUE TITLE
[BUG] - Mullvad VPN

### ISSUE THREAD

**Issue by Pentakill1995** [Atlas-OS/Atlas#1136]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

Mullvad VPN App is running on a fresh windows 10 install and a fresh Atlas OS upgrade. 27.06.2024 fresh downloaded and up to date. mullvad vpn app seems to run. can connect itself to the location and writes "connected".  internet acccess from system instantly stops. as soon as deactivating the vpn internet is back on. tryed different vpn locations. all the same. did run the default network troubleshoot and the windows network setting troubleshoot. used activate vpn support script. not working. 

### Steps to reproduce

install windows 10 fresh
do all updates as requested in atlas setup docs
install atlas os
check if internet cconnection works
install mullvad
connect your account and activate vpn
internet connection broken
deinstall mullvad or deactivate vpn
internet works again

### Expected behavior

support of mullvad VPN
access to internet connection

### Actual behavior

no internet
mullvad software itself seems to work

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

![image](https://github.com/Atlas-OS/Atlas/assets/123503780/642fae04-8551-4da0-bdab-465cbd7f8e45)

**Comment by Ast3risk-ops** [comment]
Try the network reset script in atlas folder > troubleshooting.

**Comment by Pentakill1995** [comment]
![image](https://github.com/Atlas-OS/Atlas/assets/123503780/e802d557-fb9c-4d9e-a0ac-7c7325cad57a)
network reset script was used. than the atlas default. than the enable vpn script. all not changing the problem

**Comment by Ast3risk-ops** [comment]
> ![image](https://private-user-images.githubusercontent.com/123503780/343812232-e802d557-fb9c-4d9e-a0ac-7c7325cad57a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTgwODcsIm5iZiI6MTcxOTQ5Nzc4NywicGF0aCI6Ii8xMjM1MDM3ODAvMzQzODEyMjMyLWU4MDJkNTU3LWZiOWMtNGQ5ZS1hMGFjLTdjNzMyNWNhZDU3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxNDE2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWFmMjU0NWIzZTg5Y2E5MjQ2NDFlMzU0MzRhY2FmZWRkZWM1ZTAxYzBiYWY0NTY2YThmODFhNWFiM2YyN2FmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._Eqht1rqZhzazFfoMp1jKxCI4NqvCEMcjUfdWIPpTgA) network reset script was used. than the atlas default. than the enable vpn script. all not changing the problem

You have to reboot each time.

**Comment by Pentakill1995** [comment]
additional info. using the script and instantly using mullvad makes it work. after a system reboot it is not working anymore. the app delivers a killswitch option and it can not be deactivated it seems 
![image](https://github.com/Atlas-OS/Atlas/assets/123503780/f2929bb9-e3a8-4b17-bbb7-48395f3fc9f8)

**Comment by Pentakill1995** [comment]
additional info to the killswitch: https://github.com/mullvad/mullvadvpn-app/issues/3430

**Comment by Ast3risk-ops** [comment]
> additional info. using the script and instantly using mullvad makes it work. after a system reboot it is not working anymore. the app delivers a killswitch option and it can not be deactivated it seems ![image](https://private-user-images.githubusercontent.com/123503780/343815237-f2929bb9-e3a8-4b17-bbb7-48395f3fc9f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTg1NDMsIm5iZiI6MTcxOTQ5ODI0MywicGF0aCI6Ii8xMjM1MDM3ODAvMzQzODE1MjM3LWYyOTI5YmI5LWUzYTgtNGIxNy1iYmI3LTQ4Mzk1ZjNmYzlmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxNDI0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGVhZDExZjVmYjNkN2NjNGZhMWM2ODNhNGQ1MWQyMzU4YTMwOTRkMDZiYTFiNmRmMDJmMDEzNDFhNzRiZjU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6p7J8HkKsQLrKZandJMt3FlXqv_KM-pIZ7_kLfSR2zY)

Hover over the info symbol.

**Comment by Ast3risk-ops** [comment]
> additional info to the killswitch: [mullvad/mullvadvpn-app#3430](https://github.com/mullvad/mullvadvpn-app/issues/3430)

So Always Require VPN is off?

**Comment by Pentakill1995** [comment]
it seems to be just a informational slider for people cause they asked for this function and why there is no info about it. 
![image](https://github.com/Atlas-OS/Atlas/assets/123503780/d75bc672-2dce-4b86-8a6f-b05c68d1254b)
 also the other switch is the one which makes you require to be always connected to a vpn from mullvad to have internet. this one is off: 
![image](https://github.com/Atlas-OS/Atlas/assets/123503780/8adae030-a8b0-49bf-b0e3-58b4853b1c41)

![image](https://github.com/Atlas-OS/Atlas/assets/123503780/261bf1bc-5bbc-4945-831c-6b6ede2f9a03)

**Comment by Ast3risk-ops** [comment]
> it seems to be just a informational slider for people cause they asked for this function and why there is no info about it. ![image](https://private-user-images.githubusercontent.com/123503780/343816687-d75bc672-2dce-4b86-8a6f-b05c68d1254b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MDE0MzMsIm5iZiI6MTcxOTUwMTEzMywicGF0aCI6Ii8xMjM1MDM3ODAvMzQzODE2Njg3LWQ3NWJjNjcyLTJkY2UtNGI4Ni04YTZmLWIwNWM2OGQxMjU0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxNTEyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjg5YTVjNjRkNDljZjkyOThhZDk2MGNkY2I1M2UxY2VmY2ExOWI2MjZmYzIwZTAyMmJkYWFkMTNjNDIxMWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PNQ6J2CpZg2AQxDQRloKbCuSLNzAwSJVrUmuiQIWzR8) also the other switch is the one which makes you require to be always connected to a vpn from mullvad to have internet. this one is off: ![image](https://private-user-images.githubusercontent.com/123503780/343817087-8adae030-a8b0-49bf-b0e3-58b4853b1c41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MDE0MzMsIm5iZiI6MTcxOTUwMTEzMywicGF0aCI6Ii8xMjM1MDM3ODAvMzQzODE3MDg3LThhZGFlMDMwLWE4YjAtNDliZi1iMGUzLTU4YjQ4NTNiMWM0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxNTEyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmFjMGI5YTIxYjUwZjBhZjUzYTY4MDc4ZmQ0OWNiMjI3YjkwZDhiODlhNjcxMWZmNDE5NDA2OWM3M2M0ZmNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RcDvvcpD5byS0VyRRLz7iw-MGCrAAgXotEda9AM1MwI)
> 
> ![image](https://private-user-images.githubusercontent.com/123503780/343817211-261bf1bc-5bbc-4945-831c-6b6ede2f9a03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MDE0MzMsIm5iZiI6MTcxOTUwMTEzMywicGF0aCI6Ii8xMjM1MDM3ODAvMzQzODE3MjExLTI2MWJmMWJjLTViYmMtNDk0NS04MzFjLTZiNmVkZTJmOWEwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxNTEyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTE5YzU1MDNlMzIyZTk5MGM3ZTE5MmI3ODM4OTg3ZWYzYWNhMTc0ZWUxZjIxNTZiMzU1MTc0NWZmYzQwNTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x8KgT1WWNQm8fKH7pYAnGsiFtMRyWPDTNN__WxyxtUs)

I don't speak german, but is Always Require VPN off?

**Comment by Pentakill1995** [comment]
sorry my mistake. here in english: killswitch function info (always on. not able to dissable this) 
![image](https://github.com/Atlas-OS/Atlas/assets/123503780/94d08a9e-9b73-46b5-99fd-70c7976deaff)

**Comment by Pentakill1995** [comment]
and here the english info for the lockdown function (which is off) 
![image](https://github.com/Atlas-OS/Atlas/assets/123503780/3a558ba8-9670-4c87-bbf4-0d68e49636cf)

**Comment by he3als** [comment]
I can't reproduce this issue with the same settings using VMWare and Atlas v0.4.0 with Windows 10 22H2.

I am going to close for now, as I'm guessing that it's likely unrelated to Atlas.
