### ISSUE TITLE
[BUG] -  AtlasOS causes crashes with C#'s SendKeys.SendWait()

### ISSUE THREAD

**Issue by frapstergt** [Atlas-OS/Atlas#1137]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

When using atlasOS, running any C# scripts that call SendKeys.SendWait(key) causes the system to freeze up.
Ive teted

### Steps to reproduce

1. Make a c# script that calls SendKeys.SentWait(key)
2. Run the script

### Expected behavior

The chosen key gets sent.

### Actual behavior

The system freezes up

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

i7 8700k, rtx 2080 latest drivers, 16gb ddr4 @ 3600mhz, samsung 980 pro 1tb

**Comment by Ast3risk-ops** [comment]
Need the specific version. It can be seen in windows settings > system > about.

**Comment by he3als** [comment]
I can't reproduce this issue. Are you sure that you're on v0.4.0?
```C#
using System;
using System.Diagnostics;
using System.Threading;
using System.Windows.Forms;

namespace SendKeysTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("running");
            Process.Start("notepad.exe");
            Thread.Sleep(2500); // give time for Notepad
            SendKeys.SendWait("test");
            Console.WriteLine("finished");
            Console.ReadKey();
        }
    }
}
```

https://github.com/Atlas-OS/Atlas/assets/65787561/90aeaaf6-2936-4261-a71e-4e2af313b3c1
