### ISSUE TITLE
[BUG] - Account page disappearing on updates (Included Solutions)

### ISSUE THREAD

**Issue by wuyilingwei** [Atlas-OS/Atlas#1140]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

I found that in some cases, my account settings disappeared in settings, and the entire account tab disappeared.

### Steps to reproduce

Edit gpedit Computer Configuration - Windows Settings - Security Settings - Local Policies - Security Options - Accounts: Block Microsoft Accounts (disable)

Login My MS account, my develop E5 MS account and my school MS account.

### Expected behavior

It should be normal. At least you shouldn't be unable to access account settings.

### Actual behavior

I noticed that after a while, the entire Account tab in Settings disappeared. Sometimes I could get there using certain Settings links (such as Change Password or Account Settings), and sometimes I couldn't.

Maybe it was a system update and Atlas that finally caused it (?)

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Version Windows 11 Professional Edition
Build number 23H2
Installation date ‎2024/‎5/‎3
OS version 22631.3737
Experience Windows Feature Experience Pack 1000.22700.1009.0

### Additional content

This bug does not seem to appear on Win10. One of my computers did not have this bug after the above operations, but since it is unstable to reproduce, I am not sure if it is due to luck.

What's strange is that this behavior doesn't seem to happen on the first reboot. But it happens after multiple reboots.

**Comment by he3als** [comment]
Hi, it seems like a Windows update cleared Atlas's method to disable ads on the accounts page.

To fix this, press Win+R to open the Run dialogue, paste in, then press enter on:
```powershell
RunAsTI.cmd powershell iex(irm https://cdn.jsdelivr.net/gh/Atlas-OS/Atlas@main/src/playbook/Executables/CLIENTCBS.ps1); pause
```

**Comment by wuyilingwei** [comment]
> 嗨，似乎 Windows 更新清除了 Atlas 在帐户页面上禁用广告的方法。
> 
> 若要解决此问题，请按 Win+R 打开“运行”对话框，粘贴，然后按 Enter：
> 
> ```powershell
> RunAsTI.cmd powershell iex(irm https://cdn.jsdelivr.net/gh/Atlas-OS/Atlas@main/src/playbook/Executables/CLIENTCBS.ps1); pause
> ```

Thank you, that work. (need reboot)

**Comment by he3als** [comment]
Still going to keep this open as it's an issue some users have and I want to properly fix it

**Comment by wuyilingwei** [comment]
> Still going to keep this open as it's an issue some users have and I want to properly fix it

Then it seems that it may have nothing to do with my restarting the MS account. I will modify the title.

Thanks your help.

**Comment by he3als** [comment]
It's due to the [FeatureManagement overrides](https://github.com/thebookisclosed/ViVe) being cleared

**Comment by he3als** [comment]
Fixed in [release v0.4.1](https://github.com/Atlas-OS/Atlas/releases/tag/0.4.1). See the release for more info on what v0.4 users can do.

**Comment by shadowking1443** [comment]
> Hi, it seems like a Windows update cleared Atlas's method to disable ads on the accounts page.
> 
> To fix this, open PowerShell as an Administrator, and copy and paste the below:
> 
> cd "$env:windir\AtlasModules"; $ver = 'v0.3.3'; $name = "ViVeTool-$ver"
> if ((gcim Win32_ComputerSystem).SystemType -match 'ARM64') { $name = "$name-ARM64CLR.zip" } else { $name = "$name.zip" }
> curl.exe -LSs "https://github.com/thebookisclosed/ViVe/releases/download/$ver/$name" -o "$name"
> iex(irm https://raw.githubusercontent.com/Atlas-OS/Atlas/cef5ab81b9ef5d477f3a8aeb7b1e30cd54e4bb09/src/playbook/Executables/CLIENTCBS.ps1)
> 
> Then, restart.

Hi @he3als - Unfortunately this powershell command does not appear to work on Windows 11 24H2

**Comment by Ast3risk-ops** [comment]
> > Hi, it seems like a Windows update cleared Atlas's method to disable ads on the accounts page.
> > To fix this, open PowerShell as an Administrator, and copy and paste the below:
> > cd "$env:windir\AtlasModules"; $ver = 'v0.3.3'; $name = "ViVeTool-$ver"
> > if ((gcim Win32_ComputerSystem).SystemType -match 'ARM64') { $name = "$name-ARM64CLR.zip" } else { $name = "$name.zip" }
> > curl.exe -LSs "[thebookisclosed/ViVe@`$ver` $name (download)](https://github.com/thebookisclosed/ViVe/releases/download/$ver/$name)" -o "$name"
> > iex(irm [`cef5ab8`/src/playbook/Executables/CLIENTCBS.ps1 (raw)](https://raw.githubusercontent.com/Atlas-OS/Atlas/cef5ab81b9ef5d477f3a8aeb7b1e30cd54e4bb09/src/playbook/Executables/CLIENTCBS.ps1))
> > Then, restart.
> 
> Hi [@he3als](https://github.com/he3als) - Unfortunately this powershell command does not appear to work on Windows 11 24H2

Github has autoformatted the command to markdown (with some links changed), you need to copy it raw.

**Comment by shadowking1443** [comment]
> > > Hi, it seems like a Windows update cleared Atlas's method to disable ads on the accounts page.
> > > To fix this, open PowerShell as an Administrator, and copy and paste the below:
> > > cd "$env:windir\AtlasModules"; $ver = 'v0.3.3'; $name = "ViVeTool-$ver"
> > > if ((gcim Win32_ComputerSystem).SystemType -match 'ARM64') { $name = "$name-ARM64CLR.zip" } else { $name = "$name.zip" }
> > > curl.exe -LSs "[thebookisclosed/ViVe@`$ver` $name (download)](https://github.com/thebookisclosed/ViVe/releases/download/$ver/$name)" -o "$name"
> > > iex(irm [`cef5ab8`/src/playbook/Executables/CLIENTCBS.ps1 (raw)](https://raw.githubusercontent.com/Atlas-OS/Atlas/cef5ab81b9ef5d477f3a8aeb7b1e30cd54e4bb09/src/playbook/Executables/CLIENTCBS.ps1))
> > > Then, restart.
> > 
> > 
> > Hi [@he3als](https://github.com/he3als) - Unfortunately this powershell command does not appear to work on Windows 11 24H2
> 
> Github has autoformatted the command to markdown (with some links changed), you need to copy it raw. If it's still having issues, maybe _put your error here_ instead of just bitching about it.

Hello,

My apologies if I appeared to be "bitching". I was genuinely just trying to reach out as the command does not appear to be not working, and wanted to raise awareness. 

As for an error message, I do not receive one. After inputting the command, the power shell windows closes. After restarting, the accounts page is unfortunately still not visible.

**Comment by shadowking1443** [comment]
> > > Hi, it seems like a Windows update cleared Atlas's method to disable ads on the accounts page.
> > > To fix this, open PowerShell as an Administrator, and copy and paste the below:
> > > cd "$env:windir\AtlasModules"; $ver = 'v0.3.3'; $name = "ViVeTool-$ver"
> > > if ((gcim Win32_ComputerSystem).SystemType -match 'ARM64') { $name = "$name-ARM64CLR.zip" } else { $name = "$name.zip" }
> > > curl.exe -LSs "[thebookisclosed/ViVe@`$ver` $name (download)](https://github.com/thebookisclosed/ViVe/releases/download/$ver/$name)" -o "$name"
> > > iex(irm [`cef5ab8`/src/playbook/Executables/CLIENTCBS.ps1 (raw)](https://raw.githubusercontent.com/Atlas-OS/Atlas/cef5ab81b9ef5d477f3a8aeb7b1e30cd54e4bb09/src/playbook/Executables/CLIENTCBS.ps1))
> > > Then, restart.
> > 
> > 
> > Hi [@he3als](https://github.com/he3als) - Unfortunately this powershell command does not appear to work on Windows 11 24H2
> 
> Github has autoformatted the command to markdown (with some links changed), you need to copy it raw. If it's still having issues, maybe _put your error here_ instead of just bitching about it.

Hello @Ast3risk-ops / @he3als, 

I've tried debugging further, and it looks like I'm getting the error "Settings extensions (C:\WINDOWS\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\Public\wsxpacks\Account\SettingsExtensions.json) not found."

I'm currently on Windows 11 24H2 running Atlas 0.4.0

**Comment by naumovskyi** [comment]
Hey, I'm having the exact same issue. Today I installed AtlasOS using Atlas Playbook 0.5.0 on a fresh install of Windows 11 downloaded directly from Microsoft. The user settings page is completely missing. I tried running the command you suggested, but PowerShell just closes right after execution. I restarted my PC, and the user settings page still isn't there. The bug is still present on my end.

**Comment by naumovskyi** [comment]
I fixed the link and ran the command in an elevated PowerShell. The window immediately closed itself. After restarting my PC, I got hit with a BSOD: KERNEL_MODE_HEAP_CORRUPTION (0x13A). I also got these four hex codes in the top-left corner:

0x0000000000000017
0xFFFFCB026D100340
0xFFFFCB0279D93200
0x0000000000000000

**Comment by naumovskyi** [comment]
I just reinstalled Atlas Playbook 0.5.0 over the existing AtlasOS installation, and all user settings reappeared. Bug fixed. Heh.
