### ISSUE TITLE
[BUG] - Infomaniak kDrive cloud service not syncing

### ISSUE THREAD

**Issue by Soupape50** [Atlas-OS/Atlas#1142]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

First of all, thank you for this awesome tool that is AtlasOS.

Infomaniak, the #1 web hoster in Switzerland, has a cloud storage called kDrive and an app to directly sync the files into Windows Explorer.

When using AtlasOS, it doesn't want to sync files.

I'm guessing it's a background task issue, so I tried the "Enable Background Apps.reg" in the "3. General Configuration" folder, without success.

Thanks a lot for this amazing work!

### Steps to reproduce

1. Create an Infomaniak Account on infomaniak.com
2. Download kDrive here : https://www.infomaniak.com/en/apps/download-kdrive
3. Add files using the web version https://kdrive.infomaniak.com
4. Try to sync them on your computer using the app

### Expected behavior

The app should show and sync the files

### Actual behavior

The app is stuck on "Syncing (Step 0/10)".

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

- i5 10th Gen
- 16GB RAM

**Comment by he3als** [comment]
https://docs.atlasos.net/getting-started/post-installation/atlas-folder/general-configuration/#search-indexing

Enable Search Indexing. We'll be looking to see if there's any alternatives to fully disabling it for next release

**Comment by Soupape50** [comment]
Thank you so much, it fixed it indeed!

**Comment by he3als** [comment]
Keeping this open until it's in the documentation or fixed by default

**Comment by he3als** [comment]
Fixed in [release v0.4.1](https://github.com/Atlas-OS/Atlas/releases/tag/0.4.1). See the release for more info on what v0.4 users can do.
