### ISSUE TITLE
[BUG] - doom eternal crashing

### ISSUE THREAD

**Issue by Ochlnch1n** [Atlas-OS/Atlas#1143]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

once i downloded the os i tried some games like valorant and doom eternal to check any differences i did see some in valorant my fps went from 80 to 100 but when i opened doom it ran only for a few minutes then it crashed then opened it again and iit wouldnt  let me get past  the main menu

### Steps to reproduce

just open the game on steam and itll crash

### Expected behavior

just to run doom

### Actual behavior

after the intro of bethesda screen would just turn black

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

![image](https://github.com/user-attachments/assets/627acdaf-6e21-44ab-96e6-704bc3ddb32d)
![image](https://github.com/user-attachments/assets/91c1fa8e-459f-490b-b39b-9f0fc024d47d)
Gpu intel integrated graphics

**Comment by nicklvh** [comment]
You are running Atlas on both: an unsupported Windows edition, and also not a clean install of Windows.

Try to run Atlas on Windows 10 Professional Edition, with a clean install prior, and see if this fixes your issue.
