### ISSUE TITLE
[BUG] - Dual boot causes hangup

### ISSUE THREAD

**Issue by jeffreythorne** [Atlas-OS/Atlas#1150]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

When running Atlas as per documentation (well, except my windows 11 is TPM bypassed) it hangs up and doesn't finish. My computer is a dual-boot setup, Windows 7 partition for old games. W10/11 mounts W7 as D: and I always have to hide the partition from each other or they break each other with mutual disk checking.
I forgot to do that with clean install of W11. Atlas hung up.
Restarted, hid W7 partition, bam. Ran fine.

### Steps to reproduce

1.) Attemyti install Atlas on a dual boot system on which the other version of Windows is not hidden.

### Expected behavior

Atlas should install 

### Actual behavior

Atlas does not install unless the other partition, in this case D:, is hidden by having it's assigned letter removed in disk Management.
This really isn't so much a bug as a heads up, I can't find it in any kind of troubleshooting.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Dell E6540 with Intel i7 4800mq (yes, unsupported for W11 but that's not relevant)

**Comment by jeffreythorne** [comment]
It shows the action is taking a long time or however the installer words a
delay. Not wanting to rush it and giving it a little extra grace because
I'm running TPM-bypassed W11 install, I let it run while I made dinner for
the family and cleaned up so call it a couple hours? And it stayed at the
same not quite a inch of progress bar it was when I left. Y'all's
troubleshooting saidaybe restart and try again, it hung up again but I
watched it and noticed the disk cleanup on both C: and, lightbulb moment, D:
So I hid D: (my W7 gaming partition) and tried again and it took no time at
all and worked flawlessly.
I guess it was seeing Windows in both C: and D: and didn't like it.

**Comment by JayXTQ** [comment]
Next time, please name the issue correctly

**Comment by jeffreythorne** [comment]
Sorry about that. I'm not super familiar with how that works. How should I
have labeled it?

**Comment by JayXTQ** [comment]
Make it so your issue is after the label supplied by github in the title.

**Comment by he3als** [comment]
> It shows the action is taking a long time or however the installer words a delay. Not wanting to rush it and giving it a little extra grace because I'm running TPM-bypassed W11 install, I let it run while I made dinner for the family and cleaned up so call it a couple hours? And it stayed at the same not quite a inch of progress bar it was when I left. Y'all's troubleshooting saidaybe restart and try again, it hung up again but I watched it and noticed the disk cleanup on both C: and, lightbulb moment, D: So I hid D: (my W7 gaming partition) and tried again and it took no time at all and worked flawlessly. I guess it was seeing Windows in both C: and D: and didn't like it.

Maybe it's a Windows bug? `cleanmgr` getting stuck on another drive isn't Atlas' fault, but we'd recommend not using Windows 7 in any capacity. I can review your logs to double-check the issue if you don't mind sending them here (zip everything in `C:\ProgramData\AME\Logs`).

I think it's too niche to add to the documentation. However, the AI on the docs is trained on GitHub Issues, so anyone who has this exact issue in the future should be able to ask AI.

**Comment by jeffreythorne** [comment]
I use Windows 7 offline, exclusively for some old games. A mix of game age
(XP/W7 natives) and only being on Intel HD 4600 graphics, I get better
performance in 7 but use 10 or Debian for everything else.
Will send logs when I'm at the computer.
That was my goal, just giving y'all a heads-up in some capacity. I couldn't
find an email address or I'd have skipped GitHub and just dropped you a
line.
