### ISSUE TITLE
[FEATURE] - Can you add an audio exclusive switch option?

### ISSUE THREAD

**Issue by flowerseacar** [Atlas-OS/Atlas#1152]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

Some music software may require audio exclusivity, so I wonder if a switch can be added

### Describe the solution you would like.

Add switch option

### Describe alternatives you have considered.

no

**Comment by he3als** [comment]
v0.4.0 doesn't change audio exclusivity, which is the latest version of Atlas

**Comment by Ast3risk-ops** [comment]
> > v0.4.0 doesn't change audio exclusivity, which is the latest version of Atlas
> 
> 
> 
> ok，However, I would like an option to toggle, sometimes I want to turn off exclusivity to get better game performance

Great, then Google how to disable it, Atlas won't cater to just your tastes.

**Comment by Ast3risk-ops** [comment]
So far you're the only one to ask, I haven't seen anything saying such a feature increases performance, but you're on your own at this point because the issue was closed.

**Comment by he3als** [comment]
@Ast3risk-ops, please don't be rude. One of Atlas's core goals is to cater to people by being customisable.

---

> ok，However, I would like an option to toggle, sometimes I want to turn off exclusivity to get better game performance

Audio exclusivity doesn't yield better game performance. I'm not sure why we turned it off previously, but that's why it has been reverted.
