### ISSUE TITLE
[BUG] - All start-up apps take very long time to start (except one)

### ISSUE THREAD

**Issue by l-t-k** [Atlas-OS/Atlas#1154]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

The start-up apps take very long time to start. I tried four different scenario's, but I can't figure out what the problem is. Based on the results of these scenario's there isn't a app in particular that is causing the problems, so it should be a Windows problem.

The weird thing is that all apps are slow, except one: forticlientvpn. That one loads instantly after login to Windows. Screenshot from autoruns (this one start through a service and not through the common startup proces of windows!):

![Autoruns64_r3zrojUtYQ](https://github.com/user-attachments/assets/19f50415-fdf7-494f-ab68-c4edb39aee9f)

Installed forticlient after I was already facing this issue so this app can't be the problem.

### Steps to reproduce

Scenario 1 --> Took 1 minute (!) before the first app showed up in the taskbar. All apps were started after 1 minute and 57 seconds (!)
Scenario 2 --> 40 seconds after the first app showed up in the taskbar. All apps were started after 1 minute and 55 seconds.
Scenario 3 --> 41 seconds after the first app showed up in the taskbar. All apps were started after 1 minute and 30 seconds.
Scenario 4 --> 34 seconds after the first app showed up in the taskbar. All apps were started after 1 minute.

Starting scenario, all my default start-up apps enabled:
![Taskmgr_bZ8hmaSIFf](https://github.com/user-attachments/assets/56fda8b7-2cbc-49d2-ace1-5fb7c6aea413)

Disabled apps in scenario's:

- DisplayControl (disabled in 3)
- Everything (disabled in 1)
- ProtonPass (disabled in 2)
- ProtonDrive (disabled in 2)
- ProtonVPN (disabled in 4)
- Cryptomator
- Flow.Launcher (disabled in 1)
- Sharex
- RtkAudUService64.exe (disabled in 4)

### Expected behavior

Like the forticlient application, all the apps should start instantly after login into my account.

### Actual behavior

The apps take way to long to start up.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Device = laptop (Laptop = HP Spectre x360 14-eu0045nd 2-in-1 Laptop)
Intel(R) Core(TM) Ultra 7 155H   3.80 GHz
32,0 GB
SSD --> SKU = KXG80ZNV1T02
GPU = CPU

### Additional content

Installed AtlasOS on a clean reinstalled Windows without any errors. All the apps are installed with chocolatey.

**Comment by kamild1996** [comment]
This might not be an Atlas issue - I fought with something like this on stock Windows. See if this helps you:

Regedit: "Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\"
Create a key with name "Serialize"
Create REG_DWORD value in it with name "WaitForIdleState" (case-sensitive!) with value 0. Reboot and check.

**Comment by l-t-k** [comment]
Very nice, that fixed it! Will close this one for now. 

@kamild1996 Thanks a lot!!

**Comment by kamild1996** [comment]
On second thought, how bad of an idea would be to include this registry tweak as part of Atlas? And if so, would it be always activated, or optional?
