### ISSUE TITLE
[BUG] - No Optimization After logging in a New local User

### ISSUE THREAD

**Issue by Keshav-writes-code** [Atlas-OS/Atlas#1163]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

So, creating a New Local User Account from Settings > Account > Other Users > Add Account and then logging into that account no longer Runs any Script for Tweaking the New User Environment

**What might be happening**
- Completely Made up but i think, the Widnows Updates Removed/Modified a Atlas OS Schedule of some sort that runs when you log in to a New Account for the First Time

### Steps to reproduce

- Do a Fresh Install of Windows 11 23H2 (microsoft official ISO)
- Run the Disable Automatic Driver Installation.reg immediately
- avoid any windows updates
- Do the Atlas Os Installation Process
- after, Create new User Settings > Account > Other Users > Add Account
- sign out of current User and log in to the new one
- Notice, no Optimizatino done for the new Account

### Expected behavior

- So, i tested after a Fresh install of , ran the Driver Disable reg file and did the Atlas OS Installation.
- then when i logged into a New User, it asked me a Yes/No Question in Powershell to set up New user and Restart something like that.

### Actual behavior

- It doesn't Run any Tweaking Script

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

- Form Factor `Laptop`
- Processor `Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz`
- RAM `8 GB`
- Storage `C: 60GB`
- GPU `Intel(R) HD Graphics 620`

**Comment by S1M8N** [comment]
Same

**Comment by he3als** [comment]
Will be working on a fix for this

**Comment by he3als** [comment]
Fixed in [release v0.4.1](https://github.com/Atlas-OS/Atlas/releases/tag/0.4.1). See the release for more info on what v0.4 users can do.
