### ISSUE TITLE
AtlasOS Licensing

### ISSUE THREAD

**Issue by he3als** [Atlas-OS/Atlas#117]
I have realised that this repository does not have a license, what would be the situation with a license? I am not sure how it would work with proprietary executables being contained within the repository, I am not sure. Maybe using GPL would be good?

**Comment by Zusier** [comment]
![image](https://user-images.githubusercontent.com/46111482/156887628-54097cca-dcc0-4d88-a879-4e55c768cf0d.jpeg)

This sums it up pretty well. Having the binaries is the main concern as the license needs to be compatible.

**Comment by he3als** [comment]
Ah okay, maybe this issue should stay open until a compatible license is found?

**Comment by CanadaHonk** [comment]
GPL doesn't allow modifications to proprietary things iirc. Just use a non-restrictive license like MIT / Apache probably.

**Comment by he3als** [comment]
How would it work with proprietary binaries being inside of the repository though? https://github.com/Atlas-OS/Atlas/tree/main/src/AtlasModules

**Comment by he3als** [comment]
For both ServiWin and DevManView, there is a license which states that you can distribute the application, but you need to include all the flies included in the `.zip` download. Isn't Atlas in violation of this license?

https://www.nirsoft.net/utils/device_manager_view.html
https://www.nirsoft.net/utils/serviwin.html

> This utility is released as freeware. You are allowed to freely distribute this utility via floppy disk, CD-ROM, Internet, or in any other way, as long as you don't charge anything for this. If you distribute this utility, you must include all files in the distribution package, without any modification !

**Comment by he3als** [comment]
Isn't Atlas also in violation of Pssuspend's license too? https://docs.microsoft.com/en-us/sysinternals/license-faq

> May I distribute Sysinternals utilities in my software, on my website, or with my magazine?
> 
> No. We are not offering any distribution licenses, even if the 3rd party is distributing them for free. We encourage people to download the utilities from our download center where they can be assured to get the most recent version of the utility.

**Comment by Zusier** [comment]
Seems so. I'll figure something out

**Comment by Zusier** [comment]
We actually don't need Pssuspend anymore so I can remove it.

**Comment by forart** [comment]
Hi there, dunno if it's in the project scope, but we're collecting open sourced alternatives for Windows components in out (not yet finished, of course) [Opendows git](https://github.com/forart/Opendows).

Hope that helps/inspires !

**Comment by SnowzNZ** [comment]
Have them downloaded when first connected to internet and make the user agree to their licences?

**Comment by he3als** [comment]
https://github.com/Atlas-OS/Atlas/pull/662

**Comment by he3als** [comment]
It's GPLv3 now
