### ISSUE TITLE
[BUG] - Realtek audio console not working

### ISSUE THREAD

**Issue by x51d6g4** [Atlas-OS/Atlas#1175]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

部署前可能正常打开，部署后再打开realtek audio console就闪退

### Steps to reproduce

------

### Expected behavior

希望能正常打开realtek audio console

### Actual behavior

部署后打开realtek audio console闪退，像强制关闭一样

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

5600x
16GB
RX6600XT

**Comment by JayXTQ** [comment]
Hello, is it possible for this to be translated into English for us to be able to help? If not, maybe @PencilNavigator can help us out

**Comment by PencilNavigator** [comment]
https://github.com/orgs/Atlas-OS/discussions/1174
