### ISSUE TITLE
[BUG] - Legacy vcredists doesn't support unicode in user folder names

### ISSUE THREAD

**Issue by the-P1neapple** [Atlas-OS/Atlas#1179]
https://github.com/Atlas-OS/Atlas/blob/91e0b642fd8a94757386589c3a4bce4975765ad3/src/playbook/Executables/SOFTWARE.ps1#L17
Found issue linked to temp path using user directory for all installers including legacy vcredists. Need to move to temporary directory outside of User Profile Space. - Pineapple

**Comment by he3als** [comment]
## Workaround

Either:

1. Click 'OK' to the errors from the legacy VCRedists; it should move on without them
2. Create a user without Unicode characters or spaces in the name (just standard English characters)

**Comment by he3als** [comment]
Fixed in [release v0.4.1](https://github.com/Atlas-OS/Atlas/releases/tag/0.4.1). See the release for more info on what v0.4 users can do.
