### ISSUE TITLE
Open Sourcing Website & Issues with Website

### ISSUE THREAD

**Issue by he3als** [Atlas-OS/Atlas#118]
The website for AtlasOS is proprietary, which means that people can not contribute to it to fix issues. Also, there's quite a lot of grammar issues on the AtlasOS website and it does not work on mobile properly. There is not a favicon either and there's no home button.

**Comment by Zusier** [comment]
The website is currently being revamped. Not sure if Dries (web dev) would like it to be open.

**Comment by he3als** [comment]
Okay, it would be quite good if it was open sourced but I don't think that Dries would like that too much:
![image](https://user-images.githubusercontent.com/65787561/156889465-5de59b9b-3161-4eeb-9663-b14044799601.png)

Should this issue stay open until it is decided if the website will stay closed source and when the issues are fixed?

**Comment by Zusier** [comment]
Going to close.
