### ISSUE TITLE
[BUG] - Latest dev build

### ISSUE THREAD

**Issue by DRONNCHOUDHARY** [Atlas-OS/Atlas#1180]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

unable to run the playbook

### Steps to reproduce

[Output.txt](https://github.com/user-attachments/files/16575477/Output.txt)

### Expected behavior

[Output.txt](https://github.com/user-attachments/files/16575478/Output.txt)

### Actual behavior

[Output.txt](https://github.com/user-attachments/files/16575481/Output.txt)

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

i5-1035G1 
8gb ram

**Comment by Ast3risk-ops** [comment]
You did not fill out the template or name your issue properly (cc. @JayXTQ)

**Comment by JayXTQ** [comment]
Closing due to incorrect issue format
