### ISSUE TITLE
[BUG] - Ventor cause DPC WATCHDOG VIOLATION when installed windows 11

### ISSUE THREAD

**Issue by ThirakanAomecha** [Atlas-OS/Atlas#1181]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

Ventor cause blue screen of death: DPC WATCHDOG VIOLATION.

### Steps to reproduce

I do what Reinstalling Windows: USB Drive told.
1. Inside the Ventoy folder, run Ventoy2Disk
2. In the opened window, select your USB drive and click Install
3. This will destroy all data on the USB drive! I clicked OK 
4. Copy your downloaded ISO file into the USB drive (labeled Ventoy): I put win11 file in there.
5. Using the BIOS menu, boot from the USB drive
6. I select pro then delete all partition then I waited until it restart
7. Wait second boot then BOOM! (I waited 5-20 minutes)

### Expected behavior

I do so then When I installed windows, while it boots second time for open that white page.

### Actual behavior

but then blue screen: DPC WATCHDOG VIOLATION. I tried to re-download win11 file but not work too, so I use Rufus, and it works like it should be. so.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

- Processor: Intel i3 12100f
- RAM: 1 stick of 8GB Bus 3200 Mhz
- GPU: In cpu
- SSD: M.2 230GB
All I remember.

### Additional content

My suggestion is not only you have Ventoy in USB Installation but have rufus too and another one that use USB to install too.

**Comment by he3als** [comment]
It's not an issue related to Atlas. If you're certain that you have followed the steps correctly with fully functional hardware, USB stuck, and non-corrupt ISO, then consider reporting it to Ventoy
