### ISSUE TITLE
[BUG] - Set up PIN after BIOS Update

### ISSUE THREAD

**Issue by Aubazza** [Atlas-OS/Atlas#1185]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

Updated my BIOS and after I boot I'm met with "Your PIN is no longer available due to a change to the security settings on this device. Click to set up your PIN again." I can click on the "Set up my PIN" button but it does nothing, and cannot access anything, is there a way to bypass this so my pc isn't bricked?

### Steps to reproduce

![IMG_20240814_223429478~2](https://github.com/user-attachments/assets/66a8461c-70de-45eb-bb50-1d4e8d5797e8)

### Expected behavior

-

### Actual behavior

-

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

DDR4 16GBx2
M.2 NVME 1TB CRUCIAL P2
GEFORCE RTX 3060
Unsure on  the rest currently without being able to login

**Comment by PencilNavigator** [comment]
likely not an Atlas issue. Please seek support from our discord server.
