### ISSUE TITLE
Build not supported 

### ISSUE THREAD

**Issue by Marlon5775** [Atlas-OS/Atlas#1186]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

I installed Window 11 Pro 23H2 Build 22635.3139 on my Surface Book and AME Wizard says "Requirements not met. This Windows Build is not supported by this playbook.".
![17236702538914773757164054213074](https://github.com/user-attachments/assets/f615931e-4119-4031-a867-3459c371ac16)

### Steps to reproduce

1. Install Windows 11 without Internet
2. Plugin Internet and do Updates
3. Download AME and Playbook
4. Disable Defender

### Expected behavior

That it installs it.

### Actual behavior

That it says that the build is not supported 

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

i5-6300U
8 GB Ram
230 GB SSD
Intel HD Graphics 520
NVIDIA GeForce GPU (GTX 965M)

**Comment by Ast3risk-ops** [comment]
This is not a bug, you did something wrong. Please consult the following docs page for details on how to fix this error:

https://docs.atlasos.net/install-faq/ame-wizard-errors/build-not-supported/

Chances are you reset windows instead of reinstalling or are using an older build of windows.

cc. @JayXTQ
