### ISSUE TITLE
[FEATURE] - Integration of UniGetUI into Atlas for Comprehensive Windows Package Management

### ISSUE THREAD

**Issue by catsmoker** [Atlas-OS/Atlas#1214]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

As a regular user who frequently uses Windows package managers like WinGet, Scoop, and Chocolatey, I believe Atlas would greatly benefit from integrating with UniGetUI. UniGetUI (formerly WingetUI) is a user-friendly interface that makes it easy to manage, install, update, and remove software packages on Windows 10 and 11. By incorporating UniGetUI into Atlas, users like myself could manage our software packages more efficiently through a single, unified platform.

### Describe the solution you would like.

I suggest that Atlas include built-in support for UniGetUI instead of software folder, so users can:

    Access UniGetUI’s package management features directly within Atlas.
    Automatically sync between Atlas and UniGetUI, ensuring that all software is managed consistently.
    View detailed information about each package, such as download links, publisher details, and file sizes.

### Describe alternatives you have considered.

Without this integration, users have to switch between different tools to manage packages, which can be inconvenient and lead to inconsistencies in software management.

### Additional context.

UniGetUI supports a range of package managers like Winget, Scoop, Chocolatey, Pip, Npm, .NET Tool, and PowerShell Gallery. Integrating it into Atlas would make it easier for users to manage their software and keep their systems up to date.

https://github.com/marticliment/UniGetUI

**Comment by Ast3risk-ops** [comment]
Atlas doesn't bundle bloat, we already have a software installation script in the Atlas folder.

**Comment by he3als** [comment]
As I've also found it to be a valuable tool, I'll add it to the docs and add a note to the 'Install Software.ps1' script. Thank you for the suggestion.
