### ISSUE TITLE
[BUG] - wifi 7

### ISSUE THREAD

**Issue by jeromel-1980** [Atlas-OS/Atlas#1227]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

hello

I updated Atlasos 0.3 to Atlasos 0.4 on a PC.
I equipped this PC with a Wi-Fi card Intel Wi-Fi 7 be200

According to the free hwinfo tool, the pilot is in version 23.70.2.3 dated July 24, 2024

I have a router giving me Wi-Fi 6 in standard 802.11ax and Wi-Fi 7 in norme.802.11be
I also have a Samsung mobile. Galaxy S24 ultra that supports the Wi-Fi standard 7 802.11be

If I only activate the Wi-Fi card 7 802.11be, my Samsung phone connects to Wi-Fi. While the PC equipped with the intel Wi-Fi card 7 be 200, despite the configuration of the detail of the Wi-Fi card forced wireless mode in 802.11 be does not detect my Wi-Fi network..
There are only six 5 GHz Wi-Fi lights that will be detected.

What can I do to solve the problem by keeping atlasos v0.4.0?

Thanks

### Steps to reproduce

...

### Expected behavior

see my wifi 7 network

### Actual behavior

...

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Wi-Fi card Intel Wi-Fi 7 be200

**Comment by dtest2137** [comment]
Hey,

I tried a lot of driver changes, and even a full reinstall, but similar thing happened to me on Zephyrus ROG M16 2023. I have swapped WiFi card to Intel Killer BE1750X (Wi-Fi 7, be200) 6 months ago (worked fine) and every since installing AtlasOS a month ago (clean install) I cannot connect to 6GHz band which I often use while visiting airports/hotels. W11 PRO 23H2/4.0

**Comment by the-P1neapple** [comment]
We have discovered that Windows 11 23H2 does not support WiFi 7 and had support introduced in 24H2. If you wish to have WiFi 7 Support, please perform a clean reinstallation for 24H2 and apply the recent 0.4.1 playbook.
