### ISSUE TITLE
[FEATURE] - Add 24H2 support

### ISSUE THREAD

**Issue by ygxrr** [Atlas-OS/Atlas#1243]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

New 24H2 update has been released a few days ago and trying to apply AtlasOS it says "Requirements not met" "This Windows build is not supported by this Playbook."
Forcing applying by editing the conf file inside the apbx file and adding the build number does work but Copilot, Microsoft Teams and Microsoft Edge wasn't removed.

### Describe the solution you would like.

Add 24H2 support and fix the issues

### Describe alternatives you have considered.

Opening the apbx file, editing the "playbook.conf" file and adding "26100" on "SupportedBuilds" line

**Comment by H0ggu** [comment]
![image](https://github.com/user-attachments/assets/6162de82-f19a-43a6-b47f-091cbb815210)
It's ofc planned

**Comment by Ast3risk-ops** [comment]
Thanks Captain Obvious.

**Comment by MariuzM** [comment]
Next week or 2 weeks damn thats fast, really nice to see support for this project still going.

**Comment by catsmoker** [comment]
I can't find v0.4.1

**Comment by Ast3risk-ops** [comment]
> I can't find v0.4.1

it's uh not out yet.

**Comment by Lewandioski** [comment]
> I can't find v0.4.1

I was made to read that it takes 1 month yet because it was not planned, but you can use ReviOS which is the same and is compatible.

**Comment by Ast3risk-ops** [comment]
> > I can't find v0.4.1
> 
> I was made to read that it takes 1 month yet because it was not planned, but you can use ReviOS which is the same and is compatible.

it's not the same and 0.4.1 is coming.

**Comment by Evren-os** [comment]
> > > I can't find v0.4.1
> > 
> > 
> > I was made to read that it takes 1 month yet because it was not planned, but you can use ReviOS which is the same and is compatible.
> 
> it's not the same and 0.4.1 is coming.

Any eta ?

**Comment by Lewandioski** [comment]
1/2 Month

**Comment by warhawk200** [comment]
> > it's not the same and 0.4.1 is coming.
> 
> Any eta ?

![image](https://github.com/user-attachments/assets/3558556c-0a5b-4d18-b7ab-be53c6a62498)

**Comment by Lewandioski** [comment]
> > it's not the same and 0.4.1 is coming.
> 
> Any eta ?

1/2 Month , use ReviOS

**Comment by Ast3risk-ops** [comment]
> > > it's not the same and 0.4.1 is coming.
> > 
> > 
> > Any eta ?
> 
> 1/2 Month , use ReviOS

Why bother, you'll have to reinstall anyway. Stick to whatever you have for now.

**Comment by he3als** [comment]
Fixed in [release v0.4.1](https://github.com/Atlas-OS/Atlas/releases/tag/0.4.1). See the release for more info on what v0.4 users can do.
