### ISSUE TITLE
[FEATURE] - 23H2 support

### ISSUE THREAD

**Issue by n00b69** [Atlas-OS/Atlas#1251]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

24H2 has severe issues on phones running Windows (yes, this is a niche use but still a relevant one i.m.o since AtlasOS is the current go-to debloat tool in this community) where it can randomly wipe the device's GPT, and thus 24H2 is strongly advised against being used.

Due to 23H2 support being dropped officially, modified playbooks that do still have support would have to be used.

### Describe the solution you would like.

23H2 support to remain in place

### Describe alternatives you have considered.

By re-addinf 23H2 support in the playbook.conf

**Comment by the-P1neapple** [comment]
For our official v0.5 release. We are planning to allow you to update your current installation with AME Wizard without a reinstall. This will allow you to update to 24H2.

v0.4.1 was released primarily to support new installations and is not intended for current users.

Thank you for your patience.

**Comment by n00b69** [comment]
> This will allow you to update to 24H2.
>

The issue is not that updating to 24H2 doesn't work, the issue is that using 24H2 can and will corrupt the entire device's GPT, effectively turning it into a brick. 

Keeping 23H2 support, or at least extending support for it for the time being, would be nice. But I can understand it if you won't, since this is a niche use case.

**Comment by the-P1neapple** [comment]
For the time being we will provide support for both 0.4.0 and 0.4.1 playbooks. You do not need to update to 0.4.1 to receive support.
