### ISSUE TITLE
[BUG] - WSL WslRegisterDistribution failed with error: 0x80370102

### ISSUE THREAD

**Issue by wizard-lgtm** [Atlas-OS/Atlas#1255]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

PS C:\Users\j> wsl --install
Ubuntu is already installed.
Launching Ubuntu...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization
Press any key to continue...

### Steps to reproduce

![image](https://github.com/user-attachments/assets/b5ff800e-f838-4af1-ae36-bd0e3aa8444f)

![image](https://github.com/user-attachments/assets/47393aec-c27f-4b02-963b-d5b8283368cf)

![image](https://github.com/user-attachments/assets/d4d4974c-0dda-4503-97dd-b5e0f15f84fa)

![image](https://github.com/user-attachments/assets/bd8b6af4-f4ce-4f8f-b71a-bdf8b75b60df)

### Expected behavior

Enable wsl 2

### Actual behavior

I just tried to install wsl on my computer 

### Atlas Version

Atlas v0.4.1 for Windows 10 22H2

### Desktop information

Ryzen 5600h
Rtx 3050 Mobile
16gb ram

**Comment by A1ynn5** [comment]
Not sure this is an Atlas bug, [other users suggest this is a DISM issue](https://superuser.com/questions/1753996/how-to-fix-fresh-wsl-install-wslregisterdistribution-failed-with-error-0x80370). You can run this script to disable - and then re-enable - the required services.
[WSL.zip](https://github.com/user-attachments/files/17371872/WSL.zip)
# # # #
```powershell
## Restart WSL.ps1
## Disables required services
DISM /Online /Disable-Feature /FeatureName:Microsoft-Hyper-V-All /All
DISM /Online /Disable-Feature /FeatureName:Microsoft-Windows-Subsystem-Linux /All
DISM /Online /Disable-Feature /FeatureName:HypervisorPlatform /All
DISM /Online /Disable-Feature /FeatureName:VirtualMachinePlatform /All

## Enables the services we just got rid of
DISM /Online /Enable-Feature /FeatureName:Microsoft-Hyper-V-All /All
DISM /Online /Enable-Feature /FeatureName:Microsoft-Windows-Subsystem-Linux /All
DISM /Online /Enable-Feature /FeatureName:HypervisorPlatform /All
DISM /Online /Enable-Feature /FeatureName:VirtualMachinePlatform /All

## Automatic restart
shutdown /r /t 10 /f /d p:2:16

```

**Comment by giopalma** [comment]
This problem is only for WSL 2. Using WSL 1 works fine. This problem is present also in Windows 11 23H2. It's an AtlasOS problem brcause before executing AME Wizard, WSL works fine, after installin AtlasOS, WSL 2 stop working.

**Comment by wizard-lgtm** [comment]
Just fixed by setting wsl disable and enable, and couple of wsl tweaks i found in internet. Then i rebooted it.

**Comment by giopalma** [comment]
The solution doesn't work for me on Windows 11 23H2.

WSL 2 doesn't work, only WSL 1 works.

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070003
Error: 0x80070003 Impossibile trovare il percorso specificato
```
