### ISSUE TITLE
Enable/Disable Biometrics

### ISSUE THREAD

**Issue by CodeCubeNeo** [Atlas-OS/Atlas#126]
Hello! It would be really awesome to have at least the fingerprint log in functionality for Windows Hello. It would be great to add it as an option in the desktop Atlas folder.

**Comment by Zusier** [comment]
I'd have to restore those components which I have no plans to do. You can [build the iso from source](https://github.com/Atlas-OS/Atlas/tree/main/src#building-from-source) and keep biometrics if you'd like

**Comment by CodeCubeNeo** [comment]
I see, so in order to toggle the biometrics you would have to make an separate image just like the "Faceit" version, because there is no simple way to remove/add those components after the install (which components), meaning there is no simple batch script for a simple toggle? Also can I compile the image myself with the free tier of NTLite, or is there some other way to get this working for free on Atlas OS?

**Comment by Zusier** [comment]
> I see, so in order to toggle the biometrics you would have to make a separate image just like the "Faceit" version, because there is no simple way to remove/add those components after the install (which components), meaning there is no simple batch script for a simple toggle? 

Correct.

> Also can I compile the image myself with the free tier of NTLite, or is there some other way to get this working for free on Atlas OS?

No, right now you need atleast the Home edition of NTLite

**Comment by CodeCubeNeo** [comment]
Would you maybe consider adding this to the Faceit version? Just an idea, since the Faceit version supports more things, this could be one of them. It would be really great to have this awesome open source windows mod with fingerprint for free :).

**Comment by Zusier** [comment]
Faceit edition’s only extra support is for faceit. Sorry but as I mentioned before you’ll have to build the iso yourself with biometrics support
