### ISSUE TITLE
Disable AutoRun/AutoPlay feature

### ISSUE THREAD

**Issue by Diegovsky** [Atlas-OS/Atlas#127]
Title says it all. An acquaintance got infected over a thumbdrive because of this (not using AtlasOS though, just a heads up)

**Comment by he3als** [comment]
It should already be disabled on Atlas. https://github.com/Atlas-OS/Atlas/blob/main/src/AtlasModules/atlas-config.bat#L285

**Comment by Diegovsky** [comment]
Noice :+1:
