### ISSUE TITLE
[BUG] - not able to reapply playbook

### ISSUE THREAD

**Issue by om3ga6400** [Atlas-OS/Atlas#1273]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

when trying to reapply the playbook the options to disable antivirus are not available

### Steps to reproduce

open the playbook 
![{B6207165-441F-4830-B6BA-494AE99FA1D8}](https://github.com/user-attachments/assets/213c9482-f01c-4a0e-9af5-17f6f001cce5)
run action
![{7EBEE54A-57B0-4728-9E2E-571B19ED7BB6}](https://github.com/user-attachments/assets/016fc9d3-13c8-4ae8-9bdf-ab2691c6842e)
open windows security 
![{D865BEA1-4981-4501-98B9-B533030D2AA1}](https://github.com/user-attachments/assets/83a5db08-e2e6-45d0-bce4-697bf9893aa0)

### Expected behavior

to be able to disable the security settings

### Actual behavior

page not available

### Atlas Version

Atlas v0.4.1 for Windows 10 22H2

### Desktop information

32gb ddr4, ryzen 5600g and rtx 3060 ti

**Comment by JayXTQ** [comment]
Hello, this isn't an issue relating with Atlas or the AME playbook. Please follow our documentation fully so that this doesn't occur.
