### ISSUE TITLE
Add "PnPCapabilities" to NIC settings

### ISSUE THREAD

**Issue by sirimribiy** [Atlas-OS/Atlas#129]
`"HKLM\SYSTEM\CurrentControlSet\Control\Class%%i" /v "PnPCapabilities" /t REG_DWORD /d "24" /f`
this dword can be added to NIC settings tab on the script, it will untick "Allow the computer to turn off this device to save power" option under the Power Management tab of network adapter.

**Comment by amitxv** [comment]
It already gets disabled here:

https://github.com/Atlas-OS/Atlas/blob/f4c08dd2586f3cce7591c3d8c06d26f2260e8474/src/AtlasModules/atlas-config.bat#L352

**Comment by sirimribiy** [comment]
Oh my bad, I only searched as PnPCapabilities
