### ISSUE TITLE
[BUG] -(Kaspersky) HEUR:Trojan.BAT.Agent.gen 

### ISSUE THREAD

**Issue by aymen333336** [Atlas-OS/Atlas#1297]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

A malicious program designed to electronically spy on the user’s activities (intercept keyboard input, take screenshots, capture a list of active applications, etc.). The collected information is sent to the cybercriminal by various means, including email, FTP, and HTTP (by sending data in a request).

### Steps to reproduce

A malicious program designed to electronically spy on the user’s activities (intercept keyboard input, take screenshots, capture a list of active applications, etc.). The collected information is sent to the cybercriminal by various means, including email, FTP, and HTTP (by sending data in a request).

### Expected behavior

A malicious program designed to electronically spy on the user’s activities (intercept keyboard input, take screenshots, capture a list of active applications, etc.). The collected information is sent to the cybercriminal by various means, including email, FTP, and HTTP (by sending data in a request).

### Actual behavior

A malicious program designed to electronically spy on the user’s activities (intercept keyboard input, take screenshots, capture a list of active applications, etc.). The collected information is sent to the cybercriminal by various means, including email, FTP, and HTTP (by sending data in a request).

### Atlas Version

Atlas v0.4.1 for Windows 10 22H2

### Desktop information

A malicious program designed to electronically spy on the user’s activities (intercept keyboard input, take screenshots, capture a list of active applications, etc.). The collected information is sent to the cybercriminal by various means, including email, FTP, and HTTP (by sending data in a request).

### Additional content

A malicious program designed to electronically spy on the user’s activities (intercept keyboard input, take screenshots, capture a list of active applications, etc.). The collected information is sent to the cybercriminal by various means, including email, FTP, and HTTP (by sending data in a request).

**Comment by Xyueta** [comment]
What file are you talking about?

**Comment by aymen333336** [comment]
AME

**Comment by Ast3risk-ops** [comment]
1. You did not fill out the template correctly
2. The AME wizard is not a virus, you are witnessing a false positive. No users have reported malicious activities and the source code is publicly available.

**Comment by PencilNavigator** [comment]
https://docs.atlasos.net/install-faq/ame-wizard-errors/ame-wizard-deleted
https://docs.ameliorated.io/guides/security-exceptions.html

Unrelated to Atlas and it's also a false positive. Please READ OUR DOCS before submitting an issue.

**Comment by aymen333336** [comment]
Remove the tools that require the Internet, as well as the things that
Kaspersky and Defender Virus advertise, and we will gain complete trust. I
don't feel safe even if that's your excuse, I don't know why, but I know
that bad people would do anything for money!

**Comment by JayXTQ** [comment]
Also to add to this, Atlas is not for-profit and the AME Wizard has NO paid features, so we are not doing this for any bit of money at all, people can donate if they want. We are not greedy corpo idiots.
