### ISSUE TITLE
[BUG] - No Basic commands

### ISSUE THREAD

**Issue by Antoine-PRN** [Atlas-OS/Atlas#1298]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

Hello,

I am now on AtlasOS and i dont have access to the basic CLI commands like 'ipaddress' or event 'ping'. How do i fix that ?

Thank you

### Steps to reproduce

1 I intalled AtlasOS
2 I had the bug :/

### Expected behavior

working commands

### Actual behavior

[command] is not recognised 

### Atlas Version

Atlas v0.4.1 for Windows 11 24H2

### Desktop information

16G Ram DDR4
AMD Ryzen 7 5700U with Radeon Graphics            1.80 GHz
512Go storage

**Comment by Ast3risk-ops** [comment]
Please describe your bug more clearly (i.e. commands, shell, terminal)

**Comment by Ast3risk-ops** [comment]
> Its a very simple bug, when i'm using a terminal or a shell or whatever, if i try the simple commands like 'ping' or 'ipaddress' then its says that the command does not exists.

Check that the PATH environment variable has been set properly.

**Comment by Antoine-PRN** [comment]
> > Its a very simple bug, when i'm using a terminal or a shell or whatever, if i try the simple commands like 'ping' or 'ipaddress' then its says that the command does not exists.
> 
> Check that the `PATH` environment variable has been set properly.

My PATH variable is set properly yes.
