### ISSUE TITLE
[FEATURE] - Support Newest Build of Windows 11

### ISSUE THREAD

**Issue by HosseinMiri2007** [Atlas-OS/Atlas#1302]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

the newest windows 11 is not supported yet , please support it , thank you for you`re awesome windows modification

### Describe the solution you would like.

just spend time for it

### Describe alternatives you have considered.

add support

**Comment by Ast3risk-ops** [comment]
24H2 is the latest stable build of windows 11. It's supported.

**Comment by HosseinMiri2007** [comment]
yes you're right but I mean the windows 11 23h2

**Comment by JayXTQ** [comment]
That isn't the latest Windows 11, and 23H2 is already on the past versions of Atlas, but we do not recommend using anything other than the latest.

**Comment by HosseinMiri2007** [comment]
I wanna update to 24h2 but I don't get the update from windows update

**Comment by Anthodev** [comment]
Are you going to update AtlasOS to 0.5 (to enable the upgrade from 0.4.0) and allowing people to upgrade from 23h2 to 24h2 (without reinstalling Windows)? Thanks :)

**Comment by Ast3risk-ops** [comment]
> Are you going to update AtlasOS to 0.5 (to enable the upgrade from 0.4.0) and allowing people to upgrade from 23h2 to 24h2 (without reinstalling Windows)? Thanks :)

To do major windows updates you'll have to reinstall.

Major AtlasOS updates may require a reinstall, see the release notes to know if that's the case. Also the current version is 0.4.1 (does not need a reinstall, but you should reinstall since you're on 23h2).

**Comment by Anthodev** [comment]
> To do major windows updates you'll have to reinstall.
> 
> Major AtlasOS updates may require a reinstall, see the release notes to know if that's the case. Also the current version is [0.4.1](../releases/latest) (needs a reinstall, but you should reinstall anyway since you're on 23h2).

The FAQ say otherwise: https://docs.atlasos.net/general-faq/updating-atlas/

![image](https://github.com/user-attachments/assets/4e7cf599-b90f-4ee4-9f56-3f937aa840e0)

It is planned (until further notice) to allow to upgrade to 0.5 to then update to 24h2.

**Comment by Ast3risk-ops** [comment]
> > To do major windows updates you'll have to reinstall.
> 
> > 
> 
> > Major AtlasOS updates may require a reinstall, see the release notes to know if that's the case. Also the current version is [0.4.1](../releases/latest) (needs a reinstall, but you should reinstall anyway since you're on 23h2).
> 
> 
> 
> The FAQ say otherwise: https://docs.atlasos.net/general-faq/updating-atlas/
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/4e7cf599-b90f-4ee4-9f56-3f937aa840e0)
> 
> 
> 
> It is planned (until further notice) to allow to upgrade to 0.5 to then update to 24h2.

Only when 0.5 comes out, I was discussing upgrading right now to 0.4.1.

**Comment by Anthodev** [comment]
> Only when 0.5 comes out, I was discussing upgrading right now to 0.4.1.
And i was asking when 0.5 will come out since 24h2 is available since few months and there is very few commits on the repo since the release of the 0.4.1.
