### ISSUE TITLE
Unable to save credentials in the Remote Desktop Metro app

### ISSUE THREAD

**Issue by whallin** [Atlas-OS/Atlas#131]
**Describe the bug**
When creating an account in the Remote Desktop app from the Microsoft Store, you can populate all the fields but one: the password field. You can save the account with a username, and display name saved, but it crashes as soon as you try to save a password.

**To Reproduce**
1. Download and run "Remote Desktop" from the Microsoft store
2. Go to "Settings" and create a new user account with all fields populated
3. Experience the crash as long as the password field is populated

**Expected behavior**
The application should save the user account with the username, password, and display name for use with remote desktop clients.

**Screenshots**
n/a

**Desktop Info**
 - CPU: AMD Ryzen 3700x
 - System Drive Type: NVMe SSD
 - Atlas Version: 20H2 v0.5.1 BETA (non-Faceit edition)

**Additional context**
I'm aware that remote desktop is stripped out of AtlasOS. Considering that all the features in the remote desktop store app work and run as expected, but this one feature, then I suspect there might be another root cause here.

**Comment by Zusier** [comment]
Try running:
```
sc config VaultSvc start=auto
```
and rebooting.

**Comment by Zusier** [comment]
Any updates?

**Comment by whallin** [comment]
I'm sadly not on Atlas anymore. If someone else ends up running into this issue and your solution doesn't work, I suppose they can reopen this issue then.
