### ISSUE TITLE
Visual Studio 22 Install Error

### ISSUE THREAD

**Issue by Sarotin** [Atlas-OS/Atlas#132]
Hello,
I am unable to install Visual Studio 2022(.net Desktop development), on a fresh install of 0.5.1.
Log:

================================================================================

Package 'Microsoft.Net.4.8.KB5003304,version=4.8.4375.5,chip=x64,machinearch=x64' failed to install.
    Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.Net.4.8.KB5003304;PackageAction=Install;ReturnCode=87
    Details
        Command executed: "C:\Windows\system32\dism.exe" /online /quiet /norestart /add-package /packagepath:"C:\Users\Admin\AppData\Local\Temp\910e9582-e8ac-43ab-b137-7188bd7e970e\Windows10.0-KB5003304-x64-NDP48.cab" /logPath:"C:\Users\Admin\AppData\Local\Temp\dd_setup_20220329212003_115_Microsoft.Net.4.8.KB5003304.log"
        Return code: 87
        Return code details: No file path specified.
    Log
        C:\Users\Admin\AppData\Local\Temp\dd_setup_20220329212003_115_Microsoft.Net.4.8.KB5003304.log
    Impacted workloads
        .NET desktop development (Microsoft.VisualStudio.Workload.ManagedDesktop,version=17.1.32112.364)
        Visual Studio core editor (Microsoft.VisualStudio.Workload.CoreEditor,version=17.1.32112.364)
    Impacted components
        .NET Framework 4.8 development tools (Microsoft.Net.ComponentGroup.4.8.DeveloperTools,version=17.1.32112.364)
        .NET Framework 4.8 targeting pack (Microsoft.Net.Component.4.8.TargetingPack,version=17.1.32112.364)
        Visual Studio core editor (Microsoft.VisualStudio.Component.CoreEditor,version=17.1.32112.364)

================================================================================

Also I cant install .net 4.8 with offline installer, because .net 4.8 is already installed.

**Comment by Sarotin** [comment]
Fixed was a set privacy setting.

**Comment by justkamiii** [comment]
Hello, what privacy setting was it exactly?

**Comment by AgusUruguayo** [comment]
> Fixed was a set privacy setting.

how you fix it?
