### ISSUE TITLE
Well... I don't know is my fault that my brightness adjust is broken or is atlas os fault, the others when well i guess, Is really optimization thank you and please fix it if is not my fault. (I use old version of Atlas OS)

### ISSUE THREAD

**Issue by MinyHQCraft** [Atlas-OS/Atlas#134]
**Describe the bug**
A clear and concise description of what the bug is. Providing an error code is highly recommended.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop Info (please complete the following information):**
 - CPU [Intel or AMD]
 - System Drive Type [SSD or HDD]
 - Version [e.g. 1.2]

**Additional context**

**Comment by Zusier** [comment]
#133
