### ISSUE TITLE
A Short Issue Description

### ISSUE THREAD

**Issue by SuViCSGO** [Atlas-OS/Atlas#135]
**Describe the bug**
A clear and concise description of what the bug is. Providing an error code is highly recommended.

**To Reproduce**
![Untitled](https://user-images.githubusercontent.com/102991195/161605554-e0413e9a-466b-4097-adcb-79b175b95947.png)

**Expected behavior**

**Screenshots**

**Desktop Info (please complete the following information):**
 - CPU [Intel or AMD]
 - System Drive Type [SSD or HDD]
 - Version [e.g. 1.2]

**Additional context**

Problem with Atlas Default Services Error

**Comment by Zusier** [comment]
You need to run it with Nsudo.

**Comment by SuViCSGO** [comment]
I started Nsudo what next

**Comment by Zusier** [comment]
Drag the reg onto nsudo, click run

**Comment by SuViCSGO** [comment]
thx man, i have bluescreen problem with UWP Disable All i have BlueScreen

**Comment by Zusier** [comment]
What?

**Comment by SuViCSGO** [comment]
I had a problem with BlueScreen and I put UWP Disable All and then BlueScreen happened to me and I had to download the new system now I just turned off the Xbox the rest I didn't touch and for now it's okay
