### ISSUE TITLE
A short description of the feature

### ISSUE THREAD

**Issue by SuViCSGO** [Atlas-OS/Atlas#136]
![Untitled](https://user-images.githubusercontent.com/102991195/161623773-fbc3833f-ecae-4832-873f-fdbe1a7d4d55.png)
![Untitled1](https://user-images.githubusercontent.com/102991195/161623820-f1ade461-56dd-40e2-8131-b0ab1a11e8e2.png)

 I have a problem with Nvidia Freestyle, I can't turn them on and I need colors for them. As soon as I started DSCP I was immediately disabled how to enable.

**Comment by Zusier** [comment]
How did you install the driver? ..and what does DSCP have anything to do with nvidia freestyle?

**Comment by SuViCSGO** [comment]
![Untitled](https://user-images.githubusercontent.com/102991195/161626282-6c70033e-888e-44d5-bb7f-89dc3a6be77c.png)

Write me this Unable to open share do you know maybe how to enable Nvidia Profile Inspector something

**Comment by Zusier** [comment]
I'm sorry you aren't making any sense. Did you use Nvidia Profile inspector?

**Comment by SuViCSGO** [comment]
Thanks for the help. I have another question, if I reset VCredist, will the DSCP turn off the reset so that nothing from the optimization that I clicked reset does not work at all

**Comment by Zusier** [comment]
No
