### ISSUE TITLE
Add descriptive notes of which services which are enabled in the ISO.

### ISSUE THREAD

**Issue by Aetopia** [Atlas-OS/Atlas#138]
**Is your feature request related to a problem? Please describe.**
As the title suggests, I would like to see a dedicated wiki page that describes which services are enabled by default with Atlas OS and additional state which features these services control. (Example: Capture Service + Clipboard Service allows Snip & Sketch to work.)
This would allow any user to quickly check if any given feature is not present/enabled within Atlas due to a service not being enabled.

**Describe the solution you'd like:**
A wiki page where all enabled services are listed. A small description of the service enabled should be fine + provide details of which windows features are controlled by a given service.

**Describe alternatives you've considered:**
Using `services.msc` works fine to see the service description but which features are controlled by the service must be identified by the user.

**Comment by Aetopia** [comment]
I think your point is valid. I am not sure if there is an FAQ page on the repo or on the discord so considering an FAQ might be also nice.

**Comment by Zusier** [comment]
Check the [wiki](https://github.com/Atlas-OS/Atlas/wiki)
