### ISSUE TITLE
DirectX Dependencies not working 

### ISSUE THREAD

**Issue by Stellik** [Atlas-OS/Atlas#139]
i tried install DX installed it from >  https://www.microsoft.com/en-in/download/details.aspx?id=35

and here is the error i got
![tmp](https://user-images.githubusercontent.com/86614978/162461041-ba957ad7-6855-4295-9293-0bbf6a1da259.PNG)

also i tried Enabling `CryptSVC` and it dint help..

**Comment by Zusier** [comment]
Try [this](https://www.guru3d.com/files-get/directx-end-user-runtimes-(june-2010),8.html). Otherwise you probably disabled services or did tweaks on your own as I always test DirectX setup for each release. Run default atlas services or reinstall

**Comment by Stellik** [comment]
Thank you so much works perfectley!
