### ISSUE TITLE
Logitech mouse speed

### ISSUE THREAD

**Issue by MaRkIonI** [Atlas-OS/Atlas#141]
When u go to start:
Start button
Mouse
Additional mouse settings
And change the mouse speed next time i turn on pc it is back to its default every single time 
Im using logitech g403 hero mouse with g hub software on 400dpi

**Comment by Zusier** [comment]
Have you tried any solutions online?

- [1](https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-stop-my-mouse-settings-from-resetting/e186e5e1-5af4-4189-a010-ee7f6dd0cd9c)
- [2](https://www.reddit.com/r/Windows10/comments/3i4ycg/help_win_10_mouse_pointer_speed_reseting_after/)
- [3](https://www.tenforums.com/drivers-hardware/11805-windows-10-mouse-settings-reset-every-login.html)
