### ISSUE TITLE
Change the OOBE? The microsoft account is kinda annoying if you forget to disconnect as there is no way to undo it after connecting

### ISSUE THREAD

**Issue by bazthedev** [Atlas-OS/Atlas#145]
Anyway the OOBE on windows is buggy amyway

**Comment by Zusier** [comment]
It's local account only.. not sure what you mean

**Comment by bazthedev** [comment]
> It's local account only.. not sure what you mean

It didn't do that, I got the option to connect and I did because I forgot what comes next.
