### ISSUE TITLE
Mouse Right Click Not Working

### ISSUE THREAD

**Issue by DRONNCHOUDHARY** [Atlas-OS/Atlas#148]
**Describe the bug**
A clear and concise description of what the bug is. Providing an error code is highly recommended.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop Info (please complete the following information):**
 - CPU [Intel or AMD]
 - System Drive Type [SSD or HDD]
 - Version [e.g. 1.2]

**Additional context**

**Comment by Zusier** [comment]
You didnt fill anything out. What mouse? 

I’ve never seen anybody have this before, my mouse and everyone else’s work fine
