### ISSUE TITLE
A Short Issue Description

### ISSUE THREAD

**Issue by Eclipse-5214** [Atlas-OS/Atlas#149]
**Describe the bug**
When you try to install it on an asus vivobook e200ha no disk shows up on the install prompt.

**To Reproduce**
1. Try to install it on an asus vivobook e200ha

**Expected behavior**
you wont be able to install it

**Screenshots**
N/A

**Desktop Info (please complete the following information):**
 - Intel Atom
 - emmc
 - idk

**Additional context**

**Comment by Zusier** [comment]
eMMC drives are on the unsupported list, as stated [in the wiki](https://github.com/Atlas-OS/Atlas/wiki/1.-FAQ#13-whats-removed-in-atlas-os).
