### ISSUE TITLE
i would like an windows to go version of this

### ISSUE THREAD

**Issue by alexvermaning0** [Atlas-OS/Atlas#150]
**Is your feature request related to a problem? Please describe.**
nope but kinda is an issue for me

**Describe the solution you'd like**
an windows to go version iso

**Describe alternatives you've considered**
rufus shows my sd card but the option of windows to go is not there and aomei can do it but does not detect my sdcard

**Additional context**
i want it to run on sd card even i know performace will be lower its an temp solution for the steam deck as i am saving for an bigger nvme ssd (now 64GB eemc)

**Comment by Zusier** [comment]
https://github.com/Atlas-OS/Atlas/wiki/1.-FAQ#13-whats-removed-in-atlas-os

**Comment by Johnapolitan** [comment]
@alexvermaning0

**Warning: While these methods seemingly worked for me, they are not officially supported by Atlas and you will NOT receive help if something goes wrong**
I'm actually running Atlas on my external SSD right now. I installed stock Windows 10 via Rufus Windows To Go option, then dual booted Atlas 1803 using DanL's [script](https://github.com/iidanL/InstallWindowsWithoutUSB). If you really want to run Atlas on your SD card I suggest contacting Rufus support and trying to figure out why the card isn't appearing. If that doesn't work, you could try using something like 7zip to extract the .iso files onto the SD card, and using EasyBCD to boot into the SD card (Note: Not supported on EFI Systems). I have some experience doing this so if you're still having trouble you can just respond to my comment.

**Comment by alexvermaning0** [comment]
i got it working by just putting the sdcard in the pc and selected the phisical disk option in vmware. installed windows like it was an normal harddrive via vmware and added the drivers and put it in my steam deck.
