### ISSUE TITLE
Guide on how to install Atlas without a USB device

### ISSUE THREAD

**Issue by Johnapolitan** [Atlas-OS/Atlas#153]
Wiki states to request a new issue to add a section.

1. Download [Macrorit Partition Expert](https://macrorit.com/download.html?mds&gclid=CjwKCAjwgr6TBhAGEiwA3aVuIVRrnYjiKkSiBiltjDX9mtl19KMJVRv3SUe_G_QfgmyVS78k0pyIZxoC61oQAvD_BwE)  and install it. (If prompted, choose 'Install Package')
2. Download [Install Windows Without USB by DanL](https://github.com/iidanL/InstallWindowsWithoutUSB) and extract it using 7zip or WinRAR
![Opera Snapshot_2022-05-02_154455_github com](https://user-images.githubusercontent.com/71734690/166318804-209f8ced-d2cc-45ce-ac54-b3d428dc4e14.png)
4. Download the [Atlas .iso file of your choice](https://atlasos.net/download)
5. Run Macrorit Partition Expert, and select the drive you want to partition (basically in order to use both your current OS and Atlas, you need to have a drive big enough for both. To 'partition' is to split the drive into multiple partitions). In most cases this is going to be the `C:` partition.
6. Right click the selected partition, and click 'Resize/Move Volume'. In the menu that opens, allocate (to make space) as much space as you believe is necessary for Atlas. You do this by dragging the yellow slider. The unallocated section is how much space Atlas will have. I recommend having at _least_ 29GB of storage.
![Record_2022_05_02_15_52_18_68](https://user-images.githubusercontent.com/71734690/166316148-007e1e03-2a77-4dfb-a42d-bfa249547b83.gif) (I'm currently running Atlas which is why my `C:` drive is labeled as so. You can ignore my drive names)
7. Once your done, click OK. The menu should now close. Now a new section should appear next to your selected partition. It should be called 'Unallocated' and it needs to have more than 29 GB of available space. This is where Atlas will be installed. Right click the unallocated space, and press 'Create Volume'. This should open another pop-up menu. Everything can be left as default, except you need to make sure the File System is set to 'NTFS'. _Also, make sure you remember the drive letter you set it to._ Once you're done, click OK.
![Record_2022_05_02_16_00_26_345](https://user-images.githubusercontent.com/71734690/166317198-2a18bc51-ef7b-421b-8b0f-df79bd4d2890.gif)
8. Press the 'Commit' button in the upper-left-hand corner. Press 'OK' or 'Accept' to any prompts which appear. If it asks you to restart your PC, close any other applications and accept the prompt.
9. Once your PC has restarted, open the [Install Windows Without USB](https://github.com/iidanL/InstallWindowsWithoutUSB) folder you extracted earlier. It should prompt you to select the .iso of your choice (**Note: It may take a while for the file explorer window to pop-up. Please be patient**). Select the Atlas .iso. 
10. Wait for the script to do what it does. When prompted to enter the letter of the partition you want to install the iso on, **only type the letter** of the partition we made earlier. For example: If you made the partition letter `E:` then type `E`
11. Wait for the script to finish running and display text saying you can restart your PC. At this point you may want to install [EasyBCD ](https://cfcdn.neosmart.net/software/EasyBCD/community/EasyBCD%202.4.exe?response-content-disposition=attachment%3B%20filename%3D%22EasyBCD%202.4.exe%22&response-cache-control=max-age%3D1209600&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZmNkbi5uZW9zbWFydC5uZXQvc29mdHdhcmUvRWFzeUJDRC9jb21tdW5pdHkvRWFzeUJDRCUyMDIuNC5leGU~cmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj1hdHRhY2htZW50JTNCJTIwZmlsZW5hbWUlM0QlMjJFYXN5QkNEJTIwMi40LmV4ZSUyMlx1MDAyNnJlc3BvbnNlLWNhY2hlLWNvbnRyb2w9bWF4LWFnZSUzRDEyMDk2MDAiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NTE1MjU3NjV9fX1dfQ__&Signature=mCTUREPZ-vwYCm5CIUAmOAU8s2vkP0YDTQA2uOYEeI6yUMe~y8110aWHmEK5kAeyx7WI4v2j5yVPWYuZjyJC9g7Fwvkoa55yYJC3R-YpQ5GxH5BaBso4Zjok~srb72QMDt0dPgfRg3wZsNqNKxRV6pyIr1dZo-ioBNYshtqXgXT-fxv2iUluXkw9QPs2CKCwGOfOOqf3QqX1rmGjTikVKkBTwQwWq20OirLTrBBmjcgCnk2Z3FjgHtO9GICndQvl6ICn9YO5aPjCOcOXxQTu03001nPv~w4HmpRdN3XYgPliNlxwtF2zr~FmuKP~XES6mt5XhhCFvU3SDNnnohujDg__&Key-Pair-Id=APKAIPY5GEV5EHVOFFNQ)to add the drive as a boot option, because Windows will detect Atlas as a normal windows install, so when you try to reboot, it's going to have you choose between your current OS (Windows Volume 1-10), and Atlas (Windows Volume 1-10). If you are confused by this statement though, don't install EasyBCD. Just reboot your PC, and select the non-default boot option.

**Comment by Zusier** [comment]
Added, thanks

**Comment by Johnapolitan** [comment]
Cool, thanks! Do I get a contributor role for doing so? Johnapolitan#7935

**Comment by Haydens-workshop** [comment]
https://atlasos.net/download results in a 404 error
