### ISSUE TITLE
Preinstalled SDIO

### ISSUE THREAD

**Issue by r0sayo** [Atlas-OS/Atlas#166]
**Is your feature request related to a problem? Please describe.**
No. SDIO should be preinstalled with indexes to make it simpler for the user

**Describe the solution you'd like**
A preinstalled install of SDIO with indexes downloaded

**Describe alternatives you've considered**
I haven't found any.

**Comment by Zusier** [comment]
SDIO is updated way too often for that to be integrated. Indexes would be useless a week after release.

Instructions are already included to help with installation.
