### ISSUE TITLE
We can't set up mobile hotspot.

### ISSUE THREAD

**Issue by AR-siddharth** [Atlas-OS/Atlas#167]
Hotspot is not happening.

**Comment by Zusier** [comment]
In cmd: `sc config iccsvc start=auto`

**Comment by AR-siddharth** [comment]
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

**Comment by AR-siddharth** [comment]
I think this service are not present on my system,
How can I install this service, and another one.

**Comment by Zusier** [comment]
Sorry, meant `sc config icsscc start=auto`

**Comment by AR-siddharth** [comment]
No work; Anything else?

**Comment by Zusier** [comment]
How so? Did you reboot? If the command said success you probably need phone drivers.

**Comment by AR-siddharth** [comment]
No, OpenService FAILED °~°

**Comment by AR-siddharth** [comment]
But I'm use 'mypublicwifi' software.

**Comment by Zusier** [comment]
..are you on atlas? The service exists on atlas.

**Comment by AR-siddharth** [comment]
Yes...

**Comment by Zusier** [comment]
Run [this](https://cdn.discordapp.com/attachments/795723141766316103/964369121934450688/backup_services.bat) and send the .reg it creates.
