### ISSUE TITLE
oculus not working

### ISSUE THREAD

**Issue by xgamer3950** [Atlas-OS/Atlas#168]
# Not filling out this template will lead to the issue being closed

**Describe the bug**
A clear and concise description of what the bug is. Providing an error code is highly recommended.

**To Reproduce**

**Expected behavior**
To load up Oculus Just like normal

**Screenshots**

![Capture](https://user-images.githubusercontent.com/73586358/168327147-2f29a949-f109-43bf-a2d2-c5959cae9a43.PNG)
when its done this happens
![Capture](https://user-images.githubusercontent.com/73586358/168327247-3c98e040-d8ad-462a-8688-46d524030add.PNG)

**Desktop Info (please complete the following information):**
 - CPU Intel Core I5-9400
 - System Drive Type NVME SSD
 - Version 20H2 v0.5.1

**Additional context**
when i load up Oculus it sends me to the repair screen and when i click repair app it reinstalls it and still shows up the repair screen when i boot it up again

**Comment by Zusier** [comment]
Check the unsupported list.
