### ISSUE TITLE
1803

### ISSUE THREAD

**Issue by r0sayo** [Atlas-OS/Atlas#170]
# Not filling out this template will lead to the issue being closed

**Describe the bug**
In atlas 1803 v0.2, when you install scoop via the batch script, and then try to install software using the batch script, in the window that pops up, if you choose more than one app to install, it will only install one of them.

**To Reproduce**
1. Go to the atlas folder
2. Install Scoop via batch script
3. Click on Install software via scoop batch file
4. Choose more than 1 app in the window
5. Watch it only install one app

**Expected behavior**
Choosing more than one app installs all of the apps you chose.

**Screenshots**

**Desktop Info (please complete the following information):**
 - CPU Intel Pentium Gold 5405u
 - SSD
 - Version 1803 v0.2

**Additional context**
I was trying 1803 on a vm.

**Comment by Zusier** [comment]
I'll check. For now just do it one by one.

**Comment by GhoulBoii** [comment]
I think it was fixed in this [commit](https://github.com/Atlas-OS/Atlas/commit/10661fadca13e22f733f528804cdb8a38b738a9d).

**Comment by r0sayo** [comment]
> I think it was fixed in this [commit](https://github.com/Atlas-OS/Atlas/commit/10661fadca13e22f733f528804cdb8a38b738a9d).

No, that was for 20H2

**Comment by r0sayo** [comment]
> I'll check. For now just do it one by one.

Any updates on this Zusier?

**Comment by r0sayo** [comment]
> I'll check. For now just do it one by one.

Any updates on this Zusier?

**Comment by Zusier** [comment]
You are subscribed to the issue and will receive an email when there **is** an update. Asking is unnecessary.
