### ISSUE TITLE
A bat file to set discord and spotify priority to low!

### ISSUE THREAD

**Issue by LuminaEXE** [Atlas-OS/Atlas#171]
quite self explanotry!

**Comment by Zusier** [comment]
I don't like to turn down suggestions, but this is very simple to do in task manager. If you are doing it for means of performance, it'd be better to close them while gaming. If not, setting to low often causes crackling in audio when under load.

**Comment by Johnapolitan** [comment]
You can also try disabling hardware acceleration. This'll stop the app from utilizing your GPU, increasing performance. You can also try using the Spotify web player and the Discord website and see if that helps. I'd recommend using Opera GX for this as it has a sidebar to keep the web apps organized plus you can set hardware resource limits, as well as disabling hardware acceleration.

**Comment by Zusier** [comment]
Disabling hardware acceleration offloads all of the rendering to your CPU, I wouldn't recommend it.

**Comment by Johnapolitan** [comment]
As with most performance tweaks, results vary from user to user. I'd at least try it out, especially if your CPU is more powerful than your GPU

**Comment by LuminaEXE** [comment]
i see where you oth are coming from but its really annoying to set the the priority to low on all of the tasks

**Comment by nikosszzz** [comment]
> i see where you oth are coming from but its really annoying to set the the priority to low on all of the tasks

You could try a tool like Process Lasso to do it automatically.
