### ISSUE TITLE
Certain Atlas 1803 Features not Working

### ISSUE THREAD

**Issue by Johnapolitan** [Atlas-OS/Atlas#172]
**Describe the bug**
I cannot utilize the windows clipboard, snip/sketch, nor desktop notifications.

**To Reproduce**
Install Atlas 1803, attempt to enable the listed features in the folders with their respective names. Restart PC. 

**Expected behavior**
Features to function

**Desktop Info (please complete the following information):**
 - CPU: Intel Celeron N3050
 - System Drive Type: SSD 
 - Version: 1803 v0.2

**Comment by Zusier** [comment]
Clipboard History was introduced in 1809. Otherwise I have triple checked that snip & sketch and notifications work, they do.
