### ISSUE TITLE
Says no internet on ethernet and there is no action center

### ISSUE THREAD

**Issue by that1mortal** [Atlas-OS/Atlas#174]
I need help because I also deleted my Atlas folder too and emptied recycle bin

**Comment by Zusier** [comment]
C:\Users\Default\Desktop

Go to Atlas >> troubleshooting >> networking >> reset to windows default. Otherwise you need drivers (install from another pc)

**Comment by that1mortal** [comment]
> C:\Users\Default\Desktop
> 
> Go to Atlas >> troubleshooting >> networking >> reset to windows default. Otherwise you need drivers (install from another pc)

**Comment by that1mortal** [comment]
It cant start up a certain service

**Comment by Zusier** [comment]
What certain service? Sounds like you're running the windows troubleshooter, I said in the atlas folder.

**Comment by that1mortal** [comment]
I accidentally deleted that, and its not in the recycle bin

**Comment by Zusier** [comment]
Read the top of my first comment.
> C:\Users\Default\Desktop
Its the **Default** user, not your current user.

**Comment by that1mortal** [comment]
OH
