### ISSUE TITLE
Network problem still exists after running troubleshooting from 'Atlas' Folder

### ISSUE THREAD

**Issue by that1mortal** [Atlas-OS/Atlas#175]
# Not filling out this template will lead to the issue being closed

Diagnostic Policy Service is not starting, When I troubleshooted my network problem, It said it needed to run that service, but it does not work and gives an error message (It is on the screenshots section)

**To Reproduce**
1. Press 'Windows Key + R' and type 'services.msc' then press Enter
2. Scroll Down to 'Diagnostic Policy Service'
3. Right click on it and press 'Start'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/85194303/168493366-52e9346f-2713-46be-b0c3-f635325ddbf8.png)

**Desktop Info (please complete the following information):**
 - AMD Ryzen 7 3750H
 - SATA SSD
 - Don't know

**Comment by that1mortal** [comment]
Also sorry Zusier I accidentally closed the post I made earlier

**Comment by Zusier** [comment]
Refer to the issue you already made..

> Otherwise you need drivers (install from another pc)

Windows Troubleshooter will not solve this.

**Comment by Zusier** [comment]
Again, I said troubleshooting in the atlas folder. Which has no relation to the windows troubleshooter

**Comment by that1mortal** [comment]
I tried the thing where I reset the network to windows default, ill try to find the drivers tho

**Comment by that1mortal** [comment]
Also idk of this is normal but Windows 10 is not activated when i had windows 10 before

**Comment by Zusier** [comment]
![image](https://user-images.githubusercontent.com/46111482/168494266-0de80d4e-447c-47ed-8560-1cfd6ca71ffe.png)

**Comment by that1mortal** [comment]
ohhh, well I need to get the internet working first

**Comment by that1mortal** [comment]
and I have no idea how im on firefox

**Comment by that1mortal** [comment]
Ok, I know how I can fix this, there is windows 10 updates waiting, so if there is a way for me to actually enable updating it, im good?

**Comment by Zusier** [comment]
You had internet at some point?

**Comment by Zusier** [comment]
> Ok, I know how I can fix this, there is windows 10 updates waiting, so if there is a way for me to actually enable updating it, im good?

No.. windows updates are disabled on atlas

**Comment by that1mortal** [comment]
I think I need to reinstall atlas or get back to windows 10, I tried getting back to windows 10 already and it did not work
