### ISSUE TITLE
eMMC Support

### ISSUE THREAD

**Issue by SuperPie64** [Atlas-OS/Atlas#177]
Hello, I've been unable to install AtlasOS recently because the operating system currently has no support for eMMC storage.

If you could, would you be able to add eMMC support in a future update? Thank you.

**Comment by Zusier** [comment]
Currently this is not possible, (and why I put it on the unsupported list to prevent these questions :p ). I have tried a lot to fix it but nothing has fixed it so far.

**Comment by ItsTatsuya** [comment]
@Zusier so basically if u have eMMC driver, putting the driver in the boot USB is the only way to install right
