### ISSUE TITLE
GTA is not opening it says error memory error or vcruntime error. cant fix it

### ISSUE THREAD

**Issue by Sonam200398** [Atlas-OS/Atlas#179]
# Not filling out this template will lead to the issue being closed

**Describe the bug**
A clear and concise description of what the bug is. Providing an error code is highly recommended.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop Info (please complete the following information):**
 - CPU [Intel or AMD, include specifics]
 - System Drive Type
 - Version [e.g. 20H2 v0.5.1]

**Additional context**

**Comment by Zusier** [comment]
Atlas >> troubleshooting >> vcredists reinstall
