### ISSUE TITLE
Adobe Creative Cloud not working after WIFI disable script

### ISSUE THREAD

**Issue by whallin** [Atlas-OS/Atlas#18]
**Describe the bug**
The Adobe Creative Cloud desktop app does not work properly after running the "Disable Wifi.bat" script/file bundled with Atlas.

**To Reproduce**
Make sure you are an ethernet user before reproducing:
1. Install Adobe Creative Cloud to see normal behavior
2. Run the "Disable Wifi.bat" file and restart your system
3. Launch the Creative Cloud desktop app and see the results 

**Expected behavior**
Keep Creative Cloud functionality just like usual.

**Desktop Info:**
 - CPU: AMD Ryzen 7 3700X
 - System Drive Type: NVMe
 - Version: 0.3.6

**Additional context**
I suppose this has something to do with how the script in "atlas-config.bat" disables the WIFI on the system. I've used different scripts in the past to disable WIFI while still having a functioning Creative Cloud experience. So a possible fix would be to look for a different way to disable WIFI in the script. 

As an ethernet user, there really isn't any need that WIFI is enabled, but there are definitely different alternatives to keep normal functionality while still disabling the WIFI option/service. (as I've seen it done before)

**Comment by whallin** [comment]
The same error occurs with the Microsoft Store.

Disable WiFi using the script, and then Microsoft Store thinks you're offline.

This was tested on 0.3.7.

**Comment by Zusier** [comment]
Does your netwrok status on the taskbar appear as a globe?![Like this](https://user-images.githubusercontent.com/46111482/115162516-8f3bc000-a069-11eb-96eb-fed97b99b478.jpeg)

**Comment by whallin** [comment]
It does not appear at all, the icon is completely gone. 

If I try to open my network settings in the Settings app, the visualization at the very top and the text below it is just gone.

**Comment by Zusier** [comment]
Okay so I did some testing but I didn't get this issue🤔Does it work fine if you re-enable?

**Comment by Zusier** [comment]
If so, try enabling the netprofm service via this command:
`sc config netprofm start=disabled`
