### ISSUE TITLE
Issues with "Windows Mail and Calender" and Installing "Office 365" (Fixed! check my last comments)

### ISSUE THREAD

**Issue by sophieasdi** [Atlas-OS/Atlas#180]
# Not filling out this template will lead to the issue being closed

**Describe the bug**
So. I have 2 bugs to report.

1. When i open "Windows Mail and Calender" when i click on the "add account" button it just does not do anything i.e. I cannot sign into mail to be able to access my mail

2. I keep getting an install error while downloading "Office 365" with the official installer from "https://www.office.com/?auth=2" 

**To Reproduce**
I dunno what you should do to reproduce these errors i don't know if these are just with me or a widely reported issue

**Expected behavior**
Office just stays on installing for about 7 hours (how long i waited ;-;)

When you press "Add account" it does nothing.

**Desktop Info (please complete the following information):**
 - CPU [11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80Ghz]
 - SSD
 - Version [20H2 (No updates through the updater)]

**Comment by Zusier** [comment]
Please fill out the issue template.. I dont even know what error happens when you try to install office.

For mail I’d recommend a different client such as thunderbird.

**Comment by sophieasdi** [comment]
Sorry ill send the error

**Comment by Zusier** [comment]
Without that important info, I’d say try the [offline installer](https://support.microsoft.com/en-us/office/use-the-office-offline-installer-f0a85fe7-118f-41cb-a791-d59cef96ad1c)

**Comment by sophieasdi** [comment]
I tried that but it just hung and died

**Comment by sophieasdi** [comment]
![image](https://user-images.githubusercontent.com/105531822/169427462-e1c9643f-a5b3-4a1e-bacb-872595fca90e.png)

**Comment by sophieasdi** [comment]
![ds](https://user-images.githubusercontent.com/105531822/169427758-8bc442ef-2b7b-4dc9-b715-754c50b4b3e5.PNG)
![s](https://user-images.githubusercontent.com/105531822/169427760-8eaccdd3-a040-4c5e-97d7-c2e989e8d263.PNG)

**Comment by sophieasdi** [comment]
I figured it out all i needed to do for the mail was run

"DISM.exe /Online /Add-Capability /CapabilityName:OneCoreUAP.OneSync~~~~0.0.1.0" in command prompt (Admin mode)
