### ISSUE TITLE
When I give print command it opens print app and closes it in seconds. 

### ISSUE THREAD

**Issue by Nakul-Arora** [Atlas-OS/Atlas#182]
# Not filling out this template will lead to the issue being closed

**Describe the bug**
When I give print command it opens print app and closes it in seconds. Please tell me a solution , I have to print.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop Info (please complete the following information):**
 - CPU [Intel or AMD, include specifics]
 - System Drive Type
 - Version [e.g. 20H2 v0.5.1]

**Additional context**

**Comment by Zusier** [comment]
Refer to the top of the issue.
