### ISSUE TITLE
Explorer unresponsive to USB drive ejection

### ISSUE THREAD

**Issue by joey04** [Atlas-OS/Atlas#183]
**Describe the bug**
When I eject a thumb drive in File Explorer, the drive is ejected properly but the status is not updated in Explorer. Thus the ghost drive remains listed in the left pane.

**To Reproduce**
Normal USB thumb drive usage - pop it in, read/write files, then Eject (I usually right click the drive name in 'This PC' view so the Explorer window remains open)

**Expected behavior**
After ejection, the drive should disappear from the left pane. Instead, I have to close Explorer and open a new one to get the proper state.

**Desktop Info
20H2 v0.5.1
default USB settings (I've not changed anything in the registry. The bug was present before I installed all drivers, and it remains after all drivers installed.)

**Additional context**
This is just a nuisance. As stated, the drive is ejected properly, i.e. write buffers flushed. I've verified this with two different thumb drives, and neither has been corrupted.
But if there's a way to fix it, that would be nice.

**Comment by Zusier** [comment]
Restart explorer

**Comment by joey04** [comment]
I'll add that I've never seen this bug in many years of Windows usage, all on official installs. I'm brand new to the customized Windows ISO scene; didn't know it existed until last week when I decided to re-install Win10 and found them via a Youtube recommendation.

What a breath of fresh air - a lean, optimized Windows without forced updates. Thanks for having the highest level of transparency and documentation of all the custom ISOs available. That meant a lot to this veteran power user with a number of Linux distro installs under my belt but never needed to install Windows before. Besides this minor bug, everything else is working well so far after installing two days ago.

(On that note, I do have a suggestion - your website's [documentation page](https://atlasos.net/documentation) could simply have links to the Readme and Wiki here on Github. Would be much better than a "Coming Soon..." placeholder.)

**Comment by Zusier** [comment]
This is restarting with task manager, yes? I don't see why that wouldn't work, it seems to for me.

**Comment by joey04** [comment]
Yep restarted in task manager. This problem has been there from the beginning and has persisted across several reboots/shutdowns too.
But like I said, it's a nuisance I can live with.
