### ISSUE TITLE
network bug

### ISSUE THREAD

**Issue by sehittin** [Atlas-OS/Atlas#184]
i think there is a bug about network devices or idk after i installed cyberghost vpn , os is completely broken like when i restart it enters explorer.exe crash loop. i tried safe mode it looks good but when i try safe mode with networking explorer.exe still crashes. i want to use cyberghost on atlas.

**Comment by Zusier** [comment]
win+r eventvwr >> windows logs >> system
look for recent logs from service-control manager

**Comment by RUNUPONME** [comment]
win + r 
services.msc 
search for ' Secure Socket Tunneling Protocol Service '
right click -> properties 
change startup type to automatic -> apply -> start -> okay
