### ISSUE TITLE
Explorer ran as SYSTEM when installing openshell

### ISSUE THREAD

**Issue by r0sayo** [Atlas-OS/Atlas#186]
**Describe the bug**
When installing openshell using the script in Atlas >> Config >> UWP, when it's done installing, it runs Explorer as SYSTEM.

**To Reproduce**
1. Go to Atlas >> Config >> UWP
2. Run " Install Open-shell (run first)
3. Wait for it to install
4. Look at explorer

**Expected behavior**
Explorer to restart as User

**Desktop Info (please complete the following information):**
 - Intel Pentium 5405U
 - SSD
 - Atlas 1803, v0.2

**Additional context**
On a VM

**Comment by Zusier** [comment]
Ah I know what the cause is, I'll push a commit when I have time tonight. As a workaround you can simply reboot the system. Thanks
