### ISSUE TITLE
Script goes on removing

### ISSUE THREAD

**Issue by r0sayo** [Atlas-OS/Atlas#187]
**Describe the bug**
when removing xbox components, it tells you that this is irreversible, but when you press N to cancel, it goes on anyway

**To Reproduce**
1. Run "remove xbox components"
2. Press N to cancel
3. See it remove xbox components

**Expected behavior**
the removal being cancelled

**Screenshots**

**Desktop Info (please complete the following information):**
 - Intel Pentium 5405U
 - SSD
 - 20H2 v0.5.1

**Comment by Zusier** [comment]
Thanks, fixed.
