### ISSUE TITLE
Wi-Fi Error

### ISSUE THREAD

**Issue by pratapsaiv** [Atlas-OS/Atlas#188]
I initially Connected to A WiFi System During the First setup... And after all the Default CMD Process The WiFi Disconnected Itself and I am Unable to turn it on again after reboot

**Comment by Zusier** [comment]
Atlas >> Troubleshooting >> Networking >> Reset to windows default

**Comment by SyrmGIT** [comment]
User seems to be new to GitHub and issue has surpassed 7 days. If you need help, join our Discord.

**Comment by jahidnakib** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/107399994/173324304-c2c25325-9875-4c4b-82ea-91da8568b3db.png)
