### ISSUE TITLE
Intel Graphics Command Center still not opened after 3hours

### ISSUE THREAD

**Issue by SOULJEYRO** [Atlas-OS/Atlas#189]
# Not filling out this template will lead to the issue being closed

**Describe the bug**
A clear and concise description of what the bug is. Providing an error code is highly recommended.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. ---> imgur.com/a/QEJanx8

**Desktop Info (please complete the following information):**
 - CPU - i5 9300h
 - System Drive Type - Notebook
 - Version [e.g. 20H2 v0.5.1]

**Additional context**
Add any other context about the problem here. - I installed all the drivers for the GPU and video card, on the ggOS operating system everything is fine, but in AtlasOS it does not want to load the Intel Graphics Command Center, please help.

**Comment by Zusier** [comment]
Try default windows drivers and services in the atlas folder.

**Comment by SOULJEYRO** [comment]
> Try default windows drivers and services in the atlas folder.

ty, but it doesn't help, anyway ty, i just installed another graphics control panel ;)
