### ISSUE TITLE
Lively wallpaper is not working.

### ISSUE THREAD

**Issue by Painted12** [Atlas-OS/Atlas#19]
Lively installs correctly but when i go to run it I get this error:
![image](https://user-images.githubusercontent.com/82516899/115975480-f6e68500-a519-11eb-9c72-4f2f06d3fd4d.png)

**Comment by Zusier** [comment]
Please state what version of atlas you are on. Seems to be a .net issue according to error.

**Comment by Zusier** [comment]
I've figured out the issue, will be fixed in the next version.

**Comment by SamcroBIT** [comment]
Your operating system took 1-2 years to develop, but why are there so many bugs?

**Comment by SyrmGIT** [comment]
> 
> 
> Your operating system took 1-2 years to develop, but why are there so many bugs?

It didn't take 1-2 years to develop? It took around 6 months. There are small bugs with some things that our Alpha Testers never used on Atlas, and that's what we're now debugging and releasing in patches.

**Comment by Zusier** [comment]
I haven't even spent a year on it, why are you so rude?

**Comment by SamcroBIT** [comment]
Where am i rude Am I using the wrong words? It's an OS with lots of errors?

**Comment by SamcroBIT** [comment]
If you remember me, I talked to you when you didn't launch the OS Beta, you said you would do your best. But why are there so many bugs now?

**Comment by Zusier** [comment]
On many commits I make you criticize atlas. [See here](https://github.com/Atlas-OS/Atlas/commit/dec076f4185eb3f450313bccd5403f02040ac4d2)

**Comment by SamcroBIT** [comment]
I am truthful because you do not develop anything.

**Comment by SyrmGIT** [comment]
> 
> 
> If you remember me, I talked to you when you didn't launch the OS Beta, you said you would do your best. But why are there so many bugs now?

There's not even "Lots of bugs" most bugs are fixable by us, but some Zusier is working on fixing.

You have to remember the OS is in BETA...?

**Comment by SyrmGIT** [comment]
> 
> 
> I am truthful because you do not develop anything.

How's that truthful? "you do not develop anything." he is working on fixing the bugs, and you're being rude for no reason. They take time, and it's still in Beta.

**Comment by SamcroBIT** [comment]
You should try it out before the Beta release. @SyrmGIT

**Comment by SyrmGIT** [comment]
> 
> 
> You should try it out before the Beta release. @SyrmGIT

I am using it right now, do I have any issues? Nope. Do people who use Lively Wallpaper's application have issues? Yes. I do not use Lively Wallpaper, neither does the people who used Atlas when it was in Atlas. This is why the bug exists in the public BETA.

**Comment by Zusier** [comment]
@Painted12 Update: I have to add much more components back to Atlas for it to work which I would rather not do, fortunately the Microsoft Store version does not require these dependencies. I recommend you use that version if you want to use Lively Wallpaper.
