### ISSUE TITLE
Latest Spotify update does not work

### ISSUE THREAD

**Issue by ORGINRISHITH** [Atlas-OS/Atlas#191]
**Spotify NEW UPDATE ISN'T WORKING IN ATLAS OS NEED HELP**

**Comment by ServoAtya** [comment]
But pls disable caps lock

**Comment by Zusier** [comment]
I’ll look into it after my vacatiom but for now downgrade to the previous version.

**Comment by etahamad** [comment]
> **Spotify NEW UPDATE ISN'T WORKING IN ATLAS OS NEED HELP**

are you running spotify with custom chrome_elf.dll file?

**Comment by r0sayo** [comment]
Spotify latest version non-UWP works just fine for me 20h2 v0.5.1
1.1.87.612.gf8d110e2

**Comment by v1xlrz** [comment]
i cant install spotify on atlas why???
