### ISSUE TITLE
When i open files it wont close unless i go in to the taskbar and close it

### ISSUE THREAD

**Issue by Iky0** [Atlas-OS/Atlas#20]
**Describe the bug**
When i open files it wont close unless i go in to the taskbar and close it

**To Reproduce**
1. click files
2. try click the X butten on the tab

**Expected behavior**
I expected it to close

**Comment by Zusier** [comment]
Simply reboot, I will make a fix in the post install script.

**Comment by Iky0** [comment]
Thanks that fixed it
