### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by r0sayo** [Atlas-OS/Atlas#200]
**Is your feature request related to a problem? Please describe.**
In the FAQ, eMMC drives are not listed as unsupported and the enable feature command either. I have fixed that in my own fork of the repo, but I can't seem to find a way to start a pull request for the wiki.

**Describe the solution you'd like**
For eMMC drives to be added as unsupported in the FAQ and the enable feature command to be available in the "Windows Features is not working!" section of the FAQ.

**Comment by UltimateBoi** [comment]
Search bar not working

**Comment by Johnapolitan** [comment]
@r0sayo [Guide](https://github.com/Atlas-OS/Atlas/blob/ba07ae96372347683adcaa419bbb443715c12851/.github/CONTRIBUTING.md#3-making-your-first-contribution) 
Basically just open a new issue with the requested changes in order to add to the wiki. For adding to the the README.md, open a pull request.

**Comment by Johnapolitan** [comment]
@UltimateBoi Search doesn't function on atlas 1803. Please don't randomly comment on issues. If you need help join the [the Atlas discord server](https://discord.gg/SAGJrxFc35)

**Comment by Zusier** [comment]
Fixed.
