### ISSUE TITLE
High Graphics Causing Games to Crash

### ISSUE THREAD

**Issue by Vyla1** [Atlas-OS/Atlas#206]
Whenever I play a game above the lowest graphics it always crashes. The games it's happened in are ROBLOX, VALORANT, and Minecraft. It's a reoccurring problem and I don't know hot to fix it. In ROBLOX when I set the graphics quality above 3 the game is fine for a few minutes then it freezes for a few seconds then closes. Same thing for VALORANT and Minecraft. When I play VALORANT and just use medium textures it's fine for a short period of time then it ends up crashing. My hardware isn't bad either.  All my drivers are up to date do and I've scanned for viruses multiple times. 
Specs: 
CPU: i5-11400 @ 2.60GHz
RAM: 16 GB DDR4 Ram @ 2933 MHz 
SSD: 500 GB (forgot r/w speed) 
GPU: GTX 1650 Super
OS: AtlasOS 20H2

How to see if you have the bug also:
1. Play any of the games I've listed
2. Change any of the graphics to medium or above. 
3. Wait around for a bit. 
4. Your game  becomes unresponsive and close. 

Here's a clip: 
https://imgur.com/a/3b8HItV

**Comment by Zusier** [comment]
These would likely be due to temperatures, high vram or ram usage.. none of which would be the related to Atlas.
