### ISSUE TITLE
Microsoft store

### ISSUE THREAD

**Issue by Iky0** [Atlas-OS/Atlas#21]
**Describe the bug**
When i download something from microsoft store it wont open

**To Reproduce**
1. download something from the microsoft store
2. Try opening it if you dont get an error

**Expected behavior**
It opens the app

**Screenshots**
![Capture](https://user-images.githubusercontent.com/83179635/116005742-2c907a00-a5bd-11eb-81d5-36426c9ea534.PNG)

**Comment by Zusier** [comment]
This was fixed in the latest version, closing.
