### ISSUE TITLE
Problem with msi afterburner

### ISSUE THREAD

**Issue by Pulee5** [Atlas-OS/Atlas#210]
I have a problem with msi afterburner, my fans are locked for some reason and I can't adjust the fan speed.
![Screenshot_1](https://user-images.githubusercontent.com/108616417/177039829-51db0c55-657a-4fa1-b2ab-6cc5f2e04dc1.png)

**Comment by Zusier** [comment]
Don't know what to tell you I am using my fans perfectly fine on atlas.

**Comment by Paprika4785** [comment]
It's your gpu fan problem not the software. Probably your gpu fan is just at static speed.
