### ISSUE TITLE
Monitor speakers not showing up in sound playback devices

### ISSUE THREAD

**Issue by YeeterMcYeetAss** [Atlas-OS/Atlas#218]
Before installing Atlas, my Acer KG271's speakers could be used. I just had to select them in the sound settings like any another playback devices. Now after installing Atlas, the monitor speakers don't show in either activated, disactivated or disconnected devices. I'm using a displayport, not an hdmi, for this monitor. It always worked so i don't know if i forgot to enable something in the configurations or what

**Expected behavior**
I expected the to see something along the line of KG271 Speakers in the playback devices, from which i could switch freely without issue.

**Desktop Info (please complete the following information):**
 - CPU : AMD Ryzen 5 2600 3.4 GHz 6-Core Processor
 - Monitor : Acer KG271 Cbmidpx 27.0" 1920x1080 144 Hz Monitor
 - GPU : EVGA GeForce RTX 2060 6 GB XC ULTRA GAMING Video Card
 - Version :  Most recent as of date

**Comment by SyrmGIT** [comment]
Hi @YeeterMcYeetAss,

Are you still experiencing this issue? If you are, please try and install drivers via the speaker [manufacturer's website](https://www.acer.com/ac/en/US/content/drivers), or through [SDIO](https://www.snappy-driver-installer.org/). A guide to using it is included in the Atlas folder, under the "Drivers" subfolder.

If there's no response within a week, I'll close this. Best of luck :smile:
