### ISSUE TITLE
Is there no way other then to build an image with wsl2 support?

### ISSUE THREAD

**Issue by CodeCubeNeo** [Atlas-OS/Atlas#219]
Hi I already once asked for a custom biometric support image, and now i am about to do the same with wsl2. I undewerstzand if you dont want to, but it would be really cool to make a third image (besides the faceit version) that would support a lot of things. I tried just debloating the normal windows version and its painful and you dont get good results -> Atlas is amazing!!!!! But it is still missing some features (like biometrics and wsl2). I ams sorry for bothering you again, but i guess its not  sin to ask again. Thanks for even reading this ig.

**Comment by Zusier** [comment]
Please read the [build guide](https://github.com/Atlas-OS/Atlas/tree/main/src#building-from-source), I don't have time for custom image requests anymore. Work and other side projects that take up my time now.
