### ISSUE TITLE
Creating a microsoft account on setup will brick the pc and force me to reinstall the OS

### ISSUE THREAD

**Issue by aShanki** [Atlas-OS/Atlas#22]

**Comment by Zusier** [comment]
Does it "freeze" after you get prompted to create a pin?

**Comment by aShanki** [comment]
> Does it "freeze" after you get prompted to create a pin?

Correct

**Comment by Zusier** [comment]
Check my edit.

**Comment by aShanki** [comment]
> Check my edit.

Tysm, local account ftw tho

**Comment by Zusier** [comment]
Indeed, go ahead and close the issue if your issue has been resolved.
