### ISSUE TITLE
Pppoe BoardBand Not working In AtlasOS 20H2

### ISSUE THREAD

**Issue by arifbd1205** [Atlas-OS/Atlas#220]
*Describe the bug**
I've Installed The AtlasOS 20H2 Tomorrow On My Laptop Everything Works Out of The Box Except The Dial Up Feature Or Pppoe Feature It Show Os Connection Bar Board Band Blocked.When I Try To Connect Or Create Dial Up Pppoe It Show Error 1058.But When It First Booted The Pppoe or Dial Up Feature Worked But When The Cmd Tweaking Is Done And System Restarted Then The Dial Up Or Pppoe Don't Work.
When I Go To The Adapter Settings It Show Device Missing Under The Board Band Adapter. 

Note :
Every Drivers Were Installed
Wifi Is Working
Lan Drivers Installed
Windows Is Showing Ethernet Connected.

Desktop Info
- CPU Intel n2840
- Ram 4Gb Ddr3L
- System Drive hdd 500gb
- Version AtlasOS 20H2

**Additional context**
Thanks In Advance And Sorry For My Bad English.

**Comment by Zusier** [comment]
Try enabling vpns in the atlas folder
