### ISSUE TITLE
I can't sign in on HP Smart and I can't get my printer to work

### ISSUE THREAD

**Issue by HyugAG0d** [Atlas-OS/Atlas#221]
MY PRINTER IS HP Smart tank 500

**Describe the bug**
I cannot print despite enabling printer in the atlas folder, i cant sign in on HP Smart. I tried both vpn being disabled and enabled but doesnt work, also i cant print on my printer it only allows me to save as pdf (on the printing section). My printer is detected by windows but it is not being detected by word docs or any software.

**To Reproduce**
1. open hp smart
2. sign in
3. put account details

**Expected behavior**
To be able to print and sign in on my HP acc

**Screenshots**
![image](https://user-images.githubusercontent.com/72782575/182122306-80f4b317-9f25-4c7f-a630-7f55afe4364e.png)

**Desktop Info (please complete the following information):**
MY PRINTER IS HP Smart tank 500
i5 4670
b85 killer
32gb ddr3 ram
rx570
60gb ssd
1tb hdd

**Additional context**
N/A

**Comment by nikosszzz** [comment]
Well - Have you tried enabling Printing from the Atlas folder scripts?

**Comment by HyugAG0d** [comment]
> Well - Have you tried enabling Printing from the Atlas folder scripts?

Yes, I also tried searching fixes for the error stated but it only says that I should have VPN disabled when I didn't even enable it.

**Comment by SyrmGIT** [comment]
HI @HyugAG0d,

Did you disable Wi-Fi? Try enabling it from the Atlas folder and restarting your computer.

Let me know how this goes. :smile:

**Comment by oit63** [comment]
As I find the first reason is that print spool service is not enabled, cause related reg and files are missing.

**Comment by oit63** [comment]
[Print.zip](https://github.com/Atlas-OS/Atlas/files/10102441/Print.zip)
I extract these files from newly install windows 11, and it works.

1.  put the files into system32
2. click the print.reg to import print registry keys
3. enable print with script in altas configure directory.
4. reboot

Refference:
https://www.thewindowsclub.com/print-spooler-repair-in-windows-10

**Comment by SyrmGIT** [comment]
> [Print.zip](https://github.com/Atlas-OS/Atlas/files/10102441/Print.zip)
> I extract these files from newly install windows 11, and it works.
> 
> 1.  put the files into system32
> 2. click the print.reg to import print registry keys
> 3. enable print with script in altas configure directory.
> 4. reboot
> 
> Refference:
> https://www.thewindowsclub.com/print-spooler-repair-in-windows-10

So this fixed it on Atlas? Don't understand.

**Comment by PencilNavigator** [comment]
> [Print.zip](https://github.com/Atlas-OS/Atlas/files/10102441/Print.zip) I extract these files from newly install windows 11, and it works.
> 
>     1. put the files into system32
> 
>     2. click the print.reg to import print registry keys
> 
>     3. enable print with script in altas configure directory.
> 
>     4. reboot
> 
> 
> Refference: https://www.thewindowsclub.com/print-spooler-repair-in-windows-10

does this fix the issue on atlas?

**Comment by oit63** [comment]
Sure, or why I post it here. My AtlasOS 20H2 works with HP Printer P1606dn. Attention, AtlasOS 1803 never works, as too slim.

**Comment by oit63** [comment]
but at present I can't resolve the HP Smart Installer, I cannot figure out what services this installer requires.

**Comment by PencilNavigator** [comment]
okay? so if it's fixed you can go ahead and close this issues.

**Comment by oit63** [comment]
not All fix, the newer printer with HP smart installer may meet problem

**Comment by oit63** [comment]
Require someone to fix this

**Comment by oit63** [comment]
I install driver for my HP laserjet 401 successfully.
The solution is never use HP Smart to install any printer. Just download the PCL6 Print Driver for your printer model, and install it mannully.
I download from this site, and you can just search for a driver with search engine.
https://printerdrivers.com/hp-laserjet-pro-400-mfp-m425-drivers-download/

**Comment by PencilNavigator** [comment]
> I install driver for my HP laserjet 401 successfully. The solution is never use HP Smart to install any printer. Just download the PCL6 Print Driver for your printer model, and install it mannully. I download from this site, and you can just search for a driver with search engine. https://printerdrivers.com/hp-laserjet-pro-400-mfp-m425-drivers-download/

if it's fixed you can go ahead and close this issue.

**Comment by oit63** [comment]
> 

as this is not my thread, I can't close it ;)

**Comment by PencilNavigator** [comment]
> > 
> 
> as this is not my thread, I can't close it ;)

lol
dont worry, someone will close it.

**Comment by JayXTQ** [comment]
@SyrmGIT
