### ISSUE TITLE
Please bring back the Windows photo viewer (Required to view .ico files)

### ISSUE THREAD

**Issue by amymor** [Atlas-OS/Atlas#223]
hi, windows photo viewer takes up only 8.5MB, i dont know why you removed it from Atlas OS. its the best viewer for icon files because its the only viewer that can display multi-resolution icons. (it can show all images packed to icons). i tried a lot of viewers (about 40) if you know of a viewer with the ability to switch between photos in icon package let me know, but i guess there isnt simple and clean like windows photo viewer.

for other types of images (like jpg png bmp ...) i prefer JPEGView, because it has a good interface with the best quality and features like easy photo comparison. but i currently change a lot of icons for Windows and other programs, so i need a good icon viewer. all other image viewers will only show you the first image in the icon pack, maybe a 16x16 one or 256x256 or etc... if you dont have a good viewer when creating the icons, they will be blurry or shaky (especially in detail view in the explorer) because you cant tell if 16x16 is good or not.

also is it possible to restore the photo viewer manually? i have a backup of it, but it belongs to 20h1 build 763, do you have 2004(20h2) version of it?

**Comment by wjk4** [comment]
They removed it because it's bloat, you can just download it from here anyways: https://apps.microsoft.com/store/detail/microsoft-photos/9WZDNCRFJBH4?hl=en-us&gl=US

**Comment by amymor** [comment]
> They removed it because it's bloat, you can just download it from here anyways: https://apps.microsoft.com/store/detail/microsoft-photos/9WZDNCRFJBH4?hl=en-us&gl=US

Windows Photo Viewer is different from Microsoft Photos(UWP).

**Comment by bombarulz** [comment]
There was a registry file somewhere on the internet that activates it unless in this version it's completely removed.

**Comment by amymor** [comment]
> There was a registry file somewhere on the internet that activates it unless in this version it's completely removed.

When the Windows photo viewer files don't exist in the system folder, Registry Fix can't restore them and only makes the situation worse.

i uploaded 20h1 build 763 could someone test it? 
[Windows-Photo-Viewer](https://github.com/amymor/Windows-Photo-Viewer/raw/main/Windows%20Photo%20Viewer.zip)

the command for opening Windows photo viewer is:
`START rundll32 "%ProgramFiles%\Windows Photo Viewer\PhotoViewer.dll", ImageView_Fullscreen [image path]`

**Comment by SyrmGIT** [comment]
At this moment, we won't be adding back the Windows' legacy photo viewer. There has to be alternatives out there for your use case, it may be in the future this may be brought back into Atlas. However, Atlas is completely designed for gaming and not for this use, giving us the decision to deny this suggestion.

**Comment by amymor** [comment]
> At this moment, we won't be adding back the Windows' legacy photo viewer. There has to be alternatives out there for your use case, it may be in the future this may be brought back into Atlas. However, Atlas is completely designed for gaming and not for this use, giving us the decision to deny this suggestion.

Windows Photo Viewer has no effect on gaming.
