### ISSUE TITLE
Cannot open certian websites

### ISSUE THREAD

**Issue by aShanki** [Atlas-OS/Atlas#23]
**Describe the bug**
Can't open minecraft.net and or tiny.cc... idk why
**To Reproduce**
1. Go to 'minecraft.net or tiny.cc'
2. They will not load, or you will get a gateway error
I have reinstalled the latest atlasos multiple times.

**Comment by Zusier** [comment]
Are you using Wi-Fi currently?

**Comment by aShanki** [comment]
Ethernet

**Comment by Zusier** [comment]
Do any other websites load? This sounds like and ISP issue or user error.

**Comment by aShanki** [comment]
> Do any other websites load? This sounds like an ISP issue or user error.

Other websites load properly. also adding opera.com to the list

**Comment by Zusier** [comment]
What browser are you using?

**Comment by aShanki** [comment]
I have used chrome, ungoogled chromium, chrome, and brave to test this. All sites didn't load that I have listed

**Comment by Zusier** [comment]
I can open all of these websites, I am still going to help you solve this issue but I believe it isn't related to Atlas.

What dns server are you using? Whats the specific error code?

**Comment by Apex-YT** [comment]
Try looking at the host file.

**Comment by ShadowDragonsYTs** [comment]
I've also encountered this issue, and I've changed my DNS, tried Brave and Chrome, didn't work

**Comment by Zusier** [comment]
What scripts/programs have you installed/run? And please, I'm still looking for an error code.

**Comment by Zusier** [comment]
Closing until I receive a response.
