### ISSUE TITLE
Samsung Android USB Driver won't work

### ISSUE THREAD

**Issue by s1stine** [Atlas-OS/Atlas#231]
### To reproduce
1. Download & install [Samsung Mobile USB Driver](https://developer.samsung.com/android-usb-driver)
2. Download and run Samsung Odin
3. Plug and put Samsung Android device to Download mode
4. Odin won't detect device

### Expected behavior
Odin detects device, and downloading works perfectly

### Desktop specification
 - CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz   (1.80 GHz)
 - System drive type: SSD with GPT partition table
 - Version: 20H2 latest

### Additional context
What I have done is reinstalled vanilla Windows and it works fine, might be **an Atlas driver issue**.

**Comment by Zusier** [comment]
Your header is confusing me.. if this isn't an atlas bug why are you posting here?

**Comment by s1stine** [comment]
Who knows, I don't really think it is a bug, just an Atlas driver issue.
If it's not really a bug, you can close it or even list me into your weird kids list lol

**Comment by Phongvngg1** [comment]
yeah,  its ATLAS OS BUG !!!, 
![image](https://user-images.githubusercontent.com/87188286/202438323-bb0d6177-8fec-4e74-a78b-85bcf9185989.png)
driver wont be detected at all
![image](https://user-images.githubusercontent.com/87188286/202438393-36abbd76-efa9-493a-bb70-b6429666a5eb.png)
i have installed samsung mobile phone driver
![image](https://user-images.githubusercontent.com/87188286/202438476-c51a9318-1059-425d-828b-b6b7235cf366.png)
this is the  first time i got this bug, adb works prefectly, but odin wont. btw i have flashed custom rom/blalba my redmi note 11 and poco x3 many times but not able for samsung

**Comment by s1stine** [comment]
i thought you have closed this lmao

**Comment by s1stine** [comment]
let's thank him for making the issue more clearly ^

**Comment by haidsrenke0-netizen** [comment]
I've faced same problem also in windows 10. any solution?
