### ISSUE TITLE
Anydesk is not working

### ISSUE THREAD

**Issue by hamza-mubk** [Atlas-OS/Atlas#235]
# Not filling out this template will lead to the issue being closed

**Describe the bug**
Hello, I am employed and work from home on my office PC. For me, working on my office PC via Anydesk is mandatory. However, Altas OS restricts Anydesk software to run or connect properly. Please help me in this matter. Beyond that, everything is just perfect.

**To Reproduce**

**Expected behavior**
My anydesk is not connecting to the internet. I just want it to work properly.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/111826282/186049891-e5bcacad-6c35-4d3a-be63-fcdf87d1fd34.PNG)

**Desktop Info (please complete the following information):**
 - CPU [Intel Core i7-4600U, 2.19GHZ, 2.70GHZ]
 - System Drive Type  64xbit
 - Version [e.g. 20H2 v0.5.1]

**Additional context**

**Comment by Zusier** [comment]
I have tested and used anydesk multiple times, this is not an atlas issue.

**Comment by hamza-mubk** [comment]
For real? I reinstalled Windows Altas OS latest 
and it still doesn't connect :(

**Comment by SyrmGIT** [comment]
@hamza-mubk please try enabling Wi-Fi. This will fix the issue after a restart.

**Comment by oreshkinns** [comment]
Have the same issue, enabling wifi didnt help
