### ISSUE TITLE
wireless mouse doesn't work but wired does.

### ISSUE THREAD

**Issue by ndrgith** [Atlas-OS/Atlas#238]
# Not filling out this template will lead to the issue being closed

**Describe the bug**
for the version 1803_02 when i connect my wireless logitech mouse nothing happens but wired mouse is working without any problem.

**To Reproduce**
1. Just connect a wireless mouse to any usb port
2. New usb connection apeears in taskbar for an instant, but dissappears immedately.

**Desktop Info (please complete the following information):**
 - Version 1803_02

**Comment by yCyanxs** [comment]
download the mouse drivers/software

**Comment by ndrgith** [comment]
since wired mouse worked from the beginning i didn't think that it was driver issue. but it turned out that wireless drivers were missing. I have solved the problem bu using Iobit driver booster before you replied. thanks anyway.
