### ISSUE TITLE
Show dekstop icons are not working

### ISSUE THREAD

**Issue by syashjain** [Atlas-OS/Atlas#239]
# Not filling out this template will lead to the issue being closed

**Describe the bug**
A clear and concise description of what the bug is. Providing an error code is highly recommended.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop Info (please complete the following information):**
 - CPU [Intel or AMD, include specifics]
 - System Drive Type
 - Version [e.g. 20H2 v0.5.1]

**Additional context**

**Comment by UltraToon** [comment]
bro you did not fill out the template

**Comment by syashjain** [comment]
I cant understand what do want to say

**Comment by SyrmGIT** [comment]
Template was not used, closing the issue.
