### ISSUE TITLE
Oculus Air Link

### ISSUE THREAD

**Issue by summertides** [Atlas-OS/Atlas#24]
**Describing the bug**
The bug is the Oculus Air Link not working. The app, when trying to enable Oculus Air Link for Quest 1 & 2 devices, simply restarts. When it has finished restarting, Air link is still disabled. 

**Steps to reproduce the bug**
1. Go to Oculus and install the app from under any VR Headset Series (Quest, Quest 2, Rift, etc)
2. Install the Oculus app
3. Once it is done, complete the steps shown on the screen
3a. If it asks for a VR, click "Skip". It will send you straight to the menu page.
4. Go to the settings page
5. Go to the Beta tab
6. If you do not see Air Link, refer to 6a
7. If you do see Air link, attempt to turn it on. If failure to do so and Oculus App restarts, bug reproduced.

6a. Turn on "Public Test Channel"
6b. Oculus will ask for an Update + App Restart
6c. Go back to the Settings --> Beta Tab
6d. Click Restart Oculus App as Update Restart is not enough
6e. Go back to the Settings --> Beta Tab
6f. Attempt to turn on Air Link
6g. If failed to run Air Link and Oculus App restarts, bug reproduced.

**Note**
I have already switched to normal Windows 10 to test it out and it was just fine, simply turned on. Checked my Quest 2 and it works as well. So the problem might be something missing within the Atlas OS. I have attached an Oculus App Log below which recorded what happened during the crash. It possibly could have the cause there.

[Oculus_Logs_ATLASOS-DESKTOP_20210430_171159.zip](https://github.com/Atlas-OS/Atlas/files/6408087/Oculus_Logs_ATLASOS-DESKTOP_20210430_171159.zip)

**Comment by Zusier** [comment]
According to the logs, it requires the Lanman Server service. To enable it, run these commands in command prompt as administrator:
`sc config LanmanServer start=auto
sc start LanmanServer`
You may be required to reinstall the Oculus App again.

**Comment by scuffurs** [comment]
It did not seem to work the first time, I also reinstalled Oculus which didn't also seem to do much. I checked Command Prompt and ran "sc start LanmanServer". It stated "An instance of this service is already running." but the problem is still occurring. I don't think the LanmanServer was the cause, unfortunately.

**Comment by Zusier** [comment]
Can you check for a service named “OVRService” in services.msc? If you find it, right click properties, go to dependencies and send them here.

**Comment by scuffurs** [comment]
Services.msc says No Dependencies.

**Comment by Zusier** [comment]
Does the OVRServer service run if you start it manually? Does it stop soon after you run it?

**Comment by scuffurs** [comment]
I no longer see OVRServer. I only see Oculus VR Library / Runtime Server. I had not done anything to make it happen.

**Comment by Zusier** [comment]
It disappeared? Try to start both of those services, and check dependencies.

**Comment by scuffurs** [comment]
Oculus VR Runtime service is set to automatic so it has been started from the beginning. But looks like Oculus VR Library Service is having trouble starting up. Even when set to Automatic. Both of them have no dependencies.

**Comment by Zusier** [comment]
Try starting the Library Service and check event log, the error should be located at: Windows Logs > System (source: Service-Control-Manager)

It may also be under Applications and Services Logs

**Comment by scuffurs** [comment]
The Oculus VR Library Service service terminated with the following service-specific error: 
There are no more files.
Event ID: 7024

**Comment by Zusier** [comment]
Sorry for the extremely delayed response, I would try default atlas services in the atlas folder. It may be something stripped, if so I cant do much about it unless I get an oculus

**Comment by ant-7802** [comment]
sorry for posting on an old issue, but try to open the oculus debug menu, go to service and press start oculus service, I hope this helps

**Comment by kekkodance** [comment]
it seems like with my personal testing, oculus software (and the devices it installs) seem to work fully on **Atlas 20H2 v0.5.2 FaceIT Edition**.

**Comment by matskobinks** [comment]
> According to the logs, it requires the Lanman Server service. To enable it, run these commands in command prompt as administrator: `sc config LanmanServer start=auto` `sc start LanmanServer` You may be required to reinstall the Oculus App again.

DONT DO `sc start LanmanServer` it break computer trust me lol

**Comment by Zusier** [comment]
Because you need to enable it via the atlas folder

**Comment by volkayno** [comment]
> Sorry for the extremely delayed response, I would try default atlas services in the atlas folder. It may be something stripped, if so I cant do much about it unless I get an oculus

You do not need an occulus just atlas os and try to install the occulus software, I am trying to fidn the missing service or piece for the library service to work
