### ISSUE TITLE
Can't type in windows search or settings search

### ISSUE THREAD

**Issue by Hackerly0** [Atlas-OS/Atlas#246]
Hello Atlas,
I ran into a problem. I can't type in windows search but the keyboard is running completely fine on the browser...

**Comment by SyrmGIT** [comment]
Are you on Atlas 1803?

**Comment by Hackerly0** [comment]
20H2

**Comment by SyrmGIT** [comment]
If you're on 20h2 and it's not working even after a restart, you've most likely ran other optimization scripts which have broken it.

**Comment by Hackerly0** [comment]
I've never ran optimization scripts, I just download a browser and drivers... That's it

**Comment by Hackerly0** [comment]
I have solved it, and it's running fine. Thank You @SyrmGIT
