### ISSUE TITLE
Hibernete in power sitting dont work

### ISSUE THREAD

**Issue by aazanabili** [Atlas-OS/Atlas#249]
**Hibernete in power sitting dont work**
**To reproduce**
**Steps to reproduce the behavior:**

control panal -> power -Choose what the power button does -> 
Hibernete 

**Desktop specification**
CPU: Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz (2.21 GHz)
System drive type: SSD with GPT partition table
Version: 20H2 latest

**Additional context**
i try open (As administrator)CMD and i wrote :
`powercfg -h on`
the Hibernete option appeared but not working

**Comment by Montassar22** [comment]
has this bug been fixed?

**Comment by SyrmGIT** [comment]
Hibernate won't work on Atlas and we have no plans on re-implementing it for Atlas.
