### ISSUE TITLE
Windows Precision Drivers

### ISSUE THREAD

**Issue by MuddyNX** [Atlas-OS/Atlas#25]
I recently installed atlas os on a dell insprion 5590 and it works great.
My only problem is there is no precision drivers thus resulting in the touchpad to be detected as a mouse. If possible could precision drivers be added to the os?

**Comment by Zusier** [comment]
Good to hear it's running well!

Whats the name of the "mouse" in device manager? There should be drivers for you in Snappy Driver Installer Origin. But if you tell me the device name, I can get them for you.

**Comment by MuddyNX** [comment]
The touchpad uses the default windows precision drivers, which apparently where showing a exclamation mark once the os was installed. These drivers are:
HID:
Microsoft Input Configuration Device
Portable Device Control device
Also 2 System Drivers:
ACPI Processor Aggregator
ACPI Wake Alarm

The reason for the error was due to a disabled service.
By simply updating them locally I was able to restore the touchpad functionality.
