### ISSUE TITLE
ASUS ISSUE FANMODES NOT WORKING, ARMOURY CRATE. 

### ISSUE THREAD

**Issue by xrva420** [Atlas-OS/Atlas#250]
**Describe the bug**
I have An ASUS TUF GAMING A15, and i installed armoury crate, and other asus stuff, but i cannot change fan mode, or use aura rgb, it just doesnt communicate with something, used to work on normal windows 10
**To Reproduce**
1. Install Armoury Crate Asus
2. TRY FN+F5 To change fan mode
4. Does not pop up anything, armoury crate not working.

**Expected behavior**
I expected it to work.

**Desktop Info (please complete the following information):**
 - CPU [AMD RYZEN 5 4600H]
 - SSD
 - Version [21H2]

**Comment by Vitalasy** [comment]
It is unsupported try **[msi center](https://www.msi.com/Landing/MSI-Center)** and **[open rgb](https://openrgb.org)**

**Comment by xrva420** [comment]
@Vitalasy you realise i need it? i need to control fan speeds bro or my system will overheat

**Comment by Zusier** [comment]
```
devmanview /enable "System Speaker"
devmanview /enable "System Timer"
devmanview /enable "UMBus Root Bus Enumerator"
devmanview /enable "Microsoft System Management BIOS Driver"
devmanview /enable "High Precision Event Timer"
devmanview /enable "PCI Encryption/Decryption Controller"
devmanview /enable "Intel SMBus"
devmanview /enable "PCI Memory Controller"
devmanview /enable "PCI standard RAM Controller"
devmanview /enable "Composite Bus Enumerator"
devmanview /enable "Microsoft Kernel Debug Network Adapter"
devmanview /enable "SM Bus Controller"
devmanview /enable "NDIS Virtual Network Adapter Enumerator"
devmanview /enable "Numeric Data Processor"
devmanview /enable "Microsoft RRAS Root Enumerator"
``` Run in cmd, reboot

**Comment by xrva420** [comment]
@Zusier thank you <3
