### ISSUE TITLE
Amd+Nvidia Freezing issue

### ISSUE THREAD

**Issue by xrva420** [Atlas-OS/Atlas#251]
Issue Description.
While trying to run a benchmark, or a game, my system freezes. I am on Nvidia Optimus AMD Ryzen 5 4600H and Nvidia GTX 1650ti
Amd Adrenalin version 22.5.1
Nvidia Version 516.94
I had to reinstall Amd Drivers like 10 times and only once succeded.
Freezing issue still remains, nvidia gpu is fine.
Sadly i cannot use nvidia only, since my laptop doesn't have mux switch
Laptop : Asus TUF Gaming A15

**Comment by xrva420** [comment]
Also BSOD, ERROR CODE
DRIVER_POWER_STATE_FAILURE

**Comment by SyrmGIT** [comment]
This is most likely a hardware issue. Have you tried it since?

**Comment by JayXTQ** [comment]
@xrva420

**Comment by Savillion** [comment]
I have the same exact system but from lenovo. I have never had a BSOD. It might be a hardware issue.
