### ISSUE TITLE
Sound card doesn't work

### ISSUE THREAD

**Issue by nimagp** [Atlas-OS/Atlas#252]
Windows doesn't recognize sound output devices and seems like it doesn't even detect sound card. Had this issue with both `1803` and `19042` (`20h2`).
I'm using an onboard sound card and as you can see drivers are installed properly.
![Annotation 2022-09-22 185450](https://user-images.githubusercontent.com/71447191/191788037-15961fe1-9445-4b09-b958-8944adbe97c6.png)
I didn't have this problem with previous *normal* windows 10 installation (two years ago) and windows 8/7. pipewire,pulseaudio and mesa(popular sound controller and drivers in linux systems) *do detect* my sound card(I have to choose it manually by a command though, anyways).
A weird issue which might be connected to this is that nvidia and realtek settings are not installed (or *I* can't find them).
And if these help:
![Annotation 2022-09-22 190617](https://user-images.githubusercontent.com/71447191/191791066-637fbd4c-d11e-491d-8906-3ef157a2b49b.png)
![Annotation 2022-09-22 190711](https://user-images.githubusercontent.com/71447191/191791075-cfebf913-02ae-4f83-85a8-eda13917eb8f.png)

Thanks.

**Comment by JayXTQ** [comment]
@nimagp you still experiencing this issue?

**Comment by SyrmGIT** [comment]
This is a DRIVER issue, and not related to Atlas. Make sure you look into loading drivers on for your sound card using SDIO. I will be closing this as it's been open for too long with no responses.

**Comment by SyrmGIT** [comment]
Might also be because it's a sound card, and it's unsupported by Atlas (if this is the case, we will unfortunately not be supporting it as for low demand)

**Comment by nimagp** [comment]
It was solved by downloading latest realtek driver from the site
