### ISSUE TITLE
Update Atlas 20H2 from 20H2 Revision 631 (2009) to the latest available 20H2 build.

### ISSUE THREAD

**Issue by Aetopia** [Atlas-OS/Atlas#253]
Atlas currently ships 2009 which is an older version of 20H2.
Because of this games/applications that even support 20H2 (Latest Revision) have the chance of not running under Atlas.
(Applications/Games don't provide any info which revision they support.)

**Comment by behrad0086** [comment]
warzone2.0 not opening

**Comment by uncognic** [comment]
1st of all, 2009 IS 20H2, it is not an older version of 20H2, it's just another way of saying it. And for MW2, there is a fix in the [Atlas Discord](https://discord.gg/atlas), in #announcements

**Comment by SvineruS** [comment]
https://discord.com/channels/795710270000332800/795724409808617513/1035548283734601758

**Comment by JayXTQ** [comment]
@SyrmGIT

**Comment by LeMill-Vycta** [comment]
> 00000315

You are heaven sent. Saving people 2 yrs in with this. Cheers
