### ISSUE TITLE
bluetooth audio device issue

### ISSUE THREAD

**Issue by niyal7** [Atlas-OS/Atlas#255]
# Not filling out this template will lead to the issue being closed

**Describe the bug**

when connecting bluetooth headphones or tws it only connects voice, not connecting music, so i'm not able to play music or game on my headphone

**To Reproduce**
Steps to reproduce the behavior
open bluetooth settings 
click add bluetooth device
select the bluetooth headphone

**Expected behavior**
it shows connected voice

**Screenshots**

![Screenshot (1)](https://user-images.githubusercontent.com/114277024/192081418-e0c56bb3-2cc1-490e-9b67-5b0f492a681d.png)
![Screenshot (2)](https://user-images.githubusercontent.com/114277024/192081421-88b3e2b5-f49d-46f3-bba0-905baf65c0a6.png)
![Screenshot (3)](https://user-images.githubusercontent.com/114277024/192081444-7510c0d5-a9e3-4f14-ac7b-437b73e1eeef.png)
![Screenshot (4)](https://user-images.githubusercontent.com/114277024/192081445-a0b22c8a-2fb4-4868-b9c7-1b8e0e822a16.png)

**Desktop Info (please complete the following information):**
 - intel i3 6006u
 - System Drive Type ssd
 - 20h2

**Additional context**
on using normal windows 10 when connecting my bluetooth headphone and tws it shows connected voice and music
and on sound output settings it shows eg: boat hands free ag audio , and boat 141 stereo or boat rockers 510 stereo 
and when changing output device to the second one that is "the stereo one " the sound will be ok 
in atlas os there is not showing the output device with stereo please fix them

**Comment by JayXTQ** [comment]
@niyal7 are you still experiencing this issue? if not try enable bluetooth in the atlas folder

**Comment by PencilNavigator** [comment]
Enable bluetooth in atlas folder. i solved it by doing it.

**Comment by SnowzNZ** [comment]
> Enable bluetooth in atlas folder. i solved it by doing it.

Please close this issue

**Comment by sprityx** [comment]
Olá Lucas o/, como voce ja ativou o bluetooth prla pasta do atlas, veja se seus drivers do adaptar/placa bluetooth estao instalados e atualizados, essa pode ser uma das razões do mesmo nao estar funcionando.

Caso tenha problemas contínuos, que tal entrar no server do discord oficial para tentarmos te ajudar de forma mais efetiva.

Translation: Hello Lucas o/, as you have already activated bluetooth in the atlas folder, check if your adapter/bluetooth card drivers are installed and updated, this could be one of the reasons why it is not working.

 If you have ongoing problems, how about joining the official discord server so we can try to help you more effectively.
