### ISSUE TITLE
Add back Quick Access in Explorer, and add back msconfig.

### ISSUE THREAD

**Issue by DavidRLTG** [Atlas-OS/Atlas#256]
**Is your feature request related to a problem? Please describe.**
Inability to use msconfig, or pin things in Explorer.

**Describe the solution you'd like**
Please, add back msconfig and quick access

**Describe alternatives you've considered**
just using windows 10 ame lmao

**Additional context**
please? everyone wants them anyways

**Comment by kryxzz** [comment]
You can enable Quick Access in the Atlas folder, at Atlas >> Optional Tweaks >> Quick Access.
And for msconfig, there are many alternatives you can check out by doing !msconfig in the Discord server.

**Comment by DavidRLTG** [comment]
Ah, okay. Thanks for letting me know!
