### ISSUE TITLE
Librewolf BSOD

### ISSUE THREAD

**Issue by h4rldev** [Atlas-OS/Atlas#261]
**Describe the bug**
Installing and running librewolf on Atlas BSODs with the errorcode: Driver IRQL not less or equal

**To Reproduce**
1. Install 'librewolf' with scoop
2. Run librewolf
4. BSOD

**Expected behavior**
A way to use a privacy focused browser and actually go on the internet.

**Desktop Info (please complete the following information):**
 - CPU
   AMD Ryzen 9 3900X 12-core
 - System Drive Type
   NVMe SSD
 - Version [e.g. 20H2 v0.5.1]
   21H2

**Additional context**
Does the same if you install it through choco.

**Comment by kryxzz** [comment]
Use the normal version

**Comment by H4rldev** [comment]
> Use the normal version

?? 20H2?

**Comment by kryxzz** [comment]
The non-scoop version

**Comment by H4rldev** [comment]
> The non-scoop version
> Does the same if you install it through choco.

Choco retrieves the latest setup file for librewolf from github and silent installs it so it's not an issue with scoop or it's repo for librewolf

**Comment by H4rldev** [comment]
Fixed it by downgrading to 20h2

**Comment by H4rldev** [comment]
Nevermind, after using it, it decided to BSOD once more

**Comment by H4rldev** [comment]
Moving back to normal windows 10 ig

**Comment by H4rldev** [comment]
Since I can remove bloat and telemetry myself

**Comment by SyrmGIT** [comment]
You can also just use internet explorer to download Librewolf if this is causing the BSOD.

**Comment by H4rldev** [comment]
> You can also just use internet explorer to download Librewolf if this is causing the BSOD.

It isn't the way you install it

**Comment by Intancote** [comment]
People really missed the part where it's not an install issue and instead something else

**Comment by H4rldev** [comment]
Truly

**Comment by SyrmGIT** [comment]
> Truly

I find it hard to believe that Librewolf is the cause of the BSOD considering I've used Librewolf in the past on Atlas, and others use it to this day.

If you won't try downloading it through internet explorer, I can't see the willingness to troubleshoot the problem on your end. Make sure you check Event Viewer and check the BSOD reason, and solve it yourself.

**Comment by H4rldev** [comment]
> > Truly
> 
> I find it hard to believe that Librewolf is the cause of the BSOD considering I've used Librewolf in the past on Atlas, and others use it to this day.
> 
> If you won't try downloading it through internet explorer, I can't see the willingness to troubleshoot the problem on your end. Make sure you check Event Viewer and check the BSOD reason, and solve it yourself. 

It's def an incompatibility between librewolf and atlas. Considering atlas isn't it's own os but just registry changes. The bsod is has something to do with librewolf trying to access memory to no avail. I'm not entirely sure if I posted the error code, but don't think that doing the same exact thing as doing it through internet explorer differentiates from actually doing the same thing, please get that into your head and maybe reduce the pettiness, Thanks

**Comment by SyrmGIT** [comment]
@H4rldev to comfirm your testing: you said that you had tried 20h2 and installing Librewolf; after you said it was fixed. Could it be something else that is causing the error, or have you been able to reproduce this with no changed to base Atlas except from installing LIbrewolf?  This includes running any scrips in the Atlas folder.
