### ISSUE TITLE
Fortnite Crash on new season

### ISSUE THREAD

**Issue by DeltaFlick12** [Atlas-OS/Atlas#262]
# Not filling out this template will lead to the issue being closed

**Describe the bug**
I open the fortnite and after 2 minutes just close
**To Reproduce**
1. Open fortnite
2. Wait
3. Just crash
4. No error

**Expected behavior**
I expect atlas resolve this

**Screenshots**
Nope

**Desktop Info (please complete the following information):**
 - AMD (Ryzer 7 2700x)
 - SATA
 - 20H2

**Additional context**
Overwatch 2 is crashing too

**Comment by kryxzz** [comment]
Check logs

**Comment by DeltaFlick12** [comment]
where? i send to epic games all my game logs and nothing work

**Comment by kryxzz** [comment]
Bruh show us the logs not send it to Epic Games, it should be in  %localappdata%\FortniteGame\Saved\logs

**Comment by DeltaFlick12** [comment]
[Logs.zip.zip](https://github.com/Atlas-OS/Atlas/files/9711842/Logs.zip.zip)

**Comment by kekkodance** [comment]
can confirm this is an issue.

**Comment by CptZingers** [comment]
> some of the services that might’ve been disabled can make conflict with the game and that could be the problem, can you provide which version of atlas you’re using?
> 
> (i’m on v0.5.1 and it’s running flawlessly)

Can you send the services you have, because I have the same issue with Overwatch 2.

**Comment by FeminineFemale** [comment]
this is a fortnite issue not an os issue the crash happens for everyone reseting pc seems to temporally fix it tho

**Comment by CptZingers** [comment]
> > 
> 
> yeah, add my discord: paranoia#9389 (932869124953088010)

Alright I did

**Comment by JayXTQ** [comment]
fortnite currently doesn't work in 20H2, will be fixed in 22H2

**Comment by JayXTQ** [comment]
@SyrmGIT
