### ISSUE TITLE
Add a build guide

### ISSUE THREAD

**Issue by DeGamersSpelen** [Atlas-OS/Atlas#265]
I would like to have a guide to build my own atlas iso

I just want to build a 22h2 atlas iso...

**Comment by Zusier** [comment]
We have a [build guide](https://github.com/Atlas-OS/Atlas/tree/main/src#building-from-source)

**Comment by Dystnine** [comment]
> We have a [build guide](https://github.com/Atlas-OS/Atlas/tree/main/src#building-from-source)

But the guide was disappeared recently,I don't know why.
![图片](https://user-images.githubusercontent.com/123282693/218249336-31168d84-f968-4e8c-a895-3406d4e11844.png)

**Comment by Xyueta** [comment]
Preparations for the future update

**Comment by Xyueta** [comment]
no
