### ISSUE TITLE
Active Directory compatibility

### ISSUE THREAD

**Issue by freddy1301** [Atlas-OS/Atlas#266]
Since it is possible to get old PCs running again with Atlas OS thanks to the saved background processes, I tried to set up a Windows domain with it. At first there were problems joining the domain at all, but these could be solved with the handy Atlas OS scripts on the desktop. 

I have written a small tutorial about this:

### Re-Configure Atlas OS
* Desktop/Atlas/Configuration/Workstation: Enable Lanman Workstation
* Desktop/Atlas/Troubleshooting/Network: Reser Network to Windows Default
* Desktop/Atlas/Troubleshooting/Services:
Run NSudo
Click "Browse" (next to the Textfield)
Navigate to the same folder again
Open "Default Windows Services
Click Run
Click Yes
Reboot the System
Done!

However, when updating the group policies with gpupdate /force an error occurs and when trying to access \\*\SYSVOL the access is denied. This could be fixed by two registry entries from this tutorial (http://woshub.com/cant-access-domain-sysvol-netlogon-folders/) only that I have to add "RequireMutualAuthentication=0" to "RequireMutualAuthentication=0,RequireIntegrity=0,RequirePrivacy=0" in the reg commands.

Could options be added to the AtlasOS folder on the desktop for this?

Or a whole script which is for Active Directory compatibility?

Translated with www.DeepL.com/Translator (free version)

**Comment by forart** [comment]
Well, it would be really great to have different customized targets (ex. Gaming, HiFi, AVediting, etc) in place of original "Home/Pro/N/etc" but this probably require a grow and split of the development team.

Anyway the project is open...

**Comment by PencilNavigator** [comment]
https://discord.com/channels/795710270000332800/1006527806609575936/threads/1050426255247425587
unsupported.

**Comment by Xyueta** [comment]
It will be supported within the next version.
