### ISSUE TITLE
Custom high contrast modes issues

### ISSUE THREAD

**Issue by XKane55** [Atlas-OS/Atlas#267]
I'm new to all this, I just formatted my drive to install Atlas. I got an issue here and I'm not sure if there is something I could do to fix it myself or if it's not possible...

You usually can set custom colors for high contrast mode and it's quite useful to have a quick dark theme that works with any app easily togglable with shift+alt+printscreen. It doesn't seem be functioning correctly and it would be great to have it work. It also changes the background to the default Atlas background when toggling on and off.

1. Search high contrast in windows settings.
2. Click on Turn high contrast on or off.
3. Try changing the colors to something else.
4. Turn high contrast on and see that it stays a certain color and never changes.
5. Turn high contrast off and the background is back to the default one.

You should be able to change the background color to any color and see the background become that color with high contrast mode turned on, but it doesn't work.

 - CPU: AMD Ryzen 5 3600
 - SSD
 - Version [v0.5.2]

**Comment by JayXTQ** [comment]
I'm not seeing this issue reproduced, are you still seeing it?

**Comment by SyrmGIT** [comment]
Confirmed to be working on new version, will be released in the coming weeks. Thanks for the issue!
