### ISSUE TITLE
Overwatch "Rendering Device Lost" 

### ISSUE THREAD

**Issue by CptZingers** [Atlas-OS/Atlas#268]
**So when I join an online match, I could play for a couple minutes before it gives me an error saying "rendering device lost", my GPU drivers are up to date, all my drivers are. People are saying it's your tweaked Windows which is causing this. **

**To Reproduce**
1. Open Overwatch
2. Click Unranked and choose any of the options and start
3. Rendering Device Error

**Expected behavior**
Black screen would appear, game frozen, and an error "Rendering Device Lost" would be shown.

**Screenshots**
![image_2022-10-08_193704750](https://user-images.githubusercontent.com/113254190/194717890-7fc85e0d-0903-4fa0-8eff-5eaa02ca86ad.png)

**Desktop Info (please complete the following information):**
 - AMD Ryzen 5 5600G (integrated graphics)
 - SSD and NVMe (Game on NVMe)
 - Atlas OS 21H2 v.0.5.1

**Additional context**
Im sorry if I didn't get things right, first time on Github

**Comment by mechalynx** [comment]
Do you still have this problem? What driver version where you using? I've got a 5600g and I want to use the iGPU so I'm interested to know. I may be trying to install atlas soon (not sure when) so I might be able to help troubleshoot if I know what you've already tried.

**Comment by igotthings56** [comment]
I am playing overwatch 2 just fine, the only thing I did is run the USERControlPanelAccessibility.reg here it is (github dosent support .reg files so heres a google drive) https://drive.google.com/drive/folders/1o28aWU3ERdOVbuMYaOU-4TWtZkyI_aXF

**Comment by mechalynx** [comment]
Thanks for this @igotthings56 - I've decided to just use the win10 AME scripts instead of atlas for now, for unrelated reasons to this but this is still useful. By the way, google drive thinks this is an `mp3` file for some reason but renaming to `.reg` fixes that. I don't understand the settings it sets but it seems alright. Thanks again :+1:
