### ISSUE TITLE
Using a deticated gpu in a laptop (mx250) will bug out the entire windows installation

### ISSUE THREAD

**Issue by fussybal** [Atlas-OS/Atlas#269]
laptop info:

i7-1065g7
8gb ram
gpu0: intel iris plus
gpu1: mx250
and a egpu connected with a rtx 2060.

when using the laptop without egpu and using the mx250 the entire windows bugs and everything uses 100% gpu usage. i cant figure out the cause

**Comment by JayXTQ** [comment]
Are you still receiving this issue?

**Comment by SyrmGIT** [comment]
This is probably because of the Windows version. Good news! We are moving to 22h2 in the coming weeks, so this might be in your interest to check out when it's released to the public. Sorry for the problems caused.
