### ISSUE TITLE
Intel graphics command center will not recognise games

### ISSUE THREAD

**Issue by aShanki** [Atlas-OS/Atlas#27]
**Describe the bug**
Intel graphics command center which is used by intel 6th generation graphics and above for driver versions above 24 is not recognizing supported games.

**To Reproduce**
1. Open intel graphics command center
2. Click on detect games
3. It should normally detect games within around 10 seconds but in this case it hangs there and doesn't detect anything.

**Desktop Info (please complete the following information):**
 - Intel i3-8130U
 - SSD
 - 0.3.9 beta
 - Intel UHD 620
 - 4 GB ram

**Comment by Zusier** [comment]
Seems to be working fine in v0.5, feel free to re-open if you are still having issues.
