### ISSUE TITLE
Powershell Features removed from main AtlasOS build

### ISSUE THREAD

**Issue by 312ing** [Atlas-OS/Atlas#270]
**Describe the bug**
Many powershell commands don't work, the Microsoft store doesn't work and overall a lot of main windows features are gone! I guess I'm only bugged about power shell and Microsoft store because either way you gotta remove the bloat!

**To Reproduce**
1. Go to powershell
2. Type ''Get-AppXPackage *WindowsStore* -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"} " to re-install microsoft store
5. See error: "Get-AppXPackage: The 'Get-AppXPackage' command was found in the module 'Appx', but the module could not be loaded due to the following error: [Operation is not supported on this platform. (0x80131539)]
For more information, run 'Import-Module Appx'."

**Expected behavior**
For the powershell output to return: "Get-AppXPackage: The 'Get-AppXPackage' command was found in the module 'Appx', but the module could not be loaded due to the following error: [Operation is not supported on this platform. (0x80131539)]
For more information, run 'Import-Module Appx'."

**Desktop Info (please complete the following information):**
 - Intel i7
 - 20H2

**Comment by kryxzz** [comment]
Did you try running Import-Module Appx?

**Comment by 312ing** [comment]
It returns "Import-Module: Operation is not supported on this platform. (0x80131539)"

**Comment by JayXTQ** [comment]
Odd, do you receive this on the most recent version of atlas?

**Comment by SyrmGIT** [comment]
Microsoft Store is working on default Atlas, if you're using scripts that's your fault.

The new update releasing in the coming weeks will have a better store compatibility with a newer Windows build (22h2). Wait for that to happen, and we'll look back into this.
