### ISSUE TITLE
Oculus Desktop app not working

### ISSUE THREAD

**Issue by ririinsta** [Atlas-OS/Atlas#271]
**Describe the bug**
Oculus Desktop App doesn't launch.

**To Reproduce**
1. Install Oculus
2. Attempt to launch it

**Expected behavior**
When trying to launch the Oculus app it will simply say that it can not reach the Oculus service.

**Screenshots**
![image](https://user-images.githubusercontent.com/87190112/195461940-2aa6e7d8-b39c-47d9-9b21-0be60d4522be.png)

**Desktop Info (please complete the following information):**
 - CPU : AMD Ryzen 5 5600x
 - Drive Type: SSD
 - Version 20H2 Latest

**Additional context**
The Oculus VR Runtime service is running but the library service is not running. I have ran the Atlas Services reg file and it did not fix it. The log from the library service is below and the log from event view is below that. I have checked #24 and it did not help.

`
[Debug] [10/12/2022 6:41:34 PM] Starting up OVRLibraryService v1.16.0.0.
[Debug] [10/12/2022 6:41:34 PM] Starting up.
[Warning] [10/12/2022 6:41:35 PM] IPC connection attempt failed!
[Debug] [10/12/2022 6:41:35 PM] IPC thread running; waiting for Oaf to connect.
[Debug] [10/12/2022 6:41:35 PM] App libraries for this user: [CORE_DATA]
[Debug] [10/12/2022 6:41:35 PM] OVRLibraryService starting in service mode.  Arguments: [restart-service]
[Debug] [10/12/2022 6:41:35 PM] Creating NTFS transaction.
[Debug] [10/12/2022 6:41:35 PM] Waiting for service 'OVRService' to stop.
[Debug] [10/12/2022 6:41:35 PM] Service 'OVRService' is now Stopped.
[Debug] [10/12/2022 6:41:35 PM] Attempting to start service 'OVRService'.
[Debug] [10/12/2022 6:41:35 PM] Service 'OVRService' is now Running.
[Debug] [10/12/2022 6:41:35 PM] Committing changes.
[Debug] [10/12/2022 6:41:35 PM] Exiting with code 0 (Success).
`

event viewer below

`
The Oculus VR Library Service service terminated with the following service-specific error: 
There are no more files.
`

**Comment by kryxzz** [comment]
Did you even read the unsupported features?

**Comment by ririinsta** [comment]
Can you link them please?

**Comment by kryxzz** [comment]
https://github.com/Atlas-OS/Atlas/wiki/1.-FAQ#13-whats-removed-in-atlas-os

**Comment by ririinsta** [comment]
Very sorry I did not notice that it is not supported.
