### ISSUE TITLE
Display Setting and System Menu won't work !

### ISSUE THREAD

**Issue by cmoiisk** [Atlas-OS/Atlas#272]
Hi, i got an issue : 
- When i try to open display setting with (right click -> display setting) It won't work for no reason. So i tried to go on setting -> System also same issue.

![ezgif-3-143edf7936](https://user-images.githubusercontent.com/115771216/195765798-a0146abe-7199-445d-bcf7-086620b08e3c.gif)

**Comment by kryxzz** [comment]
Send C:/Windows/AtlasModules/logs/userScript.log

**Comment by SyrmGIT** [comment]
@cmoiisk ?

**Comment by JayXTQ** [comment]
@SyrmGIT
