### ISSUE TITLE
Astro Command Center not detecting the USB Input

### ISSUE THREAD

**Issue by ttv-scales** [Atlas-OS/Atlas#277]
# Not filling out this template will lead to the issue being closed

**Describe the bug**
After installing Atlas, Astro Command Center can no longer see the Mixamp Tr Pro plugged into the PC.

**To Reproduce**
1. Go to 'Astro Command Center'
2. Follow instructions for use: switch mixamp to pc, plug into a usb port
3. Command Center Views as "Please connect an astro gaming device or switch the connected device to PC mode."

**Expected behavior**
Command center will not see the mixamp even after unplugging/swapping console-pc input back and forth.

**Screenshots**

**Desktop Info (please complete the following information):**
 - CPU [AMD Ryzen 7 3800X]
 - System Drive Type [NVMe Samsung SSD 970]
 - Version [20H2 v0.5.2]

**Additional context**

**Comment by JayXTQ** [comment]
Are you still receiving this issue?
