### ISSUE TITLE
where is AtlasOS 21H2 (faceit edition) xml file for ntlite

### ISSUE THREAD

**Issue by ogmicco** [Atlas-OS/Atlas#278]
Is the xml file supposed to be missing from this repo?

**Comment by ogmicco** [comment]
?

**Comment by SyrmGIT** [comment]
There isn't one available. We'll keep this issue open until there is one, and notify you.

**Comment by ogmicco** [comment]
thanks :)

**Comment by Dystnine** [comment]
I couldn't find this either.

**Comment by SnowzNZ** [comment]
> I couldn't find this either.

can you read

**Comment by JayXTQ** [comment]
@SnowzNZ Don’t be rude please.
