### ISSUE TITLE
Low Resolution Splash screen

### ISSUE THREAD

**Issue by cyberbasty** [Atlas-OS/Atlas#280]
when i boot my computer, the windows 10 logo and the spinning dots are streched. But when it finishes booting and goes to login screen, the resolution is normal again.

**Comment by jamesbt365** [comment]
That is typically what happens when display drivers aren't loaded before desktop.

**Comment by cyberbasty** [comment]
how do i fix it ?

**Comment by kryxzz** [comment]
there's no fix, because it changes literally nothing

**Comment by kekkodance** [comment]
wrong. try installing your chipset drivers, updating your existing ones or install all drivers SDIO says aren't optimal.

**Comment by SyrmGIT** [comment]
Did you have this solved @cyberbasty

**Comment by JayXTQ** [comment]
I think thats a yes
