### ISSUE TITLE
Bluetooth stopped working out of no where

### ISSUE THREAD

**Issue by Nam3GHUB** [Atlas-OS/Atlas#282]
Hello! So I was using my PC and the Bluetooth just stopped working
I tried to turn it on but the switch was off, and then I tried uninstalling the device in device manager, but after I did that and restarted it said I didn't have Bluetooth entirely

I need Bluetooth, so I will greatly appreciate if you'll take the time out of your day and help me

Screenshots:
https://cdn.discordapp.com/attachments/1030222979700903956/1036322749439819786/unknown.png | Device not showing in device manager (because I deleted it)
https://cdn.discordapp.com/attachments/1030222979700903956/1036322801390465175/unknown.png | Wont let me connect to anything
https://cdn.discordapp.com/attachments/1030222979700903956/1036322899436507297/unknown.png | Saying I don't have bluetooth capabilities even though my PC supports it

**Comment by jamesbt365** [comment]
You need to reinstall the bluetooth driver for the device if you removed it.

**Comment by infernus4444** [comment]
Is it fixed now? 
I have the same problem any solutionss?

**Comment by JayXTQ** [comment]
Please reinstall drivers and reinstate the device in device manager

**Comment by Zensonaton** [comment]
I've had completely different issue, but, I've found the drivers from manufacturer of mine bluetooth adapter, installed them, and now I can connect to my bluetooth headphones.
If you do so, you probably would need to update drivers using SDIO.

**Comment by JayXTQ** [comment]
@Nam3GHUB did any of this work?

**Comment by infernus4444** [comment]
> @Nam3GHUB did any of this work?

I reinstalled windows 11 and updated it, then bluetooth started working.
In Atlas Os I tried installing drivers, but still bluetooth wasn't showing in the device manager.

**Comment by SyrmGIT** [comment]
I'm going to be closing this issue as we move onto a newer Windows version within the coming weeks, if it still persists; we will look into this issue for you! :)
