### ISSUE TITLE
Screencast

### ISSUE THREAD

**Issue by dan4ik605743** [Atlas-OS/Atlas#284]
Screencast not working on samsung led

**Comment by SyrmGIT** [comment]
Could you elaborate?

**Comment by JayXTQ** [comment]
@dan4ik605743 can you elaborate on your issue (sorry for the parrot)

**Comment by dan4ik605743** [comment]
> @dan4ik605743 can you elaborate on your issue (sorry for the parrot)

Connecting to a wireless screen, let's say to a TV, is not working. It appears to have been cut. I tried it on another windows, it works.
