### ISSUE TITLE
Lively wallpaper automatically closes..

### ISSUE THREAD

**Issue by Dev-Yash502** [Atlas-OS/Atlas#287]
**Lively wallpaper crashing **
When i downloaded it from play store from the following sreps it crashes automatically. I don't know how wether i used to import any live wallpaper it closes... 😬 

**To Reproduce**
1. Go to 'microsoft store'
2. Search and install 'lively wallpaper'
3. Open and import any of the live wallpaper.

**Expected behavior**
Kindly fix it how we make our laptop or pc looking cool without these stuffs..😞

**Screenshots**
If applicable, then reply me

**Desktop Info (Low - 
end pc):**
 - CPU [Intel dual core, ]
 - 2 gb ram , 500gb hdd
 - Version where problem occur [ 20H2 ]

**Additional context**

**Comment by uncognic** [comment]
1. This OS is made for performance, not for looks.
2. Use the freaking search feature in the discord server

**Comment by Dev-Yash502** [comment]
Any other methods

**Comment by uncognic** [comment]
I literally gave you a link to the solution
