### ISSUE TITLE
How to enable system restore?

### ISSUE THREAD

**Issue by saeedvir** [Atlas-OS/Atlas#288]
How to enable system restore(create restore point) in atlas os?1

**Comment by uncognic** [comment]
https://github.com/Atlas-OS/Atlas/wiki/1.-FAQ#13-whats-removed-in-atlas-os

**Comment by uncognic** [comment]
Why do people not read the freaking FAQ

**Comment by thaynos** [comment]
is it possible to add it back to our own windows? or is it permanently deleted?

**Comment by Xyueta** [comment]
permanently deleted

**Comment by JayXTQ** [comment]
rebuild atlas with it if you require it.
