### ISSUE TITLE
UltraUXThemePatacher not working

### ISSUE THREAD

**Issue by RealFravio** [Atlas-OS/Atlas#29]
Issue: There is a tool to patch windows to add custom themes.
Its having some error with atlas.

Link for software: https://mhoefs.eu/software_uxtheme.php?lang=en

![image](https://user-images.githubusercontent.com/76403719/118233067-4b5c9080-b446-11eb-9cca-c1c074939eb1.png)

**Comment by Zusier** [comment]
I will look into it! Should be a simple fix.

**Comment by Zusier** [comment]
Not sure if you're on an older version, UltraUXThemePatcher is working on the latest (0.4.1) and the future update.
