### ISSUE TITLE
Error when open a game bug

### ISSUE THREAD

**Issue by Samiring** [Atlas-OS/Atlas#290]
---------------------------
FiveM_b2699_GTAProcess.exe - Application Error
---------------------------
The instruction at 0x00007FF6C8483D4A referenced memory at 0x00000010F16BF259. The memory could not be written.

Click on OK to terminate the program
---------------------------
OK   
---------------------------

**Comment by JayXTQ** [comment]
Have you verified game files?

**Comment by PencilNavigator** [comment]
FiveM is a private server project that modifies the game "Grand Theft Auto 5" files. Not sure if it belongs to the "Cracked Software" session which atlas will not provide support.
https://github.com/Atlas-OS/Atlas/wiki/1.-FAQ#13-whats-removed-in-atlas-os

**Comment by JayXTQ** [comment]
FiveM requires you to have GTA V, it modifies the files iirc. It is a client modification that is seperated from GTA V so GTA V can run with or without FiveM

**Comment by JayXTQ** [comment]
@Samiring did verifying the game work?

**Comment by SyrmGIT** [comment]
Install vcredists.
