### ISSUE TITLE
can't install scoop 

### ISSUE THREAD

**Issue by ShadowIsNotTrash** [Atlas-OS/Atlas#296]
Whene running scoop install says Running the installer as administrator is disabled by default 
![IMG_20221119_023016258](https://user-images.githubusercontent.com/62360322/202820113-43db7e8b-19bc-4ea6-b7fb-0b28e4ebb435.jpg)

**Comment by ShadowIsNotTrash** [comment]
Fixed by using 
$path = $env:TEMP; $Installer = "chrome_installer.exe"; Invoke-WebRequest "http://dl.google.com/chrome/install/375.126/chrome_installer.exe" -OutFile $Path\$Installer; Start-Process -FilePath $Path\$Installer -Args "/silent /install" -Verb RunAs -Wait; Remove-Item $Path\$Installer
In the PowerShell Admin

**Comment by dw5** [comment]
also does the trick
`irm get.scoop.sh -outfile 'install.ps1'`
`iex "& {$(irm get.scoop.sh)} -RunAsAdmin"`

**Comment by thaynos** [comment]
is this gonna be added to the iso?

**Comment by Xyueta** [comment]
already fixed
