### ISSUE TITLE
Cant play Warzone

### ISSUE THREAD

**Issue by Creeper215ITA** [Atlas-OS/Atlas#297]
Hi, i have a problem. I am on AtlasOS 20H2 on ASUSTeK COMPUTER INC. VivoBook_ASUSLaptop X513EP_K513EP with
BIOS
Versione
X513EP.308
Data
27/07/2021
MOTHERBOARD
Produttore
ASUSTeK COMPUTER INC.
Modello
X513EP
Versione
1.0
SISTEMA OPERATIVO
Edizione
Microsoft Windows 10 Enterprise (64-bit)
Versione (Build)

I cant play Warzone, it says that i must to go in Windows 20H2 revision 789

**Comment by Lazylllama** [comment]
Try using AtlasOS 21H2 its got better compatibility.

**Comment by SyrmGIT** [comment]
Join our Discord (https://discord.com/invite/atlasos) and go to this message: https://discord.com/channels/795710270000332800/795724409808617513/1035548283734601758

Hopefully this helps :)
