### ISSUE TITLE
High Cpu Usage

### ISSUE THREAD

**Issue by ShadowIsNotTrash** [Atlas-OS/Atlas#298]
**Describe the bug**
High cpu usage every app use high cpu

**To Reproduce**
1. Open task manager

**Desktop Info (please complete the following information):**
 - CPU Intel Core i5-8250U @ 1.16GHz
 - System Drive Type HDD
 - Version [e.g. 20H2 v0.5.1]

**Comment by Alino001** [comment]
Try idle mode: Type in cmd (admin) this: powercfg -setacvalueindex scheme_current sub_processor 5d76a2ca-e8c0-402f-a133-2158492d58ad 0 then powercfg -setactive scheme_current.
Then restart your pc

**Comment by ShadowIsNotTrash** [comment]
Thx 
It lowered th CPU usage but sometimes it goes to 43% uaage

**Comment by Alino001** [comment]
np

**Comment by Sayzyexe** [comment]
![image](https://user-images.githubusercontent.com/118611160/202850887-bb516137-7089-43ac-8a5a-39715c4305d3.png)
for me it's not fixes please help

**Comment by Alino001** [comment]
You did it wrong you have to di the first command and then the secound one

**Comment by Alino001** [comment]
*do

**Comment by Sayzyexe** [comment]
what is the first and the second please

**Comment by Alino001** [comment]
First one: powercfg -setacvalueindex scheme_current sub_processor 5d76a2ca-e8c0-402f-a133-2158492d58ad 0 
Second one: powercfg -setactive scheme_current

Then restart

**Comment by Sayzyexe** [comment]
you are the goat

**Comment by Alino001** [comment]
ty, np

**Comment by BecomeNox** [comment]
Not working for me

**Comment by JayXTQ** [comment]
> Not working for me. 30% of my cpu use for no reason.

there will be a reason, we need more information though. like pics of task manager and such.
