### ISSUE TITLE
WHAT IS THE BEST DRIVER INTEL A short description of the feature

### ISSUE THREAD

**Issue by Sayzyexe** [Atlas-OS/Atlas#299]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. When I open [blank] it hangs/freezes

**Describe the solution you'd like**

**Describe alternatives you've considered**
If you’ve found a temporary fix, list it here.

**Additional context**

**Comment by zosgreed** [comment]
https://www.intel.com/content/www/us/en/support/detect.html
