### ISSUE TITLE
Publicly available brand kit

### ISSUE THREAD

**Issue by xenforq** [Atlas-OS/Atlas#3]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Please add some way for the public to access logomarks, icons, and logos in .svg and .png formats. This would definitely be helpful if it could be easily accessible for users wanting to make their own Atlas branded wallpapers, avatars, or whatever they wish to use to personalize their experience a bit more.

Atlas could make their brand kit accessible to the public via one of these platforms:
- Wiki (https://github.com/Atlas-OS/Atlas/wiki)
- Website (https://atlasos.net/)

Adding the brand kit download somewhere else, like the Discord or in a .md file hidden somewhere, is annoying for pretty much anyone—I doubt anyone would appreciate having it anywhere else.

**Describe alternatives you've considered**
Make it more obvious and clear, with proper instructions on how to get access to the logo and such. If you guys deem the logo design too private to be shared with others, please state that and make some application system instead of gaining access to a link hosted on some cloud storage platform somewhere containing all of these files.

**Additional context**
n/a

**Comment by SyrmGIT** [comment]
This will be implemented, thank you for your suggestion.
