### ISSUE TITLE
Some applications are unable to connect to their servers.

### ISSUE THREAD

**Issue by c0rvidz** [Atlas-OS/Atlas#302]
# Not filling out this template will lead to the issue being closed

**Describe the bug**
For example, the RSI (Robert's Space Industries) client and Opera GX installer are just completely unable to download or connect to their servers, and I really have no idea why.

**To Reproduce**
Download the RSI (Star Citizen) client and try to log in or download the Opera GX installer and try to install it.

**Expected behavior**
I expected it to properly connect.

**Desktop Info (please complete the following information):**
 - CPU Intel Core i7-7700HQ
 - 20H2 latest

**Comment by uncognic** [comment]
Try enabling Wifi in Atlas >> Config >> Wifi
Also why are you using Opera GX????

**Comment by SyrmGIT** [comment]
Some apps rely on the services that we disable in the WiFi disable script to know if you have a network connection. Re-enable WiFi and it should be fixed.
