### ISSUE TITLE
ftp mirror for the iso

### ISSUE THREAD

**Issue by Shanduur** [Atlas-OS/Atlas#303]
**Is your feature request related to a problem? Please describe.**
Not really. I want to be able to periodically grab latest ISO image, by convention I am doing that by using FTP.

**Describe the solution you'd like**
ISO images hosted using FTP/SFTP protocol.

**Describe alternatives you've considered**
Scrapping website to obtain ISO URL.

**Additional context**
N/A

**Comment by jamesbt365** [comment]
why not just wget it?

**Comment by Shanduur** [comment]
@jamesbt365 The use case is nothing special, I like having 3 most recent versions of OS I am using "Just in case". Easiest way to do that is syncing particular files from FTP - I can deterministically grab `cdimage.ubuntu.com:/cdimage/ubuntu-server/jammy/daily-live/current/jammy-live-server-arm64.iso`, add timestamp, and remove when it's older than 3 copies.

**Comment by SyrmGIT** [comment]
We already have torrents for the ISOs. Check the download channel in our Discord.
