### ISSUE TITLE
Missing network icon

### ISSUE THREAD

**Issue by krymzone** [Atlas-OS/Atlas#304]
The network icon is missing, but everything else works as normal, it also can't be activated from settings, since it's greyed out

**Desktop Info:**
 - CPU = Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz 
 - System Drive Type = SSD
 - Version [20H2 v0.5.2]

**Comment by krymzone** [comment]
Performing another fresh install seemed to fix it, no idea what happened

**Comment by Xyueta** [comment]
https://github.com/Atlas-OS/Atlas/commit/68973aa095ad9755b2ea77985c25cffeb7b17557
