### ISSUE TITLE
Minecraft Crashing all the time with or without mods

### ISSUE THREAD

**Issue by ShadowIsNotTrash** [Atlas-OS/Atlas#307]
Minecraft Crashing all the time

1. Go to 'Any minecraft launcher'
2. Click on 'lunch or start the game'
3. its open and loading then crashed

**Desktop Info (please complete the following information):**
 - CPU i5-8250 @ 1.6GHZ
 - System Drive Type HDD
 - Version [Atlas version 21H2]

**Comment by TheArkian** [comment]
Is this Bedrock or Java?

**Comment by ShadowIsNotTrash** [comment]
> Is this Bedrock or Java?

java

**Comment by ShadowIsNotTrash** [comment]
and everything just start to crash and lag

**Comment by uncognic** [comment]
bruh be patient

**Comment by jamesbt365** [comment]
The new minecraft java launcher is busted i think? Try the old one. Logs would also be useful, but i'm almost certain that this isn't an atlas problem and thus can be closed. 

If you want help faster you can use the [Discord server](https://discord.com/invite/atlasos).
