### ISSUE TITLE
[SUGGESTION] Open mods/optimization integration

### ISSUE THREAD

**Issue by forart** [Atlas-OS/Atlas#308]
Hi there, we're a small italian noprofit devoted to emerging/indipendent art(ist)s growth by spreading free/open tools/softwares.
(note: we're going to try Atlas in our AIO-PC that we use to remotely - LAN - control a streaming console in live shows)

We strongly suggest you to evaluate those interesting open projects (and hopefully establish some kind of collaboration with respective authors) to "evolve" Atlas even more:
- @valinet's [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher);

- @hellzerg's [Optimizer](https://github.com/hellzerg/optimizer);
- @SanGraphic's [QuickBoost](https://github.com/SanGraphic/QuickBoost)
- @Jisll's [Sadcoy](https://github.com/Jisll/Sadcoy)

Let us know if you're interested in more resources like these.

Hope that inspires !

**Comment by SyrmGIT** [comment]
All of these optimizations offered by these repos are already in Atlas.

Anything custom like a GUI for modifying Atlas can be created in-house, so there's no need for anything of the such. Thanks for the suggestion though.

**Comment by SyrmGIT** [comment]
All of these optimizations offered by these repos are already in Atlas.

Anything custom like a GUI for modifying Atlas can be created in-house, so there's no need for anything of the such. Thanks for the suggestion though.

**Comment by forart** [comment]
Thanks for the fast reply, anyway @valinet's [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher) is a really cool (and often updated) open tool for *any* Windows 1* install.

Thanks anyway for your attention.
