### ISSUE TITLE
install language pack report error

### ISSUE THREAD

**Issue by jarodvip** [Atlas-OS/Atlas#310]
The language pack cannot be installed online, and the installation of the offline language pack also fails. Can I use other languages ​​besides English? Can it be fixed?

**Comment by SyrmGIT** [comment]
t's a Windows bug with 20h2.

https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/language-packs-known-issue.

Try some of the fixes in the docs, or try the guide from ReviOS (the U version) https://www.revi.cc/revios/workspace/lang#h.ry7gga391br1

And if you have the time, reinstall and the first thing you do should be installing languages/keyboard layout.

**Comment by jarodvip** [comment]
ok,thank you sir

**Comment by jarodvip** [comment]
Hi

I struggled installing a language module on windows 10 enterprise connected to a domain getting error 0x80073D01
and changing the below registry which is related to update policies solved the problem ..

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate

DoNotConnectToWindowsUpdateInternetLocations = 0

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU

UseWUServer = 0

Hope this will be of any help

**Comment by jarodvip** [comment]
> t's a Windows bug with 20h2.
> 
> https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/language-packs-known-issue.
> 
> Try some of the fixes in the docs, or try the guide from ReviOS (the U version) https://www.revi.cc/revios/workspace/lang#h.ry7gga391br1
> 
> And if you have the time, reinstall and the first thing you do should be installing languages/keyboard layout.

Hi

I struggled installing a language module on windows 10 enterprise connected to a domain getting error 0x80073D01
and changing the below registry which is related to update policies solved the problem ..

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate

DoNotConnectToWindowsUpdateInternetLocations = 0

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU

UseWUServer = 0

Hope this will be of any help
