### ISSUE TITLE
Can't toggle system proxy

### ISSUE THREAD

**Issue by WindLeaf233** [Atlas-OS/Atlas#311]
**Describe the bug**
As the title, I can't turn on the proxy. The proxy switch keeps turns off automatically.
I tested `Auto detect` and `Manually` modes, both didn't work.
And I've tried to set the proxy in `Internet Settings` (seems to be the IE settings), still didn't work.

BTW, I use [v2rayN](https://github.com/2dust/v2rayN) as a VPN client, didn't work same as above.

**To Reproduce**
1. Go to Settings
2. Click on Network Settings
3. Scroll down to Proxy Settings
4. Set Proxy to `Auto detect`, click the `Save` button
5. Proxy doesn't work, when I close the Settings window and reopen it, the proxy turns off automatically

**Expected behavior**
I can set the proxy normally.

**Screenshots**
I'm currently using another os, if necessary I will record a video.

**Desktop Info (please complete the following information):**
 - CPU: AMD Athlon(TM) X4 740 Quad Core Processor (ik it sucks)
 - System Drive Type: (idk what is this)
 - Version: 20H2 v0.5.1

**Additional context**
(My English's not good, if there're some grammar issues please ignore)

**Comment by SyrmGIT** [comment]
Did you enable VPNs using the batch file in the folder?

**Comment by WindLeaf233** [comment]
> Did you enable VPNs using the batch file in the folder?

Yes, I tried both enabling and disabling VPNs

**Comment by WindLeaf233** [comment]
> Did you enable VPNs using the batch file in the folder?

Let me reinstall the system, I guess this caused by something like device

**Comment by WindLeaf233** [comment]
@SyrmGIT ok works, this may be caused by device not installing correctly

**Comment by Originalimoc** [comment]
I ran the `C:\Windows\AtlasDesktop\8. Troubleshooting\Network\Reset Network to Windows Default.cmd`(it will delete all your WiFi SSID settings so save that first..) then it works. Something is indeed breaking system proxy. Maybe DMACoalescing?
