### ISSUE TITLE
Cannot display new users

### ISSUE THREAD

**Issue by CodeCubeNeo** [Atlas-OS/Atlas#313]
When creating a new user it is visible in the users  managment, but not in the logon screen or the "switch user" in the windows key menu. This is latest atlas 20h2 faceit.

**Comment by JayXTQ** [comment]
Do you mean 21H2 FACEIT?

**Comment by CodeCubeNeo** [comment]
yes

**Comment by JayXTQ** [comment]
Did you enable UAC? I know that does stuff with User Accounts, just no clue if it would bring up the option to log in with other accounts

**Comment by rogergithubbing** [comment]
I have atlas 20h2 and it happens to me too, without enabling UAC. The only way to show other users in the logon screen is to login the first time the pc boots, and then logout again; Is there any fix ?

**Comment by SyrmGIT** [comment]
I'm going to be closing this issue as we move onto a newer Windows version within the coming weeks, if it still persists; we will look into this issue for you! :)
