### ISSUE TITLE
 localization suggestions

### ISSUE THREAD

**Issue by jarodvip** [Atlas-OS/Atlas#316]
HI.
Tried to install the language, and it installed successfully.
After the system restarts, the default English status will be restored. 
Hope to add multilingual localization.

**Comment by CodeCubeNeo** [comment]
https://github.com/Atlas-OS/Atlas/wiki/1.-FAQ#13-whats-removed-in-atlas-os - read under unsuported software, first entry.

**Comment by jarodvip** [comment]
Alternate Languages [Windows Bug](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/language-packs-known-issue).Can it be fixed?

**Comment by SyrmGIT** [comment]
It's a Windows bug, so not unless we change the Windows version Atlas is built on. You should be able to use 21h2 with the language switch, if you don't wish to follow the steps on our Wiki for 20h2.

**Comment by jarodvip** [comment]
I followed the steps in the wiki and successfully installed the required language pack, but it will roll back to the default English state after restarting
