### ISSUE TITLE
onedrive not working

### ISSUE THREAD

**Issue by zhaoshuai23** [Atlas-OS/Atlas#317]
After the onedrive software package is installed, the icon cannot be clicked to run. I don’t know why, or how to configure it to make it run normally?

**Comment by RezaFeng** [comment]
I have this problem as well, you may try the following step:
1. win+r, run the regedit
2. find the path HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\OneDrive
![image](https://user-images.githubusercontent.com/18794642/204080368-a5d97e39-a5c0-4e2b-952e-7485bc7de8ed.png)
3. double click the  DisableFileSyncNGSC
4. change the value to 0
5. restart your computer and run the onedrive

**Comment by zhaoshuai23** [comment]
> I have this problem as well, you may try the following step:
> 
> 1. win+r, run the regedit
> 2. find the path HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\OneDrive
>    ![image](https://user-images.githubusercontent.com/18794642/204080368-a5d97e39-a5c0-4e2b-952e-7485bc7de8ed.png)
> 3. double click the  DisableFileSyncNGSC
> 4. change the value to 0
> 5. restart your computer and run the onedrive

Thank you for your reply, I have switched to the official system.
