### ISSUE TITLE
[REQ] In-system releases notification

### ISSUE THREAD

**Issue by forart** [Atlas-OS/Atlas#318]
Hi everyone,
since Atlas is open source, it would be very interesting to enable system notification for GH releases.

Of course it would be cool to let users customize own monitored gits, but in the 1st (experimental) phase only [Atlas ones](https://github.com/Atlas-OS/atlas-releases/releases/) should be notified.

Git-relases notifications for @abbodi1406's [VisualCppRedist AIO](https://github.com/abbodi1406/vcredist) would be extremely useful, for example.

EDIT: something like @manosim's [Gitify](https://www.gitify.io/) but limited to releases only and without the need of GH account

Hope that inspires.

**Comment by uncognic** [comment]
That would add bloat, as we would need to add a separate program that fetches the releases.

**Comment by forart** [comment]
> That would add bloat, as we would need to add a separate program that fetches the releases.
>
Well, there are some very light apps/scripts (such as @ms7m's [notify.py](https://github.com/ms7m/notify-py) or @YuriyLisovskiy's [pynotifier](https://github.com/YuriyLisovskiy/pynotifier)) that can be adapted/stripped down - even more - if needed.

However we personally prefer to sacrifice (very few) computing - and network - resources instead of all the time that would be needed to check new releases via web/browser.

Anyway the activation of such a feature should be at user's discretion, of course...

**Comment by SyrmGIT** [comment]
I like the idea @forart, however the implementation of this into Atlas doesn't really make sense from a debloated and private standpoint. Although at the discretion of the user, we would prefer to go down the route of Discord announcements/standard GitHub notifications.

Hope you understand, else this would be awesome.
