### ISSUE TITLE
Oculus Air Link

### ISSUE THREAD

**Issue by BumiMandias** [Atlas-OS/Atlas#32]
Oculus Air Link seems to not be working, Don't have bluetooth. Dunno if that's the issue, Can enable it in oculus quest but when I go to my oculus app and switch air link on it turns back off.

**Comment by BumiMandias** [comment]
Last tried 2 weeks ago ^ It actually closes my oculus software

**Comment by Zusier** [comment]
Please refer to #24 I can’t really troubleshoot it due to the fact I don't have an oculus quest.

>  Don't have bluetooth.

Can you elaborate? Does it work fine on default windows? Have you tried the bluetooth enable script?

**Comment by BumiMandias** [comment]
I don't have bluetooth itself.. No chip or anything, I don't know. I've been using atlas since before airlink was a thing.

**Comment by BumiMandias** [comment]
Dunno if bluetooth is a requirement for airlink

**Comment by Zusier** [comment]
It connects over wi-fi apparently, perhaps you disabled that?

**Comment by BumiMandias** [comment]
Ehh no never disabled wifi

**Comment by BumiMandias** [comment]
![image](https://user-images.githubusercontent.com/70164601/119872050-0d08ac00-bef1-11eb-9f90-1496b51fb675.png)
Tick this and it crashes my oculus software

**Comment by Zusier** [comment]
Is there any logs you can find and send here?

https://developer.oculus.com/distribute/log-troubleshooting

**Comment by BumiMandias** [comment]
I'm so confused and I have so many files that it just gave me, where should I go?

**Comment by BumiMandias** [comment]
Want me to send it to discord dms so it doesn't leak my ip?

**Comment by Zusier** [comment]
I doubt it includes your ip, but if you feel safer zipping them and DMing me. Go ahead 👍 (you have to add me as a friend)

**Comment by BumiMandias** [comment]
already have my user is Mr.Sniffer

**Comment by Ahmadplayz** [comment]
for un nonreason (MSI Utility V3 or MSI mode utility ) is not enabled or working by default. how can I use it?

**Comment by Zusier** [comment]
Closing, refer to #24
