### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by alphawolfz98** [Atlas-OS/Atlas#320]
I need help with some installation issue 

https://user-images.githubusercontent.com/104478766/204086327-3edc03fd-b6d1-4db7-9a4b-cc120111f34f.mp4

**Comment by SyrmGIT** [comment]
Honestly not sure what would be causing this. What is this for exactly, is it MSI related? Did a Google search, :)

**Comment by alphawolfz98** [comment]
Yes this is a msi osd software

**Comment by SyrmGIT** [comment]
Closing this issue as we're updating to a new version of Windows for Atlas in the coming weeks with many fixes. Not sure what is causing this issue.

**Comment by alphawolfz98** [comment]
It's alright, thanks for your assistance anyways🙂
