### ISSUE TITLE
Re-enable emmc support so it runs on 64Gb steam deck 

### ISSUE THREAD

**Issue by ArrowU** [Atlas-OS/Atlas#322]
Hello all,

I would like to install AtlasOS on the 64Gb Steam Deck model, which uses EMMC storage.

Due to the nature of the Steam Deck, I think AtlasOS would be a great fit to get running on it.

**Comment by jamesbt365** [comment]
afaik windows doesn't really have emmc support at all. You have to load the driver on install.

**Comment by ArrowU** [comment]
I’m far from an expert, but the reason I mentioned it it because it is listed as one of the items on the “What has been removed”-list:
https://github.com/Atlas-OS/Atlas/wiki/1.-FAQ#13-whats-removed-in-atlas-os

**Comment by SyrmGIT** [comment]
We will not be adding back eMMC support, please look elsewhere for this support in the OS community.

**Comment by AndySkaura** [comment]
Upgrade to a large-capacity ssd, emmc is outdated：）

**Comment by ArrowU** [comment]
It’s not outdated when it’s implemented and well-suited for a revolutionary and well-received gaming handheld you tool. :)

anyways, Tiny10 works great. 

To add to that, my request was already answered so I’m not sure what you’re here for. Obnoxious kid.
