### ISSUE TITLE
Call Of Duty Modern Warfare 2 Warzone 2.0 Crash

### ISSUE THREAD

**Issue by bennytrt** [Atlas-OS/Atlas#323]
**Expected behavior**
Revision error with atlas when debugged and a undescribable error when normally launcher from steam

**Screenshots**
https://cdn.discordapp.com/attachments/934164417774518333/1046480823580373055/Screenshot_57.png
https://cdn.discordapp.com/attachments/934164417774518333/1046480823983018024/Screenshot_58.png

**Desktop Info (please complete the following information):**
 - CPU [intel core i5-3570K ]
 -256gb kingston ssd
 - Version [e.g. 20H2 v0.5.1]

**Additional context**
it only does this with warzone 2.0/mw2 idk why

**Comment by Alino001** [comment]
https://discord.com/channels/795710270000332800/1045395839759175850/1045395839759175850
