### ISSUE TITLE
Fortnite Fps stuttering

### ISSUE THREAD

**Issue by Ghastifyy** [Atlas-OS/Atlas#324]
I open the fortnite and after a while, the game starts stuttering until I restart the game. 

1.Open fortnite
2.Play the game
3.Might occur

Desktop Info (please complete the following information):

i5-750 @2.81ghz
Gt 710 2gb gddr5

[Logs.zip](https://github.com/Atlas-OS/Atlas/files/10099441/Logs.zip)

Samsung 860 evo

20H2
Additional context: I use stretch res and normally run 120fps no fps issues.

**Comment by SyrmGIT** [comment]
This isn't an Atlas specific issue. Make sure you are using your correct GPU when playing.

**Comment by Ghastifyy** [comment]
> This isn't an Atlas specific issue. Make sure you are using your correct GPU when playing. 

I only have 1 gpu though. Could it be a driver issue?

**Comment by SyrmGIT** [comment]
Maybe, did you try testing it before making an issue?

**Comment by Ghastifyy** [comment]
> Maybe, did you try testing it before making an issue?

It's not a driver issue. I've tried the last 3

**Comment by pepepaco** [comment]
try using lowest setting without disabling vsync, then in nvidia control panel power management mode chose maximun performance. then in windows settings inside disk properties Disable Disk Write Caching Policy. if you changed something in the bios make sure to set it back to with it was before, specially the disk AHCI settings, check if this improve anything.

**Comment by Ghastifyy** [comment]
> try using lowest setting without disabling vsync, then in nvidia control panel power management mode chose maximun performance. then in windows settings inside disk properties Disable Disk Write Caching Policy. if you changed something in the bios make sure to set it back to with it was before, specially the disk AHCI settings, check if this improve anything.
> 
> 

I already do that

**Comment by PencilNavigator** [comment]
try the original system instead, see if it fix the issue.

**Comment by Ghastifyy** [comment]
> try the original system instead, see if it fix the issue.

normal windows 10 does not have this issue. (latest windows 10 version)

**Comment by SyrmGIT** [comment]
> > try the original system instead, see if it fix the issue.
> 
> normal windows 10 does not have this issue. (latest windows 10 version)

Unfortunately, with no one else experiencing the same issue. I'm going to have to close this.

Specific performance issues in certain games boil down to hardware issues, or end-user problems (e.g. tweaking Atlas beyond it's stock tweaks)
