### ISSUE TITLE
First time boot not showing up image on monitor 

### ISSUE THREAD

**Issue by frafe100** [Atlas-OS/Atlas#326]
At the first boot of my pc the monitor doesnt show image and give "no singnal" text, then i shutdown and boot again and it works.
I think the first boot its like a hibernation mode or something similar.

1. Boot for the first time the PC after installing the AtlasOS

 - CPU : intel i5-9400f / GPU: Nvidia gtx 1660 
 - System Drive Type : SSD
 - Version AtlasOS 21h2 faceit version

**Comment by uncognic** [comment]
If it is broken, we would know, and why did you make an issue when it worked?

**Comment by frafe100** [comment]
because its a bug and not common to boot 2 times to start the pc

**Comment by uncognic** [comment]
No one else got this issue

**Comment by TheArkian** [comment]
try plugging the hdmi to the motherboard, download gpu drivers and plug back into gpu

**Comment by uncognic** [comment]
He already said that it works now...

**Comment by TheArkian** [comment]
it's still a solution if it repeats for someone else though...

**Comment by frafe100** [comment]
its happends to me in the past when i test ggOS but idk, like its working right but takes 2 boots to work...

**Comment by SyrmGIT** [comment]
Not an Atlas issue.
