### ISSUE TITLE
Unable to Change display resolution 

### ISSUE THREAD

**Issue by Rivennighthaunt** [Atlas-OS/Atlas#329]
I'm unable to change my resolution and the option is now greyed out an unselectable. Any help would be appreciated!

**Comment by uncognic** [comment]
Did you install GPU drivers?

**Comment by jamesbt365** [comment]
you require gpu drivers. You need to install them off the respective website for whatever gpu you have.

**Comment by SyrmGIT** [comment]
This is not an Atlas issue, please make sure you have your graphics drivers installed.
