### ISSUE TITLE
Discord Issue

### ISSUE THREAD

**Issue by BumiNetwork** [Atlas-OS/Atlas#33]
Removed from the AtlasOS Discord however no reason? Just woke up and was banned and it won't let me rejoin, If someone could unban my account Sniffer#5581 that would be great.

**Comment by Zusier** [comment]
Hmm, says the ban reason is "Flooding chat." Do you recall that?

**Comment by BumiMandias** [comment]
I don't recall that

**Comment by Js0nGIT** [comment]
pretty sure you spammed . or "`" which you said was by accident

**Comment by Zusier** [comment]
Unbanned.

**Comment by BumiMandias** [comment]
Thanks
