### ISSUE TITLE
msconfig problem

### ISSUE THREAD

**Issue by omaraboalnor** [Atlas-OS/Atlas#330]
msconfig wont open and give this message
windows cannot find msconfig make sure you typed the name correctly

**Comment by SyrmGIT** [comment]
This isn't a bug. Msconfig is removed.

**Comment by Icey67** [comment]
why is msconfig removed though?

**Comment by Xyueta** [comment]
It will be reverted/not removed in the upcoming release - 22H2 v0.1.

**Comment by Icey67** [comment]
alright thanks for info
