### ISSUE TITLE
Adding Chinese Translation for REARME.md and wiki

### ISSUE THREAD

**Issue by PencilNavigator** [Atlas-OS/Atlas#331]
**Is your feature request related to a problem? Please describe.**
AtlasOS went pretty viral on some popular forums in china, so there will probably be more chinese users. Adding a Chinese translation for README.md and wiki will be great.

**Describe the solution you'd like**
Adding a Chinese translation README.md and wiki

**Describe alternatives you've considered**
if this is consider needed i can do the translation.

**Additional context**
nah

**Comment by 0bo** [comment]
I'd like to help too, let's make fork then 😄

**Comment by PencilNavigator** [comment]
a pull request regarding this is open.
https://github.com/Atlas-OS/Atlas/pull/336

**Comment by SyrmGIT** [comment]
Merged, thank you both :)
