### ISSUE TITLE
cannot login to microsoft account in settings

### ISSUE THREAD

**Issue by 300BMD** [Atlas-OS/Atlas#335]
Hello I cannot login to my Microsoft account to verify my windows key
![Picture1](https://user-images.githubusercontent.com/119628348/205151277-95f6f7d6-96ef-4b33-bef7-d9a13d1b3a32.png)

**Comment by uncognic** [comment]
You can't login with MS, you have to add the key separately

**Comment by 300BMD** [comment]
> You can't login with MS, you have to add the key separately

is there anyway to use the product key linked to my account digitally or do I need to buy a new product key?

**Comment by uncognic** [comment]
Unfortunately you do have to buy another one.

**Comment by PencilNavigator** [comment]
> > You can't login with MS, you have to add the key separately
> 
> is there anyway to use the product key linked to my account digitally or do I need to buy a new product key?

try contact microsoft support, see if they can provide you the key.
