### ISSUE TITLE
ARP.EXE - System Error

### ISSUE THREAD

**Issue by mysteriouster2018** [Atlas-OS/Atlas#34]
I keep trying to fix my vs code but every time i compile using my module, I get an error that says, the code execution cannot proceed because snmapapi.dll was not found. Even though i installed the dll that was missing to System32

![image](https://user-images.githubusercontent.com/76492914/124541825-13832100-ddd7-11eb-92f1-575104a1b02d.png)

**Comment by BumiNetwork** [comment]
Did you restart the computer..?

**Comment by BumiNetwork** [comment]
That should fix it if you correctly installed the DLL, It must just not know its in there yet because most of the time if you like y'know put a mod into a game you have to restart it for it to popup or work..

**Comment by celphogeek** [comment]
> That should fix it if you correctly installed the DLL, It must just not know its in there yet because most of the time if you like y'know put a mod into a game you have to restart it for it to popup or work..

I had the same issue, I install the DLL but even with DLL cause another issue. Maybe is a feature removed in the process of creation of the ISO.

I'm using another ISO now and is working fine now, the program that requires the same dll is Advanced Port Scanner

**Comment by Zusier** [comment]
This is indeed due to the feature removal of SNMP, it will be added back in the next update.

**Comment by Zusier** [comment]
Fixed in v0.5, closing.
