### ISSUE TITLE
Atlas on ARM Version for Apple Silicon VM

### ISSUE THREAD

**Issue by anyuzu99** [Atlas-OS/Atlas#342]
people choose to buy macbook because of its macos environment and consistent battery life, while they also want to play some games sometimes. but most game runs on windows, and steam's proton isn't available on macos. 

that's where windows on arm comes in. while windows 11 on arm is much more complicated than windows 10 and even atlasos.

i wish there could be a atlas on arm version which allow mac users to run windws games much faster on their macbooks.

**Comment by qwerzl** [comment]
Also looking forward to it!

**Comment by anyuzu99** [comment]
as [windows blog](https://blogs.windows.com/windows-insider/2020/12/10/introducing-x64-emulation-in-preview-for-windows-10-on-arm-pcs-to-the-windows-insider-program/) says, only windows 11 support x64 emulation on arm.

the cleanup method for windows 11 on x64 may also be available for arm64. so we may just need to wait for atlas team to port to windows 11?

**Comment by sohaha** [comment]
The same expectation!

**Comment by uncognic** [comment]
Also, you shouldn't buy a Mac if you want to play games on it

**Comment by SyrmGIT** [comment]
We won't be creating an ARM distribution of Atlas anytime soon, if not at all. Sorry.

**Comment by vaaski** [comment]
The documentation [specifically mentions ARM now](https://docs.atlasos.net/getting-started/installation/), I guess it should work with W11

**Comment by JayXTQ** [comment]
Yes, ARM64 Windows 11 works on Atlas now

**Comment by vaaski** [comment]
Just make sure that if you download from [uupdump.net](https://uupdump.net) you don't have `Microsoft.SecHealthUI_8wekyb3d8bbwe` uncommented in your `CustomApplsList.txt` inside the uupdump package. That will disable Windows Security and prevent atlas from installing.
