### ISSUE TITLE
Godot_v4.0 Application Error - The memory could not be written.

### ISSUE THREAD

**Issue by nturton22** [Atlas-OS/Atlas#343]
# Godot_v4.0 Application Error - The memory could not be written.

Upon opening a brand-new project in both Godot 4.0 beta 6 and beta 7, the project starts to open, but after a short time it comes up with a memory error.

**To reproduce**

1. Download Godot.
2. Unpack and run.
3. Create new project and open.

**Expected behavior**

Project should open (I have tested Godot 3.5.1 and created a brand-new project and that opens the project just fine).

**Screenshots**
![Error](https://user-images.githubusercontent.com/111663107/205438298-3c136474-bf80-4ee0-8c1a-a69fbb821f61.jpg)

**Desktop Info (please complete the following information):**

- CPU Intel Core i3-7100U
- 16GB RAM
- SSD hard drive
- Version: Atlas OS 21H2

**Comment by JayXTQ** [comment]
I have found this, it isn't specifically about Godot but hopefully it can help in some way! https://answers.microsoft.com/en-us/windows/forum/all/explorerexe-error-the-instruction-0x00000000/90fcabb4-f947-4331-9836-e900d65e48fa

**Comment by SyrmGIT** [comment]
Not an Atlas issue. Check to see if you have all vcredists installed.

**Comment by AaronW-BE** [comment]
> Not an Atlas issue. Check to see if you have all vcredists installed.

Same with my problem and vcredists is installed.
