### ISSUE TITLE
Custom Themes

### ISSUE THREAD

**Issue by ShadowIsNotTrash** [Atlas-OS/Atlas#345]
i tryed installing a custom theme but the explorer and the apps are not applied with the theme

**To reproduce**

1. Go to 'settings'
2. Click on 'Personalization'
3. Scroll down to 'Themes'
4. Click on Custom Theme
5. Dosen't work

- CPU Intel i5-8250U 1.60Ghz
- System Drive Type HDD
- Version 20H2

**Comment by Alino001** [comment]
Put the file here:[USERNAME]\AppData\Local\Microsoft\Windows\Themes

**Comment by ShadowIsNotTrash** [comment]
> Put the file here:[USERNAME]\AppData\Local\Microsoft\Windows\Themes

still not working

**Comment by ShadowIsNotTrash** [comment]
> Which theme are you using?

https://www.youtube.com/watch?v=To1AXc9ESwU&t=186s

**Comment by Alino001** [comment]
The theme is in a zip

**Comment by ShadowIsNotTrash** [comment]
> The theme is in a zip

yes

**Comment by Alino001** [comment]
Did you extract it

**Comment by ShadowIsNotTrash** [comment]
> 

but i extracted it

**Comment by Alino001** [comment]
Ah, double click on the theme

**Comment by Alino001** [comment]
Did you go to settings and enable it?

**Comment by Alino001** [comment]
*after you putted the file in the directory

**Comment by ShadowIsNotTrash** [comment]
> *after you putted the file in the directory

yes

**Comment by Alino001** [comment]
Did you put the extracked folder directly in the directory

**Comment by ShadowIsNotTrash** [comment]
> Did you put the extracked folder directly in the directory

i put the things inside the extracted folder in the directory

**Comment by Alino001** [comment]
Ok

**Comment by ShadowIsNotTrash** [comment]
![image](https://user-images.githubusercontent.com/62360322/205442277-504f48f0-7d49-4819-958f-fa5bf8ccd979.png)

**Comment by Alino001** [comment]
https://mhoefs.eu/software_uxtheme.php?lang=en
install this and try again

**Comment by ShadowIsNotTrash** [comment]
> https://mhoefs.eu/software_uxtheme.php?lang=en install this and try again

already tryed it

**Comment by ShadowIsNotTrash** [comment]
![image](https://user-images.githubusercontent.com/62360322/205442409-368094d2-84b0-4a9f-87b1-40c3d4e58e19.png)

**Comment by Alino001** [comment]
![787F5741-8E5F-4ECD-A24C-8CFE9792117E](https://user-images.githubusercontent.com/118076662/205442452-6b4e197f-f58d-4bba-8bec-c0b16a5b7a5d.jpeg)

**Comment by ShadowIsNotTrash** [comment]
> try this

ok

**Comment by ShadowIsNotTrash** [comment]
> try this

can you give me the link of the website

**Comment by Alino001** [comment]
https://github.com/namazso/SecureUxTheme

**Comment by ShadowIsNotTrash** [comment]
> https://github.com/namazso/SecureUxTheme

sorry but it was in the video and i already installed it how the video says 
it can be an error in the video

**Comment by Alino001** [comment]
then dont do that step

**Comment by ShadowIsNotTrash** [comment]
> then dont do that step

reinstalled it without the tweaks but still nothing

**Comment by Alino001** [comment]
Then idk, ask on the discord server

**Comment by Alino001** [comment]
https://discord.gg/atlasos

**Comment by SyrmGIT** [comment]
> ![787F5741-8E5F-4ECD-A24C-8CFE9792117E](https://user-images.githubusercontent.com/118076662/205442452-6b4e197f-f58d-4bba-8bec-c0b16a5b7a5d.jpeg)
> 

Following this will fix your issue. Please make sure you follow the steps correctly @ShadowIsNotTrash
