### ISSUE TITLE
Battery gone

### ISSUE THREAD

**Issue by Ludummy** [Atlas-OS/Atlas#349]
I installed it on my laptop, then I found No battery in task bar , No batteries tap in drivers manager …. (My battery is ok cuz I checked bios )
Is it a bug or you guys deleted battery from the system?

**Comment by JayXTQ** [comment]
My laptop is showing battery on Atlas 20H2. Check your drivers

**Comment by dumbuz** [comment]
My laptop is also showing battery on Atlas 21H2 Faceit.
What laptop do you have?

**Comment by uncognic** [comment]
settings >> taskbar settings >> enable or disable system icons >> check battery

**Comment by Ludummy** [comment]
Asus vivobook E203MA

**Comment by Ludummy** [comment]
> My laptop is also showing battery on Atlas 21H2 Faceit.
> What laptop do you have?

Asus vivobook E203MA

**Comment by Ludummy** [comment]
> settings >> taskbar settings >> enable or disable system icons >> check battery

It doesn’t even have a battery icon

**Comment by uncognic** [comment]
You have to enable the setting for it to show

**Comment by Ludummy** [comment]
I try 20H2 now it’s ok showing batteries
