### ISSUE TITLE
Recent documents in office disabled by administrator

### ISSUE THREAD

**Issue by dumbuz** [Atlas-OS/Atlas#350]
**Describe the bug**
The recent documents list in all MS Office programs is showing that it is 'disabled by your administrator' and not functioning as intended.

**To reproduce**
1. Install Office
2. Open any Office program (Word, Excel, Powerpoint, etc.)
3. Look at the recent documents in Home, it will say that it's disabled by your administrator

**Expected behavior**
The recent documents panel will show your recently opened documents, or it will say that you have not opened any documents recently

**Screenshots**
![image](https://user-images.githubusercontent.com/44739965/205466707-14d65d68-24ce-465f-b9e7-4cb0b9abf37c.png)

**Desktop Info (please complete the following information):**
**Main PC having this issue**
AMD Ryzen 5 2600 (6c/12t) | M.2 512 GB NVME SSD | Atlas 21H2 v0.5.2
![image](https://user-images.githubusercontent.com/44739965/205466918-d3c90773-e868-494d-bac5-0acfd0ed5b55.png)

**Laptop having this issue**
Intel Pentium Silver N5000 (4c/4t) | M.2 128 GB SATA SSD | Atlas 21H2 v0.5.2
![image](https://user-images.githubusercontent.com/44739965/205467067-a3e546e1-a118-4252-886b-8a3007b5e749.png)

**_Cleanly installed VM having this issue_**
AMD Ryzen 5 2600 (2 virtual cores/thread) | Virtualized M.2 128 GB ssd | Atlas 21H2 v0.5.2
![image](https://user-images.githubusercontent.com/44739965/205467132-4d90ab59-fe20-4120-9196-dba8de804edc.png)

**Additional context**
I've tried seaching through Group Policy to see if there are any things relating to Office, and I couldn't find anything.
I have enabled Quick Access through the provided registry tweak on all three of these systems, restarted them, and then checked for the issue again and it is still present.

**Comment by dumbuz** [comment]
Btw this issue doesn't happen on my cleanly installed Windows VM.

Sorry for forgetting the first bit of info in the bug report template but yeah, the recent documents aren't showing up in any office program stating that the administrator disabled the recents list

**Comment by Alino001** [comment]
Use LibreOffice

**Comment by Alino001** [comment]
M$ Office is shit

**Comment by dumbuz** [comment]
> Use LibreOffice

Using an entirely different office suite is not a good workaround nor a fix for this problem. Please write useful comments

**Comment by JayXTQ** [comment]
https://answers.microsoft.com/en-us/msoffice/forum/all/your-administrator-has-turned-off-the-recent/dc28318b-d747-4ddf-84a7-916b7b0130d7
Hopefully this helps in some way!

**Comment by SyrmGIT** [comment]
Hopefully this will be fixed in the new version which will be out soon, sorry for the issues. If you update and the issue still persists, we will investigate it further.

**Comment by Demon-tk** [comment]
Currently running Atlas release 4.0 and this issue is still present.  

![image](https://github.com/Atlas-OS/Atlas/assets/8584243/d8bf1b98-8b23-4557-9406-e6e57b06d359)

**Comment by he3als** [comment]
https://docs.atlasos.net/getting-started/post-installation/atlas-folder/interface-tweaks/#unlock-recent-items
