### ISSUE TITLE
RDP service

### ISSUE THREAD

**Issue by tristonpink** [Atlas-OS/Atlas#356]
I want remote desktop service , what should I do ?

**Comment by SyrmGIT** [comment]
The RDP Client is included, if you want to make your machine into a server then you cannot use Atlas. Consider other options, or purchase a NTLite license and configure Atlas to your liking.

**Comment by JayXTQ** [comment]
I believe the same is applied here, just not the NTLite part.

**Comment by Xyueta** [comment]
It is working.

**Comment by JayXTQ** [comment]
> It is working.

The ability to make your machine into a server too?
