### ISSUE TITLE
Windows Ink Workspace

### ISSUE THREAD

**Issue by 300BMD** [Atlas-OS/Atlas#369]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

Windows Ink Workspace no longer works. used to be able to right click the taskbar and enable it but it is blacked out and the shortcut windows key+ shift+ s will make it appear but the clipped area is not saved to clipboard

### Steps to reproduce (if applicable add screenshots)

1. Press windows Key+ shift+ s 
2. can select an area to screenshot
3. drag cursor to create a box which is the size of the screenshot

### Expected behavior

Screenshot is supposed to be added to the clipboard

### Actual behavior (if applicable add screenshots)

there is nothing saved to clipboard

### Atlas Version (1803/20H2/21H2)

21H2

### Desktop Info

i5 9th gen
16GB Ram
SSD
GTX 1650

**Comment by JayXTQ** [comment]
Did you enable clipboard and snip and sketch in the configuration folder in the Atlas folder?

**Comment by uncognic** [comment]
Why do you need Windows Ink Workspace?

**Comment by 300BMD** [comment]
> Why do you need Windows Ink Workspace?

Need to take screenshots of Microsoft Access for College work

**Comment by 300BMD** [comment]
> Did you enable clipboard and snip and sketch in the configuration folder in the Atlas folder?

That fixed my clipboard issue but Microsoft ink Workspace still isnt working. ill just use as is thanks for your help

**Comment by uncognic** [comment]
Just use Win+Shift+S, it'll copy the screenshots to the Clipboard and you can choose the size of the screenshot

**Comment by 300BMD** [comment]
> Just use Win+Shift+S, it'll copy the screenshots to the Clipboard and you can choose the size of the screenshot

that is what I do but ink workspace is good to have but i can do without
