### ISSUE TITLE
Feature request : traditional chinese input method "ChangJie"

### ISSUE THREAD

**Issue by linuxjackie** [Atlas-OS/Atlas#375]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

 traditional chinese input method "ChangJie",
which most user use this , but no that option , only 2 another method which seldom use.

### Describe the solution you would like.

add  traditional chinese input method "ChangJie" back

### Describe alternatives you have considered.

add  traditional chinese input method "ChangJie" back

**Comment by uncognic** [comment]
All variants of IME and similar stuff are stripped on Atlas. You could build your own Atlas ISO that has the IME in it. See /src for more details.

**Comment by PencilNavigator** [comment]
> And have to say , not all IME had been stripped, which the 2 reminded are not usual to use. Only the most one use are stripped.. As a user , really don't know how to get it done ,

install a third party input, installing the IME yourself, or just remain using english.
This might be helpful: https://github.com/Atlas-OS/Atlas/issues/319

**Comment by linuxjackie** [comment]
> > And have to say , not all IME had been stripped, which the 2 reminded are not usual to use. Only the most one use are stripped.. As a user , really don't know how to get it done ,
> 
> install a third party input, installing the IME yourself, or just remain using english. This might be helpful (its not): #319 and ignore the swearing.

Thank you for the reply, 
#319 are disscuing about Schinese , and changing windows language , that's not what I wanted.

I do installing the IME by self , but not work, the input method showed , but can't type any word.

**Comment by PencilNavigator** [comment]
> > > And have to say , not all IME had been stripped, which the 2 reminded are not usual to use. Only the most one use are stripped.. As a user , really don't know how to get it done ,
> > 
> > 
> > install a third party input, installing the IME yourself, or just remain using english. This might be helpful (its not): #319 and ignore the swearing.
> 
> Thank you for the reply, #319 are disscuing about Schinese , and changing windows language , that's not what I wanted.
> 
> I do installing the IME by self , but not work, the input method showed , but can't type any word.

because the input method is not downloaded. Windows Update is required to download it automatically.
Atlas disabled windows so it cannot automatically download.
and i alrealdy told you in the brackets that the issue link is not going to help your problem.

**Comment by PencilNavigator** [comment]
you can build your own Atlas ISO that has the IME and the input in it, or use a third party input.

**Comment by linuxjackie** [comment]
That is not easy for a user to build own custom's,
Anyway, thank you for the reply, 
I guess the original windows 10 might suit me more.
