### ISSUE TITLE
Bug report:i have installed atlas os after installing and updating drivers the display brightness level adjuster is missing

### ISSUE THREAD

**Issue by Nandu1976** [Atlas-OS/Atlas#379]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

Bug report:i have installed atlas os after installing and updating drivers the display brightness level adjuster is missing

### Steps to reproduce (if applicable add screenshots)

Bug report:i have installed atlas os after installing and updating drivers the display brightness level adjuster is missing

### Expected behavior

Bug report:i have installed atlas os after installing and updating drivers the display brightness level adjuster is missing

### Actual behavior (if applicable add screenshots)

Bug report:i have installed atlas os after installing and updating drivers the display brightness level adjuster is missing

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop Info

hp elitebook 840 g2

### Additional content

Bug report:i have installed atlas os after installing and updating drivers the display brightness level adjuster is missing

**Comment by PencilNavigator** [comment]
”I understand that not filling out this template will lead to the issue being closed“
Read it yourself, did you fill out the template correctly?

**Comment by PencilNavigator** [comment]
![Contribution Activity screenshot](https://user-images.githubusercontent.com/85282140/206943061-d4f7e924-4aff-4871-b724-65af6308ae6a.png)
