### ISSUE TITLE
System freezing/crashing completely when Alt + Tabbing out of game

### ISSUE THREAD

**Issue by RyujiVal** [Atlas-OS/Atlas#397]
### Prerequisites

- [x] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

System freezes and inorder to unfreeze it temporarily Win + Shift + Ctrl + B works but after that it completely crashes and requires a force PC restart

### Steps to reproduce (if applicable add screenshots)

1. Open Valorant/KovaaK's 
2. alt + tab then freezes
3. Win + Shift + Ctrl + b to unfreeze
4. after that alt tab and system black screens and requires a full restart

### Expected behavior

Normal alt tab

### Actual behavior (if applicable add screenshots)

but crashes/freezes

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

Intel I5-10400F
32GBs of RAM
RTX 3050

**Comment by SyrmGIT** [comment]
This issue is related to your GPU drivers, and not Atlas directly. Try troubleshooting with other driver versions.
