### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by cx9208** [Atlas-OS/Atlas#398]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

want to recover LanmanServer servie, i got error 1068 when i try to start it

### Describe the solution you would like.

a bat for recover LanmanServer service

### Describe alternatives you have considered.

not found. atlas is good for gamming, i just wish can use it in my work,but a software in my work need LanmanServer service

**Comment by SyrmGIT** [comment]
It's in the folder?

Atlas → Configuration → Workstation
