### ISSUE TITLE
Could you please not remove windows 10 OCR from Atlas?

### ISSUE THREAD

**Issue by serrebi** [Atlas-OS/Atlas#40]
Hello:
I am a blind computer user interested in alternative windows, such as windows 10 ame, and AtlasOS, for performance, and accessibility reasons. Could you please include windows 10 OCR to your OS? When I run NVDA under AtlasOS 0.4.2, NVDA tells me windows 10 OCR not found. This is included with windows 10 ame, and I believe your users wouldn't notice it being included.
Thanks for the consideration.
Brandon

**Comment by Zusier** [comment]
Okay, been a bit busy sorry about that. I promise I will get this to you tomorrow

**Comment by serrebi** [comment]
Can't wait! I already tried to install the FaceIT version, maybe you could include that in that more compatible secondary version? Thanks a lot for doing this.

**Comment by Zusier** [comment]
Will do

**Comment by serrebi** [comment]
I am serrebi#4112 on discord. I can't get by your spam prevention on the Discord: I can't send the image in time. Sorry to put this in the issue here: I didn't know how else to tell you.

**Comment by Zusier** [comment]
Sent a friend request, Ill contact you when I have it ready

**Comment by justkamiii** [comment]
Has there been any updates on this?

**Comment by SyrmGIT** [comment]
Windows OCR will not be coming to Atlas' default configuration. If you wish to include it yourself, either have it built from Atlas' source; or contact Zusier if he has enough free time to build one for you. I'll be closing this.
