### ISSUE TITLE
can't open function discovery resource publication services

### ISSUE THREAD

**Issue by Lucifer192192** [Atlas-OS/Atlas#412]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

can't open function discovery resource publication services

<img width="344" alt="1" src="https://user-images.githubusercontent.com/113205867/208248207-0ec4d76e-93f5-4ac5-a441-cf102c866609.png">

### Steps to reproduce (if applicable add screenshots)

can't open function discovery resource publication services

### Expected behavior

can't open function discovery resource publication services

### Actual behavior (if applicable add screenshots)

<img width="344" alt="1" src="https://user-images.githubusercontent.com/113205867/208248227-6fd36b68-4885-490c-8a54-035b8d6ecde6.png">

### Atlas Version (1803/20H2/21H2)

21H2

### Desktop information

amd r9 5950x

**Comment by SyrmGIT** [comment]
There's no way we're able to fix this with the information given. Try to fill out more information in the next bug report, closing this for now.

**Comment by PencilNavigator** [comment]
Function Discovery Resource Publication is related to network discovery, SSDP, or UPNP.
never seen people having this problem before, but before you submit low quality and unrelated issue go search your problem on a search engine. i've found multiple guides on how to fix it, and you should do that.
