### ISSUE TITLE
Netboot support

### ISSUE THREAD

**Issue by JuniorJPDJ** [Atlas-OS/Atlas#423]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

AtlasOS doesn't allow netbooting which I'd like to be using. Setup (boot.wim) lacks network drivers.

### Describe the solution you would like.

Don't strip network card drivers from boot.wim. This would allow using netboot configurations to provision AtlasOS.

### Describe alternatives you have considered.

I tried starting setup.exe of Atlas from boot.wim from original Windows ISO.
But no matter which english language I use I get this error anyway:  
![image](https://user-images.githubusercontent.com/7334549/208790227-25b531f5-2650-49d8-a654-74185dc46761.png)

**Comment by PencilNavigator** [comment]
This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
why would you check it if it does not match?
You will not get an answer here.
