### ISSUE TITLE
Please Enable God Mode By Default

### ISSUE THREAD

**Issue by Elshara** [Atlas-OS/Atlas#43]
**Is your feature request related to a problem? Please describe.**
I am a screen-reader user of modern desktop and mobile apps. One of the features I dearly miss from Windows 7, is the ability to enable god mode. This is not just a simple menu tweak, as it unlocks a lot of commands previously unknown in one single menu. It would help gamers a lot also keep track of their preferences and settings. I can't remember if Windows XP had it, but it came out around the time that computers were still using Bioses and not UEFI hardware. If I could, I'd only use that menu and disable both settings and control panel altogether to focus on an interface which is a single click to access key dialogs, windows and preferences within and throughout classic windows. It's very fast, and still exists for Windows 10 today.
**Describe the solution you'd like**
Enable or look into turning on God Mode by default for Atlas OS.
**Describe alternatives you've considered**
Doing things this way is not only cumbersome, but inaccessible as it requires a visual step. https://www.tomsguide.com/how-to/how-to-enable-god-mode-in-windows Speaking of which, there's no accessibility in Atlas OS to install it. But that's, another issue for another time. I brought God Mode up because your website targets your addition of Windows to Gamers, as far as I know. I could get sighted help to install Atlas in a rough and ready state right now, because I basically use this menu so frequently as a blind power user.
**Additional context**
This article has screen shots, and among other things, pdf documents describing god mode in detail. https://www.techrepublic.com/article/how-to-use-god-mode-in-windows-10/

**Comment by Zusier** [comment]
So you would like it on the desktop? For sure!

**Comment by Elshara** [comment]
Yes please, if that could be done. That would make me and a lot of users so very happy :)

**Comment by Zusier** [comment]
I can't seem to add it to the repo. Displays as a hidden file, but isn't. Not sure what to do about that :p

**Comment by Elshara** [comment]
Perhaps, one work around would be to either.
1. Include instructions to set it up in a text file under the Atlas Folder.
2. My research suggests that so long as there's a folder on the desktop with an exact character sequence, the icon will show up there.
3. Alternatively, it could be placed anywhere with a shortcut to the path itself located on the desktop with the exact character sequence within the folder name being the destination location for the shortcut to point to. My guess is, like control panel, that's something the start menu and or task bar could also support.
