### ISSUE TITLE
Display Language automatically sets to English after restart.

### ISSUE THREAD

**Issue by RovarPlaysYT** [Atlas-OS/Atlas#434]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

When I restart the system, after restarting the display language is automatically set to English, and I need to reinstall the Russian display language

### Steps to reproduce (if applicable add screenshots)

1. Go to Settings
2. Set Display language to Russian
3. Restart System
4. After restarting language automatically sets to English

### Expected behavior

Nothing

### Actual behavior (if applicable add screenshots)

Display Language automatically sets to English

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

- AMD Athlon 300U
- RAM 8GB
- SSD
- AMD Radeon Vega 3 Graphics

### Additional content

I used DoNotConnect to change display language

**Comment by Xyueta** [comment]
It's a Windows bug with 20h2.

https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/language-packs-known-issue.

Try some of the fixes in the docs, or try the guide from ReviOS (the U version) https://www.revi.cc/revios/workspace/lang#h.ry7gga391br1

And if you have the time, reinstall and the first thing you do should be installing languages/keyboard layout.
