### ISSUE TITLE
Cannot enable bluetooth

### ISSUE THREAD

**Issue by MrFarengate** [Atlas-OS/Atlas#438]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

i wanted to enable bluetooth with exe file in atlas folder but it fails to start a service

### Steps to reproduce (if applicable add screenshots)

1.go to atlas folder>Configuration>Bluetooth
2.start "Enable Bluetooth.bat"

### Expected behavior

i can enable bluetooth

### Actual behavior (if applicable add screenshots)

<img width="960" alt="screenshot" src="https://user-images.githubusercontent.com/121438698/209551341-0d3d8e8b-9fc4-47bf-ad73-79625708d2b1.png">

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

Processor:Intel Celeron N2940
Ram:4GB
Drive Type:SSD
Graphics:integrated

**Comment by PencilNavigator** [comment]
did you install network card (most with bluetooth) or whatever bluetooth device drivers?

**Comment by MrFarengate** [comment]
ive tried installing many drivers but they didnt worked i also tried Intel DSA and SDIO but they didnt find any drivers

**Comment by OneOnlineShow** [comment]
I have exactly the same problem. I installed the correct and working driver (from official asus website) for my Asus x570i-Gaming which worked on stock windows. I enabled 3 items in the Atlas config - bluetooth, network discovery and SMB. **My bluetooth does not see any devices**, a lot of reboots, launching .bat from the admin/user rights and trying to turn bluetooth on/off did not help. Hope you can fix this issue. Thank you!

**Comment by triuk** [comment]
@OneOnlineShow
+1 I have the same problem with bluetooth. Drivers installed, enabled, but can not find any device.

**Comment by JayXTQ** [comment]
@MrFarengate did you end up finding the right driver?

**Comment by MrFarengate** [comment]
yes.¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by Jamestec9** [comment]
I have the exact same problem. Everything works well except for the bluetooth. Even with the latest drivers. Any ideas?

**Comment by gopzhe** [comment]
> I have exactly the same problem. I installed the correct and working driver (from official asus website) for my Asus x570i-Gaming which worked on stock windows. I enabled 3 items in the Atlas config - bluetooth, network discovery and SMB. **My bluetooth does not see any devices**, a lot of reboots, launching .bat from the admin/user rights and trying to turn bluetooth on/off did not help. Hope you can fix this issue. Thank you!

I have the same issue with you. I can see the bluetooth icon. but if I try to connect device, cant find any device. the script enable buletooth is not work. I connect the wired headset and it is not recognized. if you have any method to fix this issue, pls share with me.

**Comment by harryIndo** [comment]
I am facing the very same concern with samsung NP305e notebook. It shows bluetooth toggle but couldn't find any device. please help

**Comment by CHHuy** [comment]
I also have this issue on Asus S551LN model, can use bluetooth before install atlasOS, after dont have option to turn on bluetooth (try both window 10 and 11)

**Comment by mamisvirj** [comment]
I followed your instructions. At first, the Bluetooth toggle became active, but when I pressed it, it started turning off again. I removed the Bluetooth adapter, restarted the PC, plugged the adapter back in, and this time the Bluetooth toggle didn’t turn off when I pressed it. However, when I started searching for devices, I received a 'Couldn't connect' error.
