### ISSUE TITLE
Add a script to re-enable Animations in AtlasOS.

### ISSUE THREAD

**Issue by 1onely-lucas** [Atlas-OS/Atlas#44]
Adding a script to bring back Windows Animations would be very helpful. It'd make it a lot easier than doing it manually.

**Describe the solution you'd like**
A script in the Atlas folder which simply returns Windows Animations.

**Describe alternatives you've considered**
I've been doing this on every Atlas OS install so far
I also posted it on the subreddit

reg delete "HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\DWM" /v "DisallowAnimations"

reg delete "HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics" /v "MinAnimate"

"systempropertiesadvanced"

Performance > Settings > Click on Adjust For Best Appearance

It's very cumbersome trying to do it manually, a script would make it loads easier.

**Comment by he3als** [comment]
I will make a commit for this

**Comment by 1onely-lucas** [comment]
Great, thanks

**Comment by he3als** [comment]
https://github.com/Atlas-OS/Atlas/pull/45
