### ISSUE TITLE
Can't connect to my NAS

### ISSUE THREAD

**Issue by OneOnlineShow** [Atlas-OS/Atlas#440]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

SMB is not working. I enabled "Workstation (SMB)" and even additionally installed SMB 1.0 via windows features. I was never able to connect to my Synology NAS.

### Steps to reproduce (if applicable add screenshots)

1. My computer
2. Map network drive.
3. I enter the correct NAS address/path, then the correct username and password.

### Expected behavior

Connection established

### Actual behavior (if applicable add screenshots)

Windows cannot access \\my_nas_name\folder
under details:
Error code 0x80070043
The network name cannot be found.

### Atlas Version (1803/20H2/21H2)

20H2 0.5.2

### Desktop information

5700g, 16gb ram, ssd

**Comment by pristis** [comment]
Hi!

I don't have a problem to map network drive with my NAS with smb.

Did you enable `Desktop\Atlas\3. Configuration\Workstation (SMB)` and reboot?

**Comment by OneOnlineShow** [comment]
> Hi!
> 
> I don't have a problem to map network drive with my NAS with smb.
> 
> Did you enable `Desktop\Atlas\3. Configuration\Workstation (SMB)` and reboot?

Yes.

**Comment by idan003** [comment]
hey, i have same issue, when i enter to network is empty, after i enbale it

**Comment by heiljsf** [comment]
+1  ......  me too !

**Comment by idan003** [comment]
> > hey, i have same issue, when i enter to network is empty, after i enbale it
> 
> Another possible solutions.
> 
> * Go to Control Panel - Programs and Features - Turn Windows features on or off.  See is SMB Direct is enabled. You can try to install SMB 1.0/CIFS file sharing protocols (another checkbox).
> * Also, be sure that you can access your NAS via SMB from another computer to exclude network problem.

i did, dont works, they have a bug

**Comment by doblejote** [comment]
Try: https://github.com/Atlas-OS/Atlas/issues/456#issuecomment-1374397631

**Comment by JayXTQ** [comment]
@OneOnlineShow did any other solution work here? Please follow-up

**Comment by JayXTQ** [comment]
Closed due to lack of response
