### ISSUE TITLE
Bug report:Camera won't work

### ISSUE THREAD

**Issue by jlj1102** [Atlas-OS/Atlas#443]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

I installed this os on inspirol 5590.That works Very good except the camera.
I use this laptop to play games also have lessons,and the lessons requires we open the camera.
But the camera works won't right.It seems its black and cannot see anything(With the light near camera flash for 1 time and closed)
I watch a lot of video and do a lot of things,like using SupportAssist ,uninstall and install again,but won't work
I have found that Windows 11 have a service about camera,but i cannot find it on this OS.

### Steps to reproduce (if applicable add screenshots)

none
only install this OS

### Expected behavior

This camera work

### Actual behavior (if applicable add screenshots)

It seem black

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz x8
Intel(R) Wireless-AC 9462
Integrated Webcam

### Additional content

the razer central seems won't work right too.Is it need runtime?

**Comment by JayXTQ** [comment]
Try installing drivers for your webcam. Otherwise there is no alternative as if I remember correctly, the service required for some webcams on Windows is disabled

**Comment by JayXTQ** [comment]
@jlj1102 please respond

**Comment by jlj1102** [comment]
Oh sorry I forgot
I found many drivers install on my computer
But it won’t work
I believe there is a service called ‘camera’ and it won’t work
Also some trouble like my computer sometimes stuck on some pages

**Comment by JayXTQ** [comment]
Webcam component is removed in every released version right now, but it should be re-added in 22H2. It would be best off if you could wait until 22H2 then your camera may work!

**Comment by Alino001** [comment]
> Webcam component is removed in every released version right now, but it should be re-added in 22H2. It would be best off if you could wait until 22H2 then your camera may work!

Hes right, webcams dosent work in version 20h2 and 1803

**Comment by JayXTQ** [comment]
@jlj1102 closing this issue as solved, also, maybe take a look online. Apparently there has been some issues with anniversary updates breaking cameras and their may be a service or 2 you can enable to fix the issue!
