### ISSUE TITLE
Smart Card Service Support

### ISSUE THREAD

**Issue by ap0h** [Atlas-OS/Atlas#453]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

I chose Atlas OS because lap top is very old and it has like ~2GB of RAM DDR 2. Anyway, this lap top is used only for payments of a small company, and I wanted to speed up a things and I removed win10 and installed AtlasOS instead. Everything went fine until I started installing smart card reader. The softwares that I used failed installaing with the following message:
"Microsoft Base Smart Card CSP cannot be found on your system."

I tried to start SCardSer but it doesn't exist, so next thing I tried copying some DLLs from the other window 10 laptop and I tried to register those DLLs using `regsvr32.exe` without any luck. 

### Describe the solution you would like.

It would've been great if you can add a script in Atlas folder to enable this service. 

### Describe alternatives you have considered.

I haven't find fixes I tried with manual installation of missing DLLs without any success. 

### Additional context.

I tried with  **Atlas 1803**

**Comment by SyrmGIT** [comment]
As Atlas is focused towards gamers and this isn't something a gamer would need to have, I will be closing this issue.

Sorry about this, hopefully you find a solution to continue using Atlas.
