### ISSUE TITLE
[FEATURE REQUEST] - Windows 11 version of Atlas

### ISSUE THREAD

**Issue by jabdullah1911** [Atlas-OS/Atlas#455]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

Can we see Windows 11 in AtlasOS?

### Describe the solution you would like.

Add Windows 11

### Describe alternatives you have considered.

None

**Comment by JayXTQ** [comment]
Already been talked about in the Discord, this will not happen, at least for a long while. Hope this helps!

**Comment by Xyueta** [comment]
Added new tags for this feature request :). It will be available in one of the next updates.

**Comment by joeskeen** [comment]
@philippjbauer I found out about this from LTT too LOL! Looks like this project is getting a lot of attention suddenly! Probably for the better :)

**Comment by jd-apprentice** [comment]
> @philippjbauer I found out about this from LTT too LOL! Looks like this project is getting a lot of attention suddenly! Probably for the better :)

Well LTT has around 15m subs hahaha ofc is going to get attention

**Comment by lukehmcc** [comment]
> Added new tags for this feature request :). It will be available in one of the next updates.

Going from windows 11 coming "not for a long while" to "one of the next updates" is quite the jump. I love it and am looking forward to being a test dummy.

**Comment by Savillion** [comment]
[w11.zip](https://github.com/Atlas-OS/Atlas/files/11330594/w11.zip)
You can install it on latest w11 via my apbx, but I strongly recommend creating your own because you really shouldn't trust anyone other than the developers of this project. Also performance is worse than w10 atm since some of the tweaks are not being applied to w11.

**Comment by Antag0nisticWomble** [comment]
> @Xyueta that's great to hear.
> 
> I saw it today on LTT and this looks very promising!
> 
> I'm running Windows 11 ARM with QEMU in a VM on a 2022 MBP M1 Pro. I'd love to get rid of all the junk that Windows ships with so it is snappier in a virtualized environment. Do you have an idea of whether that's hard for you to support?
> 
> Thanks for all the effort!

For now there is the TIW11 script you can get on github. Along with the windows 10 decrapifier script off spiceworks. I use both for my windows 11 installs and so far has worked pretty well.

**Comment by AshwinKO** [comment]
> @philippjbauer I found out about this from LTT too LOL! Looks like this project is getting a lot of attention suddenly! Probably for the better :)

what video of LTT Can you guys share the link i cant find it

**Comment by JayXTQ** [comment]
They renovate a old PC, thumbnail is where linus holds up a pc. It’s also on our website

**Comment by Originalimoc** [comment]
So what blocks using Win10 playbook on Win11?

**Comment by JayXTQ** [comment]
According to some, running the w10 playbook with some modifications to get it to work in the first place works. whilst this is possible it doesn't mean we recommend doing so. we have put out supported build numbers at 19045 which is 22H2 W10 and AME wont work if otherwise unless you change that number

**Comment by lanly-dev** [comment]
Would anybody know/guess any ETA/Plan on this?

**Comment by sabaasa** [comment]
> does anyone know or be able to guess any ETA/plan on this?

no ETA for Windows 11, new version for Windows 10 is releasing this month though. it's quite a big refactor and I'm pretty sure after 0.3 gets releases they will get to work on 11

**Comment by JayXTQ** [comment]
Windows 11 will be made when Windows 10 is **stable**. Please do not ask for any ETAs on this, if there is an ETA it will be on the Discord. Replying to this thread notifys all people who are subscribed to this issue. Thank you for your patience on the matter.

**Comment by he3als** [comment]
https://docs.atlasos.net/troubleshooting/extended-faq/#v03-faq

Please see the v0.3.0 FAQ, which covers if Windows 11 will be in v0.3.0 and the ETA.

**Comment by Xyueta** [comment]
I am closing this as completed. Windows 11 support has been officially integrated into Atlas.

You can check it out as a pre-release using `Actions` tab in this repo or use [this nightly link](https://nightly.link/Atlas-OS/Atlas/workflows/apbx.yaml/dev/Atlas%20Playbook.zip)
