### ISSUE TITLE
network discovery not working

### ISSUE THREAD

**Issue by sharafathkhan** [Atlas-OS/Atlas#456]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

network discovery is not working able locate another pc on network 

### Steps to reproduce (if applicable add screenshots)

network discovery 

### Expected behavior

does not get saved, when we run the network discovery 

### Actual behavior (if applicable add screenshots)

network discovery issue 

### Atlas Version (1803/20H2/21H2)

20h2

### Desktop information

intel 
8gb
hdd
1060

### Additional content

network discovery error

**Comment by doblejote** [comment]
Same problem

**Comment by PencilNavigator** [comment]
https://github.com/Atlas-OS/Atlas/tree/main/src/Desktop/Atlas/3.%20Configuration/Network%20Discovery
have you run this script in the Atlas folder on desktop?

**Comment by idanyolo** [comment]
> https://github.com/Atlas-OS/Atlas/tree/main/src/Desktop/Atlas/3.%20Configuration/Network%20Discovery have you run this script in the Atlas folder on desktop?

i have also the problem, i run this script, still on the share network is on off

**Comment by jasontwoody** [comment]
> > https://github.com/Atlas-OS/Atlas/tree/main/src/Desktop/Atlas/3.%20Configuration/Network%20Discovery have you run this script in the Atlas folder on desktop?
> 
> i have also the problem, i run this script, still on the share network is on off

Can confirm it didn't fix the issue for us today either it still won't save network discovery to on. Currently trying to get NDI output's working for OBS for a 2pc-to-1streamingpc connection. Win10 works great on my main but wife's running AtlasOS and the network discovery is preventing streamlabs from seeing the NDI streams

**Comment by jasontwoody** [comment]
Got it!
Ok so to fix you will need to launch Services as Admin and make sure the following services are set for Automatic and are running 
DNS Client
SSDP Discovery
UPnP Device Host
Function Discovery Resource Publication
Function Discovery Provider Host
(the Function Discovery Resource Publication failed and was the primary issue)
So long as you can set them all to automatic the next step will be fine.

run a Command prompt as Admin and use: netsh int ip reset resetlog.txt
It gave a couple access denied errors for 2 of them but once we restarted Network Discovery was working perfectly! Showed up 0 issue on streamlabs and running smoothly

**Comment by doblejote** [comment]
> Got it! Ok so to fix you will need to launch Services as Admin and make sure the following services are set for Automatic and are running DNS Client SSDP Discovery UPnP Device Host Function Discovery Resource Publication Function Discovery Provider Host (the Function Discovery Resource Publication failed and was the primary issue) So long as you can set them all to automatic the next step will be fine.
> 
> run a Command prompt as Admin and use: netsh int ip reset resetlog.txt It gave a couple access denied errors for 2 of them but once we restarted Network Discovery was working perfectly! Showed up 0 issue on streamlabs and running smoothly

Estaba haciendo todos los pasos anteriores como en los demas foros, al agregarle el comando final, se solucionó el error.  Ahora la funcion está activa. Gracias
All + The final commnd = worked for me. Thanks

**Comment by Bubbet** [comment]
> Got it! Ok so to fix you will need to launch Services as Admin and make sure the following services are set for Automatic and are running DNS Client SSDP Discovery UPnP Device Host Function Discovery Resource Publication Function Discovery Provider Host (the Function Discovery Resource Publication failed and was the primary issue) So long as you can set them all to automatic the next step will be fine.
> 
> run a Command prompt as Admin and use: netsh int ip reset resetlog.txt It gave a couple access denied errors for 2 of them but once we restarted Network Discovery was working perfectly! Showed up 0 issue on streamlabs and running smoothly

I've done all of the above and still wasnt able to get network discovery to work how you'd expect. SMB does work, but i have to do //ipaddress/foldername not //workspacename/foldername

**Comment by Xyueta** [comment]
https://github.com/Atlas-OS/Atlas/commit/68973aa095ad9755b2ea77985c25cffeb7b17557
