### ISSUE TITLE
I can't install my printer drivers

### ISSUE THREAD

**Issue by Gaston241** [Atlas-OS/Atlas#46]
When I want to install the drivers of my printer it tells me "An error occurred while installing the product, refer to the manual"

**Desktop Info (please complete the following information):**
 - CPU [Intel 8100]
 - System Drive Type [SSD Kingston 120gb]
 - Version [e.g. 0.4.2]

**Comment by Zusier** [comment]
Install printer drivers via SDIO

**Comment by Gaston241** [comment]
> When I want to install the drivers of my printer it tells me "An error occurred while installing the product, refer to the manual"
> 
> **Desktop Info (please complete the following information):**
> 
> * CPU [Intel 8100]
> * System Drive Type [SSD Kingston 120gb]
> * Version [e.g. 0.4.2]
