### ISSUE TITLE
Dotnet 3.5 service pack 1.

### ISSUE THREAD

**Issue by XLMZDrm** [Atlas-OS/Atlas#460]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

I am unable to install .net 3.5 service pack 1.
When I double click on its file to install, nothing will be shown.
I don't know why. Help me please.

### Steps to reproduce (if applicable add screenshots)

.

### Expected behavior

.

### Actual behavior (if applicable add screenshots)

.

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

.

**Comment by Xyueta** [comment]
Net 3.5 is preinstalled on Atlas.
