### ISSUE TITLE
Nvidia Control panel doesn't work

### ISSUE THREAD

**Issue by cosminmrggxsh** [Atlas-OS/Atlas#462]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

the nvidia control panel doesn t let me open it, it gave me an error, i installed the driver from the folder and after a restart it doesn t work anymore. help me

### Steps to reproduce (if applicable add screenshots)

installed the driver
restart pc
the control panel doesn t work anymore

### Expected behavior

to open it

### Actual behavior (if applicable add screenshots)

nvidia control panel doesn t work after an restart

### Atlas Version (1803/20H2/21H2)

20h2

### Desktop information

i7 4770k 10gb ram 240 and 120 ssd gtx 1060 3gb

**Comment by Alino001** [comment]
maybe reinstall the driver

**Comment by PencilNavigator** [comment]
Reinstall drivers. 
Use DDU to remove drivers COMPLETELY before reinstall.

**Comment by SyrmGIT** [comment]
Going back to an older version of driver works for me. Hopefully this helps?
