### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kori2001** [Atlas-OS/Atlas#463]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

league of legends support please

### Describe the solution you would like.

i cannot download league of legends

### Describe alternatives you have considered.

i cannot download league of legends

### Additional context.

i cannot download league of legends

**Comment by PencilNavigator** [comment]
Invalid feature request.
