### ISSUE TITLE
One Drive folder thumbnails doesn't show

### ISSUE THREAD

**Issue by pristis** [Atlas-OS/Atlas#464]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

One Drive folder and subfolders doesn't generate thumbnails and preview panel doesn't preview anything.

All other folders has thumbnails.

Screenshot: https://imgur.com/a/DAVVmEl

### Steps to reproduce (if applicable add screenshots)

1. Activate file sync from registry and install One Drive. To do that, read this post: https://github.com/Atlas-OS/Atlas/issues/317
2. Open One Drive folder with some photos.
3. Change view to large or extra large icons.

### Expected behavior

I expect to see thumbnails for One Drive folder and subfolders.

### Actual behavior (if applicable add screenshots)

There are no thumbnails even when:

- files are downloaded locally.
- folder options - always show icons, never thumbnails is **unchecked**
- system properties - advanced - visual effects - show thumbnails instead icons is **checked**

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

- Intel i7-4700MQ
- 16 GB RAM
- GPU Intel HD 4600
- GPU Nvidia Quadro K2100M

**Comment by SyrmGIT** [comment]
This is nothing we plan on fixing. If this issue is even related to Atlas, it will not be looked into as it's not related to gaming.

Please do dual boot if you wish to have compatibility (stock Windows), and a performance operating system (Atlas).
