### ISSUE TITLE
try the samsung nvme driver https://semiconductor.samsung.com/consumer-storage/support/tools/

### ISSUE THREAD

**Issue by Carlb7** [Atlas-OS/Atlas#465]
try the samsung nvme driver https://semiconductor.samsung.com/consumer-storage/support/tools/

_Originally posted by @isipisi89 in https://github.com/Atlas-OS/Atlas/issues/448#issuecomment-1368277653_

**Comment by PencilNavigator** [comment]
Invalid issue.
