### ISSUE TITLE
Make the win-capture-audio plugin work on obs 

### ISSUE THREAD

**Issue by Onikisu** [Atlas-OS/Atlas#468]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

Atlas OS makes the win-capture-audio obs plugin doesn't work.. which is pretty hindering for streamers who want to separate their audio sources 

### Describe the solution you would like.

work with the win-capture-audio obs plugin devs to solve the problem 

### Describe alternatives you have considered.

I honestly do not have an alternative to this

**Comment by JayXTQ** [comment]
We can't do this, it's a feature which doesn't exist on 20H2 or below, go 21H2 for the functionality to work. Please read the win-capture-audio GitHub repo. And in future, don't make issues before doing any research to see if it's not working on a Windows update. Thanks
