### ISSUE TITLE
Feature request temporarily enable windows update

### ISSUE THREAD

**Issue by YorkeSun** [Atlas-OS/Atlas#474]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

For some reason, I have to install some drivers using windows update. But group policy prohibits windows update. Can you provide a way to temporarily enable update?

### Describe the solution you would like.

Provide a "*.bat" to switch between two group policies

### Describe alternatives you have considered.

none

**Comment by JayXTQ** [comment]
Enabling Windows update will reset most Atlas tweaks, so it's best we don't do this in my opinion. What drivers are you having issue installing?

**Comment by SyrmGIT** [comment]
@YorkeSun please do reply.

**Comment by Zusier** [comment]
You can get drivers from windows update via the [catalog](https://www.catalog.update.microsoft.com/Home.aspx)
