### ISSUE TITLE
store

### ISSUE THREAD

**Issue by MelonsYum** [Atlas-OS/Atlas#49]
Hello,
Why wont the games that i open in the microsoft store not open?
games like roblox and stuff

thanks

**Comment by Zusier** [comment]
Store Apps work on a default install. Please send: C:\Windows\AtlasModules\userScript.log and I can help you

**Comment by MelonsYum** [comment]
i dont have userScript.log in atlas modules

**Comment by MelonsYum** [comment]
still dont have userScript.log

**Comment by Zusier** [comment]
You are probably on 0.4.2. Did you remove UWP?

**Comment by MelonsYum** [comment]
yes and yes

**Comment by Zusier** [comment]
Read: https://github.com/Atlas-OS/Atlas/blob/123b75db17be071d58d9c9dfb049e9f02125514c/src/20H2/AtlasModules/atlas-config.bat#L1527

**Comment by MelonsYum** [comment]
ok... and how fix

**Comment by Zusier** [comment]
On 0.4.2 you can't stripping UWP is permanent

**Comment by MelonsYum** [comment]
bruh,
i'll try and find a usb today

**Comment by MelonsYum** [comment]
i switched to 0.5, and i enabled UWP
yet, it still fails to load

**Comment by Zusier** [comment]
Error message or screenshot?

**Comment by SpecificationsL** [comment]
Asphalt 9 is crashing instantly when it is about to hit loading screen help and also on 0.5.2 AtlasOS 20H2
