### ISSUE TITLE
Exploring An Alternative Method To Get Basic Apps

### ISSUE THREAD

**Issue by Elshara** [Atlas-OS/Atlas#50]
**Is your feature request related to a problem? Please describe.**
When Atlas OS runs for the first time, one of the first things you will notice, is the archaic capabilities of Internet Explorer. For instance, downloading files from GitHub releases doesn't render properly in that browser. While it is absolutely true that Atlas OS comes with a desktop folder containing tweaks and software tools, the capabilities of the utilities folder is limited to .reg files and browsers as the .dat files fail to secure any output in a terminal. this could be improved, in many ways, automatically with the following tool, Ninite.com installer.

**Describe the solution you'd like**
Ninite's primary purpose, is to secure and automatically install common, every day apps needed for proper functioning of online websites and media files. I really enjoy the fact, that it does not include any bloatware in its official install choices, and you can update or install multiple apps at once with this tool. For instance, any browser, file tool or archival utility you need along with libraries, frameworks and other misc tools which are required for programs and games to run properly. Ninite could and would with a single click install, replace many of the software based tools found in Atlas OS folder today. https://ninite.com/ Which also includes an accessible option, for screen reader users. https://ninite.com/accessible

**Describe alternatives you've considered**
What I'm looking for, is an easier way to get up and running on Atlas OS once it is installed. Up to and including, using the 'administrator' account as the default to start with. So much of Windows management these days, is based on maintenance. Atlas OS is the only custom edition that removes 96% of roadblocks Windows users find cumbersome to use. 30% of which, is based on drivers and usable apps. Currently, Driver Pack Solution found at https://driverpack.io/en is the only way to auto install drivers, at the cost of bloatware for the effort. Bloatware that could completely be eliminated with an alternative solution, via NiNite. Driver Pack Solution is in fact open source, which would allow you to design an interface through which, a silent and bloat free experience could be created for getting and automatically installing the system drivers a particular PC would need. If there's a way to use the NiNite and Driver Pack Solution installers together to auto-accompany system detection methods for getting a list of interactive apps people would want in a single click, you would have literally 98% of the desktop marketplace begging for more across every computer, tech and software community there is. The alternatives are a manual and cumbersome list of searching, navigating unfamiliar interfaces, scrolling, clicks and browsing various different websites to do the same thing through manufacturers online support portals. The one click solution method is gaining in popularity, and I trust Atlas OS to do its best to become a completely powerful and independent version of Windows, big tech companies failed to maximize the potential of.

**Additional context**
As this implementation of NiNite and or custom Driver Pack Solution detection interfaces is mostly done on the back end, the best I can provide you with, at least for now, is a use case scenario that meets the needs of people who don't really understand what they need to make their computer function well. As a part of something recommended to be accessible for the widest available audience, that can do the most with the least amount of performance set backs.

**Comment by Zusier** [comment]
> the capabilities of the utilities folder is limited to .reg files and browsers as the .dat files fail to secure any output in a terminal
I see what you mean, *but* I have been planning on integrating something such as [scoop](https://scoop.sh) which will make it so much easier to install browsers and programs.

> Up to and including, using the 'administrator' account as the default to start with.
I will not be considering this, using the default admin account can arguably be seen as a security flaw

> is the only way to auto install drivers
I do not plan on having any drivers automatically installing. Because people have preference on what specific versions, and drivers in general they want to install.

> you would have literally 98% of the desktop marketplace begging for more across every computer, tech and software community there is.
That's a bit exaggerated, some people actually like the "diy" part of the installation. 

I will for sure link ninite. (I only glazed over the issue, will fully read it when I can)

**Comment by Zusier** [comment]
Now a [WIP](https://github.com/Atlas-OS/Atlas/pull/53/commits/132093edbbac207d2a6b1a62cf2e8115568fe354), closing
