### ISSUE TITLE
Is it safe?

### ISSUE THREAD

**Issue by KingKrex69** [Atlas-OS/Atlas#507]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

I want to ask, is this safe to use on to my main pc and are there any viruses or malware in this code?

### Describe the solution you would like.

.

### Describe alternatives you have considered.

.

### Additional context.

.

**Comment by JayXTQ** [comment]
1. This is a question, please ask questions in the discussion tab or the discord
2. The project is open source, just check the source code. But yes, yes it is

**Comment by PencilNavigator** [comment]
Please read every single thing on the template before submitting a shitty Issue.
![Pic](https://user-images.githubusercontent.com/85282140/212751913-a35903df-f1c6-445e-82ca-5bcc627725ee.png)
