### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by miyatatakeshi** [Atlas-OS/Atlas#508]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

![image](https://user-images.githubusercontent.com/75170571/212840065-f6f157c7-899a-4098-8ba4-a523fd71e36c.png)

### Steps to reproduce (if applicable add screenshots)

Just hover over Turkish flag.

### Expected behavior

Saying Turkish.

### Actual behavior (if applicable add screenshots)

Says Deutsch.

### Atlas Version (1803/20H2/21H2)

Not relevant.

### Desktop information

Not relevant.

**Comment by JayXTQ** [comment]
Hi, thanks for bringing this issue up. You can mitigate this issue yourself if you know how to make a pull request on GitHub. If you don’t someone else will probably fix in a bit!

**Comment by PencilNavigator** [comment]
Fixed.
