### ISSUE TITLE
Dektop Resolution Problem on an Dell E198WFP Monitor

### ISSUE THREAD

**Issue by hashplayer** [Atlas-OS/Atlas#51]
I just Installed Atlas yesterday and my Screen Resolution was on 1024x768, which my Computer says that is can have 1440x900.and the only option i have is:1024x768,1152x864 and 800x600. Can someone please help me i have tried every method to fix my Screen Resolution, and not a single of them work.

Here are all of my Details of my PC:
Processor:Intel Core Duo 2 E4500 2.20GHz 2 Core
RAM: 2GB
Hard Disk: 232GB
System Manufacturer: Dell Inc.
Monitor: Dell E198WFP
PC: Dell Vostro 2
Hard Disk Type: HDD
Bios Version: 1.0.16
Bit Version: 64 Bit
Display Adapter Driver: ATI Radeon HD 2400 Pro
Photo of The Atlas Stretched on 1024x768:
https://user-images.githubusercontent.com/71170855/134053030-a36c8e02-3085-48a0-b9b0-f7cb09f4e2ca.PNG

**Comment by Zusier** [comment]
1. Win+R Type dxdiag
2. Go to Display
3. Send a screenshot of the window here

**Comment by Zusier** [comment]
According to the "Microsoft Basic Display Adapter" You do not have graphics drivers properly installed.

Please install drivers from your vendor's site or SDIO.

**Comment by hashplayer** [comment]
https://user-images.githubusercontent.com/71170855/134178579-c6fc8d88-40e0-4f1a-9497-536dedf1c2c3.PNG

https://user-images.githubusercontent.com/71170855/134178585-a50bcc7a-4fd5-4262-ac8e-a5c1508e936a.PNG

(https://user-images.githubusercontent.com/71170855/134178591-7aced9b6-c641-4a57-b2b9-dffe7ade0779.PNG

**Comment by Zusier** [comment]
What GPU do you have?

**Comment by Zusier** [comment]
It won't display until you have a graphics driver. Just noticed you listed it in the original post. 

https://www.amd.com/en/support/graphics/amd-radeon-hd/ati-radeon-hd-2000-series/ati-radeon-hd-2400-pro

here's where you can get your driver.. but it seems your hardware no longer supports windows 10

**Comment by Zusier** [comment]
There is a driver archive that has w10 versions [here](https://driverscollection.com/_53818624101ea253543e37e862f/Download-ATI-Radeon-HD-2400-PRO-Driver-v.21.8.2-for-Windows-10-64-bit-free)

**Comment by hashplayer** [comment]
When i installed the Software it sayed that my AMD Graphics Drive is unsupported in my System Configuration with this Software, when i clicked on the Get more Details it sayed that i need to do a Windows so it can install a Display Driver
And this is the Link for the Error

https://www.amd.com/en/support/kb/faq/gpu-kb182

https://user-images.githubusercontent.com/71170855/134200108-77d302ae-0a54-49bb-88e2-15b42b877b9f.PNG

**Comment by Zusier** [comment]
Try this driver https://www.amd.com/en/support/kb/release-notes/rn-rad-win-20-4-2

**Comment by hashplayer** [comment]
When i tried to install it sayed the same thing and when i pressed the Get More Details it brought me back to the same thing

https://user-images.githubusercontent.com/71170855/134202021-a321948b-5107-4835-b568-b6854841bfb8.PNG

**Comment by hashplayer** [comment]
Also when i was Installing Windows 10 64bit 2 Weeks ago i had teh same problem But i managed to fix it by updating the Display Driver but when i do it now i doesnt work.

**Comment by hashplayer** [comment]
My Theory is that Atlas is at Version 20h2 and Windows is at 21h1, Atlas has a outdated Version of Windows
and i tried to use Windows Update but i doesnt work.

**Comment by Zusier** [comment]
I will send you a reg to try when I'm home. I can promise you windows version is not the issue.

**Comment by hashplayer** [comment]
ok Thanks

**Comment by Zusier** [comment]
[Driver_Searching.reg.zip](https://github.com/Atlas-OS/Atlas/files/7220427/Driver_Searching.reg.zip)

1. Reboot 
2. Device manager >> Action >> Scan for new hardware

**Comment by hashplayer** [comment]
Where should i import the Reg?
I pressed on Reg and Rebooted, then went to Device Manager to Action to Scan for New Hardware
And Nothing Happend.

**Comment by Zusier** [comment]
That should enable Microsoft driver updates. I would try an older driver from the driver archive linked before. 

But as your gpu is [officially unsupported on Windows 10](https://www.amd.com/en/support/kb/faq/gpu-kb182), I am going to have to close this.

**Comment by hashplayer** [comment]
Ok I already managed to make my Screen Resolution at 1600x1200 so its fine now.
