### ISSUE TITLE
system thread exception not handled even after reinstalling in laptop 

### ISSUE THREAD

**Issue by b7540** [Atlas-OS/Atlas#511]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

i have install on my old laptop (2005) (HCL ME Pentium 6100)
when i try different type of version but it keep crashing giving same error 

### Steps to reproduce (if applicable add screenshots)

1. fixing pre install software driver
2. checking incompatible driver

### Expected behavior

it will run smoothly and do game

### Actual behavior (if applicable add screenshots)

**but after reboot or restart give same error 'system thread exception not handled' before that reboot(it about sing out)it work fine** 

### Atlas Version (1803/20H2/21H2)

all

### Desktop information

(intel Pentium 6100 processor
2gb ram
320gb hhd)

**Comment by PencilNavigator** [comment]
This is more likely a support question. Please ask in the Atlas [Discord](https://discord.com/servers/atlas-795710270000332800).
