### ISSUE TITLE
There is a way to solve the windows bug of installing other language packs

### ISSUE THREAD

**Issue by Qizhen-Yang** [Atlas-OS/Atlas#513]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

You said that there's a Windows bug that disabled us to change display language in AtlasOS.
But there is a solution.

### Describe the solution you would like.

Change the value of `DoNotConnectToWindowsUpdateInternetLocations` to `0` in `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate`.

### Describe alternatives you have considered.

I myself tested it, and most parts of AtlasOS can be changed to another language.
Also, the English language can be safely removed in Settings.
Mention that in Wiki please. It will surely help many people

**Comment by JayXTQ** [comment]
You didn't do a search of the repository issues beforehand I can see, there is multiple issues under this: https://github.com/Atlas-OS/Atlas/issues/434 as an example.

**Comment by JayXTQ** [comment]
Just reread your issue and misread it. My bad, but this isn't an issue of sorts really. A discussion would have been better but thanks for the fix! Languages seem to be fixed in 22H2 though so this could be useful for people who stay on the earlier versions!

**Comment by Xyueta** [comment]
This was implemented by me a few weeks ago. Languages will work in the upcoming release.

**Comment by Qizhen-Yang** [comment]
Just mention that in wiki pls. It will certainly help many people.
