### ISSUE TITLE
Interactive Post-Install

### ISSUE THREAD

**Issue by Zusier** [Atlas-OS/Atlas#52]
Interactive script at first boot. Will prompt to continue or not, if not answered after 30 seconds it will call automatic script. Some features that may be added

- [ ] Detect Valid ethernet connection and disable wifi

- [ ] Set static ip and disable related drivers

- [ ] graphics driver install.. perhaps?

- [ ] Prompt about other features that can already be disable on atlas folder

- [ ] IE & WMP

- [ ] Interactive MSI

- [ ] Disable Task Scheduler & Eventlog option

**Comment by spddl** [comment]
Power Plan?

BCD Store?

Does this also disable drivers and services?

how about chocolatey and an update script at the login of the user?
I have built a powershell script for this.

[screen](https://i.imgur.com/TyCkfUF.png)
[script](https://gist.github.com/spddl/55dbd23287c0e2bda7b3f9880826282a)

**Comment by Zusier** [comment]
stuff from the auto version will still be done including drivers/powerplan/bcd

I’m planning on using scoop for a software interface

**Comment by Zusier** [comment]
Moved to PR, seems like a better spot #53
