### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by afastor** [Atlas-OS/Atlas#524]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

I can’t change the language to Russian, it just doesn’t download giving an error

### Steps to reproduce (if applicable add screenshots)

![Screenshot_1](https://user-images.githubusercontent.com/123393893/214085258-5e4f439d-2a78-4573-8e11-8b17b0e08379.png)

### Expected behavior

the language will change

### Actual behavior (if applicable add screenshots)

![Screenshot_1](https://user-images.githubusercontent.com/123393893/214085931-46dbf771-8ecf-4b29-99f7-d7fd8701f699.png)

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

CPU adm ryzen 3 3100 - 24G Memory - GPU nvidia 1050 ti

**Comment by JayXTQ** [comment]
Hi, there is duplicate issues based on languages. You should do a research in issues before making an issue.
