### ISSUE TITLE
Network connections' bridging doesn't create bridge network device

### ISSUE THREAD

**Issue by BorniPL** [Atlas-OS/Atlas#527]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

I wanted to check upload speeds with two internet connections bridged, but the bridge network device does not appear after you bridge two connections.

### Steps to reproduce (if applicable add screenshots)

0. Navigate to `ncpa.cpl`
1. Select two network devices
2. Right click & bridge them

### Expected behavior

New `bridge` network device appears.

### Actual behavior (if applicable add screenshots)

Selected network devices are shown as bridged, but you can't do anything with this bridge and cannot un-bridge them.

### Atlas Version (1803/20H2/21H2)

20H2 / winver shows 2009 (I didn't mess with the registry).

### Desktop information

- 12700KF
- 128GB G.SKILL RIPJAWS (4x32GB) DDR4 3600MHz CL16
- SSD 1TB 980 Pro
- 3090 Zotac Trinity

**Comment by JayXTQ** [comment]
Just tested this out on 22H2, seems like it doesn't do as you explained here either.

**Comment by he3als** [comment]
I also had the same issue, although, I am not too familiar with bridging network connections. I will look into it

**Comment by Parixshit** [comment]
> Just tested this out on 22H2, seems like it doesn't do as you explained here either.

Atlas 22H2 released ?

**Comment by he3als** [comment]
> > Just tested this out on 22H2, seems like it doesn't do as you explained here either.
> 
> 
> 
> Atlas 22H2 released ?

No, but he is a beta tester/on the Atlas team, so he has it early.

**Comment by PencilNavigator** [comment]
22H2 has solved this problem (hopefully).

**Comment by he3als** [comment]
Has anyone tested it?

**Comment by the-P1neapple** [comment]
> Has anyone tested it?

Aplolgies for reviving this thread but I found someone with the issue on 22H2. Was able to fix issue by re-enabling the NdisVirtualBus Driver. 
https://discord.com/channels/795710270000332800/1119153922075013192
