### ISSUE TITLE
the recover or reset option doesnt comes even after searching

### ISSUE THREAD

**Issue by rashuv25** [Atlas-OS/Atlas#534]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

i want to dual boot atlas os with zorin os but i am not able to enter bios and enter recover option

### Steps to reproduce (if applicable add screenshots)

1. search reset pc
2. reset or choose usb option

### Expected behavior

reset option should be there

### Actual behavior (if applicable add screenshots)

it didnt came

### Atlas Version (1803/20H2/21H2)

most downloaded

### Desktop information

lenovo ideapad 310

**Comment by Alino001** [comment]
It’s removed

**Comment by PencilNavigator** [comment]
the only proper way to reset atlas is to reinstall with a USB Disk.
Reset function is known to not work since it's removed, even if it works it will revert all atlas tweaks and will break your system.
