### ISSUE TITLE
A Short Issue Description

### ISSUE THREAD

**Issue by Stayed999** [Atlas-OS/Atlas#54]
**Describe the bug**
A clear and concise description of what the bug is. Providing an error code is highly recommended.

This "Bug" I believe is a tweak that causes my pcie adapter (Rtl8822ce from hp) to cut out. I've had this issue on ggOS in the past and it's been resolved in one of the updates (no clue which update) I've troubleshooted by my own and with Phlegm and he came to the conclusion that it was my driver version, that was incorrect.
I decided to just deal with it and wait it out.. I did and after a couple releases passed of ggOS the issue was resolved. Now the issue is back and on Atlas (main reason why I use ggOS). on discord my ping goes to max and i cannot communicate, on games everything completely freezes and continues when the connection comes back, it still shows i am connected to wifi. for example, on fortnite a game I no longer play my ping stayed the same although I couldn't move and then when I could move the ping showed 1000(or whatever) but my ping wasn't actually high
this is my prebuilt. https://www.bestbuy.com/site/hp-omen-30l-gaming-desktop-amd-ryzen-7-series-3700x-16gb-memory-nvidia-geforce-rtx-2060-1tb-hdd-256gb-ssd-black/6402514.p?skuId=6402514 i've tried changing driver versions and using default windows network settings or reapplying the atlas tweaks but the issue is still here

**Comment by Zusier** [comment]
[Driver.zip](https://github.com/Atlas-OS/Atlas/files/7214660/Driver.zip)

This should be the latest driver for your NIC, right click the .inf file and select "Install"

**Comment by Zusier** [comment]
> I believe this is a tweak 

I somehow skipped this part..

Try this:
https://user-images.githubusercontent.com/46111482/134443827-4413d9f5-a5b8-4896-bc83-96e1c65e82f9.mp4

**Comment by Stayed999** [comment]
Thanks, I'll let you know if I still have this problem.

**Comment by Stayed999** [comment]
I updated the driver and uninstalled it then scanned for new hardware changes, I'm still getting the same issue. Instantly joined a call and it's cutting out for a few seconds then resuming. It happens randomly.

**Comment by Zusier** [comment]
Is MSI mode enabled on your NIC?

**Comment by Stayed999** [comment]
Yes, just disabled it.

**Comment by Stayed999** [comment]
issue seems to be gone, thanks
