### ISSUE TITLE
Cant join any FiveM or RageMP (gta5 rp)

### ISSUE THREAD

**Issue by EarthTanks** [Atlas-OS/Atlas#55]
**Describe the bug**
Basically i cant join any servers of gta 5 rp, i get i infinite loading, and it only happens on atlas

**To Reproduce**
1. Go to 'FiveM/RageMP'
2. 'Join any server'
3. 'Load forever'

**Expected behavior**
I expect to load into the server, but it wont, i tried reinstalling the os still dosent work, but as soon as i installed back to normal win 10 it works, but ye, im still running atlas mainly just hope that it can work

**Screenshots**

**Desktop Info (please complete the following information):**
 - CPU i5 9600kf 4.6 ghz
 - System Drive Type 500GB SSD and 500GB HDD but gta is installed on my hdd
 - Version 0.4.2

**Additional context**
Oh and also plz add msconfig back.

**Comment by Zusier** [comment]
What scripts did you run? I highly doubt its an atlas issue as I know plenty of people who play FiveM on atlas.

**Comment by EarthTanks** [comment]
I didnt use any in atlas folder on desktop 
But i used scripts by adamx **https://youtu.be/hQSkPmZRCjc** 
I have used the same scripts on normal windows 10 but didnt have this issue

**Comment by EarthTanks** [comment]
Oh yeah, and i also disabled a bunch of services using win10tweaker

**Comment by Zusier** [comment]
Did you disable mpssvc or BFE?

**Comment by EarthTanks** [comment]
I dont think so cuz i dont know what it is

**Comment by EarthTanks** [comment]
I will try to revert the services and turn them back on, and see

**Comment by EarthTanks** [comment]
Will say if it fixed it

**Comment by EarthTanks** [comment]
Nope still the same infinite load

**Comment by Zusier** [comment]
https://forum.cfx.re/t/fivem-stuck-on-infinite-loading-screen-with-no-errors/1543613/3 There seems to be a few solutions on google. If none work, I will look into it

**Comment by EarthTanks** [comment]
Oh lol it just worked out of the blue, i tried opening it again lol
![image](https://user-images.githubusercontent.com/82320282/134775356-62b39354-a7ca-4020-9b68-2af36c33db31.png)
idk how this worked out

**Comment by Zusier** [comment]
Good to hear, have fun

**Comment by montyop** [comment]
Pls add ms config
