### ISSUE TITLE
NVidia GPU Driver Issue

### ISSUE THREAD

**Issue by neodev27** [Atlas-OS/Atlas#551]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [x] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

I am having trouble with Nvidia drivers.

### Steps to reproduce (if applicable add screenshots)

- I installed Atlas OS, it works good
- I loaded program i need
- When i started setup Nvidia driver, screen was gone and i never be able to interact with PC until i force to restart. And it turns back to Microsoft basic adapter.

### Expected behavior

I was excepted to successfully setup Nvidia Drivers and see request to restart.

### Actual behavior (if applicable add screenshots)

Started setup driver but screen gone until i restart pc.

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

İntel Pentium 3.00 GHz
GPU: Nvidia GeForece 210
Gigabyte Motherboard
4GB ram

**Comment by SnowzNZ** [comment]
What GPU do you have and what driver version were you trying to install?

**Comment by neodev27** [comment]
Nvidia Geforce 210

342.1 WQHL

**Comment by SnowzNZ** [comment]
> Nvidia Geforce 210
> 
> 342.1 WQHL

I asume it wont install because you are trying to install a 32bit driver on a 64bit operating system

**Comment by neodev27** [comment]
Where I can find 64 bit ver of this driver?e

**Comment by JayXTQ** [comment]
If you can’t find a 64 bit version then your guess is as good as ours. Please use an updated driver version for your graphics card if any. If you can’t find 64 bit then Atlas can’t be used as it requires 64 bit architecture

**Comment by fenneclabs** [comment]
Try with this one:
https://www.nvidia.com/download/driverresults.aspx/87988/enus/

`
Version: | 341.74
Release Date: | 2015.7.29
Operating System: | Windows 10 64-bit
`

**Comment by JayXTQ** [comment]
@neodev27 did this work?

**Comment by neodev27** [comment]
I didnt find chance to try. I will try it soon as possible.

**Comment by neodev27** [comment]
![20230221_123848.jpg](https://user-images.githubusercontent.com/88967833/220307164-1a3ee3c5-10ef-4920-a7dc-62b7b3ce93ca.jpg)

It worked! Thanks
