### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by VictorBlaes** [Atlas-OS/Atlas#553]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

 Hello,
I would like to shrink my disk for a dual boot but when i try to shrink it, it says "Bitlocker drive encryption cannot be user because critical BitLocker system files are missing or corrupted. Use Windows Startup Repair to restore these files to your computer."

I had never touched to BitLocker on that OS.
(I don't know if it changes anything but I install Atlas on MBR instead of GPT)

What can I do please ?
(btw I have the newest version of Atlas (20h2))

### Steps to reproduce (if applicable add screenshots)

1. [Open Disk Management]
2.  [Right click Your disk and click "shrink volume"]
3.  [Enter the amount of MB that you want]
4. [Click "Shrink" and you got the BitLocker Error]

![image_2023-02-11_094141269](https://user-images.githubusercontent.com/118826512/218248994-3b57fb41-37a1-4cce-876b-55f0957bb3d1.png)

### Expected behavior

I exepted for my disk to shrink.

### Actual behavior (if applicable add screenshots)

I would like to shrink my disk for a dual boot but when i try to shrink it, it says "Bitlocker drive encryption cannot be user because critical BitLocker system files are missing or corrupted. Use Windows Startup Repair to restore these files to your computer."

### Atlas Version (1803/20H2/21H2)

20h2

### Desktop information

- Intel I5-3570k
- 8Gb of RAM
- 1TO ssd
- GTX 660 TI

**Comment by JayXTQ** [comment]
Hi, BitLocker is removed on Atlas and is restored on 22H2 when it is released, please use an alternative like macrorit for now.
