### ISSUE TITLE
Battery Icon on Surface not working

### ISSUE THREAD

**Issue by RagingBuracku** [Atlas-OS/Atlas#561]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

I installed the 20H2 version of Atlas on my Surface Pro 7, and I can't see my battery icon. After attempted troubleshooting, the only thing I could conclude is that my issue stems from the “Surface Hub Serial Driver” is the core of my issue, nothing I tried actually worked in making the driver work properly. 
![bt](https://user-images.githubusercontent.com/59775668/218273483-8d67e906-9fc7-45e6-89cf-0d002d438754.png)
I tried installing official drivers from Microsoft, but they didn't allow the installation process to go through. 
![Annotation 2023-02-11 124455](https://user-images.githubusercontent.com/59775668/218273481-63eaa0d4-7f5f-4eaa-874d-86e33f441c42.png)
I tried drivers from SDIO after uninstalling the previous driver and restarting my Surface pro 7. There was also an error code for the driver in device manager, but researching it came up with nothing. 
![Annotation 2023-02-11 124455h](https://user-images.githubusercontent.com/59775668/218273482-77995db4-5f1c-48a6-961c-774d84f24b54.png)

Honestly, I suspect that this is happening because of 2 potential reasons, one I'm going to chalk up to Microsoft doing some dumb for the laptop or the fact the AtlasOS version I'm using is 20H2 and maybe the drivers don't work on 20H2, I don't know at this point. I did see a solution about enabling power icon for taskbar, but that option is greyed out for me. ![Annotation 2023-02-11 123709](https://user-images.githubusercontent.com/59775668/218273480-afb55719-6c11-4d9a-8aee-622f70fe644c.png)

If anyone does have suggestions for a solution, I'm open to hearing them. Until then, I'll just wait until Atlas devs release the 22H2 version because _**supposedly**_ that will fix compatibility issues. Hope y'all have a good day.

### Steps to reproduce (if applicable add screenshots)

1. Install AtlasOS 20H2 on a Surface Pro 7
2. Do basic setup steps
3. install essential drivers
4. battery icon is not appearing

### Expected behavior

Surface serial hub driver be working to allow battery to be read

### Actual behavior (if applicable add screenshots)

Serial hub driver not properly work

![Annotation 2023-02-11 124455h](https://user-images.githubusercontent.com/59775668/218274407-52b88ada-1fa4-42b1-a295-d188b3df9299.png)
![bt](https://user-images.githubusercontent.com/59775668/218274409-8da8e11b-0249-4b26-a6dd-38531bc0efcd.png)

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

System drive is internal 256GB SSD

![Annotation 2023-02-11 131337](https://user-images.githubusercontent.com/59775668/218274507-49a19e96-e294-4552-8a5f-fb6a3b790036.png)
![Annotation 254023-02-11 131337](https://user-images.githubusercontent.com/59775668/218274510-5953c14a-9060-43cf-b88e-cca2f4f36390.png)

**Comment by PencilNavigator** [comment]
Sorry to hear that. Could you please try installing 21H2 see if it fixes the problem? 
If 21H2 does not fix the ploblem, could you try if a normal windows install can fix it?
If yes, then i'll recommend waiting for 22H2. It fixes lots of known issue and has better compatibility.

**Comment by Xyueta** [comment]
Driver has been stripped, will be fixed in the upcoming version. Thanks.
