### ISSUE TITLE
Show the SHA-256 hash of the download on the download page

### ISSUE THREAD

**Issue by mazerty** [Atlas-OS/Atlas#562]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

The SHA-256 sum of the downloads are missing on the download page.

You obviously care of the privacy aspect of Atlas, but since you're hosting the downloads on a third-party service (MediaFire), you cannot guarantee that the ISO has not been tempered.

### Describe the solution you would like.

Can you please show the SHA-256 sum on the download page so that users (like me) who wants to be sure of what they downloaded can double-check ?

### Describe alternatives you have considered.

Unfortunately, there's no fix around that since it has to be you who provide the SHA-256 sum :)

### Additional context.

Downloading a full OS online and running it on a machine is a sensitive matter.
For Linux distributions for example, users are expected to double-check the integrity of the download by computing the SHA-256 sum of the downloaded file and compare it to the one that is visible on the website.

**Comment by Vinfall** [comment]
Besides checksum, it would even better if you could provide OpenPGP signature for the ISO along with a signing key. You can find the information on [Arch Wiki](https://wiki.archlinux.org/title/Installation_guide), [Kali](https://www.kali.org/docs/introduction/download-official-kali-linux-images/#_what_-do-i-need-to-do-this) and [Tails](https://tails.boum.org/install/expert/index.en.html).

Use GnuPG to sign the file w/o encryption would suffice. And the sig/ascii-armored file should only be tiny like 1KB. You can just upload signing key to a key server and put the signature on download page and the increased bandwidth consumption is acceptable.

**Comment by PencilNavigator** [comment]
SHA-1 will be added to the download page with the new 22H2 update. Closing it as solved.

**Comment by mazerty** [comment]
well this is disappointing
now you don't offer direct download anymore, and the building tool only works on windows
i guess i'll use tiny11 then

(if you wanted to cut the costs on hosting and bandwith, bittorrent would have been a better alternative, a lot of linux distributions use that)

**Comment by PencilNavigator** [comment]
@mazerty its not for cutting costs. we do this for legal reasons. 
Re-distributing a modified windows iso is against Microsoft's TOS, and can get our repo taken down. 
by using this new method, not only we can debug more easily, we can also push hot fix that users can just apply with a button on the AME Wizard.

**Comment by mazerty** [comment]
oh ok i didn't know sorry !
yeah that makes sense...

maybe you can put a notice on the website explaining the change ?

do you intend to have a linux build for the ame wizard ?
