### ISSUE TITLE
Problem with changing icons

### ISSUE THREAD

**Issue by injectsploit** [Atlas-OS/Atlas#564]
### Bug report information

Hi .

How to add a theme to AtlasOs .
Thank you.
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/72941085/218321646-896e9f43-8268-4b94-8dbc-38a79d629c03.png">

### Additional Content
Sorry, I did not find the place to put this QUESTION.
But I want to ask about the problem of adding Theme to AtlasOs.

Thank you

**Comment by Murhpysad** [comment]
How to enable Themes:
1. cmd: sc config Themes start=auto, restart
2. get a theme (find one online)
3. Copy to C:\Windows\Resources\Themes
4. use https://github.com/namazso/SecureUxTheme
5. Double click the theme in C:\Windows\Resources\Themes

**Comment by injectsploit** [comment]
> How to enable Themes:
> 
> 1. cmd: sc config Themes start=auto, restart
> 2. get a theme (find one online)
> 3. Copy to C:\Windows\Resources\Themes
> 4. use https://github.com/namazso/SecureUxTheme
> 5. Double click the theme in C:\Windows\Resources\Themes

Thank you so much . 
But I have a problem with changing icons .

**Comment by Zusier** [comment]
Whats the problem with changing your icons? Is it the original error? It's because restore points are stripped.

**Comment by 0xC4aE1e5** [comment]
If there's an option to prevent creating a restore point, try it.

**Comment by JayXTQ** [comment]
@injectsploit did you fix this?

**Comment by JayXTQ** [comment]
Closing this as no response, I hope you found a solution!
