### ISSUE TITLE
CMD tool not work

### ISSUE THREAD

**Issue by heroes1412** [Atlas-OS/Atlas#570]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

Desktop\Atlas\1. Install Software\ *.cmd tool not work.

It only show "'scoop' is not recognized as an internal or external command", no software will be installed.

### Steps to reproduce (if applicable add screenshots)

Run "Desktop\Atlas\1. Install Software\Install Browser via Scoop.bat"
select chrome
click OK

### Expected behavior

Chrome will be installed

### Actual behavior (if applicable add screenshots)

It only show "'scoop' is not recognized as an internal or external command", no software will be installed.

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

i5 11320H
4gb ram
ssd

**Comment by Zusier** [comment]
You need to install scoop first. There is a script to do so in the same folder.

**Comment by heroes1412** [comment]
thanks, I didn't pay attention to that file.

**Comment by heroes1412** [comment]
Running the installer as administrator is disabled by default, can't install scoop.

**Comment by heroes1412** [comment]
I run it and it show me that :)). Run with normal user and Run as administrator give me same result

**Comment by coderx546** [comment]
> I run it and it show me that :)). Run with normal user and Run as administrator give me same result

never happened with me

**Comment by lirikaontheplace** [comment]
> Running the installer as administrator is disabled by default, can't install scoop.

https://github.com/ScoopInstaller/Install#for-admin

**Comment by Xyueta** [comment]
use install script from github, if you want to have it working.

**Comment by heroes1412** [comment]
hope in 22h2 version, atlas will update script for installing scoop

**Comment by JayXTQ** [comment]
Is this fixed?

**Comment by Xyueta** [comment]
Fixed in 22H2

**Comment by thaynos** [comment]
> Fixed in 22H2

22h2 is the upcoming version? also will there be no eta updates for small issues like these?

**Comment by JayXTQ** [comment]
> 22h2 is the upcoming version? also will there be no eta updates for small issues like these?

22H2 is unrealised, and there is no ETA
