### ISSUE TITLE
Bug report: Semi-infinite crash loop on latest commit.

### ISSUE THREAD

**Issue by 0xC4aE1e5** [Atlas-OS/Atlas#572]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

On commits bbbe594 and 5054a75 (may happen on other commits, but I tested on these), Explorer.exe will get stuck in a crash loop and after about 2 or so minutes, it returns to normal. Also happens on 1803 (but compiled with 16299.125, which makes it seem to stem from a script, rather than a component removal). 

### Steps to reproduce (if applicable add screenshots)

1. Follow the steps to compile commit bbbe594, and use a 19045.2364 ISO (from UUP dump), along with the 22H2 preset.
2. Install on a VMware Workstation Pro 16.2.4 VM. (I have installed 20H2 v0.5.2 successfully on VMware WP 16.2.4, with no crash loops)
3. Let the post-install scripts finish.
4. Then a explorer crash loop will occur.

### Expected behavior

The system will boot to the desktop without any crash loops or hiccups whatsoever.

### Actual behavior (if applicable add screenshots)

Explorer loads incorrectly, with a crash loop that lasts for about 2 minutes.

![image](https://user-images.githubusercontent.com/111705094/218910590-3bbbce8b-11f4-4970-ae30-72cab40fef01.png)

(The screenshot may look normal, but the icons aren't loading because Explorer is in a crash loop and hasn't loaded them yet)

### Atlas Version (1803/20H2/21H2)

22H2

### Desktop information

- CPU: Intel Core i5 1035G1
- RAM: 2 GB
- Host disk type: NVMe SSD
- Virtualization software: VMware Workstation Pro 16.2.4

**Comment by Zusier** [comment]
This is due to a misconfiguration in services or drivers.. did you change any of the components when you built it?

**Comment by NetGaming69** [comment]
I have a same problem too. It seems like something is causing svchost to crash. I notice this when ThunderEX added something to the config bat

**Comment by Zusier** [comment]
[This?](https://github.com/Atlas-OS/Atlas/commit/b7a524fa9a9bb9b6c7093767fc4de9a4c9b00e40) That shouldn't cause anything like that. I'll try myself tomorrow or the next day.

**Comment by Netxv** [comment]
Nah way earlier. Its between January and December

**Comment by Netxv** [comment]
Alright so I have found out this Commit`https://github.com/Atlas-OS/Atlas/commit/bea7b6c8f681d479cd6c1494d499fec4f656f59f ` (sry ThunderEX 😭) causes AtlasOS to be freezing constantly. Changing it to its original value would make everything run normally (hopefully😅). Hope Zusier can help me publish this since this is my first time using github

**Comment by PencilNavigator** [comment]
@Netxv Fork the repository and do the changes in your repo, then submit a Pull Request (You can see this [Repo](https://github.com/firstcontributions/first-contributions) for guides submitting a PR.)

**Comment by Netxv** [comment]
Okay thanks a lot @PencilNavigator

**Comment by Xyueta** [comment]
Resolved in https://github.com/Atlas-OS/Atlas/commit/7faf7b80e7d180353ca2993868c5ff6b2037b96a

**Comment by wantedboy** [comment]
still having issue like this with new files

**Comment by Xyueta** [comment]
It is gonna be resolved in the version.

**Comment by Netxv** [comment]
> still having issue like this with new files

Weird cause I have fixed it. Tried on 3 different version and even windows 11. Works pretty fine

**Comment by Netxv** [comment]
If you are still having issues, try the version on January 18 to see if there is any issue

**Comment by wantedboy** [comment]
That's weird i've just cloned the files today, also I've checked the atlas-config file the changes were there. @Netxv how can I download an older version may I ask? 
![Screenshot_20](https://user-images.githubusercontent.com/22085435/219682385-399677a0-68ff-4020-a5e7-073cf3a12c6b.png)
![Screenshot_21](https://user-images.githubusercontent.com/22085435/219682389-1e3ba942-329e-4744-83d1-ae72c5f06d21.png)

**Comment by Netxv** [comment]
> That's weird i've just cloned the files today, also I've checked the atlas-config file the changes were there. @Netxv how can I download an older version may I ask?
> ![Screenshot_20](https://user-images.githubusercontent.com/22085435/219682385-399677a0-68ff-4020-a5e7-073cf3a12c6b.png)
> ![Screenshot_21](https://user-images.githubusercontent.com/22085435/219682389-1e3ba942-329e-4744-83d1-ae72c5f06d21.png)

Try this version https://github.com/Atlas-OS/Atlas/tree/b34c3619bc8a1cfc070cff59d0aacc4002d3e060

**Comment by Netxv** [comment]
I’ll rebuild the iso with the new version to see if there is any issue

**Comment by wantedboy** [comment]
Okay let me know :)

**Comment by wantedboy** [comment]
just tried that version its working fine 
![Screenshot_22](https://user-images.githubusercontent.com/22085435/219694153-79d2d309-8b8a-4e49-86d9-20cea9b8cef1.png)

**Comment by Netxv** [comment]
> Okay let me know :)

Ok after testing a bit, you were right due to an error @Xyueta made in this [commit](https://github.com/Atlas-OS/Atlas/commit/7faf7b80e7d180353ca2993868c5ff6b2037b96a)

**Comment by Xyueta** [comment]
Fixed in https://github.com/Atlas-OS/Atlas/commit/07e9aafe811195d27bff417df5a02d4fe90d5147, LanmanServer was the service which might cause it.

Please let me know if it works now.

**Comment by wantedboy** [comment]
Works fine now
