### ISSUE TITLE
Mobile Sync Center running in the background

### ISSUE THREAD

**Issue by 0xC4aE1e5** [Atlas-OS/Atlas#575]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

Mobile Sync Center was removed in the previous guide. With following the steps in the new guide, I noticed the Mobile Sync Center is now running in the background.

### Steps to reproduce (if applicable add screenshots)

1. Compile Atlas (22H2)
2. Install Atlas like you normally would
3. The mobile sync center will be running in the background

### Expected behavior

The mobile sync center will not be running, as it is deleted.

### Actual behavior (if applicable add screenshots)

The mobile sync center is running in the background, as it is not deleted.

### Atlas Version (1803/20H2/21H2)

22H2

### Desktop information

- Processor: Intel Core i5 1035G1
- RAM: 2 GB
- Host disk type: NVMe SSD
- Virtualization software: VMware Workstation Pro 16.2.4

**Comment by Zusier** [comment]
Sync Center is set to be removed on the 22h2 ntlite preset, double check how you built the iso.

**Comment by Xyueta** [comment]
It is not present in the ISO after ntlite removal.
