### ISSUE TITLE
Complaint

### ISSUE THREAD

**Issue by Twichpor** [Atlas-OS/Atlas#582]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

First of all I can't format my Unallocated volume space on my drive and there is some other thing i just can't use, I can't change the "Windows display language", I can't  costumes anything. Its like I downloaded Atlas and just broke my whole pc as it is, I just can't use it properly.
When I try to format my unallocated volume space it just resets to the way it was 

Make a new PROPER video how to install without an usb stick

### Steps to reproduce (if applicable add screenshots)

.

### Expected behavior

.

### Actual behavior (if applicable add screenshots)

.

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

-Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
-8Gb
-TOSHIBA HDWD 110 (idk if its just a buggy ssd or what "KINGSTON SV300S37A120G")
-GTX 1050

### Additional content

.

**Comment by JayXTQ** [comment]
1. The reason that is, is because BitLocker is removed and is added back in 22H2 when released.
2. Display Languages not changing is caused by some reg edit stuff which you can get the fix for easily by googling the errors.
3. Atlas definitely did not break your PC, you are just using it incorrectly.
4. The video teaches you correctly how to do the non-usb method.
