### ISSUE TITLE
Deploying MAUI/UWP fails on Rider

### ISSUE THREAD

**Issue by Bubbet** [Atlas-OS/Atlas#584]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

Building/Deploying a MAUI app from template fails in rider with "Error Running 'MauiApp1': Find package failed return code is 1" it also mentions that deployment failed.
Visual Studio seems to work fine though, oddly enough.

### Steps to reproduce (if applicable add screenshots)

1. Get Microsoft JDK 11 and MS Build Tools to install Maui toolkit
2. Get Rider and create a project from the template
3. Attempt to debug/run the project

### Expected behavior

App builds and deploys to windows.

### Actual behavior (if applicable add screenshots)

App builds, but fails to deploy.

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

- Processor: Ryzen 9 3900X
- Ram: 64gb
- Boot Drive: NVMe Samsung SSD 980 2TB
- GPU: DUAL-RTX2070S-O8G-EVO (2070 Super)

### Additional content

I've tested this on my current install of atlas, and a fresh one in a VM and got the same result.
Everything works fine on vanilla windows.

**Comment by Zusier** [comment]
Can you provide any logs from building it?

**Comment by Bubbet** [comment]
Heres the log folder from Local\Jetbrains\Rider2022.3
[log.zip](https://github.com/Atlas-OS/Atlas/files/10789456/log.zip)

**Comment by Zusier** [comment]
It seems like UAC may be the problem, try enabling it in the atlas folder

**Comment by Bubbet** [comment]
That seems to have fixed it, thanks.
