### ISSUE TITLE
Use chocolatey instead of scoop

### ISSUE THREAD

**Issue by EldonX** [Atlas-OS/Atlas#585]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

i dont really like scoop its bugged and chocolatey would work better

### Describe the solution you would like.

.

### Describe alternatives you have considered.

.

**Comment by Xyueta** [comment]
planning that

**Comment by JayXTQ** [comment]
Check the source code, this has already been implemented.
