### ISSUE TITLE
When i pres win+s,the search apear light,but the theme is on dark

### ISSUE THREAD

**Issue by tudor62** [Atlas-OS/Atlas#587]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

When i pres win+s,the search apear light,but the theme is on dark.What i can do?

### Steps to reproduce (if applicable add screenshots)

![Screenshot (3)](https://user-images.githubusercontent.com/108548448/220439450-4e40d9bb-fb92-4f6a-bb8f-878335835697.png)

### Expected behavior

To rezolve problem

### Actual behavior (if applicable add screenshots)

![Screenshot (3)](https://user-images.githubusercontent.com/108548448/220439550-9bf8db52-d848-44dd-bc31-6feffe9883b1.png)

### Atlas Version (1803/20H2/21H2)

daH2

### Desktop information

-Procesor i3-8100
-Ram-12Gb
-Sdd
-Nvidia Gt 1030
![Capture](https://user-images.githubusercontent.com/108548448/220440135-732a05a5-f5dd-4863-802b-674f47188c8b.PNG)

**Comment by Zusier** [comment]
This is because it's an [older windows version](https://www.neowin.net/news/microsoft-finally-improves-dark-mode-for-windows-10-search/)
