### ISSUE TITLE
Bangla Word does not install

### ISSUE THREAD

**Issue by Govind-Keshri** [Atlas-OS/Atlas#589]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

When trying to install Software called Bangla Word v1.9  Windows\system32\OLEAUT32.dll could not be opened. 
Please check that your disk is not full and that you have access to the destination directly

### Steps to reproduce (if applicable add screenshots)

![5739499](https://user-images.githubusercontent.com/78689542/220990093-0b5eedd3-2ab3-4cb8-a11f-347b7f6af8b3.png)

### Expected behavior

software install smoothly

### Actual behavior (if applicable add screenshots)

software install smoothly

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

Intel pentium g2010

**Comment by Zusier** [comment]
I'm assuming that screenshot is off of google?

**Comment by PencilNavigator** [comment]
Please provide more details and "Actual" screenshots of the error.

**Comment by JayXTQ** [comment]
@Govind-Keshri if no response in 24 hours, I will close. Please follow up
