### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by Js0nGIT** [Atlas-OS/Atlas#59]
Spelling mistake in main > img banenr > banner

might just become albert einstein, you never know

![feeffeefef](https://user-images.githubusercontent.com/83360782/135771600-5a66be1e-181f-4cb4-b8e7-728b5c814d92.PNG)
?

**Comment by Zusier** [comment]
I know how to spell banner.. just a typo. (it's also just a commit message, who cares)

**Comment by Js0nGIT** [comment]
was joking lov u

**Comment by Js0nGIT** [comment]
![eeeeeeeeeeeeeee](https://user-images.githubusercontent.com/83360782/135771732-27585d05-8680-4ac0-be13-0a1abb58e813.png)

had to stick to this inspirational quote i found
