### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sadzyy** [Atlas-OS/Atlas#592]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

msconfig, recovery options(recovery startup)

### Describe the solution you would like.

msconfig maybe an important tool on some situations to troubleshoot.
recovery options so we can get into bios from the os and also bootable drives

### Describe alternatives you have considered.

more compatibility on ACPI (laptop), although it doesnt really matter at all, it should still work at their best if they do
![ACPI](https://user-images.githubusercontent.com/84945798/221474660-d7f36be8-9b93-4888-91f5-2104cee222a8.png)
actually the system could recognize it after updating/installing but will not work after restart

### Additional context.

on 20h2 if possible yeah

**Comment by JayXTQ** [comment]
You didn’t do a thourough check of the Atlas issues. This is re-enabled in 22H2.

**Comment by sadzyy** [comment]
i only see that msconfig is re-enabled, the left of them arent. and im just mentioning it at here again

> You didn’t do a thourough check of the Atlas issues. This is re-enabled in 22H2.

**Comment by JayXTQ** [comment]
20H2 at the latter won’t recieve this update afaik, they may all be dropped due to 22H2. If you want to get the XML files and rebuild with NTLite with BitLocker and MSConfig go ahead.

**Comment by sadzyy** [comment]
alright
