### ISSUE TITLE
changes made to original windows could be documented better

### ISSUE THREAD

**Issue by thaynos** [Atlas-OS/Atlas#596]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

i think that every single change made to the original windows file should be documented on the changes made, along with how to revert them. the changes made section in the current documentation is horribly barebones and only covers the main features.

### Describe the solution you would like.

this was the single worst issue on other "modified" windows isos. there are so many issues that can be fixed only if we had extensive documentation to go through. for example, i had an issue with the first step in the atlas folder, that is installing scoop. it gave me a scoop cant run in admin error, so i tried to run it without admin and i saw that its impossible to do so. i had to research online and figured out that i had to change a group policy. i know this takes a lot of time, its just food for thought for now. idk if other people have this same issue, as im a poweruser who needs some particular features (like run command history).

### Describe alternatives you have considered.

idk

**Comment by Alino001** [comment]
This is almost impossible to do, because the changes are most not revertible, but if they do, they are changes for 3 months or smth, so its pointless. But if the team finds a way to find ALL changes from 2020-2023, it would be possible

**Comment by JayXTQ** [comment]
You never requested support for this or didn't read at all before making the issue. When the scoop error shows it links a documentation on how to install with Admin which is a one line bit of code. To enable normal user support there is a toggle on in the Atlas configuration folder as well and you would have known that if you asked for support. Also, if Atlas doesn't have a feature you require you can build the ISO yourself with changes. We document that well in the /src/ folder in root.
