### ISSUE TITLE
(minor) install scoop batch files launched notepad

### ISSUE THREAD

**Issue by thaynos** [Atlas-OS/Atlas#597]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

creates a notepad popup which i assume is not intentional?

### Steps to reproduce (if applicable add screenshots)

freshly install atlas os
launch the batch file

### Expected behavior

install scoop

### Actual behavior (if applicable add screenshots)

![image](https://user-images.githubusercontent.com/83282129/222532906-5f0bc566-1626-476d-9412-e150d7792f9c.png)

### Atlas Version (1803/20H2/21H2)

20h2

### Desktop information

![image](https://user-images.githubusercontent.com/83282129/222533303-43326b59-77db-4f02-9a79-9259f5c7a813.png)

**Comment by Xyueta** [comment]
You clicked Review Script before executing which makes sense to open notepad :)

**Comment by thaynos** [comment]
what do you mean review script?

**Comment by thaynos** [comment]
my bad im so stupid

**Comment by Xyueta** [comment]
![image](https://user-images.githubusercontent.com/101590573/222534180-f4393597-4fb5-4694-beac-55d7f607ab1b.png)
