### ISSUE TITLE
msconfig is not installed

### ISSUE THREAD

**Issue by gbccd** [Atlas-OS/Atlas#602]
### Prerequisites

- [x] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

when i start ms config from the "run"
menu the system tell me that no app with this name

### Steps to reproduce (if applicable add screenshots)

HG
G
G

### Expected behavior

HG

### Actual behavior (if applicable add screenshots)

HG

### Atlas Version (1803/20H2/21H2)

21H2

### Desktop information

i3 4150t
8 gb ram
500 gb storage hdd

### Additional content

gg*
![windows_cannot_find_msconfig](https://user-images.githubusercontent.com/95908225/224131727-df194b0b-8752-4b2c-8bde-5c66dec2a70d.jpg)

**Comment by lirikaontheplace** [comment]
Atlas has stripped **msconfig**, why is that?

It's removed as it depends on BitLocker, which is stripped.

Alternatively:
- To edit boot entries, use EasyBCD https://neosmart.net/EasyBCD/#comparison
- To "unlock" cores, don't do anything. Unlocking cores is placebo.
- To edit services/startup items, use serviwin, autoruns or services.msc (Win+r)
- To manage partitions use Macrorit https://macrorit.com/partition-magic-manager/free-edition.html

**Comment by JayXTQ** [comment]
This will get fixed in 22H2. For now use the options above to try get around this.
