### ISSUE TITLE
graphic driver in tlauncher

### ISSUE THREAD

**Issue by nabiloi** [Atlas-OS/Atlas#612]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

graphic driver change from nvidia to galium

### Steps to reproduce (if applicable add screenshots)

1.open tlauncher
2.open minecraft[all versions]
![Screenshot (5)](https://user-images.githubusercontent.com/75988498/227032086-2b3be8fc-2054-4fca-8cc8-2587b7aa0f7b.png)

### Expected behavior

graphics driver shows nvidia driver instead of gallium 0.4

### Actual behavior (if applicable add screenshots)

graphic driver change from nvidia to galium

### Atlas Version (1803/20H2/21H2)

21H2 [Atlas_v0.5.2]

### Desktop information

![Screenshot (6)](https://user-images.githubusercontent.com/75988498/227033750-be1db04c-3a6d-451b-95d5-d8d24deacd06.png)

![Screenshot (7)](https://user-images.githubusercontent.com/75988498/227033837-bad0df29-53a1-44c2-9fa4-1cf1d876dd34.png)
![Screenshot (8)](https://user-images.githubusercontent.com/75988498/227033903-20184f0b-9f67-47a7-8b1c-4f8795b37d56.png)
![Screenshot (9)](https://user-images.githubusercontent.com/75988498/227033955-62f381d1-983c-43e4-8370-0936cbce55fa.png)

### Additional content

I don't know if this is a bug or not, so I made this

**Comment by JayXTQ** [comment]
This doesn’t seem like an atlas issue, what have you tried to mitigate the issue? Have you installed graphics drivers? Have you selected Minecraft to use your GPU and not your iGPU?

**Comment by nabiloi** [comment]
> This doesn’t seem like an atlas issue, what have you tried to mitigate the issue? Have you installed graphics drivers? Have you selected Minecraft to use your GPU and not your iGPU?

Yes, I have installed the graphics driver
[NVIDIA System Information 03-23-2023 20-18-04.txt](https://github.com/Atlas-OS/Atlas/files/11051222/NVIDIA.System.Information.03-23-2023.20-18-04.txt)
![Screenshot (10)](https://user-images.githubusercontent.com/75988498/227216736-f20d8dba-7c07-4ada-8306-580d484f88d7.png)
![Screenshot (11)](https://user-images.githubusercontent.com/75988498/227216761-4404d146-c101-42d5-a88a-515d9605c588.png)
But, how do I select Minecraft to use the installed GPU instead of the iGPU ?

**Comment by nabiloi** [comment]
is this problem due to the jvm argument that I used?, but in normal win11 it's normal or it displays "nvidia geforce 920mx"
[java_argument-tlauncher.txt](https://github.com/Atlas-OS/Atlas/files/11051347/java_argument-tlauncher.txt)
this is the jvm argument I used

**Comment by Lazylllama** [comment]
I thought this was common sense not to allow support for piracy but I guess not.

**Comment by JayXTQ** [comment]
This is piracy? I don’t use alternate launchers for Minecraft. If this is piracy I will close this

**Comment by PencilNavigator** [comment]
Please consider using an official launcer or an alternative open-source launcher. TLauncher is considered as piracy and will not receive any support.
