### ISSUE TITLE
[BUG REPORT] - Can't use Xbox remote play

### ISSUE THREAD

**Issue by hronro** [Atlas-OS/Atlas#614]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

I can open the Xbox app, and downloading games in the Xbox app works properly. However when I click the button of connecting to my console, the Xbox app stays on a black screen until I force close it.

I also tried [Xbox Game Streaming (Test App)](https://www.microsoft.com/store/apps/9NZBPVPNLDGM) (which can be downloaded from https://store.rg-adguard.net with copy and paste the URL `https://www.microsoft.com/p/xbox-game-streaming-test-app/9nzbpvpnldgm?activatetab=pivot:overviewtab&rtc=`1 into it). This app crashed immediately after I opened it.

### Steps to reproduce (if applicable add screenshots)

N/A

### Expected behavior

The Xbox app the Xbox Game Streaming app should works.

### Actual behavior (if applicable add screenshots)

![image](https://user-images.githubusercontent.com/15059605/227246216-5dd8a0e0-5069-405f-b039-1c24f87c520d.png)

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

- AMD 5800X
- 32GB Ram
- Nvidia 1650Super

**Comment by PencilNavigator** [comment]
i am guessing that this relys on RDP which is removed? 
Try 22H2 see if it fixes this problem.

**Comment by JayXTQ** [comment]
I'm giving 24 hours for you to respond @hronro before I close the issue

**Comment by hronro** [comment]
Still not work in 22H2

**Comment by Xyueta** [comment]
Possibly re solved in https://github.com/Atlas-OS/Atlas/commit/e5a67a343fccd46fba67877129181708aa48df08.

**Comment by JayXTQ** [comment]
Can someone test if this is fixed in the dev builds made (GitHub Actions)
