### ISSUE TITLE
Cannot login to microsoft online

### ISSUE THREAD

**Issue by vargalex** [Atlas-OS/Atlas#621]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

Hi!

I cannot login on teams.microsoft.com or office.com from firefox and can only login to office.com from Edge. But teams does not work in both browsers, only teams application working.

### Steps to reproduce (if applicable add screenshots)

1. Open firefox
2. Open office.com
3. Click on login

### Expected behavior

Login to office.com

### Actual behavior (if applicable add screenshots)

The browser goes through multiple redirects and returning to office.com

### Atlas Version (1803/20H2/21H2)

2009

### Desktop information

- AMD Ryzen 5500
- 16 GB RAM
- 1 TB NVME SSD
- GTX1070 8 GB

**Comment by PencilNavigator** [comment]
Atlas does not have a "2009" version. If that's the version you are using, it's not atlas and will not receive any support from the atlas team.
This is likely not an atlas issue. Please check your hosts, DNS settings.

**Comment by SnowzNZ** [comment]
2009 is 20H2

**Comment by PencilNavigator** [comment]
> 2009 is 20H2

Apologies on that, but your problem is still likely not an atlas issue. Please check your hosts, DNS settings.

**Comment by vargalex** [comment]
I have no issues with my DNS settings on normal Windows 10 installation and on linux...
