### ISSUE TITLE
BitDefender scan breaks Atlas

### ISSUE THREAD

**Issue by Totallynotmwa** [Atlas-OS/Atlas#624]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

There is this bug that was happening for a long time on atlas 

### Steps to reproduce (if applicable add screenshots)

1 install atlas
2. Try scanning

### Expected behavior

It should scan for virus and there should be no viruses

### Actual behavior (if applicable add screenshots)

It says error and then my pc starts having problems

### Atlas Version (1803/20H2/21H2)

21h2

### Desktop information

I3 12100f
Gtx 1650
8gb ram
256gb ssd

### Additional content

I tried this on bitdefender
This should be fixed on 22h2

**Comment by JayXTQ** [comment]
Try a different antivirus for me rather than one. If this issue does not repeat please close this issue as it is most likely an anti-virus issue.

**Comment by Totallynotmwa** [comment]
when 22h2 comes out

**Comment by Totallynotmwa** [comment]
also how to fix i am unable to update microsoft store

**Comment by Totallynotmwa** [comment]
i also managed to fix it by restarting it worked but my antivirus deacted a virus

**Comment by Totallynotmwa** [comment]
1. I forgot what bit defender said 
2. Welp when i try to scan it says an error when i restart it fixes but my bit defender found a virus i didnt remove it and some components started to break like changing the wallpaper blah blah blah

**Comment by Totallynotmwa** [comment]
It happens every install

**Comment by KanekiLeChomeur** [comment]
Check maybe if it's an infection from the usb you used to install Atlas

**Comment by Zusier** [comment]
It's hard to help you without more information. Could you provide a screenshot of the bitdefender scan?

**Comment by Totallynotmwa** [comment]
![Uploading 77E4B969-8EB5-4EE6-9C11-A808784D2DB8.png…]()

**Comment by Zusier** [comment]
Can you get a error code or logs, again this is a bit vague.

**Comment by PencilNavigator** [comment]
Changed the title since Atlas does not have "virus" included.

**Comment by Totallynotmwa** [comment]
> Changed the title since Atlas does not have "virus" included.

Ok

**Comment by Totallynotmwa** [comment]
> Can you get a error code or logs? Again this is a bit vague.

No

**Comment by Totallynotmwa** [comment]
> Can you get a error code or logs? Again this is a bit vague.

I might try using that partition’s method to see if the same problem happens but since bitdefender expired i will use amother anti virus

**Comment by Totallynotmwa** [comment]
I might close this thread if i fix this annoying problem

**Comment by Totallynotmwa** [comment]
> 

Oke
