### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by DieYoungZ** [Atlas-OS/Atlas#625]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

It's a problem for me, i can't enable file and printer sharing, i need it to create a file server on my pc.

### Describe the solution you would like.

If there is any possible solution for this, please help. If not  can you please add this feature in next update?

### Describe alternatives you have considered.

Intel Unison, but it's working not the way i wish it to work

**Comment by JayXTQ** [comment]
Did you try enabling printing within the atlas folder?

**Comment by JayXTQ** [comment]
Also seems like you didn't even search for printing in the atlas issues so I will close this issue, you may find your answer in #221
