### ISSUE TITLE
[BUG REPORT] - Teredo Blocking Xbox Multiplayer Connectivity

### ISSUE THREAD

**Issue by aShanki** [Atlas-OS/Atlas#626]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

Teredo unable to qualify, blocking me from playing minecraft bedrock edition online with friends.
![image](https://user-images.githubusercontent.com/81349208/228809910-7908a0f3-c915-4302-a7ba-ab79b95bbc78.png)
![image](https://user-images.githubusercontent.com/81349208/228809918-17811a28-300f-4a4a-a3b5-aa4c87488334.png)

Before you ask, yes other people are able to join this friends world. In addition this behavior was not replicable on regular windows 10 for me. 

### Steps to reproduce (if applicable add screenshots)

1. Open minecraft bedrock edition
2. Try to join friend's multiplayer world
3. Get unable to connect error 
![image](https://user-images.githubusercontent.com/81349208/228810396-aee2ab63-0b72-436b-822a-15fa6616b199.png)

### Expected behavior

Join the world and play the game

### Actual behavior (if applicable add screenshots)

Unable to connect to world
![image](https://user-images.githubusercontent.com/81349208/228810626-ffda954c-a797-416d-a811-60af3f246c01.png)

### Atlas Version (1803/20H2/21H2)

20H2

### Desktop information

i3-8130U, 16GB RAM, UHD 620 Graphics

**Comment by Totallynotmwa** [comment]
https://answers.microsoft.com/en-us/xbox/forum/all/teredo-is-unable-to-qualify-and-server/c1303ded-ef09-47e0-b17f-e28dc6627fab

**Comment by aShanki** [comment]
![image](https://user-images.githubusercontent.com/81349208/229129936-5da56ca3-1aa0-46d2-86e5-6a7acc7f09a2.png)

Have followed the following guide and am still getting the same results.

**Comment by JayXTQ** [comment]
Did you enable FSO and Game Bar? Did you try enabling UWP? Also, this issue may be closed as 22H2 is releasing very soon. (Aprox 5 hours from this comment)

**Comment by aShanki** [comment]
FSO is enabled, Game Bar is not. UWP is enabled. Hopefully this issue is fixed in 22H2, we shall find out <3

**Comment by PencilNavigator** [comment]
Please try out 22H2 see if it fixes this problem.

**Comment by Xyueta** [comment]
issue on 22H2

**Comment by PencilNavigator** [comment]
Teredo is unable to qualify / Xbox Live multiplayer issue

"Teredo is a driver/service that needs to run to allow xbox multiplayer to work correctly, the easiest example of this is Forza horizon 4/5 where the multiplyer connection will timeout after trying to connect for X amount of time. There are ALOT of reddit and Microsoft official posts about this issue, however the only fix that seems to work is the following.

Running these commands at admin level in CMD
`netsh int teredo set state disable`
`netsh int teredo set state type=default`
`netsh int teredo set state enterpriseclient`
`netsh int teredo set state servername=teredo.remlab.net`

However it's very hit and miss whether it resolves the issue, sometimes it works for 3 hours and sometimes it works until the next reboot."

Please try the above method see if it fixes the issue.

**Comment by JayXTQ** [comment]
`The following helper DLL cannot be loaded: WWANCFG.DLL.` for every command

**Comment by aShanki** [comment]
> Teredo is unable to qualify / Xbox Live multiplayer issue
> 
> "Teredo is a driver/service that needs to run to allow xbox multiplayer to work correctly, the easiest example of this is Forza horizon 4/5 where the multiplyer connection will timeout after trying to connect for X amount of time. There are ALOT of reddit and Microsoft official posts about this issue, however the only fix that seems to work is the following.
> 
> Running these commands at admin level in CMD `netsh int teredo set state disable` `netsh int teredo set state type=default` `netsh int teredo set state enterpriseclient` `netsh int teredo set state servername=teredo.remlab.net`
> 
> However it's very hit and miss whether it resolves the issue, sometimes it works for 3 hours and sometimes it works until the next reboot."
> 
> Please try the above method see if it fixes the issue.

Still doesn't work even after these changes

**Comment by Xyueta** [comment]
Possibly re solved in https://github.com/Atlas-OS/Atlas/commit/e5a67a343fccd46fba67877129181708aa48df08.

**Comment by Xyueta** [comment]
This issue has been resolved in this commit: https://github.com/Atlas-OS/Atlas/commit/8d48b015d7b32545760c9336bdbcebd2f6350535

Even stock Windows 10 shows that, the Teredo is not qualified, despite it being fully qualified. It can be checked using the
``netsh interface teredo show state`` command in Command Prompt.

**Comment by he3als** [comment]
Is this now fixed? If so, should it be unpinned?

**Comment by Xyueta** [comment]
no, it can not be unpinned, because that's a windows issue and fully explanation is here.

**Comment by Xyueta** [comment]
I will probably insure it by adding the enterpriseclient. If the server connectivity works, then it should be all good to go. 👍

**Comment by jordanamr** [comment]
Found a fix that worked for me on 22H2 :
1. Open the Xbox Networking page in Settings > Gaming
2. Wait for the check to say that Teredo is not working
3. Click "Fix it"
4. Once it's done, run that command in an Administrator cmd: `netsh int teredo set state enterpriseclient`
5. Click "Check again", it should show that it's working

**Comment by Xyueta** [comment]
![image](https://github.com/Atlas-OS/Atlas/assets/101590573/0984547e-a3cf-4d04-a4f1-9de156cc65ff)
