### ISSUE TITLE
Visual Studio 2022 BSOD

### ISSUE THREAD

**Issue by RobinTR** [Atlas-OS/Atlas#639]
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

Starting an asp.net project in debbuging mode windows gives blue screen.

### Steps to reproduce (if applicable add screenshots)

1. Open Visual Studio
2. Create an ASP.NET Core Web App
3. Start project in debbuging mode default or iis express selected.
4. Both gives bsod
![Screenshot_1](https://user-images.githubusercontent.com/11340002/229286103-88063341-d268-4838-adc2-cf58973bc8b3.png)

### Expected behavior

Should work normally not windows crash. (Also it was giving bsod in 20H2 but i wanted to try in today 22H2 version its still gives bsod)

### Actual behavior (if applicable add screenshots)

![bsd](https://user-images.githubusercontent.com/11340002/229286013-9dc77386-7fc6-4639-b2cf-d535753b419a.jpeg)

### Atlas Version (1803/20H2/21H2)

22H2

### Desktop information

Intel i3-8100
16 GB 2400MHz DDR4
SSD
Gtx 1060 3GB

**Comment by lemonekq** [comment]
looks to me like an ram issue. You never had that issue using vs2022 with other oses? bsod shows memory access violation/Null Pointer Exception.

try memtest86+ https://www.memtest.org/

**Comment by RobinTR** [comment]
> looks to me like an ram issue. You never had that issue using vs2022 with other oses? bsod shows memory access violation/Null Pointer Exception.
> 
> try memtest86+ https://www.memtest.org/

Nope its fine with stock windows and revios. I get this crash also with ggos

**Comment by JayXTQ** [comment]
It is probably an issue on your end then if this repeats on ggOS. Is there any logs to show a reason why this is happening? If not we can't really do much to help as I never got this issue with VS 2022

**Comment by RobinTR** [comment]
> It is probably an issue on your end then if this repeats on ggOS. Is there any logs to show a reason why this is happening? If not we can't really do much to help as I never got this issue with VS 2022

Visual Studio default C# projects are fine. Problem is not my end, same behavior with atlas and ggos. If u have visual studio can u try install asp.net and try my steps to see whats happen? There is something wrong with the starting web service in asp.net both atlas and ggos. Also revios and stock windows doesn't have this problem i can just use fine, it's not releated to my pc.

**Comment by JayXTQ** [comment]
You didn't mention what type of web app you were running to get this issue, react or angular?

**Comment by JayXTQ** [comment]
Nevermind, I forgot to install the pack.

**Comment by JayXTQ** [comment]
Alright, just did some testing. No BSOD with the exact same thing you did. @Xyueta can you confirm that you don't or do get crashes either?

**Comment by Xyueta** [comment]
No issue

**Comment by JayXTQ** [comment]
Closing issue, I hope you find your solution!

**Comment by RobinTR** [comment]
I created 19045.2788 iso with uupdump and checked windows updates then installed atlas yesterday didn't do anything different what could be problem idk. I did memtest to be safe and no problem. 
![sd](https://user-images.githubusercontent.com/11340002/229349937-d7354752-dec4-4b2e-a90d-d53cc317dc2c.jpeg)

**Comment by Aranxtonel** [comment]
No updates on this issue so far?

**Comment by RobinTR** [comment]
I just tried with Windows 11 August MSDN iso + latest dev playbook (https://github.com/Atlas-OS/Atlas/actions/runs/6085616162) in vm it worked fine. When 0.3 get released i also will try with real hardware not vm.
