### ISSUE TITLE
Stuck at "Reticulating splines.." 

### ISSUE THREAD

**Issue by dtcu0ng** [Atlas-OS/Atlas#643]
### Description

Playbook stuck at "Reticulating splines..." and do nothing

### Steps to reproduce (if applicable add screenshots)

1. Install Windows 10 22H2 by UUPDump
2. Follow the instruction in docs.atlasos.net
3. Playbook gets stuck at "Reticulating splines.." after "Installing vcredist"

### Expected behavior

It will do the Atlas optimization.

### Actual behavior (if applicable add screenshots)

Playbook gets stuck at "Reticulating splines.."

### Atlas Version (1803/20H2/21H2)

22H2

### Desktop information

- CPU: Intel Xeon E3-1241v3
- RAM: 8GB (4x2 DDR3)
- Storage: 128GB SSD
- Graphics: Nvidia Geforce GTX 1050

### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Additional content

![z4230586927981_4a00dcb887817b165f118e75865ab420](https://user-images.githubusercontent.com/34135258/229305671-1e1f8f4f-62c8-4c4a-90df-e9571fbc3592.jpg)
It seems the Playbook will install vcredist and Chocolatey but nothing is installed. Some changes like profile account picture are applied

**Comment by JayXTQ** [comment]
Can you try putting the playbook and toolbox files on the desktop then running the installer again?

**Comment by dtcu0ng** [comment]
> Can you try putting the playbook and toolbox files on the desktop then running the installer again?

I've rolled back to Atlas 21H2, but will try on VM.

**Comment by dtcu0ng** [comment]
Seems its works, but it's very slow. Almost 1hr and this still not finish (I think the VM is too weak to run)
![image](https://user-images.githubusercontent.com/34135258/229353616-4577e80a-0254-4ec0-89bd-cafe05cc7b14.png)

**Comment by JayXTQ** [comment]
well it works, atleast. closing issue as this was the original issue.

**Comment by roiding** [comment]
same problem.
22H2 in macbook air(Paraellels Desktop)
after "Installing vcredist"
How long did you go there

**Comment by JayXTQ** [comment]
> same problem.
> 22H2 in macbook air(Paraellels Desktop)
> after "Installing vcredist"
> How long did you go there

If this macbook is a silicon chip. Then atlas doesn’t work.

**Comment by haightc** [comment]
same issue for me over and hours and no progress

**Comment by jasestu** [comment]
Seems to have stalled at this step for me. Inspiron 1525 core 2 duo T5800. TrustedUninstaller.CLI sitting at 35% processor usage for a couple hours with no movement in the reticulating splines (go Sim City) progress bar.

**Comment by jasestu** [comment]
Seems to have stalled at this step for me. Inspiron 1525 core 2 duo T5800. TrustedUninstaller.CLI sitting at 35% processor usage for a couple hours with no movement in the reticulating splines (go Sim City) progress bar. Installed via a Ventoy boot, ran the regedit to stop driver updates and playbook etc copied to desktop before running.

**Comment by gdnzz** [comment]
@jasestu @haightc @dtcu0ng @roiding
![Uploading IMG_20230425_091635.jpg…]()

**Comment by gdnzz** [comment]
![IMG_20230425_091635](https://user-images.githubusercontent.com/76991571/234190394-d2329f3b-624c-412c-90e9-af1bff6ca1a1.jpg)

**Comment by jasestu** [comment]
> ![IMG_20230425_091635](https://user-images.githubusercontent.com/76991571/234190394-d2329f3b-624c-412c-90e9-af1bff6ca1a1.jpg)

Thanks, that works.

**Comment by JayXTQ** [comment]
Should be fixed in the next release again! But thanks for the temporary fix!

**Comment by 969Furqan** [comment]
I cannot find the curl process in the task manager, have killed powershell and windows command processor yet the progress in reticulating splines is halted

**Comment by JayXTQ** [comment]
I recommend installing vcredists directly then and not relying on the playbook to do it

**Comment by itsprakashp** [comment]
> I cannot find the curl process in the task manager, have killed powershell and windows command processor yet the progress in reticulating splines is halted

I think you're searching for curl please search for "The Curl Executable".

**Comment by Abdalrahman-mamdouh** [comment]
Hello, I have the same problem. It has been stuck at reticulating splines for four hours now. I tried to reset my computer, and I also killed The curl executable, powershell, and Windows Command Processor, and still it didn't work. I even tried reinstalling Windows and AtlasOS again and it still didn't work. Can anyone help?

**Comment by Abdalrahman-mamdouh** [comment]
Hello, I have the same problem. It has been stuck at reticulating splines for four hours now. I tried to reset my computer, and I also killed The curl executable, powershell, and Windows Command Processor, and still it didn't work. I even tried reinstalling Windows and AtlasOS again and it still didn't work. Can anyone help?

**Comment by itsprakashp** [comment]
> Hello, I have the same problem. It has been stuck at reticulating splines for four hours now. I tried to reset my computer, and I also killed The curl executable, powershell, and Windows Command Processor, and still it didn't work. I even tried reinstalling Windows and AtlasOS again and it still didn't work. Can anyone help?

Try to manually install VCRedis 2012-2022 from (https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) before running the playbook

**Comment by danijamali** [comment]
I Installed it from Microsoft, and I am still facing the same bug, please fix this, I am moving to Ghost Spectre until you fix this bug.

**Comment by JayXTQ** [comment]
@danijamali it is fixed :) if i can find the commit number ill reference this issue

**Comment by danijamali** [comment]
It's done installing, i used that powershell trick

**Comment by JayXTQ** [comment]
What?

**Comment by danijamali** [comment]
I was stuck at this issue, i stopped powershell, cmd and the curl
executable. It worked

**Comment by JayXTQ** [comment]
You aren't supposed to do that, you may have broken your install.

**Comment by danijamali** [comment]
I tried every other way but it didn't work, i had to resort to that

**Comment by JayXTQ** [comment]
Did you join our Discord for support? I didn't see you asking for help here

**Comment by Xyueta** [comment]
Fixed already by configurating Visual Redist C++ installation.

**Comment by Xyueta** [comment]
Did you install from Github Actions? Also what is your region?

**Comment by PencilNavigator** [comment]
https://docs.atlasos.net/troubleshooting/common-issues/reticulating-splines/
check here.
