### ISSUE TITLE
"Unlock Start Menu Tiles" script doesn't work

### ISSUE THREAD

**Issue by ravenekse** [Atlas-OS/Atlas#644]
### Description

When I try to restore the tiles in the start menu by running a script, nothing happens. Yes, the script runs, but after restarting the computer, the option to add tiles in the start menu does not appear. You have to manually remove the registry entries to restore the tiles in the Start menu

### Steps to reproduce (if applicable add screenshots)

1. Run script from C:\....\Desktop\Atlas\3. Configuration\1. General Configuration\Start Menu\Unlock Start Menu Tiles.cmd
2. Restart PC
3. Nothing has changed

### Expected behavior

Return of the ability to pin programs in the start menu as tiles

### Actual behavior (if applicable add screenshots)

No changes

### Atlas Version (1803/20H2/21H2)

22H2

### Desktop information

- Intel i5 4690K
- 16GB RAM
- SSD Drive
- GPU AMD RX480

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
This script should be working in the next update, please comment if not when it comes out!
