### ISSUE TITLE
[BUG REPORT] - Cannot enable Hyper-V

### ISSUE THREAD

**Issue by rex69420** [Atlas-OS/Atlas#645]
### Description

Hyper-V is not enabled after running the included cmd file and restarting.

### Steps to reproduce (if applicable add screenshots)

1) Go to Atlas folder --> 3. Configuration\1. General Configuration\Hyper-V and VBS
2) Run Enable Hyper-V and VBS.cmd
3) Error messages show up, and after restarting, Hyper-V is not enabled.

### Expected behavior

Hyper-V would get enabled.

### Actual behavior (if applicable add screenshots)

![cmd_K8OvjNJgPy](https://user-images.githubusercontent.com/65942753/229314435-944a1e78-c0a0-4f74-9780-860dc72c335b.png)
![powershell_uR08oO2xjQ](https://user-images.githubusercontent.com/65942753/229314437-55fc7731-2a8a-4c6a-b720-a0dfe9d7cd97.png)

### Atlas Version

Atlas 10 22H2

### Desktop information

- Ryzen 5 3500
- 16GB RAM
- GTX 1660
- Windows installed on SSD.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.com/invite/atlasos).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
I take it the script was ran as admin?

**Comment by SnowzNZ** [comment]
Same issue here

**Comment by JayXTQ** [comment]
Seems like a repeating issue, will be fixed next update

**Comment by JayXTQ** [comment]
Will be fixed in the next update
