### ISSUE TITLE
[BUG REPORT] - Acer Nitro Sense

### ISSUE THREAD

**Issue by KonoKore** [Atlas-OS/Atlas#646]
### Description

Acer Nitro Sense does not work even after 3 reinstalls.

### Steps to reproduce (if applicable add screenshots)

1. Install Nitro Sense
2. Open
3. Profit

### Expected behavior

Acer Nitro Sense allows the fan speeds to be adjusted.

### Actual behavior (if applicable add screenshots)

Fans speed is not adjustable.

### Atlas Version

Atlas 10 22H2

### Desktop information

![image](https://user-images.githubusercontent.com/128200152/229324366-a1a6a291-6a06-4e03-92dc-cf400ad70ec0.png)

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.com/invite/atlasos).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
I take it the app opens but doesn't load the stats? Because that is what I am getting here too
![image](https://user-images.githubusercontent.com/54886938/229339229-dcb60282-cff8-49b1-aa5f-651d0129d4f0.png)

**Comment by KonoKore** [comment]
That's exactly what it looks like whenever I open it, not able to see stats nor control the internal fans.

**Comment by KonoKore** [comment]
Found a fix, turning on power features in the power management folder allows NitroSense to work properly

**Comment by MskSuntRoman** [comment]
> Found a fix, turning on power features in the power management folder allows NitroSense to work properly
Could you upload the power management folder or give me the command line? I can't find it in my Atlas folder, it might have been corrupted or it didn't install properly.

**Comment by Xyueta** [comment]
This should be working fine (as of version 0.2.0), the script automatically checks for your setup and sets proper changes

**Comment by MskSuntRoman** [comment]
I need the script if you can give it to me and tell me how to run it please.

**Comment by JayXTQ** [comment]
it runs automatically. please read xyueta's message. this only works from 0.2.0 (and above, if using testing versions)

**Comment by MskSuntRoman** [comment]
I don't have the power management folder in my Atlas folder, that's why I need it from someone that has it.
