### ISSUE TITLE
[BUG REPORT] - Camera

### ISSUE THREAD

**Issue by KonoKore** [Atlas-OS/Atlas#647]
### Description

Integrated Camera does not work.

### Steps to reproduce (if applicable add screenshots)

1. turn camera on
2. profit

### Expected behavior

camera turns on and shows **me**

### Actual behavior (if applicable add screenshots)

camera does nothing, neither does the indicator light turn on

### Atlas Version

Atlas 10 22H2

### Desktop information

![image](https://user-images.githubusercontent.com/128200152/229327614-8291a7eb-fd83-4331-98fc-e8864c8f9103.png)

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.com/invite/atlasos).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
Did you install webcam drivers? Did you check online to see if someone has a solution for this issue? Also, this issue has been reported before so this is pretty much a duplicate but as it's for 22H2 I will leave it open for discussion.

**Comment by KonoKore** [comment]
My integrated camera never needed drivers in 2021 with windows 10, windows 11 22H2, and then Atlas 22H2.

**Comment by Antag0nisticWomble** [comment]
Atlas removes several unnecessary drivers. I had to remove the device and then reinstall the drivers for it to work.

**Comment by KonoKore** [comment]
I mean Pencil already put this as a PlayBook issue

**Comment by PencilNavigator** [comment]
@KonoKore label "playbook" and "wizard" is used to mark either it's an possible AME issue or possible Atlas Playbook issue. it is not “confirmed” to be a playbook issue (which pending label is used for).

**Comment by KonoKore** [comment]
Ah alright, thanks pencil

**Comment by JayXTQ** [comment]
> Atlas removes several unnecessary drivers. I had to remove the device and then reinstall the drivers for it to work.

Reinstalling did not work for me, do you mean from device manager where you click Uninstall on the driver then scan for hardware changes?

**Comment by Antag0nisticWomble** [comment]
> > Atlas removes several unnecessary drivers. I had to remove the device and then reinstall the drivers for it to work.
> 
> Reinstalling did not work for me, do you mean from device manager where you click Uninstall on the driver then scan for hardware changes?

Yes uninstall from device manager and scan for hardware changes.

**Comment by bandinfinite** [comment]
It is working. Just hop on to Device Manager. Select Cameras. Right click on the driver and uninstall. Then, Restart your pc. Camera's working fine tbh. If any issues, search for drivers in OEM's website @KonoKore

**Comment by JayXTQ** [comment]
Already tried this for myself, didn’t work for me.

**Comment by bandinfinite** [comment]
Hmmph... Mine is an unbranded chinese camera... it doesn't need any drivers... so I think yours is a branded one....

**Comment by JayXTQ** [comment]
Acer, my laptops manufacturer, has not got a webcam driver on their website to download. So there is no drivers.

**Comment by Antag0nisticWomble** [comment]
There are always drivers available somewhere even if your manufacturer doesn't haven them. Googling your cameras hardware ID will usually find you something. Or use SDIO as the guide says

**Comment by JayXTQ** [comment]
I obviously did use SDIO as well, and I don't know my camera's hardware ID
