### ISSUE TITLE
[BUG REPORT] - Photos not showing unless opened with MS photos

### ISSUE THREAD

**Issue by KonoKore** [Atlas-OS/Atlas#648]
### Description

Read the title

### Steps to reproduce (if applicable add screenshots)

1. open folder full of photos
2. profit

### Expected behavior

Photos show even when not opened with MS photos

### Actual behavior (if applicable add screenshots)

Photos do not show

### Atlas Version

Atlas 10 22H2

### Desktop information

![image](https://user-images.githubusercontent.com/128200152/229330913-9af2cca3-0c63-4f09-b16e-5bc9bb353d08.png)

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.com/invite/atlasos).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
This doesn't look like an Atlas issue as the computer name would be "ATLAS-[insert random chars]". Are you sure you are on Atlas?

**Comment by KonoKore** [comment]
I have used the playbook and installed atlas onto my system, I was originally running windows 11 before I installed 22H2.

**Comment by JayXTQ** [comment]
For me, Windows Photo Viewer works for viewing multiple photos in a folder. Are you talking about the UWP app of Photos or Windows Photo Viewer?

**Comment by KonoKore** [comment]
UWP version

**Comment by JayXTQ** [comment]
Can you try Windows Photo Viewer then for me and see if you get the same issue, if you do this is likely on your end not mine.

**Comment by JayXTQ** [comment]
@KonoKore
