### ISSUE TITLE
[FEATURE REQUEST] - Start button icon

### ISSUE THREAD

**Issue by KonoKore** [Atlas-OS/Atlas#649]
### What is your Feature Request regarding to?

The Atlas OS

### Is your feature request related to a problem? Please describe.

Windows start button icon changer

### Describe the solution you would like.

A batch script to change the windows start button icon to the Atlas Logo

### Describe alternatives you have considered.

OpenShell

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.com/invite/atlasos).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
No, this can be done with open-shell.
