### ISSUE TITLE
[BUG REPORT] - LibreOffice

### ISSUE THREAD

**Issue by maciejek997** [Atlas-OS/Atlas#650]
### Description

LibreOffice can't launch due to a missing DLL file "davhlpr.dll".

### Steps to reproduce (if applicable add screenshots)

1. Install LibreOffice.
2. Try to run any of their suite program.
3. Windows displays "soffice.bin - System Error" with information about missing "davhlpr.dll".

### Expected behavior

LibreOffice would launch without any problems.

### Actual behavior (if applicable add screenshots)

![image](https://user-images.githubusercontent.com/97791277/229351291-383acb4e-6857-4c74-a651-a72e5e0edecf.png)
That's in Polish, but I can assure you that the meaning of this error is the same in English.

### Atlas Version

Atlas 10 22H2

### Desktop information

- CPU: Ryzen 5 1600 AF
- RAM: 2x8GB 2800MHz
- System is installed on SSD
- GPU: Sapphire Radeon RX 580 NITRO+

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.com/invite/atlasos).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Additional content

This can be quickly fixed by downloading missing DLL from eg. dll-files.com and putting it into `\Windows\System32\`, but I think not many people actually trust this kind of sites.

**Comment by lemonekq** [comment]
davhlpr.dll == WebDAV?

I found packages responsible for that:



	Line  755: #  - !systemPackage: {name: 'Microsoft-Windows-IIS-WebDAV-Deployment-LanguagePack', arch: amd64, language: 'en-US'}

	Line  756: #  - !systemPackage: {name: 'Microsoft-Windows-IIS-WebDAV-Deployment', arch: amd64, language: 'neutral'}

	Line  757: #  - !systemPackage: {name: 'Microsoft-Windows-IIS-WebDAV-ServerCommon-Deployment-LanguagePack', arch: amd64, language: 'en-US'}

	Line  758: #  - !systemPackage: {name: 'Microsoft-Windows-IIS-WebDAV-ServerCommon-Deployment', arch: amd64, language: 'neutral'}

	Line 1165:   - !systemPackage: {name: 'Microsoft-Windows-WebDAVRedir-ClientOnly', arch: amd64, language: 'neutral'}

	Line 1166:   - !systemPackage: {name: 'Microsoft-Windows-WebDAVRedir-ClientOnly', arch: wow64, language: 'neutral'}

	Line 1167:   - !systemPackage: {name: 'Microsoft-Windows-WebDAVRedir-DavClient', arch: amd64, language: 'neutral'}

	Line 1168:   - !systemPackage: {name: 'Microsoft-Windows-WebDAVRedir-DavClient', arch: wow64, language: 'neutral'}

	Line 1169:   - !systemPackage: {name: 'Microsoft-Windows-WebDAVRedir-Helper', arch: amd64, language: 'neutral'}

	Line 1170:   - !systemPackage: {name: 'Microsoft-Windows-WebDAVRedir-Helper', arch: wow64, language: 'neutral'}

	Line 1171:   - !systemPackage: {name: 'Microsoft-Windows-WebDAVRedir-MrxDAV', arch: amd64, language: 'neutral'}

	Line 1172:   - !systemPackage: {name: 'Microsoft-Windows-WebDAVRedir-WebClient', arch: amd64, language: 'neutral'}

	Line 1173:   - !systemPackage: {name: 'Microsoft-Windows-WebDAVRedir-WebClient', arch: wow64, language: 'neutral'}



`src\Configuration\features\atlas\packages.yml`

**Comment by JayXTQ** [comment]
What is this information supposed to convey?

**Comment by Xyueta** [comment]
will be tested, thanka

**Comment by Xyueta** [comment]
https://github.com/Atlas-OS/Atlas/commit/9de447449f079f0288fdf8b3d8047caff7c7194f

**Comment by Xyueta** [comment]
For safety mesasure, I commented each line related.
