### ISSUE TITLE
[BUG REPORT] - `Unlock Start Menu Tiles.cmd` script not unlocking Start Menu Tiles

### ISSUE THREAD

**Issue by faker2048** [Atlas-OS/Atlas#651]
### Description

The script located at "Atlas\3. Configuration\1. General Configuration\Start Menu\Unlock Start Menu Tiles.cmd" does not work as intended. The Start Menu tiles remain locked and unusable.

#### Symptoms:
- Start Menu tiles are locked and cannot be used.
- The registry value "HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer\LockedStartLayout" remains set to 1.

#### Workaround:
Manually changing the registry value "HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer\LockedStartLayout" to 0 makes the Start Menu tiles work as expected. However, this should be addressed in the script itself for a more user-friendly experience.

### Steps to reproduce (if applicable add screenshots)

1. Install Windows and Atlas scripts according to the Atlas guidelines.
2. Run the `Unlock Start Menu Tiles.cmd` script and restart the computer.
3. The Start Menu tiles remain unusable, and the registry value "HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer\LockedStartLayout" is still set to 1.

### Expected behavior

Upon successfully running the `Unlock Start Menu Tiles.cmd` script and restarting the computer, the Start Menu tiles should become unlocked and usable. The registry value "HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer\LockedStartLayout" should change to 0.

### Actual behavior (if applicable add screenshots)

- Start Menu tiles are locked and cannot be used.
- The registry value "HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer\LockedStartLayout" remains set to 1.

### Atlas Version

Atlas 10 22H2

### Desktop information

- 5800X AMD

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.com/invite/atlasos).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
This is fixed in the next version and this is a duplicate issue. Please check that you have done a check before making an issue.
