### ISSUE TITLE
[BUG REPORT] - Typo on Atlas website

### ISSUE THREAD

**Issue by NaeemBolchhi** [Atlas-OS/Atlas#654]
### Description

Not really a bug, but I didn't have any other means to reach out. I apologize for any inconvenience.

![image](https://user-images.githubusercontent.com/42773187/229752715-5a326bc1-fc2e-4da0-9a57-4427341ac3b0.png)

It should be "than" instead of "then".

### Steps to reproduce (if applicable add screenshots)

N/A

### Expected behavior

N/A

### Actual behavior (if applicable add screenshots)

N/A

### Atlas Version

Atlas 10 22H2

### Desktop information

N/A

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.com/invite/atlasos).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
@SyrmGIT

**Comment by PencilNavigator** [comment]
fixed.
