### ISSUE TITLE
[FEATURE REQUEST] - ReEnabling the touch keyboard

### ISSUE THREAD

**Issue by halal-beef** [Atlas-OS/Atlas#655]
### What is your Feature Request regarding to?

The Atlas OS

### Is your feature request related to a problem? Please describe.

When using a touchscreen based device and focusing on a textbox, the touch based keyboard wont be shown since it was disabled

### Describe the solution you would like.

ReEnabling the touch keyboard or atleast an option to reenabling

### Describe alternatives you have considered.

None

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.com/invite/atlasos).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Additional context.

![image](https://user-images.githubusercontent.com/78730004/229813321-006599b4-3293-4e08-910e-a59610e90bd8.png)

**Comment by PencilNavigator** [comment]
Not needed since touchscreen keyboard isn't related and nor needed for gaming.
If you really need touchscreen keyboard, you can use the legacy one.
