### ISSUE TITLE
[BUG REPORT] - Unlock Start Menu Tiles.cmd

### ISSUE THREAD

**Issue by Damthe** [Atlas-OS/Atlas#659]
### Description

Unlock Start Menu Tiles.cmd doesn't enable "pin to start" option in context menu because it does not include the following reg entry.

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer]
"LockedStartLayout"=-

"LockedStartLayout" still stays as the value of 1 even after executing the command line.

I hope this helps.

### Steps to reproduce (if applicable add screenshots)

Default AtlasOS installation no extra configurations are done.

### Expected behavior

Start menu functionality to return to stock windows behaviour.

### Actual behavior (if applicable add screenshots)

Start menu functionality does return to stock windows behaviour.

### Atlas Version

Atlas 10 22H2

### Desktop information

i9-10900
32gb RAM @3200Mhz
RTX 3090
MSI Tomahawk MOBO 

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.com/invite/atlasos).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
Another duplicate issue, fixed in next update.
