### ISSUE TITLE
Performance slider missing in battery flyout

### ISSUE THREAD

**Issue by f9branza** [Atlas-OS/Atlas#66]
Hello, I did not report this as a bug, because I have thought that this is intended behaviour on desktop PCs where power isn't a problem, but on some laptops this component missing makes the CPU hover at a lower clock, and sometimes comes in handy for getting best peformance and other times better battery life when needed.
On custom power plans, like Atlas, this slider does not appear. But the problem is this slider does not appear on Balanced power plan either. 
This is caused by a component removed on the Atlas NtLite preset, and I couldn't rule it out on my personal Atlas ISOs that I have built.

Intended behaviour:
![unknown](https://user-images.githubusercontent.com/93547775/139726305-b1af6d31-51f4-4323-b92e-baf54a440c1b.png)

Actual behaviour:
![20211101_205249](https://user-images.githubusercontent.com/93547775/139726395-0c749cbd-1ffc-42f8-9085-deb7350b4392.jpg)

I mostly want to find the component to restore it in my personal preset I've made, but if the owner would commit the change into the original Atlas.xml it's even better.

**Comment by f9branza** [comment]
I found out this is not caused by the deep removal of components by NtLite. Still trying to find what component or what group of components causes it.

**Comment by f9branza** [comment]
>

**Comment by f9branza** [comment]
Closing because it's not really a real issue

**Comment by 1011100011111000** [comment]
@Zusier I wonder if you added battery slider. I have been thinking of installing atlas  and those power options are important for me.

**Comment by 1011100011111000** [comment]
@f9branza does the battery saver mode work on atlas?
