### ISSUE TITLE
[BUG REPORT] - AME Wizard keeps launching at every start-up even after the complete installation of AtlasOS

### ISSUE THREAD

**Issue by Damthe** [Atlas-OS/Atlas#660]
### Description

I believe title says it all.

It used to pop-up at every start but it is gone if the AtlasOS playbook is removed from the program.

Edit: one little side note that i did not use the uupdump windows iso(with updates included) like in syrym's tutorial. i have used the official microsoft iso and after the clean installation of it i have installed all the updates.(drivers were disabled so no questionmarks on that).

Also, i haven't used Rufus with pre-checkmarked options like disable BitLocker and user name selection etc. I used Ventoy 1.0.88

### Steps to reproduce (if applicable add screenshots)

Default and complete installation of AtlasOS no extra tweaks or alterations are done.

### Expected behavior

AME Wizard to not to open up after each installation.

### Actual behavior (if applicable add screenshots)

AME Wizard opens up after each installation.

### Atlas Version

Atlas 10 22H2

### Desktop information

i9-10900
32gb RAM @3200Mhz
RTX 3090

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.com/invite/atlasos).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by 32bitx64bit** [comment]
Not a bug. AME Wizard is the thing used to update atlas-OS.
If you want to disable it auto starting to go task manager -> startup -> disable AME Wizard beta
