### ISSUE TITLE
[FEATURE REQUEST] - AtlasOS Discord server new bot

### ISSUE THREAD

**Issue by kkMihai** [Atlas-OS/Atlas#664]
### What is your Feature Request regarding to?

Other, Please specify below

### Other

The Discord Server

### Is your feature request related to a problem? Please describe.

Yes, my feature request is related to a problem. I have noticed that the current bot is not able to provide accurate answers to some user questions. I believe that implementing the feature I am requesting, which allows the bot to match specific keywords in user questions with pre-defined answers, will greatly improve the user experience and make our bot more helpful.

https://github.com/kkMihai/AtlasOS-AI-Support

### Describe the solution you would like.

The solution I am proposing is to add a feature to our bot that allows it to match specific keywords in user questions with pre-defined answers. This would involve creating a json file of frequently asked questions and their corresponding answers, and programming the bot to recognize specific keywords in user questions and provide the appropriate answer. This would greatly improve the accuracy and usefulness of our bot, and make it a more valuable resource for our users.

### Describe alternatives you have considered.

-

### Requisites

- [x] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.com/invite/atlasos).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by RadNotRed** [comment]
No

**Comment by PencilNavigator** [comment]
what are you talking about? isn't that something that the bot already have?

**Comment by lemonekq** [comment]
it would be better if atlas bot will be rewritten to eris with prismajs.

**Comment by PencilNavigator** [comment]
imo this issue doesn't really make sense, so i am closing it as an invalid.

**Comment by kkMihai** [comment]
> what are you talking about? isn't that something that the bot already have? ![pic](https://user-images.githubusercontent.com/85282140/230605323-4a2290f5-62ee-4718-86fe-feb9dbbe8e87.png)

no? the bot only response based on only 1 word, like if user message has word "stuck" it will respond, the bot i made is different check the source code please and you will understand

**Comment by kkMihai** [comment]
![image](https://user-images.githubusercontent.com/59262001/230606582-a685dfec-ff49-4311-b3ea-9f79375bd37a.png)
example

**Comment by JayXTQ** [comment]
We are already making this? Dumb issue as well because not related to the atlas project but the server.
