### ISSUE TITLE
[BUG REPORT] - Virtualization and Intel Graphics problem.

### ISSUE THREAD

**Issue by Oruch379** [Atlas-OS/Atlas#668]
### Description

Installed my all drivers properly and when I enable HyperV and VBS for WSL, Intel Graphics driver doesn't work. I just try to use WSL but without HyperV and VBS, WSL doesn't work. I'm using new 22h2 Atlas and there was no problem like this in old versions. 

### Steps to reproduce (add screenshots if applicable)

![Taskmgr_3lY75Ldgxg](https://user-images.githubusercontent.com/65034033/230728029-e5e2b3a5-5ff0-417f-9f4c-ffea983dc496.png)

### Expected behavior

HyperV and VBS works without breaking Intel HD Graphics driver

### Actual behavior (add screenshots if applicable)

![ApplicationFrameHost_GzA6JiYDNI](https://user-images.githubusercontent.com/65034033/230728014-21587c96-7fbf-4ec4-8ed1-6c80a42441f6.png)

### Atlas Version

Atlas 10 22H2

### Desktop information

Intel I5 3210M
12 Gb DDR3 Ram
Intel HD Graphics 4000 & Nvidia GeForce GT 635M

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by Antag0nisticWomble** [comment]
Chipset drivers installed and up to date? Also if you don't run the script included with atlas that enables hyper-v the modules are disabled.

**Comment by Oruch379** [comment]
> Chipset drivers installed and up to date? Also if you don't run the script included with atlas that enables hyper-v the modules are disabled.

All drivers installed and script was enabled. But when I enable hyperV script, Intel HD Graphics driver doesn't work. This is the problem.

**Comment by Xyueta** [comment]
It will be fixed in the upcoming version of Atlas 22H2.

**Comment by chlorophant** [comment]
> Chipset drivers installed and up to date? Also if you don't run the script included with atlas that enables hyper-v the modules are disabled.

I'm also having this issue as of now. Which script must I run?

**Comment by UrNightmaree** [comment]
An addition answer to this issue, you don't actually need Hyper-V. The only thing WSL1/2 need is Virtual Machine Platform enabled, not Hyper-V (MicrosoftDocs/WSL#899).
