### ISSUE TITLE
New Minecraft Launcher Bug

### ISSUE THREAD

**Issue by Zusier** [Atlas-OS/Atlas#67]
Mojang's new minecraft launcher does not work for almost everyone, including people on Default Windows. This is being investigated, but for now this is what you can do:

- Use the [old launcher](https://github.com/Atlas-OS/Atlas/files/7470666/MinecraftInstaller.zip)
- Use alternative clients like [MultiMC](https://multimc.org/), [lunar ](https://www.lunarclient.com/)or [badlion](https://client.badlion.net)

**Comment by he3als** [comment]
Permanent link to the legacy Windows 8.1/7 version: 
https://launcher.mojang.com/download/MinecraftInstaller.msi

**Comment by he3als** [comment]
It does not seem like too much of a difference anyways between the new UWP version (I presume it is UWP) and the legacy version. It is probably just for the new Minecraft on the XBOX Game Pass for PC. However, that is just an assumption and things can change (I doubt that they will drop support for the legacy version in ages anyways).

**Comment by MelonsYum** [comment]
i tried going to minecraft.net/download, and the microsoft store. both didnt work ;-;

**Comment by Zusier** [comment]
There is an issue with both.. read what I posted.

**Comment by he3als** [comment]
> i tried going to minecraft.net/download, and the microsoft store. both didnt work ;-;

@MelonsYum get this https://launcher.mojang.com/download/MinecraftInstaller.msi

**Comment by lelelelkorgpt** [comment]
finaly just download this : https://apps.microsoft.com/detail/9NQPSL29BFFF?hl=fr-fr&gl=FR&ocid=pdpshare
