### ISSUE TITLE
[BUG REPORT] - Network Drives unavailable after installing playbook

### ISSUE THREAD

**Issue by Bungeetaco** [Atlas-OS/Atlas#672]
### Description

Hi there,

I ran the AtlasOS AME playbook on my main system today. Everything works fine except network drives, which I need for storage.
Looking into it, it seems some required services for this functionality were toggled off, but I'm unsure which ones I would need to re-activate in order for this to work.

Would you please be able to assist me with this?
Thank you

### Steps to reproduce (add screenshots if applicable)

1. Run AME AtlasOS playbook to completion
2. Reboot
3. Attempt to mount/re-mount a mapped network drive

### Expected behavior

Drive mounts automatically at boot
Able to mount network drives under drive letters

### Actual behavior (add screenshots if applicable)

![image](https://user-images.githubusercontent.com/5958682/230964476-05f63597-9563-494e-92ac-6c5f3277426b.png)

### Atlas Version

Atlas 10 22H2

### Desktop information

[sysinfo.nfo.txt](https://github.com/Atlas-OS/Atlas/files/11192745/sysinfo.nfo.txt)
Attached system information file (rename to *.nfo)

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
I believe network drives have been removed or there has been issues before, maybe @Xyueta knows more about this

**Comment by Xyueta** [comment]
of course they are, it is recommended to download, and place them on the USB Stick as stated in docs

**Comment by JayXTQ** [comment]
That’s not what he is talking about though?

**Comment by Bungeetaco** [comment]
I need to mount a samba share as a network drive (with a drive letter e.g Z:). Is there a reason why this feature would have been removed?

I do audio-production work, and so I installed AtlasOS to try and lower Windows's service footprint to get better latency, but all my data is stored on a network share so I can't access my projects now. Re-installing everything from scratch would take me over a day.

If so, is there a way to re-enable it or do I need to re-install Windows?

**Comment by PencilNavigator** [comment]
your user interface doesn't look windows 10, are you using the latest 22H2 build to install atlas?

**Comment by Bungeetaco** [comment]
It is Windows 10 22H2 fully updated up-to April 10th with a Windowblinds theme that looks like 7 @PencilNavigator

**Comment by dired** [comment]
Just wanted to chip in that samba is truly broken, even after executing the enable scripts of lanman and network discovery.

Not sure why this is not clearly mentioned in the same way that is promoted that remote desktop is not working in AtlasOS.
