### ISSUE TITLE
[BUG REPORT] - MS Store Minecraft Launcher

### ISSUE THREAD

**Issue by KonoKore** [Atlas-OS/Atlas#678]
### Description

Microsoft store version of the minecraft launcher does not launch.

### Steps to reproduce (add screenshots if applicable)

1. Open MC launcher
2. Profit

### Expected behavior

Launches the launcher that launches games

### Actual behavior (add screenshots if applicable)

![image](https://user-images.githubusercontent.com/128200152/231335044-f2ee41ca-6791-4ad3-960f-b6b27651678f.png)

### Atlas Version

Atlas 10 22H2

### Desktop information

![image](https://user-images.githubusercontent.com/128200152/231335102-62c4d809-4d2b-468e-a0a9-54f912cee292.png)

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by Antag0nisticWomble** [comment]
Minecraft launcher is working fine my end after running the enable UWP Apps script.

**Comment by PencilNavigator** [comment]
Enable UWP in Atlas folder.

If it doesn't work, use the win32 version of minecraft launcher or open-source third party launcher.

**Comment by KonoKore** [comment]
where do i find the win32 version?
