### ISSUE TITLE
[BUG REPORT] - Network Discovery NOT activating

### ISSUE THREAD

**Issue by rhubear25** [Atlas-OS/Atlas#681]
### Description

I've tried activating Network Discovery via the Atlas script, or directly in Control Panel.  Neither approach works.
CP Network Discovery resets to Deactivated if set to Activated.

I do have the required services running:  DNS Client, Function Discovery Resource Publication, SSDP Discovery, UPuP Device Host.

I have read conflicting online suggestions re Discovery & Defender.  Suggestion from MS is that Defender is required for Discovery, other suggestions that Discovery only works if a "Allow Discovery" rule is set in Defender.

Either way, I find myself unable to activate Network Discovery in Atlas.  Without being able to connect to my NAS server, Atlas is useless to me.   Web browser & internet DOES work in Atlas.

Could devs confirm to me that Network Discovery CAN be activated on  your machines?   I can supply for info or screenshots if necessary.

### Steps to reproduce (add screenshots if applicable)

Run Atlas Activate Network Discovery script & reboot.
OR
In CP, Activate Network Discovery option under Network Sharing, then reboot.

### Expected behavior

I expect to be able to confirm active Discovery in CP, & be able to see network resources as per usual.

### Actual behavior (add screenshots if applicable)

Discovery refuses to activate, no LAN resources visible.

### Atlas Version

Atlas 10 22H2

### Desktop information

AMD Ryzon 5
16G RAM

Atlas running inside VMware Workstation Player 17, bridged Net adapter.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by Xyueta** [comment]
We are working on the fix, which will be available in the upcoming release of Atlas. Thanks.

**Comment by rhubear25** [comment]
Really appreciate ur reply. Looking forward to future updates!08:55, 13 April 2023, Xyueta ***@***.***>:
We are working on the fix, which will be available in the upcoming release of Atlas. Thanks.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
--Rupert Heesom Sent from Yandex.Mail for mobile
