### ISSUE TITLE
Forza Horizon 5 closes after launch

### ISSUE THREAD

**Issue by GaborVarga239** [Atlas-OS/Atlas#682]
### Description

Forza Horizon 5 closes after I launch it

### Steps to reproduce (add screenshots if applicable)

1. Start fh5
2. The launch screen will appear
3. Game closes

### Expected behavior

FH5 launches normally

### Actual behavior (add screenshots if applicable)

The game closes itself

### Atlas Version

Atlas 10 22H2

### Desktop information

Ryzen 5500
16GB Gskill aegis 3000mhz
nVME SSD - Apacer AS2280Q4 1000GB
GTX 1070 8GB OC

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [x] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by GaborVarga239** [comment]
I downloaded it from online-fix, it worked fine on stock

**Comment by JayXTQ** [comment]
Is this a pirated version then?

**Comment by GaborVarga239** [comment]
Yes

**Comment by JayXTQ** [comment]
We don’t support pirated software here. Please check the documentation for more information.

**Comment by GaborVarga239** [comment]
where is the documentation?

**Comment by GaborVarga239** [comment]
nvm i fixed it

**Comment by NoelJacob** [comment]
@GaborVarga239 how did you do it?
