### ISSUE TITLE
[BUG REPORT] - Can't set up a PIN 

### ISSUE THREAD

**Issue by luoway** [Atlas-OS/Atlas#686]
### Description

Can't set up a PIN.
There is no interface to enter.

### Steps to reproduce (add screenshots if applicable)

Sign-in Options
Windows Hello PIN
Add
First, verify your account password.
![EUCDO{K JMDU5AM 6AJ1@US](https://user-images.githubusercontent.com/12523415/232110565-6dadbc74-97b2-4f39-8a20-9570e466bf6e.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/12523415/232111601-d94769a1-3935-4a24-9198-184511954e7d.png)

### Actual behavior (add screenshots if applicable)

![EUCDO{K JMDU5AM 6AJ1@US](https://user-images.githubusercontent.com/12523415/232110565-6dadbc74-97b2-4f39-8a20-9570e466bf6e.png)

### Atlas Version

Atlas 10 22H2

### Desktop information

Intel
RAM 8GB
SSD
NVIDIA GTX 1060

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

When installing the system, I did it with a MircoSoft account..

**Comment by xXTheBigBearXx** [comment]
I'm unable to add a pin either, but using a Local Account

**Comment by bandinfinite** [comment]
Why do you need a pin>? MSN account?

**Comment by JayXTQ** [comment]
@Xyueta did PINs get re-added? I know that they weren't possible in the legacy versions but didn't they get re-added in 22H2?

**Comment by gdnzz** [comment]
Windows hello features aren't available on atlas. So pins won't work as well

**Comment by luoway** [comment]
> Why do you need a pin>? MSN account?

@bandinfinite I need a PIN to make it easier to log in to my computer. It's not very necessary.

> Windows hello features aren't available on atlas. So pins won't work either

@gdnzz If it doesn't affect performance, maybe a switch setting can be provided.

**Comment by JayXTQ** [comment]
It would have been removed for ISO size back in the day most likely, but hasn't been readded. I will discuss this with the team.

**Comment by JayXTQ** [comment]
Should be fixed now, closing issue

**Comment by Xyueta** [comment]
Still an issue.

**Comment by Xyueta** [comment]
Fully fixed in this commit: https://github.com/Atlas-OS/Atlas/commit/db2892b1c568431c46963f1f202d8233db0a5eb9.

Thanks.

**Comment by notdido** [comment]
> Fully fixed in this commit: [db2892b](https://github.com/Atlas-OS/Atlas/commit/db2892b1c568431c46963f1f202d8233db0a5eb9).
> 
> Thanks.

any idea how I can fix it on an existing windows instalation without reinstalling my whole os and running the latest playbook?

**Comment by Xyueta** [comment]
you can re run the playbook
