### ISSUE TITLE
[BUG REPORT] - Little brother is unable to download minecraft

### ISSUE THREAD

**Issue by KonoKore** [Atlas-OS/Atlas#687]
### Description

My little brother is unable to download minecraft bedrock edition from the MS Store because of a "Turn on Windows Update" error.

### Steps to reproduce (add screenshots if applicable)

1. try to download
2. profit

### Expected behavior

Minecraft downloads normally

### Actual behavior (add screenshots if applicable)

Said error appears

### Atlas Version

Atlas 10 22H2

### Desktop information

![image](https://user-images.githubusercontent.com/128200152/232265040-08d85786-510f-4918-9aec-bf629990daa1.png)

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

![image](https://user-images.githubusercontent.com/128200152/232265073-ad94a093-916e-4be9-a045-3768fa113a03.png)

**Comment by JayXTQ** [comment]
Don't install via MS Store I'd say, install using the method in #67

**Comment by he3als** [comment]
This is most likely due to external tweaks that your brother has done, which disabled Windows Update in a way that makes it so you can not download from Store.

**Comment by KonoKore** [comment]
@he3als nope, the only tweaks done were with atlas, no other tweaks were made.

**Comment by he3als** [comment]
> @he3als nope, the only tweaks done were with atlas, no other tweaks were made.

There's no tweak in Atlas that disables Windows Update this way
