### ISSUE TITLE
[BUG EPORT] - Atlas installation stalls after restart

### ISSUE THREAD

**Issue by cdnhome** [Atlas-OS/Atlas#692]
### Description

After running the AME wizard beta, the system reboots at the end and runs in to "Your device ran into a problem and needs to restart" windows message. Second time it tried Windows repair options without success. Windows 10 Home created using the Windows "MediaCreationTool22H2.exe" from the Atlas web page link. PC Toshiba laptop type LS500=19x with Samsung 850evo ssd harddrive.

### Steps to reproduce (add screenshots if applicable)

create win10 sintallation usb
Run AME Wizard beta following successful win10 install 

### Expected behavior

Expected the system to open with Atlas desktop

### Actual behavior (add screenshots if applicable)

"Your device ran into a problem and needs to restart" message after the BIOS screen and Windows logo followed by rotating circile as Win tries to start

### Atlas Version

Atlas 10 22H2

### Desktop information

pentium Dual_core CPU T4300 2.10ghz 64 bit
graphic Mesa mobile intel GM45 express chipset
memory 4gib
SSD samsung EVO850 500gib

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
Try reinstalling Atlas again following the guide step by step, do not miss any steps or do anything differently.

**Comment by JayXTQ** [comment]
@cdnhome will close in 24h if no comment as error can not be reproduced

**Comment by cdnhome** [comment]
Understood. I won’t be retrying until tomorrow.

Sent from my iPhone

On 21 Apr 2023, at 14:45, Jay ***@***.***> wrote:

﻿

@cdnhome<https://github.com/cdnhome> will close in 24h if no comment as error can not be reproduced

**Comment by JayXTQ** [comment]
@cdnhome did it work?

**Comment by cdnhome** [comment]
Hi Jay

I tried it using another old pc with UEFI bios. That worked fine. The only issue I had was trying to run atlas wizard. Windows wouldn’t let it run. So had to switch off all the Defender settings before it would run. Otherwise OK. Now experimenting.
Bitdefender A V scan doesn’t work.
Regards Colin Neal


Sent from my iPhone

On 23 Apr 2023, at 12:23, Jay ***@***.***> wrote:

﻿

@cdnhome<https://github.com/cdnhome> did it work?

**Comment by JayXTQ** [comment]
Thanks for the reply, BitDefender was reported before for not working in #624 but atleast atlas works now. Thanks for the issue!
