### ISSUE TITLE
[BUG REPORT] - Atlas script folder is not available at Windows 10 22H2 after installing Atlas OS

### ISSUE THREAD

**Issue by bd-crackers** [Atlas-OS/Atlas#694]
### Description

After installing Atlas OS I didn't get the Atlas folder which was given in the previous version of Atlas OS. I'm currently using a desktop pc which I have a bluthoot adapter connected, but i'm unable to use it. The bluthoot is disabled by default and i dont have any files into my desktop to enable the bluthoot. 

### Steps to reproduce (add screenshots if applicable)

![image](https://user-images.githubusercontent.com/78915768/233027872-46b005b3-a55d-40c3-853b-2955b8b98bd3.png)
![image](https://user-images.githubusercontent.com/78915768/233027956-ab246812-47f5-4c19-bccb-703c26e54a27.png)

### Expected behavior

What should I do now to enable the bluthoot feature?

### Actual behavior (add screenshots if applicable)

The "Atlas" Folder should appear in the desktop by default.

### Atlas Version

Atlas 10 22H2

### Desktop information

Device name	DESKTOP-J0AA270
Processor	Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz   3.20 GHz
Installed RAM	8.00 GB (7.88 GB usable)
Device ID	C35ABBC0-903B-4F9E-8467-D8650B732421
Product ID	00330-80000-00000-AA878
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
Please try installing again following the documentation fully. Nobody else has reported this issue.

**Comment by JayXTQ** [comment]
@bd-crackers please respond, if not this issue will be closed in 24h

**Comment by bd-crackers** [comment]
@JayXTQ sorry for late response. 
i've tried installing the os for thre times but nothing changed. 
I even tried to get the "AtlasModules" folder and the "Atlas" folder from the previous version of Atlas OS but it didnt worked.

**Comment by JayXTQ** [comment]
Don’t use the folders from the previous versions… use the folders from the new versions in the GitHub…

**Comment by bd-crackers** [comment]
@JayXTQ can you give me the download link for those folders

**Comment by JayXTQ** [comment]
There is no specific download link, find them and download them.

**Comment by bd-crackers** [comment]
Im unable to find them bro. help me to find them 💔

**Comment by JayXTQ** [comment]
I don’t have the time rn
