### ISSUE TITLE
[BUG REPORT] - Screensavers not working

### ISSUE THREAD

**Issue by Dilbao** [Atlas-OS/Atlas#695]
### Description

Default screensavers are missing and not working after installing Atlas OS

### Steps to reproduce (add screenshots if applicable)

1. Backup *.scr files from "C:\Windows\System32"
2. Install Atlas OS
3. Copy backed files to original places
4. Set up a screensaver and observe

### Expected behavior

All screensavers should work. Default screensavers must stay untouched.

### Actual behavior (add screenshots if applicable)

Atlas OS Installer deletes all screensaver files. There is no reason to delete default screensavers of Windows. (especially Black Screen - scrnsave.scr)
And they are not working even if you put them back.

### Atlas Version

Atlas 10 22H2

### Desktop information

(I don't think this is hardware issue)

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [x] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
I believe that screensavers have been disabled on Atlas, but @Xyueta will know the answer more than I do.

**Comment by xemulat** [comment]
Bro, who still uses screensavers? Are you using a CRT monitor or something?

**Comment by JayXTQ** [comment]
> Bro, who still uses screensavers? Are you using a CRT monitor or something?

Dude, this isn't a place to mock.

**Comment by xemulat** [comment]
> > Bro, who still uses screensavers? Are you using a CRT monitor or something?
> 
> Dude, this isn't a place to mock.

But who uses screensavers these days? Can't you just turn your monitor off?

**Comment by Xyueta** [comment]
Fixed it https://github.com/Atlas-OS/Atlas/commit/4cfde331f9972a1cf6d9feb81c5a331f6afc6a35.
