### ISSUE TITLE
[BUG REPORT] - PIN still not working.

### ISSUE THREAD

**Issue by alex3236** [Atlas-OS/Atlas#699]
### Description

I found #686 saying it's fixed, but it just not working :(

If I understand correctly, in this case I should open a new issue.

### Steps to reproduce (add screenshots if applicable)

1. Install Atlas using latest playbook  (Github Action artifact).
2. Try to add a PIN.

### Expected behavior

\-

### Actual behavior (add screenshots if applicable)

According to #686, the problem is caused by disabled VaultSvc. taskmgr says it's running, but the PIN still not work, just like #686.

### Atlas Version

Atlas 10 22H2

### Desktop information

- 11th Gen Intel(R) Core(TM) i5-11260H
- 16GB Memory
- SSD
- Nvidia RTX 3050 Laptop

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by PencilNavigator** [comment]
As you see in #686 ,yes, it is fixed. But not in the latest stable release (which was released 3 weeks ago and was not changed). This is fixed in the latest beta version which has not been officially released.

**Comment by alex3236** [comment]
> As you see in #686 ,yes, it is fixed. But not in the latest stable release (which was released 3 weeks ago and was not changed). This is fixed in the latest beta version which has not been officially released.

I installed Atlas using [Github Action artifact](https://github.com/Atlas-OS/Atlas/actions/runs/4771592195), not release. VaultSvc is running.

**Comment by Xyueta** [comment]
Closing, as it is the duplicate issue of the https://github.com/Atlas-OS/Atlas/issues/686. It is still not fixed, so continue in there.

**Comment by Xyueta** [comment]
Fully fixed in this commit: https://github.com/Atlas-OS/Atlas/commit/db2892b1c568431c46963f1f202d8233db0a5eb9.

Thanks.
