### ISSUE TITLE
[FEATURE REQUEST] - Add Scoop as an Optional Component for Software Installation

### ISSUE THREAD

**Issue by wc7086** [Atlas-OS/Atlas#702]
### What is your Feature Request regarding to?

The Atlas OS

### Is your feature request related to a problem? Please describe.

Currently, Chocolatey is the only option for installing software packages on Windows through the command line. However, using Chocolatey can sometimes result in directory pollution, which can be frustrating for some users who prefer to keep their system directories clean.

### Describe the solution you would like.

I would like to request the addition of Scoop as an optional component for software installation. Scoop is a command-line installer for Windows that installs software packages into isolated directories, and does not pollute the system directories.

### Describe alternatives you have considered.

As an alternative, users can manually install software packages without using any package manager. However, this can be time-consuming and cumbersome.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Additional context.

For some users, having a clean system directory is important, especially for those who use their machines for development or other technical tasks. Adding Scoop as an optional component for software installation would provide users with more flexibility and a cleaner installation process.

**Comment by PencilNavigator** [comment]
Scoop was REMOVED due to its instability. 
We don't need two package manager.  If you want, you can install scoop yourself.
