### ISSUE TITLE
[BUG REPORT] - 

### ISSUE THREAD

**Issue by Haydens-workshop** [Atlas-OS/Atlas#703]
### Description

link for https://atlasos.net/download does not work
proper href is https://atlasos.net/downloads

### Steps to reproduce (add screenshots if applicable)

reading through the docs https://docs.atlasos.net/getting-started/other-installation-methods/no-usb/
click on  https://atlasos.net/download

### Expected behavior

expected to reference the correct webpage 

### Actual behavior (add screenshots if applicable)

results in 404 error as page does not exist.

### Atlas Version

Atlas 10 22H2

### Desktop information

N/A/ irrelevant to issue.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
Hi, this issue got fixed ages ago. I don't know how you recieved it but it has been fixed!
