### ISSUE TITLE
[FEATURE REQUEST] - 

### ISSUE THREAD

**Issue by Savillion** [Atlas-OS/Atlas#705]
### What is your Feature Request regarding to?

The Atlas OS

### Other

Removing "XblGameSaveTask" 

### Is your feature request related to a problem? Please describe.

I really don't understand why you would remove the task "XblGameSaveTask" out from a gaming focused distro kinda thing. You never tested it? It will make you not be able to download xbox saves from microsoft, and you won't be able to play or login to any game...

### Describe the solution you would like.

Removing the deletion of "XblGameSaveTask" task from task scheduler.

Also you can import it  by the time being. Location should be : "Task Scheduler Library\Microsoft\XblGameSave"

[XblGameSaveTask.zip](https://github.com/Atlas-OS/Atlas/files/11314289/XblGameSaveTask.zip)

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by Xyueta** [comment]
https://social.technet.microsoft.com/Forums/en-US/d3cadc29-2cb6-4f96-b513-308a9c10a81e/xblgamesave-task-on-server-2016-is-this-a-joke?forum=ws2016

**Comment by Savillion** [comment]
It doesn't run on startup I checked.
It only runs when you open a game from Microsoft Store or Xbox app and when the game try to import your info/save from Microsoft servers. I checked. 
If it's deleted you can't play a game. I checked this too. So why in the world you would remove something like this? 
Don't tell me because of security or telemetry, please.

**Comment by he3als** [comment]
> [social.technet.microsoft.com/Forums/en-US/d3cadc29-2cb6-4f96-b513-308a9c10a81e/xblgamesave-task-on-server-2016-is-this-a-joke?forum=ws2016](https://social.technet.microsoft.com/Forums/en-US/d3cadc29-2cb6-4f96-b513-308a9c10a81e/xblgamesave-task-on-server-2016-is-this-a-joke?forum=ws2016)

It doesn't seem to be telemetry or anything harmful, I don't see how this forum post is related as Atlas is for gaming and should support XBOX, unlike Windows Server.

Overall, it seems like a harmless task and presuming the name and description is legitimate, it does a good function.
