### ISSUE TITLE
[BUG REPORT] - Windows Mixed Reality/Reverb G2 stuck in a crashing loop

### ISSUE THREAD

**Issue by DakotaList** [Atlas-OS/Atlas#708]
### Description

I'm trying to use my Reverb G2 VR headset with Atlas 22H2. I was able to install the drivers and the Mixed Reality portal just fine, and everything appears to run like normal on the desktop side. (SteamVR even picked up on the headset like it should.) However, when I actually look at the headset display, it gets stuck in an infinite loop of briefly showing the WMR startup/calibration screen then crashing to a blank black screen.

### Steps to reproduce (add screenshots if applicable)

1. Installed latest WMR/Hololens drivers from Microsoft website
2. Installed Mixed Reality portal from Windows Store
3. Ran through initial setup using the portal on desktop
4. Put the VR headset on

### Expected behavior

The WMR startup screen should launch, detect the environment/boundary, then take me to the WMR home

### Actual behavior (add screenshots if applicable)

The startup screen appears for a brief second then crashes to a black screen. This repeats endlessly until I close WMR or turn off the headset.

### Atlas Version

Atlas 10 22H2

### Desktop information

Ryzen 7 5800X
Asus X470-F Strix
RTX 3070
WD Black 1TB NVME
HP Reverb G2 V2 Headset

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by DakotaList** [comment]
Fixed by reinstalling the HoloLens/WMR drivers via device manager instead of directly from the INF file... i feel stupid now

**Comment by bigjohnx** [comment]
> Fixed by reinstalling the HoloLens/WMR drivers via device manager instead of directly from the INF file... i feel stupid now

How can you resolve it? I install the driver by running the exe / msi that download from ms and finally the outcome is like you.
