### ISSUE TITLE
TP Link Bluetooth adapters don't work

### ISSUE THREAD

**Issue by styris-ame** [Atlas-OS/Atlas#709]
### Description

Shows Driver error. Two reports of this on the Discord forum:

https://discord.com/channels/795710270000332800/1100172079497760838/1100172079497760838
https://discord.com/channels/795710270000332800/1100206188815196170/1100206188815196170

### Steps to reproduce (add screenshots if applicable)

Use TP Link adapter on Atlas

### Expected behavior

Should work

### Actual behavior (add screenshots if applicable)

Doesn't work
![Picture1](https://user-images.githubusercontent.com/123859041/234139896-45ed924e-a133-4113-bed4-152be2b4160e.png)
### Atlas Version

Atlas 10 22H2

### Desktop information

Computer

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
Have you tried installing the drivers via the vendor?

**Comment by Xyueta** [comment]
I will be checking out the issue on a few mobile devices. Thanks for noticing this problem.

**Comment by saintjtrhodes** [comment]
By Default, it appears the bluetooth service (Bluetooth Support Service) is disabled.  Enable it via services.msc and it appears to fix the issue (for most devices).
I am currently researching the same issue, as my Xbox Bluetooth controller is not detected at all in my bluetooth list.  Everything else appears to be detected and pairs correctly after re-enabling the bluetooth service.

**Comment by Xyueta** [comment]
There is a script in our configuration folder.

**Comment by JayXTQ** [comment]
Is this issue now fixed? @styris-ame

**Comment by styris-ame** [comment]
I was going based off the discord messages, so I can't say. I'll close the issue.

**Comment by Zensonaton** [comment]
Although I don't have a TP-Link Bluetooth adapter, I had the same "Driver error" issue. To fix that, I had to reinstall Windows, and force it to install all of the drivers via Windows Update, and then I used the Atlas playbook.
