### ISSUE TITLE
Xbox App can not open 

### ISSUE THREAD

**Issue by LilMayo69** [Atlas-OS/Atlas#71]
**Describe the bug**
I do not get an error code but the Xbox app immediately closes i tried to re enable services for Xbox and they won't start for some reason. Ive always applied the regedit will gives defualt windows services and drivers and the app didnt work.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop Info (please complete the following information):**
 - AMD
 - ssd
 - Version [e.g. 1.2]

**Additional context**

**Comment by Zusier** [comment]
#62
