### ISSUE TITLE
Question: value of AllowAutoWindowsUpdateDownloadOverMeteredNetwork

### ISSUE THREAD

**Issue by Tiagoquix** [Atlas-OS/Atlas#715]
Shouldn't https://github.com/Atlas-OS/Atlas/blob/main/src/Configuration/features/atlas/start.yml#L60 be set to zero instead of one? (So it doesn't allow automatic updates over metered connections.)

https://www.tenforums.com/tutorials/139722-turn-off-download-updates-over-metered-connections-windows-10-a.html

**Comment by Xyueta** [comment]
Fixed, thanks. The Default is 0.
