### ISSUE TITLE
[BUG REPORT] - MS EDGE NOT COMPLETELY UNINSTALL

### ISSUE THREAD

**Issue by bandinfinite** [Atlas-OS/Atlas#716]
### Description

Just found out that there are some leftovers. In control panel and some telemetry in the background (not sure if its for ms edge)

### Steps to reproduce (add screenshots if applicable)

1. 
![image](https://user-images.githubusercontent.com/119771087/234273342-6c8ae68a-b2b7-4f50-a64f-bbdfc1b1ebd0.png)

### Expected behavior

Expected to have MS EDGE uninstalled fully and no more ms telemetry's

### Actual behavior (add screenshots if applicable)

Still the atlas script didn't remove MS EDGE

### Atlas Version

Atlas 10 22H2

### Desktop information

- Processor AMD A8 6500 APU WITH RADEON HD 8570 GFX CARD
- 8 GIG RAM 1333 MHZ
- 2 500 GB HDD'S
- 

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by bandinfinite** [comment]
I posted this issue as a bug-tracing for atlas or to help and in no way I asked to how to fix it. Dev's, I hope you guys will fix it in upcoming updates.

**Comment by JayXTQ** [comment]
I believe this is left over because Microsoft doesn’t want Edge to be uninstalled so they leave a trace but I understand your concern. Is this something we know @Xyueta @he3als?

**Comment by bandinfinite** [comment]
Thanks for understanding and replying Mr. Jay, these left overs sometimes reinstall on themselves, that's why I wanted to raise this issue
