### ISSUE TITLE
[BUG REPORT] - BROKEN SHORTCUT

### ISSUE THREAD

**Issue by bandinfinite** [Atlas-OS/Atlas#717]
### Description

It is located in Atlas/Configuration/General Configuration/UWP.

It is a broken shortcut

### Steps to reproduce (add screenshots if applicable)

![image](https://user-images.githubusercontent.com/119771087/234274766-5834d5cf-8447-465e-9771-0e22cb90b86f.png)

### Expected behavior

The shortcut to redirect me to the stated folder

### Actual behavior (add screenshots if applicable)

It says the stated folder is deleted or not available

### Atlas Version

Atlas 10 22H2

### Desktop information

AMD A8 6500 APU 
8 GIG RAM
2 500 GB HDD'S
AMD INTEGRATED GFX CARD

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
@Xyueta I think this one is for you, I don’t know where this directs to

**Comment by JayXTQ** [comment]
@Xyueta I think this one is for you, I don’t know where this directs to

**Comment by bandinfinite** [comment]
Thank you Mr. Jay for replying :), have a good day sir.

**Comment by bandinfinite** [comment]
Oh founded it out, C:\Users\Default\Desktop\Atlas\3. Configuration\1. General Configuration\Start Menu target is this

**Comment by bandinfinite** [comment]
Before the target had missed some paths

**Comment by bandinfinite** [comment]
Can I close it?

**Comment by JayXTQ** [comment]
Yup, you can close. But as you didn’t I will
