### ISSUE TITLE
start.yml have some double quotation marks and single ones

### ISSUE THREAD

**Issue by Tiagoquix** [Atlas-OS/Atlas#722]
https://github.com/Atlas-OS/Atlas/blob/main/src/Configuration/features/atlas/start.yml

There's some `"0"`, but also `'0'`. Just a guess, but I think only one of the two formats is correct.

**Comment by JayXTQ** [comment]
1. Please use the issue templates provided. Don't delete them.
2. If you wish to fix this yourself make a PR
3. They are both quotation marks and they both work the same afaik.

**Comment by Xyueta** [comment]
Thanks for noticing.
