### ISSUE TITLE
[BUG REPORT] -  Virus software

### ISSUE THREAD

**Issue by 22350** [Atlas-OS/Atlas#725]
### Description

Get the error that "Requirements not met  All third party antivirus software must be uninstalled before continuing"

### Steps to reproduce (add screenshots if applicable)

![2023-04-25 11_43_51-Window](https://user-images.githubusercontent.com/2864726/234372308-f6194a08-f118-4ee3-99eb-6b5d35ebb8be.png)

### Expected behavior

allowed to continue`

### Actual behavior (add screenshots if applicable)

saying software is present, which doesn't exist.

### Atlas Version

Atlas 10 22H2

### Desktop information

xeon e5-2699 v3
128 gb quad channel ddr 4 2133
evo 980 nvme
dual 2080ti nvlink

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by Xyueta** [comment]
Did you install a clean windows version and updated it to the latest version?

**Comment by JayXTQ** [comment]
Well do you have third party anti-virus software? Also, are you on a clean Windows 10 22H2 install like the docs said?

**Comment by gdnzz** [comment]
https://github.com/KonoKore/Atlas-AV-Detection-Bypass/blob/main/README.md
