### ISSUE TITLE
Can't change my keyboard layout

### ISSUE THREAD

**Issue by abehidek** [Atlas-OS/Atlas#73]
**Describe the bug**
When trying to change keyboard layout, an error appears saying

"SystemSettings.exe - SystemError
The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application"

**To Reproduce**
1. Go to 'Language settings'
2. On ''Preferred languages' click English
3. then click 'Options'
4. See pop up system error

**Expected behavior**
To be able to change language settings

**Screenshots**
[
![Screenshot_1](https://user-images.githubusercontent.com/39712525/143957576-f58400d2-a57d-4008-9fd2-162dd4e9b384.png)
](url)
**Desktop Info (please complete the following information):**
 - i5 3570
 - SSD
 - AtlasOS 20H2

**Additional context**
Also, who encountered this bug was a friend of mine, who uses the same version, I tried to reproduce it here it and it's not working here

**Comment by Zusier** [comment]
It's a Windows bug: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/language-packs-known-issue. Try some of the fixes in the docs

If you have the time, reinstall and the first thing you do should be installing languages/keyboard layout
