### ISSUE TITLE
[BUG REPORT] - Dont include or use ProcessHacker\x64\kprocesshacker.sys

### ISSUE THREAD

**Issue by wazerstar** [Atlas-OS/Atlas#730]
### Description

So I saw the video from ltt and Just wanted to test this Atlas-Os out.

3 other friends did the same, but apparently when the 3 of them wanted to game they where met with anti cheat issues about ProcessHacker in several games, they panicked!!

Other issue is that the account is suddenly changed of which user that you want to login in with during startup, also background for lock screen is changed by policy, making it hard to change it back.

### Additional content

In general you have not made it easy for people to choose what they would want from beginning and making a restore does not solved any of those pointed out issues..

**Comment by JayXTQ** [comment]
Can you mention what games, and also all the other stuff can be enabled in the Atlas folder

**Comment by Xyueta** [comment]
This is related to AME Wizard, not to Atlas. It should be already removed.

**Comment by wazerstar** [comment]
> This is related to AME Wizard, not to Atlas. It should be already removed.

I dont know what it is, it was all downloaded from https://atlasos.net/downloads which link to here.

**Comment by wazerstar** [comment]
> AME Wizard is the tool that you run the playbooks with, it is on our website.
> 
> For more information: https://ameliorated.io.

Still does have kprocesshacker.sys, anyways reporting it, do whatever you want, close, delete threat i don't really care :)

**Comment by styris-ame** [comment]
@wazerstar We've done a lot to fix this issue, but it seems to still have a very small chance of happening. Apologies for the inconvenience.

If you're willing, you can follow the steps below to solve it:

Download and unzip NSudo (https://github.com/M2TeamArchived/NSudo/releases/download/9.0-Preview1/NSudo_9.0_Preview1_9.0.2676.0.zip)

Run x64\NSudoLG.exe

Set it to TrustedInstaller, and enter cmd in the input box and click run.

In the cmd window, type the following and press enter:

reg delete "HKLM\SYSTEM\CurrentControlSet\Services\kprocesshacker2" /f


Let me know if this fixes it for you.

**Comment by PencilNavigator** [comment]
Hi, sorry but this issue wasn't filled out correctly with our template so we will be closing and locking it. If you want to report a bug please follow our template.
