### ISSUE TITLE
[BUG REPORT] - Disabling Wifi/Wi-Fi via Atlas Configuration Options Breaks Windows Explorer

### ISSUE THREAD

**Issue by Savillion** [Atlas-OS/Atlas#732]
### Description

Disabling Wifi/Wi-Fi via Atlas Configuration Options Breaks Windows Explorer

### Steps to reproduce (add screenshots if applicable)

After installing Atlas, when you disable Wi-Fi via Atlas config batch files, it disables "NlaSvc", "netprofm", "WlanSvc", "vwififlt" services. I really don't know which, but disabling Wi-Fi and restarting makes Windows Explorer to restart infinitely.
You cant close or reopen it via Task Manager.
Restoring to Atlas Default Services via given batch file fixes it.

### Expected behavior

Not restarting Windows Explorer infinitely?

### Actual behavior (add screenshots if applicable)

Restarts Windows Explorer infinitely.

### Atlas Version

Atlas 10 22H2

### Desktop information

-R7 3700x
-1070ti
-16G 3200Mhz ram
-250G 970Evo ssd
-b450m s2h

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
maybe something to look into @Xyueta ?

**Comment by Xyueta** [comment]
Will be checked, thanks.

**Comment by Savillion** [comment]
Problem was on my end, sorry.
