### ISSUE TITLE
[BUG REPORT] - Chrome extensions reload after every system restart

### ISSUE THREAD

**Issue by AyaanFr** [Atlas-OS/Atlas#735]
### Description

When I restart my PC, the Chrome extensions reload, meaning I must repeatedly sign in to extensions like LastPass and Grammarly.

### Steps to reproduce (add screenshots if applicable)

1. Restart PC
2. Start Chrome

### Expected behavior

Not having to sign in to extensions each time I restart my PC.

### Actual behavior (add screenshots if applicable)

When I start Chrome after restarting/first boot of the day, I am met with extension pop-ups asking me to sign in again.

### Atlas Version

Atlas 10 22H2

### Desktop information

Intel i7 3770
16GB Ram
OS on 512GB SSD
GTX 1060 6GB

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by AyaanFr** [comment]
I installed Chrome Beta as well as Chrome Public build. Both have the same behavior. I will try reinstalling first.

**Comment by ExorcistF1** [comment]
same thing happens with edge, after rebooting the pc, some extensions (Enhancer for YouTube™, Twitch Adblock) restore their initial settings.

**Comment by sakshiagrwal** [comment]
I'm using Chrome v112.0.5615.138 and everything is fine here.
You are using some cleaner? This happens because of the deletion of `Cookies`

**Comment by ExorcistF1** [comment]
it also affects the functionality of sites, reddit can't remember pinning the sidebar, twitter switches the Following bar to For you, restarting the browser has no effect, just restarting the pc

**Comment by sakshiagrwal** [comment]
> it also affects the functionality of sites, reddit can't remember pinning the sidebar, twitter switches the Following bar to For you, restarting the browser has no effect, just restarting the pc

This enabled? https://github.com/Atlas-OS/Atlas/blob/main/src/Executables/AtlasModules/Scripts/Auto-Cleaner.cmd

**Comment by ExorcistF1** [comment]
I installed OS for the first time. And I don't know what it is and where I can see it

**Comment by JayXTQ** [comment]
@sakshiagrwal that file shouldn't delete anything anyway afaik

**Comment by Xyueta** [comment]
It will be fixed soon.

**Comment by Xyueta** [comment]
Should be working now.

**Comment by AyaanFr** [comment]
Noob question, for updating Atlas, I need to use the AME Wizard and a new playbook, right?

**Comment by Xyueta** [comment]
Yes either that or reinstall. 👍

**Comment by AyaanFr** [comment]
So how do I go about updating it right now? Could you let me know if you pushed an update that fixes the extension issue? Sorry, I didn't understand what you meant by this.

> Should be working now.

**Comment by Xyueta** [comment]
made changes to the auto-cleaner.cmd in the ``C:\Windows\AtlasModules\Scripts`` folder.

**Comment by JayXTQ** [comment]
Easiest way to do it is using GitHub actions or replace the files we changed manually

**Comment by JayXTQ** [comment]
With every github commit, there is an action, with every action there is a new dev playbook. I wouldn’t recommend it though unless you don’t care

**Comment by gramatik** [comment]
I just installed Atlas 2 weeks ago and I also have this problem with Chrome. Adblock extension installs every time I restart the PC and also Whatsapp Web keeps making me login by scanning the QR with the phone every time I open it.
