### ISSUE TITLE
[BUG REPORT] - HDD dissappearing

### ISSUE THREAD

**Issue by Alucardzy** [Atlas-OS/Atlas#736]
### Description

After fresh installing Atlas OS HDD keeps disappearing and crashing (before installing it everything worked fine) idk if its atlas issue or something went wrong with my system

### Steps to reproduce (add screenshots if applicable)

Install Stock windows
Upgrade to Atlas
Problem appears.

### Expected behavior

Everything working smoothly without problems

### Actual behavior (add screenshots if applicable)

HDD stopped showing and stuff became slower

### Atlas Version

Atlas 10 22H2

### Desktop information

Intel UHD Graphics 630
16GB RAM
SSD
GTX 1060

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

How do i fix it.

**Comment by Xyueta** [comment]
Hey.

Send me the status of SysMain and FontCache services in services.msc.

**Comment by Alucardzy** [comment]
![image](https://user-images.githubusercontent.com/112097293/234660892-96f51f71-7ba9-43f8-9564-2e587dc87576.png)
and there is no FontCache in services, i cant seem to find it

**Comment by Xyueta** [comment]
If your main drive is SSD, it is okay.

**Comment by Alucardzy** [comment]
I use HDD to store games, since my SSD doesn't have much storage, i would like to know if there is a fix to HDD disappearing and not working anywhere.

**Comment by Alucardzy** [comment]
I only have launched the enable bluetooth and game mode, haven't touched anything else.

**Comment by Xyueta** [comment]
Tests on multiple machines resulted in no replication.
