### ISSUE TITLE
0.51 version not able to create an bootable flash drive

### ISSUE THREAD

**Issue by abehidek** [Atlas-OS/Atlas#74]
**Describe the bug**
I'm trying to install this new version since it's possible to access the new xbox app, but, after downloading it, and then using rufus or etcher to make the pendrive a bootable device with the os, it says it's not possible

**To Reproduce**
1. Download the new iso version from atlasos.net/download
2. Download Rufus or BalenaEtcher 
3. Open Rufus/BalenaEtcher
4. Select your flash drive and then proceeds to select the new iso
5. See error

**Expected behavior**
To be able to make my flash drive an bootable device to install new version of atlas (0.5.1).

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/39712525/144318372-7b931323-e815-42d7-912e-6ef3e83d97c2.png)
![Screenshot_2](https://user-images.githubusercontent.com/39712525/144318380-089a0288-0853-4883-ba3b-b11b0c680e54.png)

**Desktop Info (please complete the following information):**
 - CPU Ryzen 7 1700
 - SSD
 - 0.5.1

**Additional context**
I actually tried to create an bootable flash drive anyway but the system don't recognize the flash drive as an bootable option
I face the same problem using faceit version

**Comment by Zusier** [comment]
Hash check the iso in cmd:

```
certutil -hashfile "%HOMEPATH%\Downloads\Atlas_v0.5.1.iso"
```
Should match: `C84663A0A0405817F91675CFD308FEE63F2A4311`

**Comment by abehidek** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/39712525/144318831-84d12ea5-68cd-4dca-a3ef-3b04ff78cfe7.png)

its not matching actually

**Comment by Zusier** [comment]
Then you need to redownload the iso.

**Comment by abehidek** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/39712525/144319318-4ba98d5e-96dc-463b-82da-9ff0c863ba1c.png)
it looks like it will take some time (even though my friend has an 100mbps fiber optics connection), but I return if the new downloaded iso matches the one that was given

**Comment by Zusier** [comment]
You may want to try the [torrent](https://cdn.discordapp.com/attachments/882760919439011901/912916877993455647/Atlas_v0.5.1.iso.torrent)

**Comment by abehidek** [comment]
way faster via torrent
the hash is matching and it's working too
thanks for all the support and good work

**Comment by uhIgnacio** [comment]
Just a warning: you can't use `balena etcher` to create Windows bootable USB, use [`woeusb`](https://github.com/WoeUSB/WoeUSB-ng) instead

**Comment by Zusier** [comment]
> thanks for all the support and good work

No problem and thank you. Closing.
