### ISSUE TITLE
[FEATURE REQUEST] - Use NTSuspendProcess and/or Image File Execution Options to disable processes and services instead of permanently removing them

### ISSUE THREAD

**Issue by rcmaehl** [Atlas-OS/Atlas#740]
### What is your Feature Request regarding to?

The Atlas OS

### Is your feature request related to a problem? Please describe.

AtlasOS removes various features that may be needed to free up system resources. An obvious side effect of this is that these features are lost and can't not be easily reinstalled.

### Describe the solution you would like.

A few options are available that can disable processes and services without stripping them out completely.

## NTSuspendProcess
NTSuspendProcess halts processing of the process or service but keeps the process resources in RAM so they can continue to be used once the process is resumed. This provides quick disabling and renabling of features without having to load resources used back into RAM. The obvious downside to this is RAM usage is not decreased.

## Image File Execution Options
Image FIle Execution Options, along with it's filter option, allow calls to execute processes or services to be intercepted, and optionally ignored altogether. This can be applied and removed at any time in the Registry without needing a reboot or relog to disable processes or services.

Perhaps users can be given the option to customize what features they want "removed", "disabled", or "disabled in RAM" which will improve compatibility and security, while still heavily reducing resource usage. 

### Describe alternatives you have considered.

Leaving the features in

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
This won't be done, the reason why we totally remove some stuff is because it is Windows bloat and in some cases many of our users don't need it. If you want to add features yourself, modify the playbook using the repo and the AME docs.
