### ISSUE TITLE
[BUG REPORT] - Intermittent Windows Hello

### ISSUE THREAD

**Issue by jacob153** [Atlas-OS/Atlas#741]
### Description

From the lock screen Windows hello will not allow me to scan my fingerprint. This does not happen all the time, but sometimes it seems to fail to initialize and the option to switch to fingerprint is not available until login with pin/password and relocking to lock screen. I am on a clean install of the latest Atlas and have installed drivers from my hardware and the issue still persists.

### Steps to reproduce (add screenshots if applicable)

1. Set up Fingerprint reader
2. Locking the screen from normal use will show the issue occurring

### Expected behavior

Windows Hello is typically initialized every time the lock screen is showing, so the expectation is that I would be able to utilize my fingerprint scanner every time I am on the lock screen.

### Actual behavior (add screenshots if applicable)

I am unable to collect screenshots as it is on the Lock Screen

### Atlas Version

Atlas 10 22H2

### Desktop information

- Latitude 7310 2-in1
- cpu: i7-10610U
- Ram: 16gb
- Intel GPU

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

I have verified that the intermittent behavior does not occur before installing atlas.

**Comment by JayXTQ** [comment]
@Xyueta maybe something to look into when you are back

**Comment by Xyueta** [comment]
Can you check the release using https://github.com/Atlas-OS/Atlas/actions.

**Comment by JayXTQ** [comment]
@jacob153 did you check?

**Comment by jacob153** [comment]
@JayXTQ I have. I am on the latest release and am still experiencing the issue

**Comment by JayXTQ** [comment]
You mean latest artifact like xyueta linked?
