### ISSUE TITLE
Task view shortcut

### ISSUE THREAD

**Issue by marioqqq** [Atlas-OS/Atlas#744]
### What is your Feature Request regarding to?

The Atlas OS

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you would like.

I was not able to find / enable task view shortcut (switch between) CTRL+WIN+ARROW. It would be nice to enable this feature for productivity. If this feature already exist, please let me / us know and consider this feature request as irrelevant. Thanks

### Describe alternatives you have considered.

No

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by PencilNavigator** [comment]
Issue was closed because the template wasn't filled our correctly. Please fill out the template correctly for us to work on your issue.
