### ISSUE TITLE
[BUG REPORT] - Windows Ink doesn't work

### ISSUE THREAD

**Issue by C0D3-M4513R** [Atlas-OS/Atlas#745]
### Description

When trying to use Windows Ink, the cursor doesn't move and pen clicks are not recognised.
I'm using OpenTabletDriver, the WindowsInk plugin and the VMulti driver to test Windows Ink.
This setup has worked on other Windows machines.
Using OpenTabletDriver with the VMultiMode plugin and the VMulti driver makes the pen move, so it is not a VMulti driver issue. 
OpenTabletDriver also correctly detects my tablet movements, so not a OpenTabletDriver issue.
And the WindowsInk plugin works on other computers with the same software installed. So also not a WindowsInk issue.
Additionally multiple Contributers to OpenTabletDriver have confirmed, that it is probably not a OpenTabletDriver issue.

### Steps to reproduce (add screenshots if applicable)

1. Download OpenTabletDriver (https://opentabletdriver.net/Wiki/Install/Windows)
2. Add the WindowsInk plugin.
3. Download and install VMulti (https://github.com/X9VoiD/vmulti-bin/releases/tag/v1.0)
4. Connect a supported Tablet (by OpenTabletDriver) and verify, that the pen position is updated correctly.
5. Switch the output mode to Windows Ink Absolute.
6. The pen position doesn't update.

### Expected behavior

In step 6. the pen position updates.

### Actual behavior (add screenshots if applicable)

The tablet pen position doesn't update

### Atlas Version

Atlas 10 22H2

### Desktop information

AMD Ryzen 3600
32Gb Ram
Samsung EVO SSD
Nvidia RTX 2060 Super

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

Windows Ink is not stated as removed in the documentation.
Only other issue which even mentions Windows Ink is #369 , but the issue itself was about something else.
Discord support was either: being ignored, or they could not tell me how to reenable Windows Ink.

**Comment by JayXTQ** [comment]
We either can or just link your issue whenever someone asks.  Nobody has really asked how to enable. Closing as you found a solution

**Comment by JayXTQ** [comment]
> That requires that you have someone that knows this issue exists, and that someone actually responds to discord questions (which is often not the case)
> How lazy do you have to be, to not include one more folder and two .reg files...

Why be rude here? I was trying to infer that not many people ask this question so we aren’t going to implement a quick fix unless we get people asking for it. Reason being is that we don’t want to clog up the Atlas folder with so many folders that people get confused and the documentation becomes so long that it spreads off of the world. Also, people are active in the discord and most of them are community so obviously people have lives :)

**Comment by JayXTQ** [comment]
Dude, I gave you the reason why we aren’t going to add the reg key ourselves. If you really want to you can make a PR and we will probably accept it but as for right now, no need until people ask. Also, not everyone has the greatest knowledge in this and only help people with the knowledge they have. I don’t tend to give support anymore as I am less of a developer and more of a maintainer on the github side of things (issues and prs) and the documentation writer but I know how most of us think.
