### ISSUE TITLE
[BUG REPORT] - UWP Music Player App Unable to Play Music on AltasOS

### ISSUE THREAD

**Issue by Lorde627** [Atlas-OS/Atlas#746]
### Description

I recently encountered an issue while using AltasOS where a frequently used UWP (Universal Windows Platform) music player application cannot play music. I suspect that the audio playback module for UWP apps might have been removed or streamlined in this operating system version. I would like to inquire about how to resolve this problem.

Before installing this app locally, you have to update the app installer, or there will be error.
or you can install this UWP app by command: `Add-AppxPackage -Path file.appx
`

Here's the app:
https://github.com/JasonWei512/NetEase-Cloud-Music-UWP-Repack/blob/master/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90UWP%20%E4%B8%8D%E6%9B%B4%E6%96%B0%E7%89%88%20x64.appx

Installation Instructions
- Right-click on the appx installation package for x86 / x64 / ARM, click on properties and switch to the "Digital signatures" tab. 
- Double click on "esaeten" in the signature list. In the "Digital Signature Details" pop-up window, click "View Certificate", and then click "Install Certificate".
- In the "Certificate Import Wizard":
- Select "Local computer" for "Storage location, " then click Next. (You need to agree to the UAC permission request)
- Select "Place all certificates in the following storage", click "Browse", select "Trusted root certificate authority", OK, next, and continue to complete the certificate import.
- Double click the appx installation package for x86 / x64 / ARM to install.

### Steps to reproduce (add screenshots if applicable)

1. install the app
2. play a song
3. and it stuck

### Expected behavior

Make this app play music normally.

### Actual behavior (add screenshots if applicable)

keeps loading but won't playing.

### Atlas Version

Atlas 10 22H2

### Desktop information

- i3 - 10105F
- AMD RX6700
- 16G RAM

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
Hm, I take it that the app works on default 22H2 Windows 10?

**Comment by Lorde627** [comment]
> Hm, I take it that the app works on default 22H2 Windows 10?

Yes!

**Comment by Lorde627** [comment]
and I found that the app seems to use `WIndwos Media Playback EXE` to play music, don't know if this is the .

**Comment by JayXTQ** [comment]
I doubt that's the problem, have you managed to fix this? Nobody else has reported this issue afaik.

**Comment by PencilNavigator** [comment]
Use the win32 version of netease cloud music for now.
https://d1.music.126.net/dmusic/NeteaseCloudMusic_Music_official_2.10.8.200945.exe

**Comment by Lorde627** [comment]
> Use the win32 version of netease cloud music for now. https://d1.music.126.net/dmusic/NeteaseCloudMusic_Music_official_2.10.8.200945.exe

The whole point is to UWP version 😭

**Comment by JayXTQ** [comment]
You didn’t even respond to my question

**Comment by PencilNavigator** [comment]
@Lorde627 the UWP version of it is legacy and will not receive any official support from netease. Just use the Win32 version.

I personally don't really think a fix for this issue should even matter because the app itself is legacy and we have no other users reporting this issue.

**Comment by Lorde627** [comment]
okay, thx guys 😭
