### ISSUE TITLE
[BUG REPORT] - Disable Automatic Elevation of Admin and UAC Prompts in Atlas OS

### ISSUE THREAD

**Issue by lh1207** [Atlas-OS/Atlas#747]
### Description

Currently, after the installation of Atlas OS, the system automatically elevates the user to admin privileges and disables all UAC prompts without any consent through the ConsentPromptBehaviorAdmin registry key. This feature poses a security risk as it could potentially allow malicious software to gain access to sensitive system files and data. By addressing this issue, users, especially those not as acquainted to computer management, would have more control over their system's security and could ensure that they are only giving admin privileges to trusted applications and software. It would also be helpful for users who prefer to work with non-admin accounts for added security.

### Steps to reproduce (add screenshots if applicable)

1. Install AtlasOS with default settings
2. Check the ConsentPromptBehaviorAdmin registry key to confirm it is set to 0 after installation

### Expected behavior

Enable UAC.cmd should be the default script ran by AtlasOS. Only advanced users should have the ability to disable UAC since they will yield the knowledge and risks that come with disabling UAC as opposed to leaving it on.

### Actual behavior (add screenshots if applicable)

Disable UAC (default).cmd is the default script ran by AtlasOS, which generates the proposed security flaw in the script.

### Atlas Version

Atlas 10 22H2

### Desktop information

Applies to all systems

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
This was done purposefully by one of our devs, we know of the risks and we don't know if they will revert it. Honestly, I don't see the issue with having UAC off if you know what you are doing but yeah. For now this may or may not be changed. Thanks for the query though!
