### ISSUE TITLE
[FEATURE REQUEST] - Support for unsigned/cracked software

### ISSUE THREAD

**Issue by aditya-0805** [Atlas-OS/Atlas#750]
### What is your Feature Request regarding to?

The Atlas OS

### Is your feature request related to a problem? Please describe.

“Your internet security has prevented one or more files to open”. Piracy isn’t moral, but often times as gamers and programmers there isn’t a way around it.

### Describe the solution you would like.

An option to even temporarily enable installation/running of such files would go a long way towards making atlas usable.

### Describe alternatives you have considered.

Tried pretty much all relevant options in Internet Options.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
Atlas doesn’t provide support for pirated content.

**Comment by PencilNavigator** [comment]
absolutely NO SUPPORT for ANY PIRACY.
Don't even think about it, not going to happen now, and not going to happen in the future.

**Comment by Xyueta** [comment]
Should be working fine, however we don't and support piracy software.
