### ISSUE TITLE
[BUG REPORT] - Surface Pro 9 stuck restarting after successful install

### ISSUE THREAD

**Issue by fuzelet** [Atlas-OS/Atlas#752]
### Description

After the installer is completely finished and the machine is rebooted for the last time, the surface pro 9 never successfully starts. The surface just sits on black windows screen with spinning white circle that never finishes and spins forever.  The surface is configured to not use TPM or Secure Boot using the newest windows 10 iso made from UUP dump(feature update 19045.2846). Bitlocker is not enabled, etc.

### Steps to reproduce (add screenshots if applicable)

Install windows 10 pro fresh on surface pro 9.
Run installer and follow all prompts.
Once installer completes and does final reboot, issue happens.

### Expected behavior

Successful boot after install that said everything was fine.

### Actual behavior (add screenshots if applicable)

Machine never booted after install

### Atlas Version

Atlas 10 22H2

### Desktop information

Surface Pro 9
Intel I7-1255U
16Gb RAM
256GB SSD

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
I take it you followed the documentation fully?

**Comment by fuzelet** [comment]
> I take it you followed the documentation fully?
To the best of my knowledge, yes.  I used the same iso, process, etc on other machines with no issues.  Surface Pro 9 is the only machine i have that has ran into problems so far.  I even attempted to let it spin for like 20+ minutes, however nothing changes. Upon restarting the device a few times, automatic repair starts, however it does not provide any impact be it find any issues or not.  Aside from potentially pulling the drive and putting it into another machine to try to read the drive, 

I have tried 2+ times using clean isos, updating machine with WU prior to running installer, etc.  No change from what I can tell.  Install says no errors encountered every time, reboots, sits there.

**Comment by JayXTQ** [comment]
Hm, this is definitely an odd one. @Xyueta can probably understand what is going on here

**Comment by fuzelet** [comment]
I attached some photos of the specs of the machine (prior to completing the installer) as well as the outcome of it just sitting at the windows logo after install and it just spins.

![PXL_20230429_215529745 MP](https://user-images.githubusercontent.com/70331495/235493647-ec20f284-4849-4a84-b249-c17c7b448a70.jpg)
![PXL_20230429_222116993](https://user-images.githubusercontent.com/70331495/235493651-987bd0dd-326e-45c4-9ae4-0c6851835b85.jpg)
![PXL_20230429_222925509](https://user-images.githubusercontent.com/70331495/235493654-b885463b-d362-4867-a3bb-c0a0bae8f924.jpg)

**Comment by fuzelet** [comment]
Just tried doing another install on my surface pro 9 using the playbook from https://github.com/Atlas-OS/Atlas/actions/runs/4840890674

I did not immediately restart after install this time and grabbed all the logs from the installer. As it stands now, I did reboot and I am stuck on windows loading screen again.
![PXL_20230501_225207410](https://user-images.githubusercontent.com/70331495/235546147-ed9e84b5-2687-4215-815b-7b188fb7ec25.jpg)

[AdminOutput.txt](https://github.com/Atlas-OS/Atlas/files/11368558/AdminOutput.txt)
[ErrorLog.txt](https://github.com/Atlas-OS/Atlas/files/11368559/ErrorLog.txt)
[FileChecklist.txt](https://github.com/Atlas-OS/Atlas/files/11368560/FileChecklist.txt)
[Packages.txt](https://github.com/Atlas-OS/Atlas/files/11368561/Packages.txt)
[TIOutput.txt](https://github.com/Atlas-OS/Atlas/files/11368562/TIOutput.txt)

**Comment by fuzelet** [comment]
So i decided to try this all again this morning.  I reset my UEFI settings back to default, turned on TPM, Secure Boot, etc.  I then used the Windows 10 22H2 Media creator off Microsoft's website to make the iso.  I used the newest playbook from https://github.com/Atlas-OS/Atlas/suites/12617363318/artifacts/675351178  All this said, still running into the exact same issue.  Installer does not provide any errors, etc however upon first reboot after installer completes the machine never loads windows. Sits at spinning windows logo forever.

At this point I am not sure what else I can try or provide. Please let me know how else I can help.  Really want to get Atlas working on my SP9.
![PXL_20230502_123033103](https://user-images.githubusercontent.com/70331495/235689735-71f40d98-ed94-4b13-95e3-f13d6e3b439d.jpg)
![PXL_20230502_134257199](https://user-images.githubusercontent.com/70331495/235689743-3c362569-71cd-46ed-a85c-d51ac16b0783.jpg)
![PXL_20230502_134340593](https://user-images.githubusercontent.com/70331495/235689746-7d52750e-9ecc-4ab2-b3ed-328f179bf498.jpg)
![PXL_20230502_134447091](https://user-images.githubusercontent.com/70331495/235689749-a93623a3-b843-40c8-a22e-f94dd8b662d9.jpg)
![PXL_20230502_135244343](https://user-images.githubusercontent.com/70331495/235689752-ca7d5cc7-f376-4804-9e19-d4fb01619586.jpg)
![PXL_20230502_135348334](https://user-images.githubusercontent.com/70331495/235689759-4f82a044-c829-4db8-80d6-9cd8c8ccc15e.jpg)
![PXL_20230502_135539510](https://user-images.githubusercontent.com/70331495/235689760-14965cf3-39ee-46c1-a6e4-e8c66c2b1c91.jpg)


[AdminOutput.txt](https://github.com/Atlas-OS/Atlas/files/11373992/AdminOutput.txt)
[ErrorLog.txt](https://github.com/Atlas-OS/Atlas/files/11373993/ErrorLog.txt)
[FileChecklist.txt](https://github.com/Atlas-OS/Atlas/files/11373995/FileChecklist.txt)
[Packages.txt](https://github.com/Atlas-OS/Atlas/files/11373996/Packages.txt)
[TIOutput.txt](https://github.com/Atlas-OS/Atlas/files/11373998/TIOutput.txt)

**Comment by kubo6472** [comment]
I'm experiencing this same issue on a different device. Upon automatic repair by plugging in the USB and selecting "Startup repair" I managed to nuke AtlasOS along with all the programs. I tried running the playbook again. Should I open a new issue if it's another device but same behavior? thanks.

**Comment by Xyueta** [comment]
Unfortunately, I couldn't replicate this issue, but please give it a shot when v. 0.3.0 releases ;).
