### ISSUE TITLE
[BUG REPORT] - Errors 2503 and 2502 occur during installation/uninstallation of apps with .msi files

### ISSUE THREAD

**Issue by timius100** [Atlas-OS/Atlas#756]
### Description

When attempting to install or uninstall an application using a .msi file on Windows, users may encounter errors 2503 and 2502, which prevents the installation or uninstallation process from completing successfully.
However, if user will grant themselves full permissions on the C:\Windows\TEMP folder before attempting to install or uninstall an application with a .msi file, the app will be installed without any problems.
Installing .msi file from cmd with Administrator privileges also works.

### Steps to reproduce (add screenshots if applicable)

1. Download and try to install any .msi file (like Epic Games Launcher installer) or try to uninstall any app
2. Encounter error 2503
4. Encounter error 2502

### Expected behavior

The application should be installed/uninstalled successfully without any problems

### Actual behavior (add screenshots if applicable)

Errors 2503 and 2502 appear, which prevent the installation or uninstallation process from completing successfully
![2503](https://user-images.githubusercontent.com/74375674/235346792-bf3ffe48-72e9-4fa0-9852-31d161611c0b.png)
![2502](https://user-images.githubusercontent.com/74375674/235346796-bc889c94-ca22-4656-bf36-d9bdc42361c1.png)

### Atlas Version

Atlas 10 22H2

### Desktop information

- Windows 10 22H2 19045.2913, Atlas 10

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
This is fixed in the next update afaik, but for now https://cdn.discordapp.com/attachments/828192192703102976/1024023193490567258/Fix_error_2502_and_2503.cmd

**Comment by he3als** [comment]
https://github.com/Atlas-OS/Atlas/blob/main/src/Executables/Atlas/4.%20Troubleshooting/Fix%20Error%202502%20and%202503.cmd

Added a script to fix this.
