### ISSUE TITLE
[BUG REPORT] - Disable Xbox script errors out (when MS Store is disabled)

### ISSUE THREAD

**Issue by JayXTQ** [Atlas-OS/Atlas#757]
### Description

Provided by: @SlovenianSlobodan#9859 on Discord under her thread [here](https://discord.com/channels/795710270000332800/1102181325143818260/1102181325143818260).

If you first disable M$ Store using the provided script, the script for Xbox app removal fails to do anything, presumably due to disabled AppXSvc and/or ClipSVC. Also the script for Xbox app removal seems to be broken in the current version of the playbook (v0.2), but that has already been fixed upstream on the Github, I'm using the latest (fixed) version.
I'd highly suggest adding a check for this. I'd post on Github but I can't be bothered to dig up my account. Thanks

### Steps to reproduce (add screenshots if applicable)

1. Run disable MS Store script
2. Run disable Xbox app

### Expected behavior

Xbox app supposed to disable

### Actual behavior (add screenshots if applicable)

Xbox app doesnt disable

### Atlas Version

Atlas 10 22H2

### Desktop information

N/A

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

This wasn't written by me, if you want answers from the original person, check the thread

**Comment by JayXTQ** [comment]
@Xyueta I saw you closed #782, can this be closed too?

**Comment by Xyueta** [comment]
Not related.

**Comment by JayXTQ** [comment]
ok no need for the ending period kek

**Comment by Xyueta** [comment]
Fixed in https://github.com/Atlas-OS/Atlas/commit/9156b2804d675b457576d98006b3a88be1069593.

Now, XBOX is disabled inside the Store script before the restart, which will work for the disable.
