### ISSUE TITLE
[FEATURE REQUEST] - Missing 7Zip actions

### ISSUE THREAD

**Issue by jordanamr** [Atlas-OS/Atlas#759]
### What is your Feature Request regarding to?

The Atlas OS

### Is your feature request related to a problem? Please describe.

Selecting multiples files and right clicking should enable us to open the full 7Zip "add to..." so we are able to choose from zip, 7z, rar, choose a password and many more...
Right now we only have this option :
![image](https://user-images.githubusercontent.com/55905781/235372294-7c714895-3f60-4c5c-b2b2-5c570fb8e4ea.png)

### Describe the solution you would like.

Having the latest 7Zip version with full right click support like the default installation ?

### Describe alternatives you have considered.

Replacing the default 7Zip

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by Xyueta** [comment]
Only Zip and 7Z are available in the default 7zip

**Comment by Xyueta** [comment]
We are gonna add zip back though, thanks.

**Comment by jordanamr** [comment]
We should be able to have those options, which are present on a default 7Zip installation from 7-zip.org : 
![image](https://user-images.githubusercontent.com/55905781/235372343-427fe3a3-b1c4-47ba-a7dc-bb125f3d93a1.png)



> Only Zip and 7z are available in the default 7-Zip.
Not true. Selecting the "Add to archive..." option lets use choose from a variety of format, this is why the "Add to archive..." option that pops up that larger GUI is important : 
![image](https://user-images.githubusercontent.com/55905781/235372400-20c80a69-72c5-4b84-8654-54090333141e.png)

**Comment by jordanamr** [comment]
The best fix fox me is having 3 options inside the right click menu : 

Add to *.zip
Add to *.7z
Add to archive...

**Comment by Xyueta** [comment]
Oh, sorry.

**Comment by jordanamr** [comment]
If you're interested. I can PR the needed changes :)

**Comment by JayXTQ** [comment]
Making a PR would be helpful, unless @Xyueta is very quick

**Comment by Xyueta** [comment]
Sure, make a pr.

**Comment by jordanamr** [comment]
Are you guys OK with these ?
Right clicking an archive :
![image](https://user-images.githubusercontent.com/55905781/235373190-17249657-7b22-4b13-b42e-49f7a8c66936.png)

Right clicking something else : 
![image](https://user-images.githubusercontent.com/55905781/235373201-f54c1b64-cae3-4817-b9b5-bfb13ec17eb0.png)

**Comment by JayXTQ** [comment]
lgtm

**Comment by Xyueta** [comment]
> Are you guys OK with these ? Right clicking an archive : ![image](https://user-images.githubusercontent.com/55905781/235373190-17249657-7b22-4b13-b42e-49f7a8c66936.png)
> 
> Right clicking something else : ![image](https://user-images.githubusercontent.com/55905781/235373201-f54c1b64-cae3-4817-b9b5-bfb13ec17eb0.png)

It is basically a stock menu

**Comment by JayXTQ** [comment]
better than what we have tho

**Comment by Xyueta** [comment]
Add that point use the manager.

**Comment by jordanamr** [comment]
> > Are you guys OK with these ? Right clicking an archive : ![image](https://user-images.githubusercontent.com/55905781/235373190-17249657-7b22-4b13-b42e-49f7a8c66936.png)
> > Right clicking something else : ![image](https://user-images.githubusercontent.com/55905781/235373201-f54c1b64-cae3-4817-b9b5-bfb13ec17eb0.png)
> 
> It is basically a stock menu

Not at all.
Stock menu looks like this (right click on any file/folder) :
![image](https://user-images.githubusercontent.com/55905781/235373284-317d0442-5131-4f1e-ad54-8b3e8a1db252.png)

Right click on archive : 
![image](https://user-images.githubusercontent.com/55905781/235373293-90859789-0472-4826-82b7-ada76fcf3214.png)

**Comment by JayXTQ** [comment]
The manager is too clunky and tbf, I don't even know how to get there. So I think this is best. I'd rather make zips than 7z
