### ISSUE TITLE
[BUG REPORT] - Hibernate

### ISSUE THREAD

**Issue by sadzyy** [Atlas-OS/Atlas#764]
### Description

something for hibernate has been disabled/removed, hibernate feature is turned on properly but isn't available to use

### Steps to reproduce (add screenshots if applicable)

1. Run Enable Hibernation.cmd script at C:\Users\Atlas\Desktop\Atlas\3. Configuration\1. General Configuration\Power\Hibernation as administrator
2. Hibernate isn't showing up in power menu, even after restart

### Expected behavior

hibernation feature is turned on in powercfg and available to use, the hibernate section should show up in power menu

### Actual behavior (add screenshots if applicable)

hibernate feature is turned on but unavailable due to some missing or disabled components
![image](https://user-images.githubusercontent.com/84945798/235620596-cf59c72d-75f0-4ac3-8566-abc17be51b10.png)

### Atlas Version

Atlas 10 22H2

### Desktop information

-Lenovo V310-14IKB
-i5 7200u
-AMD RX 590 GME through pcie riser
-Power management driver from lenovo is installed, my hardware supports this feature

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

There isn't something for u to toggle like S1-S3 sleep states in group policy too, the "show hibernate in power options menu" wont work because it's unavailable
![image](https://user-images.githubusercontent.com/84945798/235622751-3517e27f-232d-4ff6-a60d-f0fa1264ad68.png)
~With filter on by keyword "sleep"
![image](https://user-images.githubusercontent.com/84945798/235622894-79d0b832-1aae-48c5-bd3e-c71447d13405.png)
~With filter on by keyword "hibernate"

**Comment by sadzyy** [comment]
would like to have this included in autocleaner too
```powercfg /h /type reduced```

**Comment by PencilNavigator** [comment]
https://github.com/Atlas-OS/Atlas/issues/249#issuecomment-1326107557

**Comment by sadzyy** [comment]
this is not a dupe, I have checked before posting this, I was the first to post for this for 0.2 ver

**Comment by PencilNavigator** [comment]
It was said before, we have no plans on re-implementing it for Atlas.
Hibernation eats up alot of space on your hard drive, this is against this part of our [README](https://github.com/Atlas-OS/Atlas#-more-space).

**Comment by sadzyy** [comment]
so u guys just made the script to allow us to enable it but be not responsible

**Comment by PencilNavigator** [comment]
are you on the dev version?

**Comment by sadzyy** [comment]
no, it's the public release

**Comment by PencilNavigator** [comment]
i don't have a test enviornment now, someone else will probably test it, hopefully it fixes!

**Comment by sakshiagrwal** [comment]
> i don't have a test enviornment now, someone else will probably test it, hopefully it fixes!

I tested this on my second laptop, but it's not working for me either


Atlas Version
Atlas 10 22H2 [Commit](https://github.com/Atlas-OS/Atlas/actions/runs/4871058785)

Desktop information
- Vivobook Pro 15X
- Ryzen 9 6900HX
- NVIDIA GeForce RTX 3070
- Power driver from ASUS is installed

**Comment by sadzyy** [comment]
found the issue, hibernate file type must be set to full
default filetype was set to reduced after running `powercfg /h /on`
https://learn.microsoft.com/en-us/windows/win32/power/system-power-states#hibernation-file-types

https://github.com/Atlas-OS/Atlas/pull/776

**Comment by sadzyy** [comment]
https://github.com/Atlas-OS/Atlas/pull/776

**Comment by Xyueta** [comment]
Thanks.
