### ISSUE TITLE
[FEATURE REQUEST] - xbox removal script

### ISSUE THREAD

**Issue by wozzyi** [Atlas-OS/Atlas#765]
### What is your Feature Request regarding to?

The Atlas OS

### Is your feature request related to a problem? Please describe.

enhancement to the remove xbox components script

### Describe the solution you would like.

Powershell
```powershell
Get-ProvisionedAppxPackage -Online | `

Where-Object { $_.PackageName -match "xbox" } | `

ForEach-Object { Remove-ProvisionedAppxPackage -Online -AllUsers -PackageName $_.PackageName }
```
To check current installed packages that match string "xbox"
```powershell
dism /Online /Get-ProvisionedAppxPackages | Select-String PackageName | Select-String xbox
```

### Describe alternatives you have considered.

add more restriction to the selective string if some of it is meant to be kept

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
As a gaming OS, we won't be removing Xbox due to Xbox game pass. If you wish to uninstall Xbox yourself go ahead but I doubt we will provide a script to allow you to do so

**Comment by sadzyy** [comment]
it already exist, just isn't working properly
![image](https://user-images.githubusercontent.com/84945798/235640010-b03bd37e-413a-40e9-a55e-9afd48f5f0d3.png)

**Comment by Xyueta** [comment]
Fixed in the next release.
