### ISSUE TITLE
[FEATURE REQUEST] - 可以给个iso版本嘛

### ISSUE THREAD

**Issue by emmIsabella** [Atlas-OS/Atlas#767]
### What is your Feature Request regarding to?

The Atlas OS

### Is your feature request related to a problem? Please describe.

安装在vmware里用的

### Describe the solution you would like.

安装在vmware里用的

### Describe alternatives you have considered.

安装在vmware里用的

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
Hi, for future please speak in English, but for now. @PencilNavigator can you translate for me? Also, no ISO will be provided if that is the question. No ISO will **ever** be provided afaik. Just follow the docs, it’s simple and works in VMWare which you mentioned 4 times.

**Comment by PencilNavigator** [comment]
Please write issues in english, and fill out the template correctly.
Absoutely NO ISO will be provided in the future.
