### ISSUE TITLE
[BUG REPORT] -  Whatsapp crashes after launching

### ISSUE THREAD

**Issue by Kolzi** [Atlas-OS/Atlas#773]
### Description

So if I install whatsapp from microsoft store and launch it. The logo pops up for a few seconds then the app crashes. Idk any fix for it. This is on atlas 0.2 from playbook. My friend who is on the 0.1 version doesnt have this issue.

### Steps to reproduce (add screenshots if applicable)

1. Launch Microsoft store
2. Install Whatsapp
3. Run whatsapp
4. Whatsapp crash

### Expected behavior

Whatsapp should put up the qr code to link a device so we can chat while using the desktop app

### Actual behavior (add screenshots if applicable)

It crashes after a few seconds

### Atlas Version

Atlas 10 22H2

### Desktop information

Intel i7 6006u
1tb ssd
16gb ddr4 ram
Nvidia 940MX GPU

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
Works for me in a dev build, may be fixed v0.3.0
