### ISSUE TITLE
[BUG REPORT] - not able to install Logitech G hub

### ISSUE THREAD

**Issue by Algeneralo** [Atlas-OS/Atlas#774]
### Description

I'm not able to install the Logitech g hub application even though it was installed before without any issues.
https://www.logitechg.com/en-us/innovation/g-hub.html

### Steps to reproduce (add screenshots if applicable)

Download the app from here https://www.logitechg.com/en-us/innovation/g-hub.html
Try to install it. 

### Expected behavior

App should be downloading without any issues 

### Actual behavior (add screenshots if applicable)

Downloaded app from link not even opening, just show a mouse loading then nothing 

### Atlas Version

Atlas 10 22H2

### Desktop information

Inter core I 7
32g ram
1tb ssd

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
Seems to work for me! Maybe fixed in v0.3.0 when it comes out!
![video](https://user-images.githubusercontent.com/54886938/236687316-6b708885-7823-4598-90ad-de85e02f3fe4.mp4)

**Comment by Algeneralo** [comment]
@JayXTQ you mean v0.3.0 of atlas or what?

**Comment by PencilNavigator** [comment]
the latest dev version. 
https://github.com/Atlas-OS/Atlas/actions

**Comment by Algeneralo** [comment]
@PencilNavigator can I install the dev version on my pc directly? The v0.3.0

**Comment by Algeneralo** [comment]
@PencilNavigator @JayXTQ I can confirm that the issue is fixed on the dev version
