### ISSUE TITLE
Can't Enable Xbox Gamebar

### ISSUE THREAD

**Issue by YounesxSmt** [Atlas-OS/Atlas#78]
i enabled it from the settings app > gaming > enable xbox gamebar 
but after i exit the settings app it goes back to disabled
I Tried Clean install,enabled all xbox services but nothing worked
If this is a feature can you please and option or script to enable it in the next update?

**Comment by Zusier** [comment]
[Enable-gamebar.reg.zip](https://github.com/Atlas-OS/Atlas/files/7764861/Enable-gamebar.reg.zip)

**Comment by YounesxSmt** [comment]
> [Enable-gamebar.reg.zip](https://github.com/Atlas-OS/Atlas/files/7764861/Enable-gamebar.reg.zip)

Thank you!
