### ISSUE TITLE
[FEATURE REQUEST] - TO HAVE CHKDSK AND SFC COMMANDS

### ISSUE THREAD

**Issue by bandinfinite** [Atlas-OS/Atlas#781]
### What is your Feature Request regarding to?

The Atlas OS

### Is your feature request related to a problem? Please describe.

Yes. My Hard Drive got corrupted due to a file which was not written correctly while shutting down. It didn't let me resize partitions. And I was so frustrated at the point because I had to resize it no matter what stops me, even 3rd party softwares failed and it took much of my time.

### Describe the solution you would like.

Just to not remove it in next update

### Describe alternatives you have considered.

Atleast integrate an Atlas custom PE

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by Muki-tech** [comment]
These commands could technically mess up / revert tweaks AtlasOS does. Although the developers know the best.

**Comment by sadzyy** [comment]
u can boot into pe on 0.2 ver directly, not sure if u have to enable recovery or not, mine booted into diskgenius's pe and completed my resize without any issue

**Comment by PencilNavigator** [comment]
running such commands can revert tweaks and possibly corrupt your install.

**Comment by bandinfinite** [comment]
Atleast @PencilNavigator can your team provide a PE because if someone has an issue they can't keep searching for PE's, after the windows install, we could readily flash it ....

**Comment by bandinfinite** [comment]
And I understand your idea, and thanks for the reply @PencilNavigator . I will close this
