### ISSUE TITLE
[BUG REPORT] - XBOX UNINSTALL COMMAND NOT WORKING

### ISSUE THREAD

**Issue by bandinfinite** [Atlas-OS/Atlas#782]
### Description

The XBOX folder present in general configuration folder includes some cmd files. And it is stated that they will uninstall all XBOX apps, but it does not uninstall.

### Steps to reproduce (add screenshots if applicable)

Go to general configuration folder and then Xbox
Click on remove xbox applications (double click)
afterwards, still it would be there

### Expected behavior

To get rid of xbox apps

### Actual behavior (add screenshots if applicable)

Did not uninstall xbox apps

### Atlas Version

Atlas 10 22H2

### Desktop information

AMD A8 6500 APU
8 GIG RAM
2 500 GB HDD
AMD RADEON HD 8570D IGPU

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by Xyueta** [comment]
Fixed in the latest commits. Thanks.
