### ISSUE TITLE
[BUG REPORT] - Not reportting event 19 in windows' events log

### ISSUE THREAD

**Issue by youngbe** [Atlas-OS/Atlas#784]
### Description

I believe that many Atlas os users are Ryzen users, and a lot of OC users. When setting fclk ferq over 1900mhz, Windows may report 19 events, and this can be used to check mem OC stability.
However, Atlas os seens not reporting it. I then install the original win 10 22h2 to compare, it do report.

### Steps to reproduce (add screenshots if applicable)

![image](https://github.com/Atlas-OS/Atlas/assets/24429886/a3b77ed8-d6ca-4b8b-942c-36a46b95e89d)

### Expected behavior

Report event 19

### Actual behavior (add screenshots if applicable)

Not report event 19

### Atlas Version

Atlas 10 22H2

### Desktop information

amd 5600
asus tuf-gaming-b550m-plus-wifi-ii
16g ddr4 3600mhz oc to 3866mhz 3933mhz or 4000mgz
7900 xtx

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by youngbe** [comment]
Some information that might be useful：
https://www.reddit.com/r/buildapc/comments/su7sdl/ram_xmp_profilefclk_setting_causes_whea_event_19/
https://www.reddit.com/r/AMDHelp/comments/k0a3z8/ryzen_5_5600x_whealogger_event_19/
https://www.reddit.com/r/AMDHelp/comments/10cxhpw/whea_event_19_error_5800x3d/
https://www.reddit.com/r/overclocking/comments/r733dq/whea_19_error_fix/

**Comment by JayXTQ** [comment]
@Xyueta maybe something for you?

**Comment by he3als** [comment]
Fixed in next release, disable 'Auto Cleaner' in Task Scheduler to fix.

Run https://cdn.discordapp.com/attachments/1036401998335057955/1110222966568009738/Fix-2502-2503.cmd to fix any MSI issues as well
