### ISSUE TITLE
[BUG REPORT] Cluster Size 128k - DirectX failure

### ISSUE THREAD

**Issue by KiralyCraft** [Atlas-OS/Atlas#789]
### Description

I have installed my machine with a 128k cluster size for C:. It's my first time running Atlas, according to the instructions. It seems that DirectX 2010 is not happy about the cluster size being 128k, and therefore refuses to install. It opened in the background, as my resolution was 800 x 600, and couldn't see behind the installer. It was only after closing it that I noticed DirectX's message.

### Steps to reproduce (add screenshots if applicable)

1. Install Windows with a 128k cluster-sized C:\ disk
2. Attempt to install Atlas according to the instructions
3. Observe installation fail, and atlas hang when installing DirectX (the message should be "Reticulating Splines")

### Expected behavior

The user should be warned (during checks) that certain steps will fail due to the cluster size. The user should be given the option to skip these steps, or a different setup method should be used for DirectX 2010. 

### Actual behavior (add screenshots if applicable)

The installer hung at "Reticulating Splines", and I was wrongly guided to fixes that didn't cover the problem. The installer continued after I acknowledged the failure of installation for DirectX 2010.

### Atlas Version

Atlas 10 22H2

### Desktop information

- Processor - 16 x Intel(R) Xeon(R) CPU X7560 @ 2.27GHz (2 Sockets)
- RAM amount - 16 GB
- System Drive Type - VirtIO 
- Graphics Card - GTX 1060

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
@Xyueta another one for you maybe?

**Comment by Xyueta** [comment]
Should be working fine as of v0.3.0. The Reticulating Splines issue has been resolved as well.
