### ISSUE TITLE
[FEATURE REQUEST] - Hope to provide more support for Chinese players.

### ISSUE THREAD

**Issue by zpc1042245970** [Atlas-OS/Atlas#790]
### What is your Feature Request regarding to?

The Atlas OS

### Is your feature request related to a problem? Please describe.

With a huge PC user group in China, Atlas OS cannot change the system language to Chinese.

### Describe the solution you would like.

Atlas OS hopes to support changing the system language in subsequent updates, and will also provide Chinese as an optimization option. Please support Windows 11 system as soon as possible.

### Describe alternatives you have considered.

nope

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
You can install Chinese before using atlas afaik. Please do so. Also duplicate issue relating to windows 11, please find the duplicate
