### ISSUE TITLE
[BUG REPORT] - Extensions on chromium browsers  reinstall or forget settings after reboots (still on v0.2.0)

### ISSUE THREAD

**Issue by palamosteliaro** [Atlas-OS/Atlas#798]
### Description

This is a previously reported bug that was marked as solved 3 weeks ago with the latest playbook. However, it's still happening for me on all chromium-based browsers (tried chrome, edge and opera). I tried the "auto-cleaner.cmd" as administrator on safe mode as well as normal mode, but it didn't fix it. Fresh installation of 22h2, with nothing else installed.

### Steps to reproduce (add screenshots if applicable)

1. Fresh installation of 22h2 
2. Latest atlas playbook (0.2.0)
3. tried chrome, edge, opera

### Expected behavior

Expected extensions to be kept installed after system reboot.

### Actual behavior (add screenshots if applicable)

Extensions reinstalling after system reboot.

### Atlas Version

Atlas 10 22H2

### Desktop information

- 5800x3d
- 64gb ram
- 970 Evo Plus
- 3080

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by Xyueta** [comment]
It is fixed, please try running the latest playbook from Github Actions.

**Comment by JayXTQ** [comment]
You obviously didn't read the original thread, Xyueta has already told you it's fixed in the next update but it also states that in the original thread and the way to fix it isn't running auto-cleaner in a different way but instead it is replacing it with the updated one. Please read

**Comment by ErcouldnT** [comment]
Sorry, how can I reach the main thread?
