### ISSUE TITLE
[BUG REPORT] - 

### ISSUE THREAD

**Issue by grandpa1946** [Atlas-OS/Atlas#801]
### Description

when downloading the src dir, creating the archive using 7zip (7z format with right extension) and loading it in the ame wizard, it reports as malicious even tho it's been downloaded from a trusted source (almost the same as version 0.2)

### Steps to reproduce (add screenshots if applicable)

already in description

### Expected behavior

![image](https://github.com/Atlas-OS/Atlas/assets/115040432/f3dcfeb8-8c9c-4303-83fe-4a65ceb688ee)

### Actual behavior (add screenshots if applicable)

malicious:
![image](https://github.com/Atlas-OS/Atlas/assets/115040432/c85b634e-9439-41c8-9b35-eb43855369e1)

### Atlas Version

Atlas 10 22H2

### Desktop information

Intel® Core™ i7-8705G 
8gb ram
KXG50ZNV512G NVMe TOSHIBA 512GB
radeon rx vega m gl

### Requisites

- [x] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by Xyueta** [comment]
No, it is because it has not been verified by the Ameliorated Team.

**Comment by JayXTQ** [comment]
> No, it is because it has not been verified by the Ameliorated Team.

This too, but I'm just explaining another reason ok?

**Comment by Xyueta** [comment]
They didn't modify any source files.

**Comment by JayXTQ** [comment]
> They didn't modify any source files.

I know.
