### ISSUE TITLE
[FEATURE REQUEST] - Installation in offline state

### ISSUE THREAD

**Issue by tglsf** [Atlas-OS/Atlas#804]
### What is your feature request regarding to?

AtlasOS

### Is your feature request related to a problem? Please describe.

In some areas the network quality is poor or there is no network, causing the installation process to be slow or even interrupted. We hope that the installation can be done without internet connection.

### Describe the solution you would like.

If you can prepare all the files you need to download in advance, you can install them on devices without internet access.

### Describe alternatives you have considered.

I don't know for now.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by janwinard** [comment]
Or they want something in our file. Its noticeable the larger your hdd, the longer to download the playbook. Also the amount of upload also gets higher, so I suspect, we sent something to these guys our vulnerable files.
