### ISSUE TITLE
[BUG REPORT] - Fivem NUI Crash

### ISSUE THREAD

**Issue by Agentsarkar** [Atlas-OS/Atlas#805]
### Description

While using any NUI on Fivem it automatically crashes and F8 Shows Unable to load WebGL 
Though i have seen WebGL loads successfully on chrome,keeping an eye on Task manager showed me its killing one of the fivem processes automatically after running for few minutes 

### Steps to reproduce (add screenshots if applicable)

Go to any server 
Open NUI for a couple of minutes
No NUI Loads , Game Crashes 

### Expected behavior

Stuck on NUI Load

### Actual behavior (add screenshots if applicable)

Run normally without getting any background process killed

### Atlas Version

Atlas 10 22H2

### Desktop information

I5 6500
GTX 1650 
8GB Ram

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by Agentsarkar** [comment]
![Uploading 16844801396651549138339519367888.jpg…]()

**Comment by JayXTQ** [comment]
Nobody else has reported issues with FiveM, can you also actually upload the image.

**Comment by PencilNavigator** [comment]
closing since there isn't a reply for 5 days.

**Comment by WEEZOOKARP** [comment]
anyone found a fix for this as it happens really often for me
