### ISSUE TITLE
Couldn't connect bluetooth

### ISSUE THREAD

**Issue by Felipe-Antonio19** [Atlas-OS/Atlas#81]
i try to connect my xbox control through bluetooth, but it is not possible because it asks to update the drivers in windows update, but it is not possible to work in windows update... can you help me?

**Comment by Zusier** [comment]
Atlas >> Drivers >> SDIO, make sure bluetooth is enabled aswell

**Comment by Felipe-Antonio19** [comment]
![cmd_bluetooth](https://user-images.githubusercontent.com/91768101/147618272-376effe3-2505-4450-bb90-3b496cfb5bbb.jpg)
when i try to enable bluetooth the cmd returns this. Is correct?
