### ISSUE TITLE
[BUG REPORT] - Atlas os wont install

### ISSUE THREAD

**Issue by VideoBeeYT** [Atlas-OS/Atlas#813]
### Description

I followed the tutorial on youtube on how to install atlas os but it didn't install.
From what i've researched my password was meant to change to ''atlas'' and my backround would become atlas and i would have a script folder but none of this happens despite the installer reporting 0 errors and restarting my laptop at end  but nothing changes, please help.

### Steps to reproduce (add screenshots if applicable)

1. Install atlas os using AME wizard.exe
2. Let it prepare your Laptop / PC 
3. Let it restart
4. Let it do its stuff 
5. Let it restart (Again)
6. Now see as nothing has changed and you got 0 error codes.

### Expected behavior

my password was meant to change to ''atlas'' and my backround would become atlas and i would have a script folder

### Actual behavior (add screenshots if applicable)

![image](https://github.com/Atlas-OS/Atlas/assets/128188382/22967125-75d8-4b80-8c08-40a627103eb5)

### Atlas Version

Atlas 10 22H2

### Desktop information

Device name	DESKTOP-2EPQB69
Processor	Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz   1.19 GHz
Installed RAM	8.00 GB (7.80 GB usable)
System type	64-bit operating system, x64-based processor
GPU : IGPU

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

I was logged in a mincrosoft account (if it changes anything)

**Comment by PencilNavigator** [comment]
try again without logging into microsoft account, see if this occurs again.

**Comment by VideoBeeYT** [comment]
> try again without logging into microsoft account, see if this occurs again.

i tried it didnt work either

**Comment by JayXTQ** [comment]
Try installing via the method on the docs. Also, sorry for a long response.
