### ISSUE TITLE
[FEATURE REQUEST] - Option to keep Edge

### ISSUE THREAD

**Issue by Slowwwww** [Atlas-OS/Atlas#828]
### What is your feature request regarding to?

AtlasOS

### Is your feature request related to a problem? Please describe.

I use and prefer using Edge as my daily browser (due in part to vertical tabs).

### Describe the solution you would like.

An option to install Atlas-OS so that Edge is fully functional.

### Describe alternatives you have considered.

Sucking it up and switching to a different browser.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by he3als** [comment]
This will be considered for v0.3 with a prompt to keep it or not and a script to uninstall it (no install script as you can just download it normally), only if it doesn't cause issues.

**Comment by Xyueta** [comment]
You can install it after it was uninstalled.
To make it easier for you, I added an option to install from our Software Installer app:
https://github.com/Atlas-OS/Atlas/commit/0779624a4a44b3a9f64b3325d6d67c758ef08ee6

**Comment by llors418** [comment]
I installed it by myself and seems to have some issues with windows update and loggin as well as rendering some web pages like the atlas webside, i dont know if it goes here but seems to have realation on keeping the edge browser on the os may not be so simple

**Comment by he3als** [comment]
This issue is fully fixed as a note, using Edge is an option in v0.3.0.
