### ISSUE TITLE
[BUG REPORT] -  Extensions resetting on every Microsoft Edge restart

### ISSUE THREAD

**Issue by ashjaylk** [Atlas-OS/Atlas#830]
### Description

I'm encountering an issue with Microsoft Edge where all my extensions reset to their default settings every time I restart the browser. The IDM (Internet Download Manager) extension installs itself again upon each browser launch, displaying a "thank you" page. Moreover, the "Enhancer for YouTube" extension requires reconfiguration every time I open Edge, causing inconvenience and frustration.

### Steps to reproduce (add screenshots if applicable)

1. Launch Microsoft Edge.
2. Install and configure desired extensions, such as IDM and Enhancer for YouTube.
3. Restart Microsoft Edge.
4. Observe that all extensions reset to their default settings.
5. Notice that the IDM extension installs again, displaying a "thank you" page.
6. Note that the Enhancer for YouTube extension requires reconfiguration.

### Expected behavior

Extensions should retain their settings and configurations after restarting Microsoft Edge. The IDM extension should remain installed without reinstalling or displaying a "thank you" page. The Enhancer for YouTube extension should retain its configuration settings.

### Actual behavior (add screenshots if applicable)

Extensions reset to default settings, requiring manual reconfiguration after each browser restart. The IDM extension reinstalls itself upon browser launch and shows a "thank you" page. The Enhancer for YouTube extension needs reconfiguration every time Edge is opened.

### Atlas Version

Atlas 10 22H2

### Desktop information

Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz   1.19 GHz
4.00 GB RAM (3.77 GB usable)
Intel GPU

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

I have tried disabling and re-enabling extensions, clearing the browser cache, and reinstalling Microsoft Edge, but the issue persists. This problem occurs consistently on my system with the following specifications:

Operating System: Atlas OS Version 22H2 (OS Build 19045.2965)
Microsoft Edge Version: 114.0.1823.43 (Official build) (64-bit)

Please let me know if there are any further troubleshooting steps or if you require additional information to address this issue effectively.

**Comment by JayXTQ** [comment]
Duplicate issue #735
