### ISSUE TITLE
[BUG REPORT] - Roblox crashes when i launch the game on the web version of it

### ISSUE THREAD

**Issue by SZASUKE10** [Atlas-OS/Atlas#831]
### Description

when i press play on a game on the roblox website roblox will launch then crash right away with just a sound of the game

### Steps to reproduce (add screenshots if applicable)

![Screenshot_2](https://github.com/Atlas-OS/Atlas/assets/103879928/0ffc5393-23b0-4954-a04f-c3db5b5029ae)
![Screenshot_3](https://github.com/Atlas-OS/Atlas/assets/103879928/f903e368-66fc-4236-be2e-3bb7f4c223a4)

### Expected behavior

to launch the game and play it

### Actual behavior (add screenshots if applicable)

![Screenshot_3](https://github.com/Atlas-OS/Atlas/assets/103879928/76a0ba89-cacd-4753-bb75-a735c7df142c)
it says it crashes but still plays the game sound

### Atlas Version

Atlas 10 22H2

### Desktop information

- Intel i5 12500h
- 8gb ram DDR4
- NVIDIA RTX 3050 Laptop Gpu
- from Acer Nitro 5 aka ACER itself

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

please just fix this if im not the only one

**Comment by SZASUKE10** [comment]
i fixed it ty

**Comment by Icey67** [comment]
> i fixed it ty

how did you fix it?
