### ISSUE TITLE
[BUG REPORT] - microphone not working

### ISSUE THREAD

**Issue by dipeshm12** [Atlas-OS/Atlas#834]
### Description

Microphone is not working.
I tried on google and other place , microphone is not working .
i also can't hear my teammates voices in cyber hunter game and also micorphone is not working.

### Steps to reproduce (add screenshots if applicable)

   i

### Expected behavior

sites should hear what i say in microphone because its working on other devices and i should also hear what my teammates are saying in game.

### Actual behavior (add screenshots if applicable)

even when i allow sites they can't hear me. i can't hear my teammates in any game.

### Atlas Version

Atlas 10 22H2

### Desktop information

intel i5 - 5200u
 ram -4gb
intel hd graphics 5500

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
Hi, can you check you have sound and microphone drivers installed for your device and relevant microphone(s)!

**Comment by Xyueta** [comment]
Also make sure that the Microphone's options in Privacy tab in Settings app are enabled and that NSI service works fine.

**Comment by vifezdev** [comment]
> Also make sure that the Microphone's options in Privacy tab in Settings app are enabled and that NSI service works fine.

This worked for me, thanks!

**Comment by VladimirPchelko** [comment]
After installing atlasOs my microphone stopped working and only this fixed issue for me: https://www.reddit.com/r/windows/comments/94wg5x/updated_to_win10_april_update_1803_and_cannot/


> [HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy]

"LetAppsAccessMicrophone"

Make sure this is not set to 2. Just delete it. It was very common for some of the privacy hacks to disable this.

**Comment by vifezdev** [comment]
> After installing atlasOs my microphone stopped working and only this fixed issue for me: https://www.reddit.com/r/windows/comments/94wg5x/updated_to_win10_april_update_1803_and_cannot/
> 
> (Microphone's options in Privacy tab in Settings app was grayed out)
> 
> > [HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy]
> > "LetAppsAccessMicrophone"
> > Make sure this is not set to 2. Just delete it. It was very common for some of the privacy hacks to disable this.

Yo broski, try to reinstall the drivers i had this issue till i un installed atlas (i fixed it but had to re install mic drivers and do some other shit on the site, just find the discord and ask in support!)
