### ISSUE TITLE
[FEATURE REQUEST] -  Retention function

### ISSUE THREAD

**Issue by FynnFbc** [Atlas-OS/Atlas#837]
### What is your feature request regarding to?

AtlasOS

### Is your feature request related to a problem? Please describe.

Hope to support version 21H2 19044
Request retention
Remote Desktop Services Features
Unified Write Filter
thanks

### Describe the solution you would like.

1

### Describe alternatives you have considered.

1

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by Xyueta** [comment]
- Remote Desktop is supported in the latest playbook (actions). 
- 21H2/2109/19044 won't be supported by the Atlas playbook and we have no reason to.
