### ISSUE TITLE
Add Microsoft Edge to the browser installation script

### ISSUE THREAD

**Issue by 1011100011111000** [Atlas-OS/Atlas#84]
I have seen in a video that there is a browser installation script. I think Ms Edge chromium should be there too. I know it is not a privacy friendly one, but you already added Google chrome. So why not edge. It is the best chromium browser imo. Good luck

**Comment by dran1x** [comment]
It is the better chromium browser but, you can just install it using https://www.microsoft.com/en-us/edge/business/download

**Comment by 1011100011111000** [comment]
Well, it was just an idea. Let me close this then :d
