### ISSUE TITLE
[BUG REPORT] - Resolution problems with RadeonSlimmer

### ISSUE THREAD

**Issue by UltraToon** [Atlas-OS/Atlas#840]
### Description

I know this may not be the correct place to discuss but I dont know where else since issues are closed at RadeonSlimmer.
Without my AMD drivers installed (RX 6600 WHQL Recommended) Im set on a 800x600 resolution in which applications such as RadeonSlimmer does not have a "Run Installer" button as its off the screen. There is a scrollbar at the bottom, but it doesnt seem to work, personally im assuming that the scrollbar problem is AtlasOS related.

### Steps to reproduce (add screenshots if applicable)

1. First boot, no AMD drivers installed (800x600)
2. Open WHQL Drivers Setup
3. Setup RadeonSlimmer as from the docs, but there is no "Run Installer" button
4. Attempting to scroll does nothing.

### Expected behavior

For the scroll bar to work so i can reach the button or the button be squeezed on the window.

### Actual behavior (add screenshots if applicable)

Cannot proceed due to no visibility or accessibility of the "Run Installer" button since I am on 800x600

### Atlas Version

Atlas 10 22H2

### Desktop information

Intel i3 12100F
Silicon Power 16gb DDR4 cl16 RAM
TEAM 512GB NVME SSD
AMD RX 6600
144HZ Freesync 1920x1080 Monitor

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

I tried to force a display resolution, that did not work.

**Comment by Xyueta** [comment]
Mind sending the picture of your Radeon Slimmer?

**Comment by UltraToon** [comment]
![image](https://github.com/Atlas-OS/Atlas/assets/92064752/49734c07-76a5-49d2-b159-03655347ed80)
The scrollbar at the bottom doesn't work. This is the best recreation of the issue as I used DDU to uninstall my drivers to get back into this state. I have attempted to freesize the window but to no luck. @Xyueta

**Comment by UltraToon** [comment]
P.S. I have pressed Modify Installer in this image.

**Comment by Xyueta** [comment]
Try reporting it on their github website. It should be working just fine
