### ISSUE TITLE
On Supporting the Network Environment of the China

### ISSUE THREAD

**Issue by wwb521** [Atlas-OS/Atlas#842]
### What is your feature request regarding to?

AtlasOS

### Is your feature request related to a problem? Please describe.

I hope to support the network environment of the China. The current script is stuck and too slow in China

### Describe the solution you would like.

I hope to support the network environment of the China

### Describe alternatives you have considered.

Using VPN, but the effect is unstable

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by PencilNavigator** [comment]
If you are talking about stucking on reticulating spilines for very long. here is a **temporary** solution. https://rs.atlasos.dev
For the whole playbook, unfortunatly we cannot do much about it unless the dependencies we use are served in china and has an ICP license (Whichi is required by the Government to legally provide public service in china). Use a VPN that proxies system processes, see if that helps.
