### ISSUE TITLE
[FEATURE REQUEST] - Barebones "video game console"-like mode (or edition)

### ISSUE THREAD

**Issue by jan-kleks** [Atlas-OS/Atlas#843]
### What is your feature request regarding to?

AtlasOS

### Is your feature request related to a problem? Please describe.

Video game consoles do not run a full desktop -- you always feel like gaming is the main focus. Maybe you could streamline Atlas OS even further to achieve a similar effect. It could be especially nice for computers connected to TVs and those handheld gaming Windows computers. Suggestions below.

### Describe the solution you would like.

- could be implemented as a mode (in this case a "maintenance" setting would bring a normal desktop) or as a new separate edition

- **turn off as much system stuff as possible** when running a given game (maybe there even could be some kind of a game profiler to check what is absolutely necessary for a given title)

- there could be an option allowing user to replace explorer.exe with something more console-like, for example Playnite, Steam Big Picture mode, or Armoury Crate SE (ROG Ally)  See: https://learn.microsoft.com/en-us/windows/configuration/kiosk-shelllauncher

- create guides showing people how to easily replace the operating system on their devices (Steam Deck, ROG Ally, computers connected to living room TVs) with your console-like version

- these are just my suggestions, maybe other people will have even better ones regarding this topic

### Describe alternatives you have considered.

Playing on an actual console

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by jan-kleks** [comment]
See also: https://github.com/Ingan121/DWMKiller

**Comment by sabaasa** [comment]
this is wayyyyy out of scope of Atlas lmao 

you should look into something else than custom os's for something like this

**Comment by JayXTQ** [comment]
As the comment above said, Atlas wouldn’t really have a need for this as it is for PC only and we (as in the atlas team) have not had any ideas of doing this so far. This is the only person I have seen ask for something like this. What would **you** personally use this for?

**Comment by jan-kleks** [comment]
For a computer connected permanently to the TV, and possibly for ROG Ally.

I normally use macs (and sometimes Linux) for work, but Windows solely for gaming. It would have been just nice to use something like "maintenance mode" (described in the first post) only for initial setup of some games that I want to play, and then go full "console-like". 

And maybe the system could be optimized even further, if more stuff was turned off?

**Comment by JayXTQ** [comment]
Does Windows 10 have that functionality though to be used in that way. I’ve never looked into “Tablet Mode” which by looking at the name, could be what you are looking for. I have seen people put Atlas on the steam deck and stuff so try with the ROG. Otherwise, if tablet mode works for what you are doing you can modify the Atlas source code to fit your need. This isn’t something we want to implement ourselves probably as it wouldn’t be used by many unlike our default version we have now. Please get back if this doesn’t fit your need

**Comment by jan-kleks** [comment]
Thank you for looking into this, it shows that you care about users' suggestions! I will also explore various other ways of customizing the OS myself. You can close this GitHub issue, or leave it open in case someone would have more feedback.

Keep up the great work!

**Comment by JayXTQ** [comment]
Will close unless someone gives feedback, which is when I will reopen if valid
