### ISSUE TITLE
Untrusted system file uxtheme.dll

### ISSUE THREAD

**Issue by dxwil** [Atlas-OS/Atlas#845]
### Description

Trying to launch Fortnite but Easy Anti Cheat shows an error “Untrusted system file (C:\Windows\System32\uxtheme.dll)”. Fortnite used to sometimes show this but launch after trying again, but now I cannot launch it as it shows this error every time.

### Steps to reproduce (add screenshots if applicable)

1. Launch Fortnite from Epic Games Launcher

### Expected behavior

Fortnite launching

### Actual behavior (add screenshots if applicable)

Easy Anti Cheat shows an error “ Untrusted system file (C:\Windows\System32\uxtheme.dll)”

### Atlas Version

Atlas 10 22H2

### Desktop information

- AMD Ryzen 5 2600
- 28GB ram
- NVIDIA GeForce gtx 750 ti

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by Xyueta** [comment]
It is a random issues that happens sometimes, verify games files (integrity of files).

**Comment by rez1xt** [comment]
This might happen if you used nvcleanstall to install gpu drivers, and didn't check antichest support. If you did that, I suggest u to remove driver with ddu, and install from nvidia's site. Or follow atlas docs and use nvcleanstall like that. 

@dxwil

**Comment by dxwil** [comment]
> This might happen if you used nvcleanstall to install gpu drivers, and didn't check anticheat support. If you did that, I suggest u to remove driver with ddu, and install from nvidia's site. Or follow atlas docs and use nvcleanstall like that. 
> 
> 
> 
> @dxwil 

I installed nvidia drivers from the official GeForce Experience application

**Comment by dxwil** [comment]
> It is a random issues that happens sometimes, verify games files (integrity of files).

Verifying files fixed it once, now when it happens verifying files does not change anything
