### ISSUE TITLE
[BUG REPORT] - Can't install Windows Media Feature Pack (for watching Netflix or Amazon)

### ISSUE THREAD

**Issue by Duke-M-commits** [Atlas-OS/Atlas#847]
### Description

Payed streaming services wont play in an [Windows 10 N Edition](https://en.wikipedia.org/wiki/Windows_10_editions#Regional_variations) because of the cut out "Windows Media Feature Pack".

Normally you can just post-install that missing component.

But all versions available on [this official site](https://www.microsoft.com/en-us/software-download/mediafeaturepack) won't install.
![image](https://github.com/Atlas-OS/Atlas/assets/69652463/e3cd3a4c-a470-469a-9bd6-caedf48973e3)

### Steps to reproduce (add screenshots if applicable)

1. Install an Windows N Edition
2. Upgrade to AtlasOS
3. Try to play an Netflix or Amazon Video, feel terrified
4. Try to install the Windows Media Feature Pack, feel horrified

### Expected behavior

Watching Netflix or Amazon Prime should work.

### Actual behavior (add screenshots if applicable)

Netflix (Error Code F7701-1003):
![image](https://github.com/Atlas-OS/Atlas/assets/69652463/5dfd1ee9-4163-40fc-a96e-921f0e9dbcc4)
Amazon (Digital Rights Error):
![image](https://github.com/Atlas-OS/Atlas/assets/69652463/53f1aee1-2a0d-450d-8265-27cbdf88b61c)
That's the referenced link if you're interested:
https://support.mozilla.org/en-US/kb/fix-video-audio-problems-firefox-windows

### Atlas Version

Atlas 10 22H2

### Desktop information

* i7-3770
* 16 GB
* 2TB (Samsung 870 Evo)
* GTX 1060 (Founders Edition)

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

Firefox 115.02 (64-bit)
Widevine Content Decryption Module - Enabled
![image](https://github.com/Atlas-OS/Atlas/assets/69652463/c186660d-2a4c-48c1-ae1d-47a61d1d3a7e)

And yes, that stuff works on an Windows Version with Windows Media Feature Pack.

**So the question is:**  
What can be done to make that Feature Pack installable?

PS: Depending on how you look at it, this can be a feature request or a bug, sorry for mislabeling, if you are standing on the other side :)

**Comment by sabaasa** [comment]
basically blah blah blah I installed an N edition and am suffering from skill issue.
??? why install n edition? it has no performance improvements and only exists because of legal reasons.

**Comment by PencilNavigator** [comment]
Can you try installing the atlas official supported Home/Pro edition?

**Comment by Duke-M-commits** [comment]
I have one key, and it's this one. It's what I have. @sabaasa please keep it together, that's not contributing to anything

**Comment by Duke-M-commits** [comment]
I'll try to to find an compatible package when I have the time for it these next days.

If not, my next test will be reinstalling, installing the missing component and then upgrade to AtlasOS. Although that's a hassle I'd like to miss out on.

Anyway, I'll report back.

**Comment by PencilNavigator** [comment]
@Duke-M-commits https://forum.atlasos.net/d/24-how-to-activate-atlas-for-the-people-that-get-stuck-in-settings
If you don't have a pro/home license, please follow this.

**Comment by Duke-M-commits** [comment]
I found the solution to my problem.
At some point in time Microsoft started to integrate the pack into Windows optional features.
Settings -> Apps & Features -> Optional features -> Add a feature -> Install Media Feature Pack
This makes video streaming work again.

**Comment by sabaasa** [comment]
> @PencilNavigator I have one key, and it's this one. It's what I have, sorry.
> 
> @sabaasa please keep it together, that's not contributing to anything.
> This is an dev platform, not the steam forums. We're on a bug tracker, it tracks bugs, this doesn't mean that they need to get fixed, it's a documentation utility, not a chat, your personal opinion is only viable if you contribute information or ask for it in that context.

you're completely oblivious to the fact that N editions aren't officially supported. you're also oblivious to the fact that Windows Update components are removed and hence you can't install packages. I don't understand what kind of "bug report" this is, of course bugs will fucking appear on unsupported conditions

**Comment by Duke-M-commits** [comment]
I already posted a solution and closed the issue myself. Windows 10 N works.

**Comment by PencilNavigator** [comment]
Good to hear. But just to note we will only provide support for Home/Pro editions. I'll be closing it as an invalid.
If in any near future you found this not working on Home/Pro editions, you are welcome to open an issue again.

**Comment by alagane** [comment]
> I found the solution to my problem. At some point in time Microsoft started to integrate the pack into Windows optional features. Settings -> Apps & Features -> Optional features -> Add a feature -> Install Media Feature Pack This makes video streaming work again.

Thanks for the tip!

**Comment by Permanently** [comment]
Under Windows 10, it'll be **Windows Media Player Legacy (App)** in Optional features.
