### ISSUE TITLE
[BUG REPORT] - Bluetooth audio is unusable

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Atlas-OS/Atlas#848]
### Description

I'm about ready to pull my hair out. After installing a driver for the Beelink SER 5 (in which drivers are rare as hell, fuck you Beelink) and enabling Bluetooth using the script, the audio delay is so bad it is completely unusable. The only thing that works right is the Handsfree Audio Sink, high quality audio however doesn't.

### Steps to reproduce (add screenshots if applicable)

1. Install bluetooth drivers for the Beelink SER 5 (MUST BE A BEELINK SER 5)
2. Enable Bluetooth using the script provided.
3. Connect to a Bluetooth speaker
4. Play audio.

### Expected behavior

High quality Bluetooth audio with little to no audio delay.

### Actual behavior (add screenshots if applicable)

Practically unusable Bluetooth audio with tons of audio delay.

### Atlas Version

Atlas 10 22H2

### Desktop information

System: Shitty Beelink SER 5
AMD Ryzen 5 5600H with Radeon Graphics            3.30 GHz
32.0 GB (31.4 GB usable)
Adapter in question: MediaTek Inc RZ608

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by TheSystemGuy1337** [comment]
Since I mostly use Linux, here is my LSHW:
thesystemguy-ser            
    description: Mini PC
    product: SER (SER)
    vendor: AZW
    version: Default string
    serial: B56002KH10325
    width: 64 bits
    capabilities: smbios-3.3.0 dmi-3.3.0 smp vsyscall32
    configuration: boot=normal chassis=mini sku=SER uuid=03000200-0400-0500-0006-000700080009
  *-core
       description: Motherboard                                                           
       product: SER                                                                       
       vendor: AZW                                                                        
       physical id: 0                                                                     
       version: V01                                                                       
       serial: B7PS0690711953                                                             
       slot: Default string                                                               
     *-firmware                                                                           
          description: BIOS                                                               
          vendor: American Megatrends International, LLC.                                 
          physical id: 0                                                                  
          version: SER_V1.14_P4C7M43                                                      
          date: 07/08/2022                                                                
          size: 64KiB                                                                     
          capabilities: pci upgrade shadowing cdboot bootselect socketedrom edd int13floppynec int13floppytoshiba int13floppy360 int13floppy1200 int13floppy720 int13floppy2880 int5printscreen int9keyboard int14serial int17printer int10video acpi usb biosbootspecification uefi                                                                                                            
     *-memory
          description: System Memory
          physical id: 13
          slot: System board or motherboard
          size: 32GiB
        *-bank:0
             description: SODIMM DDR4 Synchronous Unbuffered (Unregistered) 3200 MHz (0.3 ns)
             product: CT16G4SFS832A.C8FE
             vendor: Unknown
             physical id: 0
             serial: E7237A09
             slot: DIMM 0
             size: 16GiB
             width: 64 bits
             clock: 3200MHz (0.3ns)
        *-bank:1
             description: SODIMM DDR4 Synchronous Unbuffered (Unregistered) 3200 MHz (0.3 ns)
             product: CT16G4SFS832A.C8FE
             vendor: Unknown
             physical id: 1
             serial: E7237C51
             slot: DIMM 0
             size: 16GiB
             width: 64 bits
             clock: 3200MHz (0.3ns)
     *-cache:0
          description: L1 cache
          physical id: 15
          slot: L1 - Cache
          size: 384KiB
          capacity: 384KiB
          clock: 1GHz (1.0ns)
          capabilities: pipeline-burst internal write-back unified
          configuration: level=1
     *-cache:1
          description: L2 cache
          physical id: 16
          slot: L2 - Cache
          size: 3MiB
          capacity: 3MiB
          clock: 1GHz (1.0ns)
          capabilities: pipeline-burst internal write-back unified
          configuration: level=2
     *-cache:2
          description: L3 cache
          physical id: 17
          slot: L3 - Cache
          size: 16MiB
          capacity: 16MiB
          clock: 1GHz (1.0ns)
          capabilities: pipeline-burst internal write-back unified
          configuration: level=3
     *-cpu
          description: CPU
          product: AMD Ryzen 5 5600H with Radeon Graphics
          vendor: Advanced Micro Devices [AMD]
          physical id: 18
          bus info: cpu@0
          version: 25.80.0
          serial: Unknown
          slot: FP6
          size: 1950MHz
          capacity: 4250MHz
          width: 64 bits
          clock: 100MHz
          capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp x86-64 constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm cpufreq
          configuration: cores=6 enabledcores=6 microcode=173015052 threads=12
     *-pci:0
          description: Host bridge
          product: Renoir/Cezanne Root Complex
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 00
          width: 32 bits
          clock: 33MHz
        *-generic UNCLAIMED
             description: IOMMU
             product: Renoir/Cezanne IOMMU
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 0.2
             bus info: pci@0000:00:00.2
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: msi ht bus_master cap_list
             configuration: latency=0
        *-pci:0
             description: PCI bridge
             product: Renoir/Cezanne PCIe GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 2.1
             bus info: pci@0000:00:02.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:27 ioport:f000(size=4096) memory:fcf00000-fcffffff
           *-network
                description: Ethernet interface
                product: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
                vendor: Realtek Semiconductor Co., Ltd.
                physical id: 0
                bus info: pci@0000:01:00.0
                logical name: enp1s0
                version: 15
                serial: 70:70:fc:00:7d:b5
                capacity: 1Gbit/s
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress msix bus_master cap_list ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
                configuration: autonegotiation=on broadcast=yes driver=r8169 driverversion=5.15.0-76-generic firmware=rtl8168h-2_0.0.2 02/26/15 latency=0 link=no multicast=yes port=twisted pair
                resources: irq:32 ioport:f000(size=256) memory:fcf04000-fcf04fff memory:fcf00000-fcf03fff
        *-pci:1
             description: PCI bridge
             product: Renoir/Cezanne PCIe GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 2.2
             bus info: pci@0000:00:02.2
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:28 ioport:e0300000(size=2097152)
           *-network
                description: Wireless interface
                product: MEDIATEK Corp.
                vendor: MEDIATEK Corp.
                physical id: 0
                bus info: pci@0000:02:00.0
                logical name: wlp2s0
                version: 00
                serial: 10:6f:d9:3c:ba:d3
                width: 64 bits
                clock: 33MHz
                capabilities: pciexpress msi pm bus_master cap_list ethernet physical wireless
                configuration: broadcast=yes driver=mt7921e driverversion=5.15.0-76-generic firmware=____010000-20220209150915 ip=192.168.1.27 latency=0 link=yes multicast=yes wireless=IEEE 802.11
                resources: irq:70 memory:e0300000-e03fffff memory:e0400000-e0403fff memory:e0404000-e0404fff
        *-pci:2
             description: PCI bridge
             product: Renoir/Cezanne PCIe GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 2.3
             bus info: pci@0000:00:02.3
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:29 memory:fce00000-fcefffff
           *-nvme
                description: NVMe device
                product: KINGSTON SNVS500G
                vendor: Kingston Technology Company, Inc.
                physical id: 0
                bus info: pci@0000:03:00.0
                logical name: /dev/nvme0
                version: S8542105
                serial: 50026B7381753EFC
                width: 64 bits
                clock: 33MHz
                capabilities: nvme pm msi pciexpress msix nvm_express bus_master cap_list
                configuration: driver=nvme latency=0 nqn=nqn.2020-04.com.kingston:nvm-subsystem-sn-50026B7381753EFC state=live
                resources: irq:42 memory:fce00000-fce03fff
              *-namespace:0
                   description: NVMe disk
                   physical id: 0
                   logical name: hwmon0
              *-namespace:1
                   description: NVMe disk
                   physical id: 2
                   logical name: /dev/ng0n1
              *-namespace:2
                   description: NVMe disk
                   physical id: 1
                   bus info: nvme@0:1
                   logical name: /dev/nvme0n1
                   size: 465GiB (500GB)
                   capabilities: gpt-1.00 partitioned partitioned:gpt
                   configuration: guid=5794cda3-3d13-4506-8417-23e93a7b47f4 logicalsectorsize=512 sectorsize=512 wwid=eui.00000000000000000026b7381753efc5
                 *-volume:0 UNCLAIMED
                      description: Windows FAT volume
                      vendor: MSDOS5.0
                      physical id: 1
                      bus info: nvme@0:1,1
                      version: FAT32
                      serial: 8ab0-c6ce
                      size: 95MiB
                      capacity: 99MiB
                      capabilities: boot fat initialized
                      configuration: FATs=2 filesystem=fat label=SYSTEM name=EFI system partition
                 *-volume:1
                      description: reserved partition
                      vendor: Windows
                      physical id: 2
                      bus info: nvme@0:1,2
                      logical name: /dev/nvme0n1p2
                      serial: fc3010f3-fc07-4c3d-b6b5-618b94d52c6a
                      capacity: 15MiB
                      capabilities: nofs
                      configuration: name=Microsoft reserved partition
                 *-volume:2
                      description: Windows NTFS volume
                      vendor: Windows
                      physical id: 3
                      bus info: nvme@0:1,3
                      logical name: /dev/nvme0n1p3
                      logical name: /mnt/ntfs
                      version: 3.1
                      serial: 005b9db7-25c2-544d-8754-d252fc9c2716
                      size: 184GiB
                      capacity: 184GiB
                      capabilities: ntfs initialized
                      configuration: clustersize=4096 created=2022-07-27 11:48:26 filesystem=ntfs mount.fstype=fuseblk mount.options=rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096 name=Basic data partition state=mounted
                 *-volume:3
                      description: EXT4 volume
                      vendor: Linux
                      physical id: 4
                      bus info: nvme@0:1,4
                      logical name: /dev/nvme0n1p4
                      logical name: /
                      version: 1.0
                      serial: 6e3bb957-76b4-470d-8f1f-97f210d736e0
                      size: 281GiB
                      capabilities: journaled extended_attributes large_files huge_files dir_nlink recover 64bit extents ext4 ext2 initialized
                      configuration: created=2023-05-25 09:18:07 filesystem=ext4 lastmountpoint=/ modified=2023-07-15 11:22:55 mount.fstype=ext4 mount.options=rw,relatime,errors=remount-ro mounted=2023-07-15 11:22:56 state=mounted
        *-pci:3
             description: PCI bridge
             product: Renoir Internal PCIe GPP Bridge to Bus
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 8.1
             bus info: pci@0000:00:08.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:30 ioport:e000(size=4096) memory:fc900000-fccfffff ioport:d0000000(size=270532608)
           *-display
                description: VGA compatible controller
                product: Cezanne
                vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                physical id: 0
                bus info: pci@0000:04:00.0
                logical name: /dev/fb0
                version: c6
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix vga_controller bus_master cap_list fb
                configuration: depth=32 driver=amdgpu latency=0 resolution=1920,1080
                resources: irq:49 memory:d0000000-dfffffff memory:e0000000-e01fffff ioport:e000(size=256) memory:fcc00000-fcc7ffff
           *-multimedia:0
                description: Audio device
                product: Renoir Radeon High Definition Audio Controller
                vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                physical id: 0.1
                bus info: pci@0000:04:00.1
                logical name: card0
                logical name: /dev/snd/controlC0
                logical name: /dev/snd/hwC0D0
                logical name: /dev/snd/pcmC0D3p
                logical name: /dev/snd/pcmC0D7p
                logical name: /dev/snd/pcmC0D8p
                logical name: /dev/snd/pcmC0D9p
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress msi bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:72 memory:fccc8000-fcccbfff
              *-input:0
                   product: HD-Audio Generic HDMI/DP,pcm=3
                   physical id: 0
                   logical name: input5
                   logical name: /dev/input/event5
              *-input:1
                   product: HD-Audio Generic HDMI/DP,pcm=7
                   physical id: 1
                   logical name: input6
                   logical name: /dev/input/event6
              *-input:2
                   product: HD-Audio Generic HDMI/DP,pcm=8
                   physical id: 2
                   logical name: input7
                   logical name: /dev/input/event7
              *-input:3
                   product: HD-Audio Generic HDMI/DP,pcm=9
                   physical id: 3
                   logical name: input8
                   logical name: /dev/input/event8
           *-generic
                description: Encryption controller
                product: Family 17h (Models 10h-1fh) Platform Security Processor
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.2
                bus info: pci@0000:04:00.2
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix bus_master cap_list
                configuration: driver=ccp latency=0
                resources: irq:32 memory:fcb00000-fcbfffff memory:fcccc000-fcccdfff
           *-usb:0
                description: USB controller
                product: Renoir/Cezanne USB 3.1
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.3
                bus info: pci@0000:04:00.3
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:35 memory:fca00000-fcafffff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 5.15.0-76-generic xhci-hcd
                   physical id: 0
                   bus info: usb@1
                   logical name: usb1
                   version: 5.15
                   capabilities: usb-2.00
                   configuration: driver=hub slots=4 speed=480Mbit/s
                 *-usb:0
                      description: Mouse
                      product: PixArt USB Optical Mouse
                      vendor: PixArt
                      physical id: 1
                      bus info: usb@1:1
                      logical name: input3
                      logical name: /dev/input/event3
                      logical name: /dev/input/mouse0
                      version: 1.00
                      capabilities: usb-2.00 usb
                      configuration: driver=usbhid maxpower=100mA speed=2Mbit/s
                 *-usb:1
                      description: Keyboard
                      product: Unicomp Inc Unicomp R7_2_10x_Kbrd_v7_48
                      vendor: Unicomp Inc
                      physical id: 2
                      bus info: usb@1:2
                      logical name: input4
                      logical name: /dev/input/event4
                      logical name: input4::capslock
                      logical name: input4::compose
                      logical name: input4::kana
                      logical name: input4::numlock
                      logical name: input4::scrolllock
                      version: 7.48
                      capabilities: usb-2.00 usb
                      configuration: driver=usbhid maxpower=100mA speed=12Mbit/s
              *-usbhost:1
                   product: xHCI Host Controller
                   vendor: Linux 5.15.0-76-generic xhci-hcd
                   physical id: 1
                   bus info: usb@2
                   logical name: usb2
                   version: 5.15
                   capabilities: usb-3.10
                   configuration: driver=hub slots=2 speed=10000Mbit/s
           *-usb:1
                description: USB controller
                product: Renoir/Cezanne USB 3.1
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.4
                bus info: pci@0000:04:00.4
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:49 memory:fc900000-fc9fffff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 5.15.0-76-generic xhci-hcd
                   physical id: 0
                   bus info: usb@3
                   logical name: usb3
                   version: 5.15
                   capabilities: usb-2.00
                   configuration: driver=hub slots=4 speed=480Mbit/s
                 *-usb:0
                      description: Mass storage device
                      product: Cruzer Glide
                      vendor: SanDisk
                      physical id: 1
                      bus info: usb@3:1
                      logical name: scsi2
                      version: 1.00
                      serial: 03021226051821044446
                      capabilities: usb-2.00 scsi emulated scsi-host
                      configuration: driver=usb-storage maxpower=200mA speed=480Mbit/s
                    *-disk
                         description: SCSI Disk
                         product: Cruzer Glide
                         vendor: SanDisk
                         physical id: 0.0.0
                         bus info: scsi@2:0.0.0
                         logical name: /dev/sda
                         version: 1.00
                         serial: 03021226051821044446
                         size: 57GiB (61GB)
                         capabilities: removable
                         configuration: ansiversion=6 logicalsectorsize=512 sectorsize=512
                       *-medium
                            physical id: 0
                            logical name: /dev/sda
                            size: 57GiB (61GB)
                            capabilities: gpt-1.00 partitioned partitioned:gpt
                            configuration: guid=a0891d7e-b930-4513-94d9-f629dbd637b2
                          *-volume:0
                               description: data partition
                               vendor: Windows
                               physical id: 1
                               logical name: /dev/sda1
                               logical name: /media/thesystemguy/Ubuntu 22.04.2 LTS amd641
                               serial: a0891d7e-b930-4513-94d8-f629dbd637b2
                               capacity: 4694MiB
                               capabilities: precious readonly
                               configuration: mount.fstype=iso9660 mount.options=ro,nosuid,nodev,relatime,nojoliet,check=s,map=n,blocksize=2048,uid=1000,gid=1000,dmode=500,fmode=400,iocharset=utf8 name=ISO9660 state=mounted
                          *-volume:1
                               description: Windows FAT volume
                               vendor: mkfs.fat
                               physical id: 2
                               logical name: /dev/sda2
                               version: FAT12
                               serial: f7db-4d56
                               size: 15EiB
                               capabilities: boot fat initialized
                               configuration: FATs=2 filesystem=fat label=ESP name=Appended2
                          *-volume:2
                               description: data partition
                               vendor: Windows
                               physical id: 3
                               logical name: /dev/sda3
                               serial: a0891d7e-b930-4513-94da-f629dbd637b2
                               capacity: 299KiB
                               capabilities: precious readonly
                               configuration: name=Gap1
                          *-volume:3
                               description: Windows NTFS volume
                               vendor: Windows
                               physical id: 4
                               logical name: /dev/sda4
                               logical name: /media/thesystemguy/LOL1
                               version: 3.1
                               serial: ccdc-a08d
                               size: 52GiB
                               capacity: 52GiB
                               capabilities: nomount ntfs initialized
                               configuration: clustersize=4096 created=2023-06-17 10:31:58 filesystem=ntfs label=LOL mount.fstype=fuseblk mount.options=rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096 name=Basic data partition state=mounted
                 *-usb:1
                      description: Bluetooth wireless interface
                      product: Wireless_Device
                      vendor: MediaTek Inc.
                      physical id: 3
                      bus info: usb@3:3
                      version: 1.00
                      serial: 000000000
                      capabilities: usb-2.10 bluetooth
                      configuration: driver=btusb maxpower=100mA speed=480Mbit/s
              *-usbhost:1
                   product: xHCI Host Controller
                   vendor: Linux 5.15.0-76-generic xhci-hcd
                   physical id: 1
                   bus info: usb@4
                   logical name: usb4
                   version: 5.15
                   capabilities: usb-3.10
                   configuration: driver=hub slots=2 speed=10000Mbit/s
           *-multimedia:1 UNCLAIMED
                description: Multimedia controller
                product: Raven/Raven2/FireFlight/Renoir Audio Processor
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.5
                bus info: pci@0000:04:00.5
                version: 01
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress msi cap_list
                configuration: latency=0
                resources: memory:fcc80000-fccbffff
           *-multimedia:2
                description: Audio device
                product: Family 17h (Models 10h-1fh) HD Audio Controller
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.6
                bus info: pci@0000:04:00.6
                logical name: card1
                logical name: /dev/snd/controlC1
                logical name: /dev/snd/hwC1D0
                logical name: /dev/snd/pcmC1D0c
                logical name: /dev/snd/pcmC1D0p
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress msi bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:73 memory:fccc0000-fccc7fff
              *-input:0
                   product: HD-Audio Generic Headphone
                   physical id: 0
                   logical name: input10
                   logical name: /dev/input/event10
              *-input:1
                   product: HD-Audio Generic Mic
                   physical id: 1
                   logical name: input9
                   logical name: /dev/input/event9
        *-pci:4
             description: PCI bridge
             product: Renoir Internal PCIe GPP Bridge to Bus
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 8.2
             bus info: pci@0000:00:08.2
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:31 memory:fcd00000-fcdfffff
           *-sata:0
                description: SATA controller
                product: FCH SATA Controller [AHCI mode]
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0
                bus info: pci@0000:05:00.0
                version: 81
                width: 32 bits
                clock: 33MHz
                capabilities: sata pm pciexpress msi ahci_1.0 bus_master cap_list
                configuration: driver=ahci latency=0
                resources: irq:34 memory:fcd01000-fcd017ff
           *-sata:1
                description: SATA controller
                product: FCH SATA Controller [AHCI mode]
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.1
                bus info: pci@0000:05:00.1
                version: 81
                width: 32 bits
                clock: 33MHz
                capabilities: sata pm pciexpress msi ahci_1.0 bus_master cap_list
                configuration: driver=ahci latency=0
                resources: irq:48 memory:fcd00000-fcd007ff
        *-serial
             description: SMBus
             product: FCH SMBus Controller
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 14
             bus info: pci@0000:00:14.0
             version: 51
             width: 32 bits
             clock: 66MHz
             configuration: driver=piix4_smbus latency=0
             resources: irq:0
        *-isa
             description: ISA bridge
             product: FCH LPC Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 14.3
             bus info: pci@0000:00:14.3
             version: 51
             width: 32 bits
             clock: 66MHz
             capabilities: isa bus_master
             configuration: latency=0
           *-pnp00:00
                product: PnP device PNP0c01
                physical id: 0
                capabilities: pnp
                configuration: driver=system
           *-pnp00:01
                product: PnP device PNP0b00
                physical id: 1
                capabilities: pnp
                configuration: driver=rtc_cmos
           *-pnp00:02
                product: PnP device PNP0c02
                physical id: 2
                capabilities: pnp
                configuration: driver=system
     *-pci:1
          description: Host bridge
          product: Renoir PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 101
          bus info: pci@0000:00:01.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:2
          description: Host bridge
          product: Renoir PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 102
          bus info: pci@0000:00:02.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:3
          description: Host bridge
          product: Renoir PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 103
          bus info: pci@0000:00:08.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:4
          description: Host bridge
          product: Cezanne Data Fabric; Function 0
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 104
          bus info: pci@0000:00:18.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:5
          description: Host bridge
          product: Cezanne Data Fabric; Function 1
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 105
          bus info: pci@0000:00:18.1
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:6
          description: Host bridge
          product: Cezanne Data Fabric; Function 2
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 106
          bus info: pci@0000:00:18.2
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:7
          description: Host bridge
          product: Cezanne Data Fabric; Function 3
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 107
          bus info: pci@0000:00:18.3
          version: 00
          width: 32 bits
          clock: 33MHz
          configuration: driver=k10temp
          resources: irq:0
     *-pci:8
          description: Host bridge
          product: Cezanne Data Fabric; Function 4
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 108
          bus info: pci@0000:00:18.4
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:9
          description: Host bridge
          product: Cezanne Data Fabric; Function 5
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 109
          bus info: pci@0000:00:18.5
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:10
          description: Host bridge
          product: Cezanne Data Fabric; Function 6
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10a
          bus info: pci@0000:00:18.6
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:11
          description: Host bridge
          product: Cezanne Data Fabric; Function 7
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10b
          bus info: pci@0000:00:18.7
          version: 00
          width: 32 bits
          clock: 33MHz
  *-input:0
       product: Power Button
       physical id: 1
       logical name: input0
       logical name: /dev/input/event0
       capabilities: platform
  *-input:1
       product: Power Button
       physical id: 2
       logical name: input1
       logical name: /dev/input/event1
       capabilities: platform
  *-input:2
       product: Video Bus
       physical id: 3
       logical name: input2
       logical name: /dev/input/event2
       capabilities: platform

**Comment by JayXTQ** [comment]
Hi, thanks for the issue. I see nobody has responded sadly. Are you still getting this issue? If not, please mention the fix. From my end, I haven't seen this issue. Also, I can't look through that description well enough to understand what headphones you have and does this issue exist on default Windows 10 or just Atlas. I will close if no response!

**Comment by TheSystemGuy1337** [comment]
I have not tried again. I used a generic Walmart “Onn” Bluetooth speaker. Bluetooth on Windows 11 stock worked perfectly on my Sony headphones before I switched to Linux Mint as Windows was becoming unbearable to use. Since nobody is going to solve this, I’ll let this float around until the the devs take notice.

**Comment by Xyueta** [comment]
Hello,
Thanks for creating this issue.
Would you try version v0.3.0 and check out if it works?

**Comment by TheSystemGuy1337** [comment]
How am I supposed to try 0.3.0 when it literally doesn't exist? I looked on
releases and it's not there. Any how would I upgrade an existing
installation?

**Comment by Xyueta** [comment]
Actions tab on GitHub.

**Comment by xSliver** [comment]
I've got the similar issues but I'm using my onboard Bluetooth (Z790 Apex, Intel Bluetooth Controller). No issues with regular BT devices, only those paired for sound have a (big, idk ~+500ms) delay. The pairing device seems to be irrelevant (my speaker is a "soundboks gen 3"). I haven't had this issue on regular windows. I'm on "Atlas Playbook 22H2.apbx".

**Comment by JustOptimize** [comment]
Updates? @TheSystemGuy1337

**Comment by TheSystemGuy1337** [comment]
Reinstalling the driver and unpairing and repairing the device fixed the
issue.
