### ISSUE TITLE
我觉得你这个系统会让鼠标有点飘，不知道为哈

### ISSUE THREAD

**Issue by unknownUser99999** [Atlas-OS/Atlas#851]
### Description

玩fps游戏的时候感觉鼠标好飘

### Steps to reproduce (add screenshots if applicable)

fps游戏

### Expected behavior

鼠标流畅

### Actual behavior (add screenshots if applicable)

很飘

### Atlas Version

Atlas 10 22H2

### Desktop information

w11
3070

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by unknownUser99999** [comment]
> 我不认为这是由 Atlas OS 引起的。 如果问题仅在玩游戏时出现，您应该检查游戏设置中是否启用了鼠标平滑等功能。 如果您为鼠标安装了软件，您也应该检查一下。

我觉得跟其他的没关系吧，我在原来的系统感觉还不错

**Comment by PencilNavigator** [comment]
Hi, Please keep the discussion in english. Thx.
