### ISSUE TITLE
[FEATURE REQUEST] - Audio/Video production-oriented config

### ISSUE THREAD

**Issue by forart** [Atlas-OS/Atlas#861]
### What is your feature request regarding to?

AtlasOS

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you would like.

Many people uses (or are forced to use) Ms-Windows for multimedia production, but obtaining an optimized configuration is not always for everyone.

It would be extremely useful (to push AtlasOS adoption/diffusion too) to have a dedicated configuration of Windows for this purpose.

Some resources:
https://support.presonus.com/hc/en-us/articles/360025279231-Optimizing-Your-Computer-for-Audio-Windows-10
https://support.focusrite.com/hc/en-gb/articles/207355205-Optimising-your-PC-for-Audio-on-Windows-10
https://www.audinate.com/learning/faqs/how-can-i-tune-a-windows-pc-for-best-audio-performance

https://devblogs.microsoft.com/windows-music-dev/unofficial-windows-10-audio-workstation-build-and-tweak-guide-part-1/
https://devblogs.microsoft.com/windows-music-dev/unofficial-windows-10-audio-workstation-build-and-tweak-guide-part-2/

https://www.highend-audiopc.com/PDF/audiophile-optimizer-setup-guide.pdf
https://musicproductionnerds.com/how-to-optimize-windows-10-for-music-production
https://bandzoogle.com/blog/20-ways-to-optimize-your-windows-10-pc-for-music-production

Hope that inspires !

### Describe alternatives you have considered.

Many Windows tweakers, but need time and knowledge to be effective.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by sabaasa** [comment]
Atlas is designed for Gamers and Low-end system users

You should look into ReviOS instead.

**Comment by forart** [comment]
OK, we've collected some open source Windows customization projects (Atlas too) on our [Opendows project](https://github.com/forart/Opendows):
https://github.com/forart/Opendows#open-source-custom-windows-isos

Hope that inspires !

**Comment by he3als** [comment]
> OK, we've collected some open source Windows customization projects (Atlas too) on our [Opendows project](https://github.com/forart/Opendows): [forart/Opendows#open-source-custom-windows-isos](https://github.com/forart/Opendows#open-source-custom-windows-isos)
> 
> Hope that inspires !

Atlas OS is designed for tasks that require low latency in general, not just for gaming, although that's what its focused on.

Many of what Atlas OS already does will highly benefit low latency tasks like music production, although if you have any specific improvements, you can pull request or comment them here.

However, if a certain tweak to do with low latency audio conflicts with another tweak that benefits gaming, it most likely won't be added.
