### ISSUE TITLE
[FEATURE REQUEST] - Activate action center

### ISSUE THREAD

**Issue by giovane1-8** [Atlas-OS/Atlas#865]
### What is your feature request regarding to?

AtlasOS

### Is your feature request related to a problem? Please describe.

Re-enable the Windows Action Center to activate Bluetooth, brightness, and other functions within it

### Describe the solution you would like.

There is a way to activate or have the action center already active when installing the Atlas OS.

### Describe alternatives you have considered.

I don't have any solution, I've tried to activate it in several ways, but without success.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by sabaasa** [comment]
open Atlas folder on desktop, 
3. Configuration > 1. General Configuration > Notifications > Enable Notifications.cmd

are you seriously this dense?

**Comment by giovane1-8** [comment]
I did this procedure countless times, only the notifications had returned, but now the action center appeared. Thank you.
