### ISSUE TITLE
[FEATURE REQUEST] - 

### ISSUE THREAD

**Issue by tak-gamingYT** [Atlas-OS/Atlas#866]
### What is your feature request regarding to?

AtlasOS

### Is your feature request related to a problem? Please describe.

Where is atlas OS for Win 10 21h2 ver?

### Describe the solution you would like.

I want a file .apx for win 10 21h2 ver

### Describe alternatives you have considered.

i dont find any of .apx file for win 10 21h2 version

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by sabaasa** [comment]
why do you want specifically 21h2?

**Comment by tak-gamingYT** [comment]
> why do you want specifically 21h2?
cuz my pc run in win 10 21h2

**Comment by sabaasa** [comment]
update to 22h2 using windows update

**Comment by tak-gamingYT** [comment]
> update to 22h2 using windows update

my pc cant bruh
