### ISSUE TITLE
[BUG REPORT] - Promises and leaks

### ISSUE THREAD

**Issue by Xyson** [Atlas-OS/Atlas#869]
### Description

Hi,

I've been using AtlasOS the past 6 months and love the dedicated work it wint into it, but the disablement of selection of windows updates/security underlies a risk. Too many security issues what Windows was designed for. Give more insight what updates does and what file's it changes (even if you don't like it, it protects). You would get a great backing. As you know they implement hardware failsafe's. These can be used as destruction or abused for personal influence and captalism etc... Hoped that the new release came earlier. Thanks for letting us know more.

Regards,
Digitice/Digitize

### Steps to reproduce (add screenshots if applicable)

1. Unknowing
2. Outdated wiki
3. Inform

### Expected behavior

Abuse of corporations.

### Actual behavior (add screenshots if applicable)

Both sides will abuse this technology for their own good.

### Atlas Version

Atlas 10 22H2

### Desktop information

- i5 4690K
- 16GB
- Windows 10 Pro
- EVGA 1070

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

Learn more :D

**Comment by sabaasa** [comment]
https://deepl.com
please I beg you

**Comment by PencilNavigator** [comment]
https://docs.atlasos.net/
> “I checked the [documentation](https://docs.atlasos.net/) to understand that the issue I am reporting is not normal behavior.”

You checked the box and didn't do what it saids. It's on there.
