### ISSUE TITLE
[BUG REPORT] - Can't Use Ryzen Master Because of "Missing Required OS" 

### ISSUE THREAD

**Issue by Savillion** [Atlas-OS/Atlas#877]
### Description

I cannot start ryzen master because of given error:

Ryzen Master Requires Windows 10 or greater. 
Missing required OS!

### Steps to reproduce (add screenshots if applicable)

1. Install Atlas into a fresh copy of Windows. 
2. Install Ryzen Master and open it.
3. Error:
![Untitled](https://github.com/Atlas-OS/Atlas/assets/107732612/59bfc5af-beb7-456b-a65b-1013070c3f06)

### Expected behavior

Ryzen Master should work because it works on Windows 10. I believe Atlas changes OS name somewhere in the registry. This may cause that error.

### Actual behavior (add screenshots if applicable)

![Untitled](https://github.com/Atlas-OS/Atlas/assets/107732612/79f3c232-c721-45a0-865a-a3a4d1ef9263)

### Atlas Version

Atlas 10 22H2

### Desktop information

Lenovo Ideapad Gaming 3
-R5 4600h
-24gb ram
-Gtx 1650 

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by Savillion** [comment]
I have found that this program requires workstation service to be running. I returned services to defaults by given .reg file in atlas directory and problem is fixed. But with default atlas services, it won't work.

**Comment by SnowzNZ** [comment]
Did you go into the Atlas folder and enable lanman workstation?

**Comment by Savillion** [comment]
No, it was on a clean, untouched setup. To fix the problem, I only enabled default Windows services .reg file. I come to conclusion for "enabling workstation fixing it" from a solution I found on a website. I tried to enable workstation service only but all the dependencies was disabled so I only used the registry file created by atlas. Sorry for my bad language.

**Comment by SnowzNZ** [comment]
Well you need to enable it in the folder 🤦‍♂️

**Comment by Savillion** [comment]
Can you explain it a bit? Is lanman workstation a fix for things like this? I never used it before.

**Comment by sabaasa** [comment]
> Can you explain it a bit? Is lanman workstation a fix for things like this? I never had to used it before.
> 
> Also I cant enable it by the .reg file
> 
> ![2](https://github.com/Atlas-OS/Atlas/assets/107732612/59cfd65e-4352-404a-b07c-b8ede46dd062)
> 

facepalm

**Comment by sabaasa** [comment]
you already broke your install trying to troubleshoot such a simple fucking problem, how did you miss the workstation toggling folder and you didn't miss the default services one?

**Comment by Savillion** [comment]
Its called Lanman workstation I have no idea about what lanman is. I am an old time Atlas user so I know default services one and I always used it but it never caused a problem. 
Why are you that aggressive?

**Comment by sabaasa** [comment]
sorry I woke up from a bad nap 😅

you can toggle a lot of things from the general configuration folder, it's there so you can enable things you need that Atlas disables by default. you can just keep in mind next time you get any issues with something

**Comment by JayXTQ** [comment]
This has been solved in the Discord and it looks like it has been solved here because the answers here were the same as in the Discord. If you are still having troubles, please join the Discord or use our forum!
