### ISSUE TITLE
FH5 bug, when videocard is at 100% use, it only uses 80 watts instead of 160, and because of that the performance is worse than normal windows

### ISSUE THREAD

**Issue by GaborVarga239** [Atlas-OS/Atlas#882]
### Description

As i stated in the title, FH5 use 100% of my gpu (RX 6600 XT) but only draws 80 watts (to clarify i tested it on normal windows and its using the right amount of power) and because of that the performance is worse than on normal windows.

### Steps to reproduce (add screenshots if applicable)

1. Start FH5
2. See that performance is worse than on normal win10

### Expected behavior

FH 5 works fine

### Actual behavior (add screenshots if applicable)

FH 5 have worse performace than on normal windows 10

### Atlas Version

Atlas 10 22H2

### Desktop information

AMD Ryzen 5 5500
16 gb gskill aegis 3000mhz ddr4
APACER nvme ssd 1tb + HGST sshd 1tb + WD purple 2tb (game is installed here)
AMD Radeon 6600XT, newest driver at the time i created the post.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by Ross0907** [comment]
try :1) updating to latest amd drivers
      2) set power limit to max in wattman settings (performance--> tuning --> custom --> power tuning)
      3) check if the gpu pcie power pins are connected properly

**Comment by jacksyrm** [comment]
The issue can't be reproduced. If more people are having difficulty and can provide more information on v0.3.1, we will look into it further.
