### ISSUE TITLE
[BUG REPORT] - Ghelper and armoury crate fan speed and power limit not working.

### ISSUE THREAD

**Issue by WheatGrasses** [Atlas-OS/Atlas#886]
### Description

In both armoury crate and g helper the fan speed and cpu/gpu temps are N/A or just missing. i cannot change the cpu power limit before installing atlas i could.

### Steps to reproduce (add screenshots if applicable)

Download G helper or armoury crate 
open g helper or armoury crate 
and stuff doesnt work.

### Expected behavior

i expected to be able to adjust my cpu power see the temps and fan speed. i also expected to see my gpu temps and fan speed 

### Actual behavior (add screenshots if applicable)

![image](https://github.com/Atlas-OS/Atlas/assets/114834043/ddfc7bcc-c273-4b2e-b721-47c3c5b091a2)
![image](https://github.com/Atlas-OS/Atlas/assets/114834043/f8d66244-3758-429f-b55f-82193438a341)
doesnt work

### Atlas Version

Atlas 10 22H2

### Desktop information

AMD ryzen 9 5980hx 
16gb ram
ssdx2 one crucial one intel
amd radeon rx6800m on driver version 23.7.2

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

The solution from this issue https://github.com/Atlas-OS/Atlas/issues/250 didnt work for me. before installing atlas os g helper worked fine

**Comment by Savillion** [comment]
Can you see if there is any device disabled in device manager? Something that controls this may be disabled. And can you try to reinstall your motherboard chipset drivers and armory crate?

**Comment by Xyueta** [comment]
Is this v0.2? Would you test it on the latest dev branch?

**Comment by alex3236** [comment]
I haven't tested it yet, but maybe it's a driver problem? I believe this kind of software needs driver support

**Comment by jacksyrm** [comment]
Tested and working on v0.3.1 which is releasing today.
