### ISSUE TITLE
Repeat delay should be set to short by default

### ISSUE THREAD

**Issue by gdnzz** [Atlas-OS/Atlas#89]
Since this os focuses on performance, I think it should be delivered with repeat delay set to short by default (from keyboard settings)
![image](https://user-images.githubusercontent.com/76991571/147815130-709430f8-1447-49b5-a8ff-40007d40ed9b.png)

p.s. also you can scrape the on-screen keyboard off from the os, and you can add powershell scripts to uninstall calculator, store and snip&sketch

**Comment by Zusier** [comment]
Repeat delay is simply preference, no? I don't see how thats related to performance

> p.s.
I'm aware 😆 theres a reason they are there

**Comment by gdnzz** [comment]
> Repeat delay is simply preference, no? I don't see how thats related to performance
> 
> > p.s.
> 
> I'm aware 😆 theres a reason they are there

I mean, isn't repeat delay related to input lag? Shorter repeat delay, less input lag, faster keyboard response.

**Comment by Zusier** [comment]
Repeat delay is for after the key is already pressed, so no.
