### ISSUE TITLE
[BUG REPORT] - RANDOM SHUTDOWN

### ISSUE THREAD

**Issue by gigachdd** [Atlas-OS/Atlas#901]
### Description

So I have 2 concerns:

1. I'm having this bug where my laptop that is currently running on Atlas OS is randomly shutting down. I don't know why. 
2. And when I check the device manager, the CHARGE ARBITRATION DRIVER has a yellow exclamation mark something. I tried updating the driver but it says the best version of it is installed.

I don't know what to do guys, please help me.

### Steps to reproduce (add screenshots if applicable)

I cannot screenshot the bug 

### Expected behavior

I cannot screenshot the bug 

### Actual behavior (add screenshots if applicable)

I cannot screenshot the bug 

### Atlas Version

Atlas 10 22H2

### Desktop information

i3 6th gen
4gb ram
Acer

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by alex3236** [comment]
I believe you should try asking this kind of question at Discord :)
