### ISSUE TITLE
[BUG REPORT] - Atlas completed with error

### ISSUE THREAD

**Issue by laolarou726** [Atlas-OS/Atlas#902]
### Description

rt

### Steps to reproduce (add screenshots if applicable)

1. Install Windows 10 22H2 using the official image
2. Perform a Windows update before running Atlas
3. Run Atlas with instructions provided by the AME Wizard

### Expected behavior

It should run without any error

### Actual behavior (add screenshots if applicable)

![image](https://github.com/Atlas-OS/Atlas/assets/25716486/f3b5aabb-ce21-4cbb-87c8-7d96cdd4ae10)

### Atlas Version

Atlas 10 22H2

### Desktop information

- i7-11800H
- 2G RAm
- SSD 60GB (using VMware)
- VMware default display adapter

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

[TIOutput.txt](https://github.com/Atlas-OS/Atlas/files/12505385/TIOutput.txt)
[AdminOutput.txt](https://github.com/Atlas-OS/Atlas/files/12505386/AdminOutput.txt)
[ErrorLog.txt](https://github.com/Atlas-OS/Atlas/files/12505387/ErrorLog.txt)
[FileChecklist.txt](https://github.com/Atlas-OS/Atlas/files/12505388/FileChecklist.txt)
[Packages.txt](https://github.com/Atlas-OS/Atlas/files/12505389/Packages.txt)

**Comment by Xyueta** [comment]
It is an old playbook, run the latest one.

**Comment by laolarou726** [comment]
> It is an old playbook, run the latest one.

Isn't v0.2.0 is the latest version right now?

**Comment by Originalimoc** [comment]
Tradition says bug report needs to on main/master branch ; )
Try using this: https://github.com/Atlas-OS/Atlas/actions/runs/6066917984
