### ISSUE TITLE
[BUG REPORT] - Activating NetFx3 (.NET 3) keeps failing and breaking DISM in 0.3

### ISSUE THREAD

**Issue by xatanu** [Atlas-OS/Atlas#907]
### Description

Hi,

This keeps failing and breaking DISM in my test VM environment:
- !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"NetFx3" /NoRestart', weight: 30}

It complains that a file is in use. Running the DISM command from the command line success. I guess the cause is that AME Wizard (which is developed in C#) blocks a .NET resource that makes dism to fail when trying to install the .NET optional feature.

The only solution I have found is activating NetFx3 feature through windows settings before applying the Playbook or use chocolatey or similar like you did in v0.2

Best

### Steps to reproduce (add screenshots if applicable)

1. Apply 0.3 dev playbook and check disabling Defender
2. After the computer restart it will say that disabling Defender failed. It's because DISM is broken and fails to install the package properly
3. Check the TIOutput file and check for errors.

### Expected behavior

.NET 3 should be installed
Defender should be disabled (if checked in the options)

### Actual behavior (add screenshots if applicable)

.NET 3 is not installed
Defender is not disabled

### Atlas Version

Atlas 10 22H2

### Desktop information

VM with Windows 11 22621
8 GB of RAM
4 Processors

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by he3als** [comment]
Can you please send logs?

**Comment by xatanu** [comment]
I created an empty Playbook just with that line. Here is the playbook and the logs

[test_logs.zip](https://github.com/Atlas-OS/Atlas/files/12666602/test_logs.zip)
[test_playbook.zip](https://github.com/Atlas-OS/Atlas/files/12666603/test_playbook.zip)

**Comment by xatanu** [comment]
Another log with the latest dev version
[9-20-2023-Atlas-AtlasOS.zip](https://github.com/Atlas-OS/Atlas/files/12667157/9-20-2023-Atlas-AtlasOS.zip)
