### ISSUE TITLE
Microsoft Edge full installed through security update

### ISSUE THREAD

**Issue by LinuxfarmerHH** [Atlas-OS/Atlas#917]
### Description

Atlas OS 22H2, installed may 2023

Today microsoft delivered a tiny security update, shown as yellow dot when shutting down. After that the MS Edge is the prime browser, that appears for any HTML help and files. It's back on the desktop, in menu and in the programs without uninstall button.

### Steps to reproduce (add screenshots if applicable)

1. Just let windows do his security update this day
2. See MS Edge appearing on your desktop and menu
3. Use any help in the setting enforce MS Edge to appear with auto logon at microsoft

### Expected behavior

MS Edge should stay removed or disabled in a way, the browser of choice can be used.

### Actual behavior (add screenshots if applicable)

![grafik](https://github.com/Atlas-OS/Atlas/assets/20478560/26730109-a2ed-4ca0-a352-0d88e2f1f295)

### Atlas Version

Atlas 10 22H2

### Desktop information

AMD Ryzen 2-2700
2x 8GB Memory Dual Channel
WDC PC SN530 512G
Intenso SSD 2048G

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by sabaasa** [comment]
atlas folder, 1. Install Software\Remove Edge.ps1

**Comment by sabaasa** [comment]
?

**Comment by PencilNavigator** [comment]
https://github.com/Atlas-OS/Atlas/blob/main/src/playbook/Executables/AtlasDesktop/1.%20Software/Remove%20Edge.ps1

Use this script in your AtlasDesktop Folder.

**Comment by LinuxfarmerHH** [comment]
Downloaded the sctri8pt, because in my Atlas Desktop Folder reside only the "Install Software.ps1" script. Run through and okay, 

Please check if all scripts are really placed in this folder, here on 2 computers it did not work.

Problem solved.

**Comment by he3als** [comment]
Closing, make a new issue when v0.3.1 releases if it happens again.
