### ISSUE TITLE
[INVALID] - Support

### ISSUE THREAD

**Issue by ChaseKnowlden** [Atlas-OS/Atlas#919]
### Description

When I open Internet Explorer to download Firefox, it says Internet Explorer 11 is no longer supported. Would you like to search the Microsoft Store for a supported browser? Internet Explorer does not open.

### Steps to reproduce (add screenshots if applicable)

1. Open Atlas Folder
2. Click on a Internet Shortcut
3. Does not open IE.

### Expected behavior

I want to download Firefox or Chrome.

### Actual behavior (add screenshots if applicable)

I can't get the programs I want.

![image](https://github.com/Atlas-OS/Atlas/assets/46290258/2147cb50-2de2-4dfc-a156-072cf08eff65)

![image](https://github.com/Atlas-OS/Atlas/assets/46290258/a2b865c0-f9a7-47b3-b263-51092f3c490e)

### Atlas Version

Atlas 10 22H2

### Desktop information

- 2GB RAM
- Processor: AMD Ryzen 5700G

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by sabaasa** [comment]
Atlas folder>1. Install Software

**Comment by ChaseKnowlden** [comment]
Thank you! @sabaasa

**Comment by sabaasa** [comment]
youre welcome :)
