### ISSUE TITLE
[BUG REPORT] - File sharing Atlas OS 22H2

### ISSUE THREAD

**Issue by Artimos** [Atlas-OS/Atlas#923]
### Description

Unable to get network file sharing working at all

### Steps to reproduce (add screenshots if applicable)

After extensive google-fu i still can not get network sharing to work with the latest atlas os windows 10 install ever. I ran through the following step in this order.
1. gone to Atlas\3. Configuration\1. General Configuration\Network Discovery > ran Enable Network Discovery.cmd as admin and without admin > restarted the system
2. gone to Atlas\3. Configuration\1. General Configuration\Lanman Workstation (SMB) > ran Enable Lanman Workstation (SMB) as admin and without admin > restarted the system
3. then restarted the system and sharing a folder is still entirely disabled > enabled network discovery and file sharing in windows network settings.
4. reenabled the following services and have them start automatically.
DNS Client
SSDP Discovery
UPnP Device Host
Function Discovery Resource Publication
Function Discovery Provider Host
5. attempted using  (\\ipaddress\foldername) with no parenthesis and using the double backslash in file explorer and still no luck
6. Validated both systems can ping each other and are connected to the same switch. File sharing worked between these two systems prior to moving to a AtlasOS installation.
I still have no option for sharing a folder in any way, shape or form, or any option to access the folder from another atlas os system that I repeated these steps on so both have it all enabled.

### Expected behavior

to be able to access a folder and copy data from one system to another like normal file sharing can do.

### Actual behavior (add screenshots if applicable)

Unable to access a drive or folder on either system outside of itself.

### Atlas Version

Atlas 10 22H2

### Desktop information

MSI MPG Z690 Carbon WiFi
Intel I9 11900k
32GB G.SKILL Ripjaws V Series
Crucial MX500 2TB 3D NAND SATA 2.5 Inch Internal SSD, up to 560MB/s - CT2000MX500SSD1 (disk with folder to be "Shared")
Atlas OS 22H2 / Windows 10 Pro

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

Would love any insight to something I may have missed in the last hour of working out the issues,

**Comment by sabaasa** [comment]
latest atlas os as in 0.3 from GitHub actions or 0.2?

**Comment by Artimos** [comment]
V0.2 in my current installed setup

**Comment by Artimos** [comment]
![image](https://github.com/Atlas-OS/Atlas/assets/2500645/e76f3634-c330-46f8-bce8-c43632aa7830)

**Comment by Artimos** [comment]
![image](https://github.com/Atlas-OS/Atlas/assets/2500645/2b748c44-c246-440b-a8cb-dd49553c6678)

**Comment by sabaasa** [comment]
> ![image](https://github.com/Atlas-OS/Atlas/assets/2500645/e76f3634-c330-46f8-bce8-c43632aa7830)

this has been fixed in atlas 0.3, it's in development still but it'll be released this month or next month

**Comment by Xyueta** [comment]
Works fine in the latest release.

**Comment by oleroc** [comment]
Running Atlas 0.4. 
Only way to access shared folders is to add the username/passord to windows credential manager, and then the shared folders are only available with IP adress, and not netbios name. The folder is shared to everyone on both share and security and should not require user/pass.
Password sharing is disabled.
Client for Windows networking and filesharing is enabled on adapter.
Netbios is activated.
Have also run Enable File sharing commandlet.
Still not able to make it work like normal.

**Comment by FDAHNet** [comment]
Another way to work with "shared" folder is:

In the machine migrated to AtlasOS (ex: 192.168.1.25, will be a good idea makes this machine with fixed ip):

- Install xlightftpd
- Create a user for share (ex: AtlasOS)
- Configure the shared folders in the FTP server under this user



On the external machines that wants to access to the shared folder on the AtlasOS machine:

- Install RaiDrive
- Mount in a drive letter the share route create in xlightftpd (ex: letter M: route \\192.168.1.25)
- Now you can access via letter M: your contents on the AtlasOS Machine (slowly, but better than nothing)
- You can access a little faster (not 100% but better than via Raidrive) using in your file explorer ftp://login:password@192.168.1.25/sharedfolder

All theses options are for free. Raiddrive is a Freemium mode, but use to FTP connect is free. XlightFTPD is totally free (donations accepted).

I know that this only a "meshpatch" but better than nothing,

Thanks to developers and I still waiting for real solution from hims.

FN

**Comment by mariomanic** [comment]
You need to go to your network adapter settings/properties and enable (put a checkmark) on "File and Printer Sharing for Microsoft Networks". I have both PCs running Atlas OS, this did the trick. Previously, I have enabled SMB 1.0 support within Windows Features as well, but this might not be needed.

**Comment by eqprio** [comment]
> You need to go to your network adapter settings/properties and enable (put a checkmark) on "File and Printer Sharing for Microsoft Networks". I have both PCs running Atlas OS, this did the trick. Previously, I have enabled SMB 1.0 support within Windows Features as well, but this might not be needed.

<img width="364" height="466" alt="Image" src="https://github.com/user-attachments/assets/6ecb73c4-2bc9-401a-bf74-c9a553a111b1" />


Worked!
Thanks.
