### ISSUE TITLE
[FEATURE REQUEST] - Add a dark version of wallpaper to go with the dark theme

### ISSUE THREAD

**Issue by MacroHard-Winux** [Atlas-OS/Atlas#931]
### What is your feature request regarding to?

AtlasOS

### Is your feature request related to a problem? Please describe.

no

### Describe the solution you would like.

I want a dark variant of the wallpaper to be added to the dark theme 

### Describe alternatives you have considered.

Find my own wallpaper

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by he3als** [comment]
It's dark
