### ISSUE TITLE
[FEATURE REQUEST] - Playbook Maker Wizard - Feature Selector (Custom Playbook Maker)

### ISSUE THREAD

**Issue by nikkdrive18** [Atlas-OS/Atlas#932]
### What is your feature request regarding to?

AtlasOS

### Is your feature request related to a problem? Please describe.

Requesting a "Playbook Maker Wizard" that can make a custom playbook based on feature selections as tickboxes.
Features like Win Defender, System restore, Microsoft Store, etc. which are removed could be un/selected as needed to make a custom playbook.

### Describe the solution you would like.

Requesting a "Playbook Maker Wizard" that can make a custom playbook based on feature selections as tickboxes.

### Describe alternatives you have considered.

Try to change after Install

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by he3als** [comment]
Done next release (v0.3.0)

**Comment by nikkdrive18** [comment]
ok thanks

**Comment by CodingArctic** [comment]
> ok thanks. can you guestimate when it will be released

0.3 is releasing tomorrow, if you join the discord you can see the specific time in your timezone
