### ISSUE TITLE
[BUG REPORT] - Finalizing installation prompt on reboot

### ISSUE THREAD

**Issue by oscar-wos** [Atlas-OS/Atlas#940]
### Description

Whenever I reboot the prompt shows up, I enabled process tracking and filtered through the security log, but there are no commands being issued.

This was on a fresh 23H2 windows 11 install.

### Steps to reproduce (add screenshots if applicable)

1. Reboot

### Expected behavior

No prompt being shown

### Actual behavior (add screenshots if applicable)

![image](https://github.com/Atlas-OS/Atlas/assets/29248751/443d11a1-3a72-464c-b05d-44252382345c)

### Atlas Version

Atlas 10 22H2

### Desktop information

- 4820k
- 16gb
- 120gb
- gtx 1080

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

Complete list of process creation event logs from clicking restart to loading windows.
https://pastebin.com/YJW2craW

**Comment by coffandro** [comment]
Same here, don't think it's a bug sadly

**Comment by sabaasa** [comment]
it's a bug

**Comment by Xyueta** [comment]
This has been fixed in the commits.

Thanks for reporting the issue.
