### ISSUE TITLE
[BUG REPORT] - Error: vcruntime140_1.dll not found after AMD driver installation w/ RadeonSoftwareSlimmer

### ISSUE THREAD

**Issue by realav** [Atlas-OS/Atlas#946]
### Description

**Issue Description:**
After following the GPU AMD driver installation guide from the Atlas documentation, I encountered an error when attempting to open Radeon Software.

### Steps to reproduce

[AMD GPU Driver Installation Instructions](https://docs.atlasos.net/getting-started/post-installation/drivers/gpu/amd/)
1. Downloaded the latest WHQL recommended driver from the AMD Drivers and Support page.
2. Downloaded RadeonSoftwareSlimmer as instructed (`RadeonSoftwareSlimmer_XXX_net48.zip`).
3. Ran RadeonSoftwareSlimmer and navigated to the Pre Install tab.
4. Selected the installer file and proceeded with the extraction process.
5. In the Packages tab, I left only the following items ticked:
   - AMD Display Driver
   - AMD Settings
   - AMD Audio CoProcessor Bus Driver (for monitor sound)
   - AMD Audio filter driver
   - AMD HDMI Audio driver
   - AMD High Definition Audio Controller
   - AMD Streaming Audio Filter Driver
6. Unticked all items in the Scheduled Tasks tab.
7. Unticked all items in the Display Driver Components, except for High Definition Audio Bus (since I am using Audio from the monitor).
8. Clicked 'Modify Installer and Run Installer' and completed the driver setup as usual.

### Expected behavior

Radeon Software should open after installation.

### Actual behavior

**Error Encountered:**
Upon opening Radeon Software by right-clicking on the desktop, I received the following error message: `vcruntime140_1.dll not found`.

### Atlas Version

Atlas 10 22H2

### Desktop information

- i5 4460 
- 12GB
- RX 560
- whql-amd-software-adrenalin-edition-23.11.1-win10-win11-nov3-vega-polaris

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

The error seems to be related to the Visual C++ runtime library which is not detected by the system. This file is typically installed with Visual C++ Redistributables.

**Comment by sabaasa** [comment]
how do people use their PC's without vc redistributables 💀
