### ISSUE TITLE
[BUG] - Static IP script malfunction

### ISSUE THREAD

**Issue by AuraGx** [Atlas-OS/Atlas#950]
### Description

So to explain this i tried to use the static ip script it work fine but when you restart your computer every network services failed like the network link services and many other but you still can use the internert

### Steps to reproduce (add screenshots if applicable)

go to the atlas file 
![image](https://github.com/Atlas-OS/Atlas/assets/65039701/045645d7-799d-4992-a9c3-f1c5fff49c88)
go to the Advanced Configuration tab
![image](https://github.com/Atlas-OS/Atlas/assets/65039701/7f785b39-d9ec-46ee-a3f6-3e25eab55fcc)
go to the static ip tab
![image](https://github.com/Atlas-OS/Atlas/assets/65039701/0081fa73-09e1-495a-a587-a326ebf886e1)
and then run the static ip script
![image](https://github.com/Atlas-OS/Atlas/assets/65039701/1799ab29-24a7-4e8c-9b95-cd434905b839)

### Expected behavior

I expected to have my ethernet device to have a static ip

### Actual behavior (add screenshots if applicable)

break the network tab and more
![image](https://github.com/Atlas-OS/Atlas/assets/65039701/850eb619-faf9-46d8-81ad-eb17527ed0ed)
![image](https://github.com/Atlas-OS/Atlas/assets/65039701/1c8a3d33-064e-4d48-9849-969bbdae9536)

### Atlas Version

Atlas 10 22H2

### Desktop information

Ryzen 5 5600x
RTX 3060 ti
ROG STRIX B550-F GAMING WIFI II
16gb ram

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

to repare everything do the undo script

**Comment by Xyueta** [comment]
It should be fixed now.
