### ISSUE TITLE
[BUG REPORT] -  MS Teams not working?

### ISSUE THREAD

**Issue by thathindicoder** [Atlas-OS/Atlas#952]
### Description

I'm using Atlas 22H2 Playbook. I need to get on to Teams, but the old usual app doesn't work, and the new app doesn't either.
The old app said there as something wrong with my TPM Module, as below-
`Your Computer's Trusted Platform Module has malfunctioned.`
The NEW app just gave me gibberish.

### Steps to reproduce (add screenshots if applicable)

1. Install Atlas on your PC
2. Try to log in (or open if you're already logged in)
3. Voila!

### Expected behavior

I expected it to open normally as a Windows 10 22H2 PC (without Atlas) would.

### Actual behavior (add screenshots if applicable)

It opens, and then on the OLD Teams it says somethings wrong with my TPM, and the NEW Teams gives me gibberish.

### Atlas Version

Atlas 10 22H2

### Desktop information

- Intel Core i7-6500U @ 2.50 GHz (2 real CPUs, 2 virtual CPUs = 4 cores), ~ 2.6 GHz
- 8 GB Ram
- BIOS (if it helps) Insyde 2.0 BIOS
- HP laptop
### Requisites

- [ ] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [ ] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by sabaasa** [comment]
are you using the latest playbook?

**Comment by thathindicoder** [comment]
wait how to check tha?

**Comment by thathindicoder** [comment]
ok im running v0.2

**Comment by thathindicoder** [comment]
do i update?

**Comment by sabaasa** [comment]
of course?

**Comment by thathindicoder** [comment]
actually, i updated anyway. I'll reboot now

**Comment by thathindicoder** [comment]
ah, no difference.

**Comment by thathindicoder** [comment]
exact error-
![image](https://github.com/Atlas-OS/Atlas/assets/149785329/8ef5ca82-1c0f-4f7d-bfcd-9d193924e079)

**Comment by sabaasa** [comment]
you did not update -_- clicking the update button in ame wizard is not how it works

**Comment by thathindicoder** [comment]
ok so uhhh.... what do i do?

**Comment by thathindicoder** [comment]
winget --update atlas or smth???

**Comment by thathindicoder** [comment]
( yes i used to have linux )

**Comment by sabaasa** [comment]
you need to reinstall windows to update to latest atlas, it has 7 months of new features and other stuff added so it isn't possible to just "apply over"

**Comment by thathindicoder** [comment]
you mean do a reset?!
uh oki

**Comment by sabaasa** [comment]
just follow the atlas documentation man sobs

**Comment by thathindicoder** [comment]
oh no
i couldnt reset
there was a problem 
### _**OH NO**_

**Comment by thathindicoder** [comment]
you know wht? i'll find a different way around.
