### ISSUE TITLE
[BUG REPORT] - Wallpaper engine not working

### ISSUE THREAD

**Issue by BigSip** [Atlas-OS/Atlas#956]
### Description

Wallpaper Engine breaks after every system restart.

### Steps to reproduce (add screenshots if applicable)

1. Install Wallpaper Engine
2. Restart

### Expected behavior

System boots, WPE loads, wallpapers play

### Actual behavior (add screenshots if applicable)

WPE starts, no wallpapers appear

### Atlas Version

Atlas 11 23H2

### Desktop information

- AMD Ryzen 9 5900X
- NVIDIA RTX 3080Ti ASUS TUF Gaming
- 32GB Corsair DDR4
- Seagate 2TB M.2 PCIE 4.0 SSD

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

Issue resolves by reinstalling GPU drivers. This lasts until system restart.

**Comment by JayXTQ** [comment]
Next time, please set a title <3

**Comment by coffandro** [comment]
Have you checked the faq for wallpaper engine?
https://help.wallpaperengine.io/en/noshow/nowallpaper.html

**Comment by coffandro** [comment]
@JayXTQ I think that counts as no response lol
