### ISSUE TITLE
[BUG REPORT]+[FEATURE REQUEST]- fix old version of ms store

### ISSUE THREAD

**Issue by wozzyi** [Atlas-OS/Atlas#958]
### Description

if u didn't update ms store before applying atlas playbook, ms store will stay on older versions which atlas will break tabs like library, downloads & updates, there's no way to update ms store itself within the app, u must do additional troubleshoot, remove msstore package and reinstall through winget

note: all ms store resetting ways wont work, windows troubleshooter cant detect and fix actual problems

### Steps to reproduce (add screenshots if applicable)

1. Open MS Store
2. Click on any tab related to library

### Expected behavior

Tabs related to library should work normally

### Actual behavior (add screenshots if applicable)

Old version:
![ms-store_old](https://github.com/Atlas-OS/Atlas/assets/84945798/22fea888-ea49-4a12-9b23-6085331098a7)

New, current version:
![ms-store_new](https://github.com/Atlas-OS/Atlas/assets/84945798/0c19a30d-a1a0-4b8f-90e2-6fcbb79c323f)

### Atlas Version

Atlas 10 22H2

### Desktop information

-Windows 10 Pro 22H2

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

pull request created: https://github.com/Atlas-OS/Atlas/pull/957

**Comment by jacksyrm** [comment]
Unfortunately, we won't be able to fix this issue. Our documentation guide clearly states that before applying Atlas, you need to update the Microsoft Store and its associated apps. 

Therefore, if there is no legitimate reason to stay on an older version, our team will not be able to provide support for it.

**Comment by wozzyi** [comment]
there was a time windows update servers were down, users can't access WU or MS store
