### ISSUE TITLE
[BUG REPORT] - Spotify Titlebar Messed Up

### ISSUE THREAD

**Issue by GhoulBoii** [Atlas-OS/Atlas#959]
### Description

Sometimes, when listening to music on spotify, the top left and top right corner of the window get rounded. After that, clicking on any button in the spotify window, the titlebar turns into the windows 7-esque titlebar. This issue is also there on Windows 11 23H2.

![image](https://github.com/Atlas-OS/Atlas/assets/78494833/177457d4-9b2e-4847-b9cb-c21199f77a81)

### Steps to reproduce (add screenshots if applicable)

1. Open Spotify
2. Fullscreen the window
3. Minimise the window
4. The window is now bugged

### Expected behavior

It should have the normal windows 10 titlebar.

### Actual behavior (add screenshots if applicable)

![image](https://github.com/Atlas-OS/Atlas/assets/78494833/bc1f4ea5-6ca2-471d-8c5c-b14773764619)

### Atlas Version

Atlas 10 22H2

### Desktop information

- Intel i5-2410M
- 8GB RAM
- Geforce Gt 525M (391.35)
- 512GB SSD

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.

### Additional content

https://discord.com/channels/795710270000332800/1110593249153929336/1172808815465480212
https://discord.com/channels/795710270000332800/1110593249153929336/1172994333121716234

**Comment by lukasekulic** [comment]
I encountered difficulties in reproducing the issue on the Windows 11 platform. Have you considered attempting the installation of the latest Microsoft Visual C++ Redistributable Runtimes as a potential resolution?

**Comment by GhoulBoii** [comment]
> I encountered difficulties in reproducing the issue on the Windows 11 platform. Have you considered attempting the installation of the latest Microsoft Visual C++ Redistributable Runtimes as a potential resolution?

Reinstalled the latest Microsoft Visual C++ Redistributable Runtimes; however, the issue is still present.

**Comment by clidx** [comment]
I believe this is to do with a borked recent Windows update as it happens on my systems running stock Win 11.

**Comment by kevvlol** [comment]
Getting the same thing on Windows 11 22635.2771 23H2 (Insider Beta)
![image](https://github.com/Atlas-OS/Atlas/assets/132225874/17b96a2a-474e-4465-b8de-6008e5b9495d)
12th Gen Intel(R) Core(TM) i5-12600K
RAM 16.0 GB (15.8 GB usable)
Nvidia 3060 GPU

**Comment by he3als** [comment]
> Windows 11 22635.2771 23H2 (Insider Beta)
> This happens on Windows 1909 too

@kevvlol @Yurichtofen I presume you're not on Atlas?

**Comment by lukasekulic** [comment]
After some research, most, if not all, similar issues have been caused by the app itself. Could you guys possibly remove the app and reinstall it?

**Comment by lukasekulic** [comment]
Also, what I do every time I install a new system, I install this first, maybe this will fix the issue you’re having?

https://github.com/abbodi1406/vcredist

**Comment by GhoulBoii** [comment]
I reinstalling vcredist and also reinstalled spotify but still face this issue. I think to reproduce this issue, you have to click the minimise button in the spotify titlebar. It is hard to reproduce otherwise.

**Comment by he3als** [comment]
Is this still an issue?

**Comment by GhoulBoii** [comment]
Issue seems to be fixed on the latest version of Spotify (1.2.25.1011.g0348b2ea) on Windows 10.
