### ISSUE TITLE
Can I switch from reviOS playbook to AtlasOS? Are there implications?

### ISSUE THREAD

**Issue by FormalSnake** [Atlas-OS/Atlas#962]
### What is your feature request regarding to?

AtlasOS

### Is your feature request related to a problem? Please describe.

I have heard some good things about AtlasOS, but before testing it in a VM I wonder if I can switch ReviOS to AtlasOS

### Describe the solution you would like.

.

### Describe alternatives you have considered.

.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by xe1st** [comment]
no you have to reinstall windows first. Also atlas github isn't the place to ask these questions.

**Comment by FormalSnake** [comment]
Sorry, I did not know where else to ask. Is it worth the hassle to reinstall?

**Comment by xe1st** [comment]
> Sorry, I did not know where else to ask. Is it worth the hassle to reinstall?

atlas discord is better place for overall support and questions. Anyways, personally yeah. I think atlas is the perfect balance between performance and compatibility.

**Comment by FormalSnake** [comment]
Thank you very much, I swill switch when the time is right (when windows autodestructs, if you know you know)
