### ISSUE TITLE
[BUG] - Google Nearby Sharing connection fails

### ISSUE THREAD

**Issue by ItzDatMC** [Atlas-OS/Atlas#963]
### Description

Basically it takes a long time to detect the phone and when I select my device to share any files, it fails to connect to the phone. This used to work on vanilla Windows 10/Windows 11.

### Steps to reproduce (add screenshots if applicable)

1. Download and install Nearby Share by Google for Windows
2. Choose a random file and select the receiving device
3. It will fail to connect to the device

### Expected behavior

The file should be shared without any issue

### Actual behavior (add screenshots if applicable)

It fails to connect to the device and the file was not sent.
![image](https://github.com/Atlas-OS/Atlas/assets/33323458/f99f1af0-598f-4232-9636-fa8495f58169)

Enabling Network Discovery, File Sharing, Bluetooth, Reset Network to Windows Default did not solve the issue

### Atlas Version

Atlas 10 22H2

### Desktop information

- Processor: Intel Core i5-4570 @ 3.20GHz
- RAM amount: 8 GB DDR3 1333 MHz 
- Storage: Samsung SSD EVO 860 250 GB (SATA 2.5")
- Graphics card: NVIDIA GeForce GTX 750 Ti 2 GB [version 546.01]
- Network & Bluetooth card: Intel Wi-Fi 6E AX210 160MHz [latest driver version from Intel website was installed]
- Atlas version: Windows 11 23H2 0.3.2 (the picker above should be updated)

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by xe1st** [comment]
Just tried and I can replicate this w11 0.3.2

**Comment by 27Sasuke** [comment]
Just tried as well and replicate the issue. Nearby share from windows to phone seems to work if both devices are paired with bluetooth once but still cant share files from the phone to windows.

**Comment by Mlgprofi** [comment]
I could replicate the problem only one time. I changed from "Receive from your devices" to "Receive from everyone"
then It worked with an Image , and a PDF file. I don't have problems on w11 v0.3.2


![Screenshot 2023-12-25 161322](https://github.com/Atlas-OS/Atlas/assets/16103820/387624d3-762a-41f0-923e-4458d8f5e5b4)
![Screenshot 2023-12-25 161401](https://github.com/Atlas-OS/Atlas/assets/16103820/c310d0e6-7c33-4a28-bd33-cb0fb51fc679)

**Comment by he3als** [comment]
Hi - does this still happen on v0.4.0?

**Comment by ItzDatMC** [comment]
> Hi - does this still happen on v0.4.0?

I’ll install 0.4.0 later today and let you know.

**Comment by the-P1neapple** [comment]
Can confirm issue is fixed on v0.4

**Comment by he3als** [comment]
I'll close this presuming that there's no issues, but if it doesn't work, comment under this issue and it'll be re-opened
