### ISSUE TITLE
[BUG] - HDMI Audio Not Working

### ISSUE THREAD

**Issue by BlackWolf999** [Atlas-OS/Atlas#968]
### Description

I've been using Atlas OS since it was an ISO, and recently, I updated to Atlas OS version 0.3, which is based on Windows 10. After applying the playbook, I noticed that HDMI audio output won't work with two drivers:

**Nvidia HD Audio :**
After applying the playbook, it simply states that it's not plugged in. However, after disabling and reenabling the driver, it becomes available. Unfortunately, both the audio and video are very choppy and slow.

**VIA HD Audio :**
It's recognized, but after I use it, there is no audio coming out, and the same issue persists during testing.

normal motherboard audio is working fine tho

### Steps to reproduce (add screenshots if applicable)

1. Install the graphics card drivers or the sound driver
2. Apply the atlas playbook

### Expected behavior

Audio working fine through hdmi

### Actual behavior (add screenshots if applicable)

Audio Doesnt work or very choppy

### Atlas Version

Atlas 10 22H2

### Desktop information

-Intel Core 2 Duo E7400
-2x2GB DDR3
-500GB HDD Samsung
-Geforce 210

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by jacksyrm** [comment]
Hi BlackWolf999,

I wanted to check if you used NVCleanstall while installing your display driver. If yes, during the installation process, it would have prompted you to select the components you want to include. Could you make sure that you choose HDMI audio from the list of components to be included?

To try this out, use [DDU](https://www.guru3d.com/download/display-driver-uninstaller-download/) to remove your current display driver!

I hope this information helps you. Let me know if you have any more questions.

**Comment by BlackWolf999** [comment]
Thank you very much for replying. I have removed and reinstalled the drivers three times, making sure the audio driver is installed. However, it didn't really help. I didn't use nvcleaninstall because my GPU driver isn't supported in nvcleaninstall. As of right now, I still haven't found a fix.

**Comment by jacksyrm** [comment]
> Thank you very much for replying. I have removed and reinstalled the drivers three times, making sure the audio driver is installed. However, it didn't really help. I didn't use nvcleaninstall because my GPU driver isn't supported in nvcleaninstall. As of right now, I still haven't found a fix.

I've installed Atlas for a user who uses a gaming TV with an HDMI hooked up (and uses the TV audio). It should work as long as it's not stripped when installing the graphics driver.

It must be an issue on your end specifically and not with Atlas. I don't have anything else to lead with this, so I hope you find a fix for it.

**Comment by BlackWolf999** [comment]
ok thanks for taking some time and testing i guess its just a problem on my end

if i ever find a solution i will post about it, anyways thank you for trying to help i appreciate it

**Comment by Pernicio** [comment]
Not sure if this will solve your problem, but you can try to increase the priority of the sound AND GPU driver with this tool; [GoInterruptPolicy](https://github.com/spddl/GoInterruptPolicy/releases)

You can also try different policies with them, like spreading interrupts across all the processor or specific processors. XBit Labs recommend to spread the interrupts for at least 4 cpu's [How to Use The Interrupt-Affinity Policy Tool](https://www.xbitlabs.com/how-to-use-interrupt-affinity-policy-tool/)

**Comment by he3als** [comment]
Closing as this seems to be unrelated to Atlas.

If there's proof that one of Atlas' modifications causes this or other people also have the issue, it'll be re-opened.
