### ISSUE TITLE
[BUG] - Missing Taskbar

### ISSUE THREAD

**Issue by refactorinqq** [Atlas-OS/Atlas#972]
### Description

Taskbar is just gone
![image](https://github.com/Atlas-OS/Atlas/assets/143757135/0adbe066-ca23-408b-b1e4-f113dfddba77)
The purplish area is where the taskbar is supposed to be. It seems like it has just froze.

### Steps to reproduce (add screenshots if applicable)

1. Install AtlasOS Playbook on 23H1 (Or any past updates before 23H2)
2. Upgrade to 23H2

### Expected behavior

Taskbar is supposed to appear

### Actual behavior (add screenshots if applicable)

![image](https://github.com/Atlas-OS/Atlas/assets/143757135/00b74ad4-15ca-44c6-91f7-9e376050d026)

### Atlas Version

Atlas 10 22H2

### Desktop information

Processor: AMD Ryzen 5 5600H
RAM: 8GB
Graphics Card: AMD Radeon iGPU // RTX 3050

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [x] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by he3als** [comment]
You're meant to fully update your system before running Atlas, especially for feature updates, as feature updates are unsupported.

I'll still keep this open to look into the issue

**Comment by he3als** [comment]
Also, 23H1 doesn't exist, and 23H2 doesn't exist for Windows 10. I'm confused on what you did.

**Comment by btsambo** [comment]
sorry to jump on this - had posted on atlas's dscord which led me here - am just doing a fresh atlas and updating windows pre playbook - windows is offering an optional november preview (kb5032278) and wondering if atlas is meant for this or to leave it out

**Comment by Ast3risk-ops** [comment]
> sorry to jump on this - had posted on atlas's dscord which led me here - am just doing a fresh atlas and updating windows pre playbook - windows is offering an optional november preview (kb5032278) and wondering if atlas is meant for this or to leave it out

This is fully unrelated. Please ask again on Discord.

**Comment by Ast3risk-ops** [comment]
> > You're meant to fully update your system before running Atlas, especially for feature updates, as feature updates are unsupported.
> 
> > 
> 
> > I'll still keep this open to look into the cause of the issue.
> 
> 
> 
> This wasn't listed on the prerequisites. Neither was it listed on the "Preparation" section.

In the docs? I'll look into that.

**Comment by Ast3risk-ops** [comment]
> > > > You're meant to fully update your system before running Atlas, especially for feature updates, as feature updates are unsupported.
> > > > I'll still keep this open to look into the cause of the issue.
> > > 
> > > 
> > > This wasn't listed on the prerequisites. Neither was it listed on the "Preparation" section.
> > 
> > 
> > [![image](https://private-user-images.githubusercontent.com/83875983/289136923-9a919777-bbd7-4810-96ce-5397cfa753fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNjk2MjUsIm5iZiI6MTcwMjA2OTMyNSwicGF0aCI6Ii84Mzg3NTk4My8yODkxMzY5MjMtOWE5MTk3NzctYmJkNy00ODEwLTk2Y2UtNTM5N2NmYTc1M2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDIxMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMDdkMDZlYTc1NDdhMTg3OTg1YmZmZWEzZjNmNDZlMTM5MWQwZmZjODU5NDU0OTJlYjJkMTc2YjA5OTVmYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n5q2Tj7QUy2HKpe-zxQ7azPGF_f63WJGVVqWO6__rq0)](https://docs.atlasos.net/getting-started/installation/#installing-atlasos_1)
> > But it is in the [docs](https://docs.atlasos.net/getting-started/installation/#installing-atlasos_1), which you seem not to have read.
> 
> I _did_ read the documentation, I was up to date according to Windows.

Then it's in the docs :P

**Comment by JayXTQ** [comment]
Is this issue resolved? Nobody else has had this issue as of late

**Comment by refactorinqq** [comment]
> Is this issue resolved? Nobody else has had this issue as of late

Yup. Issue has been resolved.
I just had to update everything *before* installing Atlas, updating after seems to cause this.
