### ISSUE TITLE
[BUG REPORT] - Vencord Installer is being run as administrator

### ISSUE THREAD

**Issue by Uranite** [Atlas-OS/Atlas#973]
### Description

For some reason, Vencord Installer is being run as administrator

### Steps to reproduce (add screenshots if applicable)

1. Download Vencord Installer from https://vencord.dev/download/
2. Open Vencord Installer

### Expected behavior

Vencord Installer should open as normal without any warning

### Actual behavior (add screenshots if applicable)

A warning will show, "Do not run me as Administrator"
![image](https://github.com/Atlas-OS/Atlas/assets/62639703/bd469bb5-06c1-4461-bbbc-19b43bdbbd6a)

### Atlas Version

Atlas 10 22H2

### Desktop information

- Intel Core i5-6400
- 8 GB RAM
- ADATA SU800 128 GB
- GTX 1050

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by JayXTQ** [comment]
You have UAC disabled on atlas, please enable it. You can find it in the atlas folder

**Comment by 0xAA289** [comment]
not really a bug, as thats intended, just press Cancel to continue anyways.
![image](https://github.com/Atlas-OS/Atlas/assets/41299185/d3e9b9a4-8083-485e-afd0-f7d591a4fb3f)

**Comment by JayXTQ** [comment]
It's not recommended to do that for vencord, it legit says it there...

**Comment by 0xAA289** [comment]
Its not recommended to disable all this windows stuff anyways, yet you still do if you use Atlas.

**Comment by Ast3risk-ops** [comment]
> Its not recommended to disable all this windows stuff anyways, yet you still do if you use Atlas.

@0xAA289 That's because Microsoft wants you to suffer. They'd prefer you leave the spyware in, so they can say whatever they want. Also UAC is *enabled* by default in Atlas versions 3.0 and above.

**Comment by 0xAA289** [comment]
Not complaining here, I gave a solution which I had used myself. Disregarding that promt, also as I marked the section about UAC.

**Comment by Ast3risk-ops** [comment]
That solution isn't a good fix, a better question is why this user even disabled UAC in the first place.

**Comment by 0xAA289** [comment]
I also disable UAC myself.
The solution is just something so OP can install the software they were originally trying to.
I don't go around telling people how to run their system.

**Comment by Ast3risk-ops** [comment]
> I also disable UAC myself. The solution is just something so OP can install the software they were originally trying to. I don't go around telling people how to run their system.

However, as the warning box states, UAC should not be disabled. You seem to have forgotten that when making this comment: https://github.com/Atlas-OS/Atlas/issues/973#issuecomment-1822693009

Having UAC set to never notify is the same as having it off. This is not how Vencord is supposed to be run.

**Comment by Uranite** [comment]
> That solution isn't a good fix, a better question is why this user even disabled UAC in the first place.

My bad, I should've mentioned I never disabled UAC in the first place, and enabling UAC does fix the problem.
