### ISSUE TITLE
[BUG REPORT] - Screen brightness still broken

### ISSUE THREAD

**Issue by horusra** [Atlas-OS/Atlas#975]
### Description

After having done a fresh install of Windows 11 Enterprise (latest version, and latest updated version of AtlasOS playbook) my laptop's screen is on full brightness no matter what I do.

I've found the same issue mentioned here: https://github.com/Atlas-OS/Atlas/issues/714#issuecomment-1522029297

However, for me, setting the "Display Enhancement Service" to start automatically and starting the service does not fix the issue. the brightness slider still does absolutely nothing.

**do note: "AtlasPlaybook_v0.3.2" still sets the service to disabled by default. This should have been fixed but is not on 0.3.2.**

### Steps to reproduce (add screenshots if applicable)

Go to Settings > Display > Change brightness > nothing changes

### Expected behavior

Go to Settings > Display > Change brightness > Brightness changes

### Actual behavior (add screenshots if applicable)

Go to Settings > Display > Change brightness > nothing changes

### Atlas Version

Atlas 10 22H2

### Desktop information

Asus VivoBook X509JA
Intel Core i7-1065G7

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by xe1st** [comment]
This issue is not present anymore. Did you install necessary drivers - both gpu and igpu?
you can send a screenshot of your display adapters from device manager to make sure

**Comment by horusra** [comment]
> This issue is not present anymore. Did you install necessary drivers - both gpu and igpu? you can send a screenshot of your display adapters from device manager to make sure
The laptop only has an integrated igpu, no dedicated gpu.
The necessary drivers have been installed. However at this moment I don't have physical access to the laptop, so I will post screenshots of the display driver in a couple of days.
Please keep the issue open until then.

**Comment by horusra** [comment]
@xe1st 
>since `display enhancement service` already set to auto. 

Actually I had to manually set the service to start automatically as it was stopped and set to disabled. I used "AtlasPlaybook_v0.3.2" yesterday and both it and the wizard were up to date.

**Comment by horusra** [comment]
I can confirm on my Desktop which I also uses the same playbook version on (but Windows 10 Enterprise as opposed to Windows 11 Enterprise on my laptop) the same service is still set to disabled.
![image](https://github.com/Atlas-OS/Atlas/assets/17074394/7730c5b4-fb7b-4739-abc6-fbeaad2b21bc)

**Comment by xe1st** [comment]
@horusra now I checked it - I am also on laptop. Service itself is set to manual(triggered), hence it runs when it is required. So yeah, everything works for me. I suggest double-checking your drivers when you have the chance :)

**Comment by xe1st** [comment]
btw discord is better place for general support questions like these since it is much more active and more opportunity to real-time chat.

**Comment by horusra** [comment]
> btw discord is better place for general support questions like these since it is much more active and more opportunity to real-time chat.

I will try discord on Tuesday when I have access to the laptop again.



> @horusra now I checked it - I am also on laptop. Service itself is set to manual(triggered), hence it runs when it is required. So yeah, everything works for me. I suggest double-checking your drivers when you have the chance :)

as you see on [the screenshot above](https://github.com/Atlas-OS/Atlas/issues/975#issuecomment-1826418974), "AtlasPlaybook_v0.3.2" still sets the service to disabled.

**Comment by the-P1neapple** [comment]
@horusra Go to the support page on the Asus website for your model.

At the software and utility section, click show all and find ASUS System Control Interface V3. Download the latest version shown and install it. It should install the relevant driver for your brightness slider keys

**Comment by he3als** [comment]
Seems like an issue with laptop and PC detection in one of the playbook's scripts.

@horusra Can you run `for /f "delims=:{}" %a in ('wmic path Win32_SystemEnclosure get ChassisTypes ^| findstr [0-9]') do set "CHASSIS=%a"` in Command Prompt and post the result?

**Comment by horusra** [comment]
> Seems like an issue with laptop and PC detection in one of the playbook's scripts.
> 
> @horusra Can you run `for /f "delims=:{}" %a in ('wmic path Win32_SystemEnclosure get ChassisTypes ^| findstr [0-9]') do set "CHASSIS=%a"` in Command Prompt and post the result?

that returns `set "CHASSIS=10"`

I've fixed the issue by manually enabling `display enhancement service` and installing the vendor's own graphics driver (the one from windows update wasn't enought apparently).

So the issue remains that AtlasOS disabled the `display enhancement service` on this Asus laptop. So apparently the device recognition wasn't working?
