### ISSUE TITLE
[BUG] - Snipping Tool broken

### ISSUE THREAD

**Issue by coffandro** [Atlas-OS/Atlas#978]
### Description

I use the application "Snipping tool" from Microsoft quite often but when I launch it to record the screen it doesn't work.

### Steps to reproduce (add screenshots if applicable)

1. Install Snipping tool
2. Run Snipping tool
3. Switch to video recording mode
4. Click new
5. Mark area
6. Boom break ![image](https://github.com/Atlas-OS/Atlas/assets/75324436/7d7073e8-ba6c-48a5-bfc2-25ea5004dc0e)

### Expected behavior

I run the Snipping tool, designate an area and begin recording

### Actual behavior (add screenshots if applicable)

I run the Snipping tool, designate an area and it breaks with this output
![image](https://github.com/Atlas-OS/Atlas/assets/75324436/7d7073e8-ba6c-48a5-bfc2-25ea5004dc0e)

### Atlas Version

Atlas 10 22H2

### Desktop information

- Atlas 11 23H2
- Asus TUF gaming F15 FX506HCB
- 11th gen core i5 11400H
- Intel(R) UHD Graphics
- NVIDIA GeForce RTX 3050 Laptop GPU

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by ArbestRiAgain** [comment]
I don't use the recording feature of Snipping Tool that much, so I won't care about this bug anyway

**Comment by coffandro** [comment]
Okay? Some people use this tool including myself, your comment dosen't help anyone in any way and dosen't have any purpose.

**Comment by coffandro** [comment]
fixed itself on reinstall
