### ISSUE TITLE
[FEATURE] - Option to remove Xbox App and Script to show all system tray icons

### ISSUE THREAD

**Issue by fabcard** [Atlas-OS/Atlas#979]
### What is your feature request regarding to?

AtlasOS

### Is your feature request related to a problem? Please describe.

Not a problem.

### Describe the solution you would like.

Hello. Please add an option to remove all apps related to Xbox. I don't use any of them and every time I turn on my controller, an annoying message appears saying that “ms-gamebar” is not installed as seen on the picture. If people use them, please add a .cmd/.reg files to remove/re-install the Xbox apps on Atlas folder. Also, if possible, please add a script to show all system tray icons, removing that show hidden icons arrow, just like on Windows 10. Thanks in advance.

### Describe alternatives you have considered.

As said above.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Additional context.

<img width="362" alt="Untitled" src="https://github.com/Atlas-OS/Atlas/assets/88634350/ff462e4b-a48f-45b4-a5ed-5e432ce9bccc">

**Comment by the-P1neapple** [comment]
A script in older versions of Atlas was used to remove the Xbox apps. It was removed in version 0.3.x since the script could not reverse the changes, and uninstalling the Xbox app was permanent.

Concerning your issue, the Xbox Game Bar shouldn't be opening with the controller by default (Atlas disables this when you install it). Can you go to Settings, Gaming, then Game Bar, and make sure the Allow your Controller to open Game Bar setting is disabled, please tell us if it was already disabled.

If this still doesn't work, try reinstalling Game Bar using the Microsoft Store, go back to the same setting as above, turn it on then off again, and reboot. Let us know if the issue still occurs after trying this.

For the system tray icons, you can re-enable them in Windows 11 by going to Settings, Personalisation section, and then taskbar. Scroll down to Other System Tray Icons and disable the Hidden Icon Menu. Then, re-enable all the other icons so they show in the taskbar.

**Comment by fabcard** [comment]
> Can you go to Settings, Gaming, then Game Bar, and ensure the Allow your Controller to open Game Bar setting is disabled? Please tell us if it has already been disabled.

This option is disabled on my system.

> If this still doesn't work, try reinstalling Game Bar using the Microsoft Store, returning to the same setting as above, turning it on and off again, and rebooting. Let us know if the issue still occurs after trying this.

I tried to install game bar from ms store and got a problem.
<img width="591" alt="Untitled" src="https://github.com/Atlas-OS/Atlas/assets/88634350/49e7a5d0-efbb-4ac9-a769-d43ed655ae9c">

> For the system tray icons, you can re-enable them in Windows 11 by going to Settings, the Personalisation section, and then taskbar. Scroll down to Other System Tray Icons and disable the Hidden Icon Menu. Then, re-enable all the other icons so they show in the taskbar.

This works but when a new program is installed and/or used, when it goes to system tray, it will not appear, or it will go to the hidden arrow and I have to manually repeat the steps you said above. It's not like the Windows 10 when I was able to click on show all system tray icons…

**Comment by Ast3risk-ops** [comment]
> > Can you go to Settings, Gaming, then Game Bar, and ensure the Allow your Controller to open Game Bar setting is disabled? Please tell us if it has already been disabled.
> 
> This option is disabled on my system.
> 
> > If this still doesn't work, try reinstalling Game Bar using the Microsoft Store, returning to the same setting as above, turning it on and off again, and rebooting. Let us know if the issue still occurs after trying this.
> 
> I tried to install game bar from ms store and got a problem. <img alt="Untitled" width="591" src="https://private-user-images.githubusercontent.com/88634350/287138274-49e7a5d0-efbb-4ac9-a769-d43ed655ae9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MzgwMTcsIm5iZiI6MTcwMTQzNzcxNywicGF0aCI6Ii84ODYzNDM1MC8yODcxMzgyNzQtNDllN2E1ZDAtZWZiYi00YWM5LWE3NjktZDQzZWQ2NTVhZTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDEzMzUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MjJiNTgxMzIyODkxYTNmN2EwOThiOGI5ZTRkYzBlZjg0MDhjOGVmOGYyMzExM2IyZWZiMjlhZDQxNWI3N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bmWNvkbXA-2OxL35ZHnnizdbwPTlbpwd2mIUaMJDJFc">
> 
> > For the system tray icons, you can re-enable them in Windows 11 by going to Settings, the Personalisation section, and then taskbar. Scroll down to Other System Tray Icons and disable the Hidden Icon Menu. Then, re-enable all the other icons so they show in the taskbar.
> 
> This works but when a new program is installed and/or used, when it goes to system tray, it will not appear, or it will go to the hidden arrow and I have to manually repeat the steps you said above. It's not like the Windows 10 when I was able to click on show all system tray icons…

There should be something in your Atlas folder under config > FSO and Xbox.

and to repeat:

> Concerning your issue, the Xbox Game Bar shouldn't be opening with the controller by default (Atlas disables this when you install it). Can you go to Settings, Gaming, then Game Bar, and ensure the Allow your Controller to open Game Bar setting is disabled? Please tell us if it has already been disabled.

**Comment by fabcard** [comment]
> There should be something in your Atlas folder under config > FSO and Xbox.

Hello there. I tried that too. All the 3 .reg files, but the issue persists. There's also a game bar download which gives me an error when I try to install it.

**Comment by fabcard** [comment]
> Have you tried installing game bar via https://store.rg-adguard.net? (guide: https://forum.atlasos.net/d/719-uwp-app-tutorial-fixed)

There are over 40 files to download for gamebar following the atlasos guide. To download all and then add one by one is too much work… Isn't there any easier way for doing that, please?

**Comment by Ast3risk-ops** [comment]
> > Have you tried installing game bar via [store.rg-adguard.net](https://store.rg-adguard.net)? (guide: [forum.atlasos.net/d/719-uwp-app-tutorial-fixed](https://forum.atlasos.net/d/719-uwp-app-tutorial-fixed))
> 
> There are over 40 files to download for gamebar following the atlasos guide. To download all and then add one by one is too much work… Isn't there any easier way for doing that, please?

Just find the `appx` or `msixbundle` pertaining to gamebar that has the latest version (should be one file) and download that.

If the file is an `msixbundle` stop following the guide, you can just double click `msixbundle` files to install them.

**Comment by Originalimoc** [comment]
This issue does not show on my 0.3.2 though? All Xbox functions working as I use XGP.

**Comment by Originalimoc** [comment]
Hmmmm no.. Seems like I can't login to Minecraft Bedrock edition. Fine on normal Windows.

**Comment by CodingMadness** [comment]
> Hmmmm no.. Seems like I can't login to Minecraft Bedrock edition. Fine on normal Windows. Edit: I can.. After restart game multiple times and reboot multiple times it finally works... Not sure why

Is it better now or you still need to reboot and such to login?

**Comment by Originalimoc** [comment]
> > Hmmmm no.. Seems like I can't login to Minecraft Bedrock edition. Fine on normal Windows. Edit: I can.. After restart game multiple times and reboot multiple times it finally works... Not sure why
> 
> Is it better now or you still need to reboot and such to login?

Still on that 0.3.2, no problem login MC, takes ~10s after clicking, normal I guess.
