### ISSUE TITLE
[BUG REPORT] - Microsoft Edge gets worse after installing AtlasOS

### ISSUE THREAD

**Issue by loisadf** [Atlas-OS/Atlas#980]
### Description

After installing atlas, all browser's contex menus lose transparency and rounded edges. Also, the browser is taken over by the organization, so it is impossible to change the dns provider. All this degrades functionality Microsoft Edge.

### Steps to reproduce (add screenshots if applicable)

1. Launch Microsoft Edge.

### Expected behavior

It was working before atlas was installed.

### Actual behavior (add screenshots if applicable)

1. 
![image](https://github.com/Atlas-OS/Atlas/assets/152587990/c6c62cdd-2260-45d9-ae55-70370b2f7f03)
2. 
![image](https://github.com/Atlas-OS/Atlas/assets/152587990/ba1afba6-96f3-4408-993a-a9e8bdfbbff9)

### Atlas Version

Atlas 10 22H2

### Desktop information

CPU Intel i7
GPU AMD RX 570
RAM 16 GB

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

AtlasOS version 0.3.2
Windows 11 23h2 build 22631.2787
Microsoft Edge 119.0.2151.9 (Official build) (64-bit)

**Comment by Ast3risk-ops** [comment]
Fun fact: Atlas modifies Edge, and we highly recommend removing edge and replacing it with your browser of choice.

**Comment by loisadf** [comment]
Fun fact: Atlas was installed before the Edge was installed (I tested this on different windows even with the Edge completely cut out, lol), so I don't think Atlas modifies the Edge. Probably Atlas blocks or removes in the system itself that through which the transparency of the contex menus in the Edge is implemented. 

In the problem of blocking the ISP's dns change. Maybe the problem is that I'm using a standalone Edge installer (for business) and it automatically detects the Edge under organization management, but there was no problem with changing dns before installing Atlas. Perhaps Atlas installs something similar in windows itself and the Edge takes the organization from windows itself. I wonder how Atlas wants to ensure privacy by disallowing dns provider changes) ?
 
I can see why Atlas doesn't like Edge. Not because it is spyware, but because most of the users use Chrome or Firefox and they don't like it when there is an Edge lying idle in their system. The same chrome I'm sure leaks even more information than Edge, but using Firefox after many years on chromium is just impossible.

**Comment by Ast3risk-ops** [comment]
> Fun fact: Atlas was installed before the Edge was installed (I tested this on different windows even with the Edge completely cut out, lol), so I don't think Atlas modifies the Edge. Probably Atlas blocks or removes in the system itself that through which the transparency of the contex menus in the Edge is implemented.
> 
> In the problem of blocking the ISP's dns change. Maybe the problem is that I'm using a standalone Edge installer (for business) and it automatically detects the Edge under organization management, but there was no problem with changing dns before installing Atlas. Perhaps Atlas installs something similar in windows itself and the Edge takes the organization from windows itself. I wonder how Atlas wants to ensure privacy by disallowing dns provider changes) ?
> 
> I can see why Atlas doesn't like Edge. Not because it is spyware, but because most of the users use Chrome or Firefox and they don't like it when there is an Edge lying idle in their system. The same chrome I'm sure leaks even more information than Edge, but using Firefox after many years on chromium is just impossible.

Either way it's easier to replace Edge.

**Comment by norwaytiewon** [comment]
ok so first of all pardon me for my bad English and second is i couldn't use win11 so idk how you would get mica transparency effects (probably toggling transparency effects settings in personalization tab would help) but i can help you with something else i guess

it's not really Atlas related issue but atlas changes animation settings (which can be toggled ofc), which also disables edge's rounded corners and other features

solution:
search "Adjust the appearance and the performance of Windows" and there you can check/uncheck animation related settings of Windows. If you specifically check "Show shadows under the windows" then you will get rounded corners
Try yourself what other options do and what meets your requirements

https://github.com/Atlas-OS/Atlas/assets/123308285/5204cc2e-5955-444a-bccc-904483860dd8

**Comment by xe1st** [comment]
You can enable rounded tabs from **edge://flags** without setting anything in **Adjust the appearance and the performance of Windows**
![image](https://github.com/Atlas-OS/Atlas/assets/140727743/71a982da-eed0-427b-9918-744ec1d881fc)


Atlas didnt limit my ms edge settings tho (organisation thingie). Did you fresh install windows first?

**Comment by xe1st** [comment]
> Yes, Windows was fresh. I was looking for a solution to this problem and found that this is a common problem. All chromium browsers that become managed by organizations. To solve this problem you need to edit the Windows group policy. The problem is that I have Windows Home and you can't edit it in this version. I'll try installing the Pro version and see if that solves the problem.

I remember getting this issue by running a tweaker before. I had fixed it by completely deleten ms edge related reg files. 
https://www.reddit.com/r/MicrosoftEdge/comments/ja5mlo/microsoft_edge_managed_by_your_organization/ check comments

**Comment by loisadf** [comment]
Problem solved. Thanks to @norwaytiewon and @xe1st  for his help.
