### ISSUE TITLE
[BUG] -  Mouse left clicks not registering at random intervals

### ISSUE THREAD

**Issue by brahimlmlm6** [Atlas-OS/Atlas#987]
### Description

oftentimes when i'm using windows 11 (Atlas OS 0.3.2) the left mouse click does not register sometimes when double clicking or using chrome, though this issue doesn't occur in-game nor when right-clicking.

### Steps to reproduce (add screenshots if applicable)

<Step 1> Click
<Step 2> Click Again
<Step 3> Click again until issue appears or hold the left click

### Expected behavior

Mouse Clicks to work.

### Actual behavior (add screenshots if applicable)

Clicks often stop registering and sometimes holding the left click registers as separate click, for example when dragging and dropping files

### Atlas Version

Atlas 10 22H2

### Desktop information

<OS Build>: Windows 11 23H2 22631.2428
Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz   3.30 GHz
8.00 GB (7.89 GB usable)
Dell OEM Geforce GT 730
Windows Feature Experience Pack 1000.22674.1000.0

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by brahimlmlm6** [comment]
yes im on atlas 0.3.2, should i reinstall the playbook?

**Comment by brahimlmlm6** [comment]
also just want to mention this in case anyone has this issue, in the Atlas folder/Troubleshooting/Network, Both files result in network being disabled, had to reenable the WLANAutoConfig and WiredAutoconfig in order for it to work

**Comment by norwaytiewon** [comment]
how do you know that mouse is not at fault 💀

**Comment by JayXTQ** [comment]
What? AME isn't a virus.

**Comment by Ast3risk-ops** [comment]
> Why ame have a virus?

Off-topic.

**Comment by daBroma** [comment]
it could be, we have no idea yet

**Comment by Ast3risk-ops** [comment]
> it could be, we have no idea yet

![illuminauti](https://weylin.com/wp-content/uploads/2018/02/Illuminati.jpg)

Wait for all these comments to be marked as off-topic.

**Comment by brahimlmlm6** [comment]
> > yes im on atlas 0.3.2, should i reinstall the playbook?
> 
> No, have you tried other mice?

yes, still same issue

**Comment by brahimlmlm6** [comment]
> Why ame have a virus?

i checked it for malware on virustotal and it came back with "0/72 No security vendors and no sandboxes flagged this file as malicious"


Though maybe virustotal are also on the deal
![Uploading d390xvar.png…]()

![image](https://github.com/Atlas-OS/Atlas/assets/74789731/e88219f5-55f4-4020-9b3d-b3bf7a88bf4e)

![Uploading image.png…]()

**Comment by JayXTQ** [comment]
mcafee itself is a virus lol, ame isn't a virus.

**Comment by Ast3risk-ops** [comment]
> > > Why ame have a virus?
> > 
> > 
> > i checked it for malware on virustotal and it came back with "0/72 No security vendors and no sandboxes flagged this file as malicious"
> > Though maybe virustotal are also on the deal
> > ![image](https://private-user-images.githubusercontent.com/74789731/289352042-e88219f5-55f4-4020-9b3d-b3bf7a88bf4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMTM1NjUsIm5iZiI6MTcwMjIxMzI2NSwicGF0aCI6Ii83NDc4OTczMS8yODkzNTIwNDItZTg4MjE5ZjUtNTVmNC00MDIwLTliM2QtYjNiZjdhODhiZjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDEzMDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNjViNmIzMmEzYzA2ODU1ODIzZDI3ODJhYTI5MzBmNzI3NzNiYjM3ZmNhMzExYzczMzVmOTk1NWVkMDA1ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IQiKJoPCpQ2a-Lx5_SWuISnQ9G05QIVtgxR2osePfR0)
> 
> Bro, its virus . Mcafee says :
> 
> ![IMG20231210134005.jpg](https://private-user-images.githubusercontent.com/122066492/289358674-4ef57644-9eee-4def-a402-76fe1585528c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMTM1NjUsIm5iZiI6MTcwMjIxMzI2NSwicGF0aCI6Ii8xMjIwNjY0OTIvMjg5MzU4Njc0LTRlZjU3NjQ0LTllZWUtNGRlZi1hNDAyLTc2ZmUxNTg1NTI4Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxMzAxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzdjMzliNWI4MjkzNTZiNDZlMDU2MDQ5MjcyOGQ3ZWNkZDhhMDkzYjdlMTEyODYzMWE5ODIzYzdlZTlmMzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q5MyVFRZmnLPJ07KgrUzhavGwY8zr01pYNEK5ree_oI)

That is a false positive.

**Comment by he3als** [comment]
I can't see how this could be an Atlas issue. Try using other USB ports and different mice. Unless there's something in Atlas that proves this, I am closing this as invalid.

You might find this useful: <https://boringboredom.github.io/Mouse-Functionality-Tester/>

**Comment by brahimlmlm6** [comment]
the mouse was working on another HDD i booted up into with Windows 11 ReviOS, and btw its not the drivers because my mouse on both uses the default mouse driver, i even booted Kali and it was working fine, only on atlas

after a few days the issues seems to have fixed itself.

**Comment by brahimlmlm6** [comment]
> > > > yes im on atlas 0.3.2, should i reinstall the playbook?
> > > 
> > > 
> > > No, have you tried other mice?
> > 
> > 
> > yes, still same issue
> 
> Weird, are you missing any USB chipset drivers?

nope
