### ISSUE TITLE
README.md translations are deprecated

### ISSUE THREAD

**Issue by he3als** [Atlas-OS/Atlas#989]
Firstly, we want to say that we are very thankful for everyone that contributed to the README translations. Any contributions are greatly appreciated, and README translations were no exception.

However, due to issues regarding maintaining the README, we have decided to remove translations.

We are currently looking into ways of localising the documentation instead. We'll send updates regarding that here and on the [Discord server](https://discord.atlasos.net/).

**Comment by Ast3risk-ops** [comment]
Currently, we are looking at:

- Google translate (works quite well)

- Crowdin (community translations)

**Comment by SnowzNZ** [comment]
self host weblate

**Comment by Ast3risk-ops** [comment]
> self host weblate

We already considered that, but Crowdin's open source plan is better.

**Comment by ItzDatMC** [comment]
+1 Crowdin. Google Translate automatic translation can be inaccurate and may cause unwanted confusion

**Comment by Ast3risk-ops** [comment]
+1 Google translate, it works and we don't want to wait for slow human translators to make and update translations. This is what we'll be using for now unless issues crop up.

**Comment by JayXTQ** [comment]
> +1 Google translate, it works and we don't want to wait for slow human translators to make and update translations. This is what we'll be using for now unless issues crop up.

Hold up, "slow... translators"? Can we not be rude to our past translators that translated completely for free and our current ones that have been helping us with our current translations. This is a rude comment and shouldn't be made here.

**Comment by NextWork123** [comment]
> ## Currently, we are experimenting with:
> * Automatic translation (e.g. Google Translate)
> * Crowdin (community translations)

much probably is better to use some translation with AI like deepl

**Comment by Ast3risk-ops** [comment]
> > +1 Google translate, it works and we don't want to wait for slow human translators to make and update translations. This is what we'll be using for now unless issues crop up.
> 
> Hold up, "slow... translators"? Can we not be rude to our past translators that translated completely for free and our current ones that have been helping us with our current translations. This is a rude comment and shouldn't be made here.

Not trying to be rude, it's a human constraint that applies to anybody.

**Comment by Ast3risk-ops** [comment]
> > ## Currently, we are experimenting with:
> 
> > * Automatic translation (e.g. Google Translate)
> 
> > * Crowdin (community translations)
> 
> 
> 
> much probably is better to use some translation with AI like deepl

Again, Google translate works and is verified by human people.

**Comment by NextWork123** [comment]
> > > ## Currently, we are experimenting with:
> > 
> > 
> > > * Automatic translation (e.g. Google Translate)
> > 
> > 
> > > * Crowdin (community translations)
> > 
> > 
> > much probably is better to use some translation with AI like deepl
> 
> Again, Google translate works and is verified by human people, I personally do not trust an AI to do the work.

i don't think is correct to base all the translation on google translate because if you gonna start to do translation in italian it gonna be innacurate 100%. But whatever if you are fine with that enjoy google translate (anyway is funny enough on discord it was always suggested "deepl" for translating things)
