### ISSUE TITLE
[BUG REPORT] - Shutdown and sleep not working

### ISSUE THREAD

**Issue by brahimlmlm6** [Atlas-OS/Atlas#990]
### Description

I tried to turn my pc off today and waited until the fans turned off, then got surprised when they sprung on again but this time the display only shows a black screen on my monitor (without a "No Display" or "No Signal") and a beep, thought it was a BIOS issue or RAM so i checked both but the issue persisted, then i did tried a reinstall of AtlasOS, but still the same issue, so i then put it to sleep only for the same thing to happen, to the point where whenever i want to turn it off, i have to hold the power button for 5 second in order for it to TURN OFF.

I thought it might be because of fast startup or Hibernation, but when i disabled those i still had the same issues

Then i remembered i had a 320GB HDD with ReviOS windows 11, i boot it up and surprise surprise: it works like normal again

BTW i have AtlasOS 0.3.2 on Windows 11, so i guess the issues are because of hard edits and the (beta) state of AtlasOS on windows 11

### Steps to reproduce

Power off or sleep

### Expected behavior

Turn off

### Actual behavior

Not turn off

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz   3.30 GHz
8.00 GB (7.71 GB usable)
OS Build: Windows 11 Pro 22631.2428
Windows Feature Experience Pack 1000.22674.1000.0

**Comment by Ast3risk-ops** [comment]
Can you check Control Panel, under Battery > change what the power buttons do?

**Comment by Ast3risk-ops** [comment]
> sleep and hibernate, but no fast startup option, which is why i needed regedit and cmd to turn it off, but it changed nothing

Wrong section, the thing above it.

**Comment by brahimlmlm6** [comment]
as i said only sleep and hibernate and lock, nothing else

**Comment by Ast3risk-ops** [comment]
> as i said only sleep and hibernate and lock, nothing else

No, the part that says what the power button does, is that set correctly.

**Comment by brahimlmlm6** [comment]
oh , that's set to shutdown

**Comment by Ast3risk-ops** [comment]
> oh , that's set to shutdown

So it's normal, have you checked your Atlas folder for anything?

**Comment by brahimlmlm6** [comment]
all that i tried didn't work

**Comment by ZeldrexK0DE** [comment]
the issue here is MODERN STANDBY (S0 SLEEP) is malfunctioning. happens to me on normal windows and altlas but since i havent tried normal windows on this pc this is experience from an older system..

**Comment by ZeldrexK0DE** [comment]
How do I upload 400mb video

**Comment by Ast3risk-ops** [comment]
> How do I upload 400mb video

https://studio.youtube.com

**Comment by he3als** [comment]
Closing the issue as stale. If there's any new information about this, feel free to create a new issue, or comment here.

**Comment by dauntlessArtist** [comment]
Came here to comment on something someone said on here. Someone mentioned that there is no fast start up option at all. Is there a way to bring that back?

**Comment by Ast3risk-ops** [comment]
> Came here to comment on something someone said on here. Someone mentioned that there is no fast start up option at all. Is there a way to bring that back?

If you're on a fast SSD the difference isn't noticeable.

**Comment by tade818** [comment]
this exactly happens to me in atlas v0.5.0, any solution?

**Comment by talkenson** [comment]
> Closing the issue as stale. If there's any new information about this, feel free to create a new issue, or comment here.

It's repeating 80% times. I saved prev installation of win 11 22h2, now 25h2 with atlas 0.5.0
After clicking Shutdown button windows successfully shuts, no errors in sleepstude reports too. 

```
PS C:\Windows\system32> powercfg /a
The following sleep states are available on this system:
    Standby (S3)

The following sleep states are not available on this system:
    Standby (S1)
        The system firmware does not support this standby state.

    Standby (S2)
        The system firmware does not support this standby state.

    Hibernate
        Hibernation has not been enabled.

    Standby (S0 Low Power Idle)
        The system firmware does not support this standby state.

    Hybrid Sleep
        Hibernation is not available.

    Fast Startup
        Hibernation is not available.

PS C:\Windows\system32> powercfg /devicequery wake_armed
HID Keyboard Device
HID Keyboard Device (002)
Realtek Gaming 2.5GbE Family Controller
HID-compliant mouse
HID-compliant mouse (001)
HID Keyboard Device (004)
HID Keyboard Device (005)
HID-compliant mouse (002)
```

I'm in the middle of discovering that issue, but I faced it before for like a month with 22h2, it fixed somehow, or I did idk. 
Anyway, this is strongly Atlas behavior on specific chipsets I suppose. 

On my gigabyte b760m ds3h ddr4 with 13400f and 4070 it reproduces roughly every time, but on b460 asrock with 10105f and 1660 super it works just fine.

**Comment by talkenson** [comment]
POSSIBLE FIX 
Oh, by the way
Try to query `reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v PowerdownAfterShutdown`

If it says = 0, the fix below might help you
Run:
`reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v PowerdownAfterShutdown /t REG_SZ /d 1 /f`

Then on Shutdown I instantly got expected result of disabling PC with Fans, RGBs and etc.

After booting up again I used again Query command and got 

```
PS C:\Windows\system32> reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v PowerdownAfterShutdown

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    PowerdownAfterShutdown    REG_SZ    1
```

Please let me know if it helps
