### ISSUE TITLE
[FEATURE] - add playnite as optional install

### ISSUE THREAD

**Issue by Koriebonx98** [Atlas-OS/Atlas#991]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

Be like a console as an option,

### Describe the solution you would like.

Playnite portable app as an option with atlas install.

### Describe alternatives you have considered.

None 

### Additional context.

have in “playnite/emulation/emulators/<emu name>”  
a portable emulator for each platform 
E.g yuzu, dolphin, rpcs3 ect 

have each emu set up in playnite to scan “playnite/Roms/<platform>/games” folder and 
Set up “roms” folder in root of drives such as 

“d,e,f,g”
 e.g 
“d:/roms/Xbox 360/games” 

replace “Xbox 360” with platform and d with “d-g” for c drive use “{playniteDir}/roms/“ 

When set so each emu will search all 5x letters, any rom in correct folder will be discovered automatically and playable in playnite.

Set a script before emu launch to scan for latest update if already got then skip if not download and install update then close emu. This will auto update the emulators.

**Comment by Ast3risk-ops** [comment]
> ### What is your feature request regarding to?
> 
> Atlas Playbook
> ### Is your feature request related to a problem? Please describe.
> 
> Be like a console as an option,
> ### Describe the solution you would like.
> 
> Playnite portable app as an option with atlas install.
> ### Describe alternatives you have considered.
> 
> None
> ### Additional context.
> 
> have in “playnite/emulation/emulators/” a portable emulator for each platform E.g yuzu, dolphin, rpcs3 ect
> 
> have each emu set up in playnite to scan “playnite/Roms//games” folder and Set up “roms” folder in root of drives such as
> 
> “d,e,f,g” e.g “d:/roms/Xbox 360/games”
> 
> replace “Xbox 360” with platform and d with “d-g” for c drive use “{playniteDir}/roms/“
> 
> When set so each emu will search all 5x letters, any rom in correct folder will be discovered automatically and playable in playnite.
> 
> Set a script before emu launch to scan for latest update if already got then skip if not download and install update then close emu. This will auto-update the emulators if you set something up using Task Scheduler.

This is not necessary, we already have a script in the Atlas folder for software installation. It has a list of common software that one can choose from, including the most popular PC games launcher, Steam.

The optional installs section is for very commonly used software like browsers and text editors.

Also implementing such update scripts would be outside of the scope of the playbook, use tools like `scoop` or `winget` for updates, and use alternate tools for rom scanning.

Your entire proposal goes against what the optional apps section is all about, and any additional scripts or setup are outside of the scope of this playbook.

Plus, more people use Steam than Playnite, it's a known fact.

P.S. There could also be legal issues regarding the emulators. (Emulation is legal in a lot of places, but there's still a connotation to piracy)

**Comment by Koriebonx98** [comment]
what i mean is so its a portable version of playnite,

all can be done via commands or bat scripts such as 
"download dolphin to "{playnitedir/emulation/emulators/dolphin" and add a "portable.txt"

users would then need emu bios/roms ect that they'll need to  obtain themselfs (not illegal only illegal if pirating roms but emu's are not)

in planite add emu's using "{PlayniteDir}/emulation/emulators/<emu name>"
and scan folders "{PlayniteDir}\Roms\<Platform name>\Games" and "D:/Roms/<platfrom name>/Games" 

this results in all emu's set and will scan rom folders, user can also place folder on C or D drive and itll still work.

you can also install steam,gog,epic ect via playnite and itll find any legal games you own (user doesnt need login but is needed for more features such as achivements)

alternativly they could go into playnite.desktop.exe and click restore/back up with a custom backup

ive trialed it and it works 
however emu folder (with system files installed such as yuzu, rpcs3 ect) comes to like 10gb

**Comment by Ast3risk-ops** [comment]
> what i mean is so its a portable version of playnite,

Doesn't change anything,

> all can be done via commands or bat scripts such as
> "download dolphin to "{playnitedir/emulation/emulators/dolphin" and add a "portable.txt"

You don't understand what I said at all.

> you can also install steam,gog,epic ect via playnite and itll find any legal games you own (user doesnt need login but is needed > for more features such as achievements)

On a side note, Playnite doesn't install these, it installs Playnite plugins for them.

> ive trialed it and it works

Good for you.

Again, this issue has been closed and will not be considered, reasons [stated above](https://github.com/Atlas-OS/Atlas/issues/991#issuecomment-1857182207). Please stop trying to revive it, you're just beating a dead horse.

**Comment by Koriebonx98** [comment]
why so rude when all i was doing is asking a few questions, not exactly trying to revive.

i did read what you said hence asked some questions such as where you have playnite as an optional install via atlas couldn't you have a optional customisation/ portable folder where it has emu pre set and rom folders set? or a custom playnite backup so user can choose it as an option.

i mentioned about it using plugins for launchers such as steam gog spic ea and it doesnt require user to log in via playnite if they have them launchers downloaded and logged in, (if playnite is portable you can preinstall addons, so if made a portable playnite when atlas-os downloads it for user via script itll be ready to go with the addons installed)

yes steam and retroarch are more popular than playnite there's not a debate on that but playnite has grown very popular in recent years as a good game manger for all launchers.

ive been using atlas-os as a mini console project for a little while as its light weight, paired with a custom version of playnite, and is makng it seem like a console  almost, that's why i decided to ask other day as i thought it could be of some help or maybe could get some ideas for my project

**Comment by Ast3risk-ops** [comment]
> why so rude when all i was doing is asking a few questions, not exactly trying to revive.
> 
> i did read what you said hence asked some questions such as where you have playnite as an optional install via atlas couldn't you have a optional customisation/ portable folder where it has emu pre set and rom folders set? or a custom playnite backup so user can choose it as an option.
> 
> i mentioned about it using plugins for launchers such as steam gog spic ea and it doesnt require user to log in via playnite if they have them launchers downloaded and logged in, (if playnite is portable you can preinstall addons, so if made a portable playnite when atlas-os downloads it for user via script itll be ready to go with the addons installed)
> 
> yes steam and retroarch are more popular than playnite there's not a debate on that but playnite has grown very popular in recent years as a good game manger for all launchers.
> 
> ive been using atlas-os as a mini console project for a little while as its light weight, paired with a custom version of playnite, and is makng it seem like a console almost, that's why i decided to ask other day as i thought it could be of some help or maybe could get some ideas for my project

However what you are asking is way **outside the scope of the playbook**. It might just be easier to add Playnite to the software installer ps1 without any additional tweaks (just installed via `winget` like everything else) I already explained this and the issue is closed.

If you really want to build this, fork the playbook (commit to the `dev` branch, not `master`) and figure it out.

**Comment by Koriebonx98** [comment]
> > why so rude when all i was doing is asking a few questions, not exactly trying to revive.
> > i did read what you said hence asked some questions such as where you have playnite as an optional install via atlas couldn't you have a optional customisation/ portable folder where it has emu pre set and rom folders set? or a custom playnite backup so user can choose it as an option.
> > i mentioned about it using plugins for launchers such as steam gog spic ea and it doesnt require user to log in via playnite if they have them launchers downloaded and logged in, (if playnite is portable you can preinstall addons, so if made a portable playnite when atlas-os downloads it for user via script itll be ready to go with the addons installed)
> > yes steam and retroarch are more popular than playnite there's not a debate on that but playnite has grown very popular in recent years as a good game manger for all launchers.
> > ive been using atlas-os as a mini console project for a little while as its light weight, paired with a custom version of playnite, and is makng it seem like a console almost, that's why i decided to ask other day as i thought it could be of some help or maybe could get some ideas for my project
> 
> However what you are asking is way **outside the scope of the playbook**. It might just be easier to add Playnite to the software installer ps1 without any additional tweaks (just installed via `winget` like everything else) I already explained this and the issue is closed.
> 
> If you really want to build this, fork the playbook (commit to the `dev` branch, not `master`) and figure it out.

know its possible as playnite works on windows 10/11 and have been working on a custom portable for a little while, easiest way as I've added emu's to playnite folder (10gb) is to extract zip on root of a drive, 
and have a roms folder on all drives they wish to use, i made a roms template and just copy/paste it
playnite updates itself and the addons so user wouldn't have to stress about that

emu's such as duckstation and similar wont require updates often so can be skipped, 
emu's such as yuzu and rpcs3 auto update on open/close by default
xenia i had to make a custom script in playnite that would check for update on start or close 

where its 10gb with all system files for emus it could be possible to have the emus as seprate zips to install so user can choose but playnite still have addons and rom folders set.

ive been trying to talk to the dev of playnite but he doesnt seem interested in any ideas i try to give him to add to default playnite, that.s why resulting in using atlas-os with a custom version of playnite ive modified myself

**Comment by Koriebonx98** [comment]
out of curisoty is there away to do a custom system restore via atlas-os?

as its a project im trying to do it would be good if i had a template os pre set that i could install on another pc.
so like can i back up my version of windows 10 with atlas-os but as a bootable iso to throw on a usb?

**Comment by Ast3risk-ops** [comment]
> out of curisoty is there away to do a custom system restore via atlas-os?
> 
> as its a project im trying to do it would be good if i had a template os pre set that i could install on another pc. so like can i back up my version of windows 10 with atlas-os but as a bootable iso to throw on a usb?

No custom Windows can do that, you'll want to make your own Playbook or pay for NTLite.

**Comment by Koriebonx98** [comment]
> > out of curisoty is there away to do a custom system restore via atlas-os?
> > as its a project im trying to do it would be good if i had a template os pre set that i could install on another pc. so like can i back up my version of windows 10 with atlas-os but as a bootable iso to throw on a usb?
> 
> No custom Windows can do that, you'll want to make your own Playbook or pay for NTLite.

always though there was a way to back up a windows 10 machine and convert to a bootable iso for usb installation? would be good if it was possible cuz then could convert mine that has atlas-os on and clone it to my other pc's 

okay ill have a look into that thank you, its mainly for myself so not to stressed if doesnt work like i want,

do you also know if you can disable the desktop and keep the notifications intact? so for example if i change windows boot from "explorer.exe" to "location of playnite.fullscreen.exe"  it disables all windows stuff such as desktop and notifications ect, i need notifications for stuff like achievement watcher but dont really need the desktop? i know i could remove all icons with a black screen on desktop but its not the same feeling
