### ISSUE TITLE
[BUG] - Passkeys doesn't work

### ISSUE THREAD

**Issue by holybaechu** [Atlas-OS/Atlas#992]
### Description

When i try to log-in with passkeys into website such as [github.com](https://github.com/login) it won't open passkeys prompt and instead shows me security key prompt.

### Steps to reproduce

1. Go to [github.com login page](https://github.com/login)
2. Click **Sign in with a passkey**

### Expected behavior

Passkey prompt pops up
![image](https://github.com/Atlas-OS/Atlas/assets/66154521/a1be79b6-f3c5-4a01-995f-85886f1cd3d5)

### Actual behavior

Security key prompt pops up 
![image](https://github.com/Atlas-OS/Atlas/assets/66154521/5f3793b9-2269-475a-abd2-a05e89cb1827)

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

- AMD Ryzen 7 5800X
- 32 GBs of DDR4 RAMs
- 1 TB, SK Hynix P41
- NVIDIA RTX 3060

### Additional content

**What did i try**
Tried other browsers
Tried latest Windows Update
Tried to install the update that brought passkeys via the update catalog (Which was already installed)
Tried stock Windows 11 without Atlas in VM which did work so i am assuming this as Atlas's bug.

**Comment by JayXTQ** [comment]
On Atlas, some biometric stuff is disabled/removed, I can't remember which is which. If windows hello is removed from your system I believe biometrics do not work, maybe @he3als can give more input

**Comment by he3als** [comment]
Biometrics should work, are you on the latest version of Atlas?

**Comment by baechooYT** [comment]
Yes, AtlasPlaybook v0.3.2.

**Comment by sakshiagrwal** [comment]
> Yes, AtlasPlaybook v0.3.2.

Then how did you register Passkeys if biometrics aren't working? Btw, Passkeys are working fine here.

**Comment by baechooYT** [comment]
No, I saved my passkeys on my phone and i'm trying to use QR code to use the passkey

**Comment by he3als** [comment]
Is the 'Passkeys' page in the Accounts section of Settings?

**Comment by he3als** [comment]
You need to add a Windows account PIN or another way of authentication with Windows Hello.

Passkeys should work after that.

![V3ithdeUlE](https://github.com/Atlas-OS/Atlas/assets/65787561/5b3393a5-5ed5-4aac-9f49-1dbcb3c144dd)

![vmconnect_ZcwuOFp16I](https://github.com/Atlas-OS/Atlas/assets/65787561/fbe04072-f0c2-4a3a-af81-a3edfe5c2381)
