### ISSUE TITLE
[BUG] - Windows 11 Japanese IME broken

### ISSUE THREAD

**Issue by SeleDreams** [Atlas-OS/Atlas#993]
### Description

I installed AtlasOS on Windows 11 in French. I later installed the Japanese language pack which normally allows to write in Hiragana, Katakana and Kanjis. However, while I can trigger the Japanese writing mode, no matter what I choose, it will stay in alphanumeric mode and won't ever switch to hiragana or katakana
![image](https://github.com/Atlas-OS/Atlas/assets/16335601/e323be49-6ec3-4b0e-9526-cb5b3e5c5706)

### Steps to reproduce

1. Install Atlas OS on Windows 11
2. Install the Japanese language pack
3. switch to Japanese input method
4. Try switching to hiragana or katakana input

### Expected behavior

The input should allow to type hiraganas and katakanas

### Actual behavior

The input stays stuck at alphanumeric

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Ryzen 7 3700x
Nvidia RTX 2080
32gb ram ddr4 3200mhz

**Comment by lisansas** [comment]
wwwwwww``wwwwadawwaaw

**Comment by lisansas** [comment]
I have the same issue,and solved it.

Unlike other OS，you should click 日语  "..."

Select first option,then you can see that the basic ime do not install.

Just click download.

そして解決しました

**Comment by Xyueta** [comment]
@SeleDreams Can you check if the issues still persists?

**Comment by SeleDreams** [comment]
The issue stopped happening around a month or two ago on its own. Probably an update or something fixed it
