### ISSUE TITLE
AtlasModules not installed?

### ISSUE THREAD

**Issue by AskAlice** [Atlas-OS/Atlas#995]
### Description

the scripts can't seem to find RunAsTI, and i see now that this is supposed to be a part of a powershell module. I'd like to enable search indexing and printing, but I can't seem to find where these modules should have installed to or how to install it.

### Steps to reproduce

unknown

### Expected behavior

.

### Actual behavior

.

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

..\

**Comment by Ast3risk-ops** [comment]
They should be in C:/Windows/AtlasModules

**Comment by he3als** [comment]
> the scripts can't seem to find RunAsTI, and i see now that this is supposed to be a part of a powershell module. I'd like to enable search indexing and printing, but I can't seem to find where these modules should have installed to or how to install it.

It's possible that your antivirus could of falsely flagged and removed it.

**Comment by AskAlice** [comment]
I manually added the tools dir to my path. Not sure why it wasn't added. I wish i was warned before it nuked my quick access btw

**Comment by he3als** [comment]
> I wish i was warned before it nuked my quick access btw

You were meant to run Atlas on a clean install, so this wouldn't of been an issue. However, we're aware of the issue and will be trying to fix it next version.

> I manually added the tools dir to my path. Not sure why it wasn't added

Can you send the `TIOutput.txt` log file from `%PROGRAMDATA%\AME\Logs` please? This will help to see what went wrong, although I suspect it was due to the PATH variable already being too long.

> Was more curious if there is a more proper way to install this as a powershell module?

There is not, but why?

**Comment by Ast3risk-ops** [comment]
> I suspect it was due to the PATH variable already being too long.

If that is the case do we need to do what Python does and remove the limit?

**Comment by AggressivelyMeows** [comment]
Running into this issue as well, however looking at the PATH, its clear it ran out of space:

![image](https://github.com/Atlas-OS/Atlas/assets/25571984/39e8f55e-bdeb-4c03-a7c2-6c2ead04f16b)

**Comment by he3als** [comment]
Ideally Atlas should be run only on fresh Windows installs, so this wouldn't of been an issue. However, I'll see what I can do to fix this for next version.

**Comment by he3als** [comment]
Fixed on Git ready for the next release. Closing.
