### ISSUE TITLE
[BUG] - GPU is almost unutilized

### ISSUE THREAD

**Issue by jarodvip** [Atlas-OS/Atlas#999]
### Description

When playing PUBG, the CPU is almost fully loaded and the GPU utilization is only 5%?

### Expected behavior

Under normal windows, the GPU utilization is basically 75%+

### Actual behavior

![123](https://github.com/Atlas-OS/Atlas/assets/12871436/086cdf37-e074-4442-81f8-7499b6c28721)

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

CPU：I7 7280HK
ram：16GB
GPU: GF 1070

**Comment by Ast3risk-ops** [comment]
This sounds like a good thing, less utilization for the same performance!

**Comment by jarodvip** [comment]
The GPU is not utilized and there will be lags during the game.


> 这听起来像是一件好事，相同性能的利用率更低！

**Comment by he3als** [comment]
I don't see how this is related to Atlas. If there's any cause found, this issue can be re-opened
